### ISSUE TITLE
Errors while attempting to install

### ISSUE THREAD

**Issue by smkoberg** [SeydX/homebridge-camera-ui#11]
Attempting to install on a Raspberry Pi with the following command
`[sudo] npm i homebridge-yi-camera`
I get the attached output

[junk.txt](https://github.com/SeydX/homebridge-camera-ui/files/3567585/junk.txt)

npm version 1.4.21

node version 8.11.1

[npm-debug.log](https://github.com/SeydX/homebridge-camera-ui/files/3567590/npm-debug.log)

**Comment by SeydX** [comment]
sudo npm install homebridge-camera-ui@latest -g
