### ISSUE TITLE
HOOBS stopped working after updating

### ISSUE THREAD

**Issue by motogon** [SeydX/homebridge-camera-ui#116]
**Describe the bug**
HOOBS stopped working after updating
Service stops

**Logs**

28.04.2021, 18:46:22 Failed to find plugin to handle accessory Camera 1
28.04.2021, 18:46:22 Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 404d3fda-a266-4712-a3f1-18a7efa9eddf
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/src/lib/Accessory.ts:564:15)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:260:25
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:221:81)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:155:14)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Environment**
- Node.js Version: 14.16.0
- Homebridge Version: 3.3.5
- Camera UI Version: 4.0.2
- Operating System: Ubuntu 20.04.2
- Browser: FF

**Comment by SeydX** [comment]
Hey @motogon 

there is a new test version to address this issue, can u try it pls?

https://github.com/SeydX/homebridge-camera-ui/wiki/Test-Upcoming-Changes

**Comment by SeydX** [comment]
[v4.0.3](https://github.com/SeydX/homebridge-camera-ui/releases/tag/4.0.3) is online

can u try it pls

**Comment by motogon** [comment]
errors occurred during installation

0 verbose cli [
0 verbose cli   '/usr/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   '--prefer-offline',
0 verbose cli   '--no-audit',
0 verbose cli   '--unsafe-perm',
0 verbose cli   '--progress=true',
0 verbose cli   'homebridge-camera-ui@4.0.3'
0 verbose cli ]
1 info using npm@7.6.0
2 info using node@v14.16.1
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/home/hoobs/.hoobs/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/home/hoobs/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 8ms
19 verbose npm-session 2cb4eb4a7161c462
20 timing npm:load Completed in 13ms
21 timing arborist:ctor Completed in 0ms
22 timing idealTree:init Completed in 98ms
23 timing idealTree:userRequests Completed in 2ms
24 silly idealTree buildDeps
25 silly fetch manifest homebridge-camera-ui@4.0.3
26 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
27 http fetch GET 200 https://registry.npmjs.org/homebridge-camera-ui 26ms (from cache)
28 silly placeDep ROOT homebridge-camera-ui@ OK for: @hoobs/hoobs@3.3.5 want: 4.0.3
29 timing idealTree:#root Completed in 33ms
30 timing idealTree:node_modules/homebridge-camera-ui Completed in 0ms
31 timing idealTree:buildDeps Completed in 33ms
32 timing idealTree:fixDepFlags Completed in 2ms
33 timing idealTree Completed in 136ms
34 timing command:install Completed in 139ms
35 verbose type version
36 verbose stack homebridge-camera-ui: No matching version found for homebridge-camera-ui@4.0.3.
36 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:207:23)
36 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:117:26
36 verbose stack     at async Arborist.[nodeFromEdge] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:888:19)
36 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:836:11)
36 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:7)
36 verbose stack     at async Promise.all (index 1)
36 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:130:5)
36 verbose stack     at async install (/usr/local/lib/node_modules/npm/lib/install.js:38:3)
37 verbose cwd /home/hoobs/.hoobs
38 verbose Linux 5.8.0-40-generic
39 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "install" "--prefer-offline" "--no-audit" "--unsafe-perm" "--progress=true" "homebridge-camera-ui@4.0.3"
40 verbose node v14.16.1
41 verbose npm  v7.6.0
42 error code ETARGET
43 error notarget No matching version found for homebridge-camera-ui@4.0.3.
44 error notarget In most cases you or one of your dependencies are requesting
44 error notarget a package version that doesn't exist.
45 verbose exit 1

**Comment by SeydX** [comment]
thats related to HOOBS. I think u need to wait until they update their cache

**Comment by ScharV** [comment]
You need to clear cached accessories and everything will be back up and running

**Comment by SeydX** [comment]
Everything good now?

**Comment by ScharV** [comment]
Yes it’s working smooth as ever with 4.0.6👌🏼

**Comment by motogon** [comment]
0 verbose cli [
0 verbose cli   '/usr/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   '--prefer-offline',
0 verbose cli   '--no-audit',
0 verbose cli   '--unsafe-perm',
0 verbose cli   '--progress=true',
0 verbose cli   'homebridge-camera-ui@4.0.6'
0 verbose cli ]
1 info using npm@7.6.0
2 info using node@v14.16.1
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/home/hoobs/.hoobs/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/home/hoobs/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 6ms
19 verbose npm-session 19629eb43872ae23
20 timing npm:load Completed in 11ms
21 timing arborist:ctor Completed in 0ms
22 timing idealTree:init Completed in 112ms
23 timing idealTree:userRequests Completed in 1ms
24 silly idealTree buildDeps
25 silly fetch manifest homebridge-camera-ui@4.0.6
26 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
27 http fetch GET 200 https://registry.npmjs.org/homebridge-camera-ui 118ms (from cache)
28 silly placeDep ROOT homebridge-camera-ui@ OK for: @hoobs/hoobs@3.3.5 want: 4.0.6
29 timing idealTree:#root Completed in 124ms
30 timing idealTree:node_modules/homebridge-camera-ui Completed in 0ms
31 timing idealTree:buildDeps Completed in 126ms
32 timing idealTree:fixDepFlags Completed in 1ms
33 timing idealTree Completed in 242ms
34 timing command:install Completed in 247ms
35 verbose type version
36 verbose stack homebridge-camera-ui: No matching version found for homebridge-camera-ui@4.0.6.
36 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:207:23)
36 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:117:26
36 verbose stack     at async Arborist.[nodeFromEdge] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:888:19)
36 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:836:11)
36 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:7)
36 verbose stack     at async Promise.all (index 1)
36 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:130:5)
36 verbose stack     at async install (/usr/local/lib/node_modules/npm/lib/install.js:38:3)
37 verbose cwd /home/hoobs/.hoobs
38 verbose Linux 5.8.0-40-generic
39 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "install" "--prefer-offline" "--no-audit" "--unsafe-perm" "--progress=true" "homebridge-camera-ui@4.0.6"
40 verbose node v14.16.1
41 verbose npm  v7.6.0
42 error code ETARGET
43 error notarget No matching version found for homebridge-camera-ui@4.0.6.
44 error notarget In most cases you or one of your dependencies are requesting
44 error notarget a package version that doesn't exist.
45 verbose exit 1

**Comment by motogon** [comment]
installed via web and console :(

**Comment by SeydX** [comment]
@motogon 

reset your npm cache and try again

``sudo rm -fR /home/hoobs/.npm``

**Comment by motogon** [comment]
@SeydX 

Thank you
problem solved
