### ISSUE TITLE
Error when select camera in Homebridge UI X

### ISSUE THREAD

**Issue by nexusle** [SeydX/homebridge-camera-ui#123]
```
[5/7/2021, 7:39:37 AM] [Homebridge UI] [homebridge-camera-ui] events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs: [
    '-rtsp_transport',
    'tcp',
    '-re',
    '-i',
    'rtsp://192.168.1.153:554/live/ch0',
    '-f',
    'mpegts',
    '-codec:v',
    'mpeg1video',
    '-s',
    '1280x720',
    '-b:v',
    '299k',
    '-r',
    20,
    '-bf',
    0,
    '-preset:v',
    'ultrafast',
    '-threads',
    '1',
    '-loglevel',
    'quiet',
    '-codec:a',
    'mp2',
    '-ar',
    '44100',
    '-ac',
    '1',
    '-b:a',
    '128k',
    '-'
  ]
}
```

**Comment by SeydX** [comment]
`Error: spawn ffmpeg ENOENT` means that u have not installed ffmpeg or camera ui can not access it

what does the terminal say if u type following: 

`ffmpeg -version`

**Comment by nexusle** [comment]
`ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-indev=alsa --enable-outdev=alsa
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100`

**Comment by SeydX** [comment]
@nexusle 

can u post your config.json pls

**Comment by nexusle** [comment]
`{
    "name": "CameraUI",
    "port": 3000,
    "atHomeSwitch": true,
    "theme": "auto",
    "language": "de",
    "debug": false,
    "mqtt": {
        "active": false
    },
    "http": {
        "active": true,
        "port": 7777,
        "localhttp": false
    },
    "ssl": {
        "active": false
    },
    "cameras": [
        {
            "name": "Carport",
            "manufacturer": "Hauppauge",
            "model": "Smarthome Camera",
            "motion": true,
            "unbridge": true,
            "videoConfig": {
                "source": "-rtsp_transport tcp -re -i rtsp://192.168.1.154:554/live/ch0",
                "stillImageSource": "http://admin:Mac1ntosh@192.168.1.154/mjpeg/snap.cgi?chn=0",
                "audio": false
            }
        },
        {
            "name": "Flur",
            "motion": true,
            "unbridge": true,
            "videoConfig": {
                "source": "-rtsp_transport tcp -re -i rtsp://192.168.1.151:554/live/ch0",
                "stillImageSource": "http://admin:Mac1ntosh@192.168.1.151/mjpeg/snap.cgi?chn=0",
                "audio": false
            }
        },
        {
            "name": "Küche",
            "motion": true,
            "unbridge": true,
            "videoConfig": {
                "source": "-rtsp_transport tcp -re -i rtsp://192.168.1.153:554/live/ch0",
                "stillImageSource": "http://admin:Mac1ntosh@192.168.1.153/mjpeg/snap.cgi?chn=0",
                "audio": false
            }
        }
    ],
    "platform": "CameraUI"
}`

**Comment by SeydX** [comment]
can u type following in your terminal and copy paste the output/path into your config config.json (see below)

`which ffmpeg`

(if output =  /usr/local/bin/ffmpeg)

```
"options": {
  "videoProcessor": "/usr/local/bin/ffmpeg"
}
```

_Note: replace the example output/videoProcessor path with yours!_

Full config.json:

```

{
  "name": "CameraUI",
  "port": 3000,
  "atHomeSwitch": true,
  "theme": "auto",
  "language": "de",
  "debug": false,
  "mqtt": {
    "active": false
  },
  "http": {
    "active": true,
    "port": 7777,
    "localhttp": false
  },
  "ssl": {
    "active": false
  },
  "options": {
    "videoProcessor": "/usr/local/bin/ffmpeg"
  },
  "cameras": [
    {
      "name": "Carport",
      "manufacturer": "Hauppauge",
      "model": "Smarthome Camera",
      "motion": true,
      "unbridge": true,
      "videoConfig": {
        "source": "-rtsp_transport tcp -re -i rtsp://192.168.1.154:554/live/ch0",
        "stillImageSource": "http://admin:Mac1ntosh@192.168.1.154/mjpeg/snap.cgi?chn=0",
        "audio": false
      }
    },
    {
      "name": "Flur",
      "motion": true,
      "unbridge": true,
      "videoConfig": {
        "source": "-rtsp_transport tcp -re -i rtsp://192.168.1.151:554/live/ch0",
        "stillImageSource": "http://admin:Mac1ntosh@192.168.1.151/mjpeg/snap.cgi?chn=0",
        "audio": false
      }
    },
    {
      "name": "Küche",
      "motion": true,
      "unbridge": true,
      "videoConfig": {
        "source": "-rtsp_transport tcp -re -i rtsp://192.168.1.153:554/live/ch0",
        "stillImageSource": "http://admin:Mac1ntosh@192.168.1.153/mjpeg/snap.cgi?chn=0",
        "audio": false
      }
    }
  ],
  "platform": "CameraUI"
}
```

**Comment by nexusle** [comment]
Thanks! This works...
