### ISSUE TITLE
hello my password wont' work anymore

### ISSUE THREAD

**Issue by platini76** [SeydX/homebridge-camera-ui#125]
what I have to do? I am sure about it

**Comment by SeydX** [comment]
Default credentials are `master` / `master`

If you have changed your username/password you have two options.

1. You can remove your database (config.ui.db.json) located in your homebridge folder (homebridge/db/config.ui.db.json)
2. Or you remove instead only the user, therefore you need to open cour config.ui.db.json, search for

```
"users": [
  ...
]
``` 

and change it to

```
"users": []
```

**Comment by platini76** [comment]
I kiss you... master and master works well!
