### ISSUE TITLE
Not working with Node 10 nor Node 12

### ISSUE THREAD

**Issue by xorguy** [SeydX/homebridge-camera-ui#14]
Fails to load when using Node 10 or Node 12. Is it possible to update compatibility with new Node versions?

**Comment by MrTeal** [comment]
Same for me, tried installing git no my rPi with node 10.15.0 but it's unable to run.

**Comment by montanaishome** [comment]
Same experience here

**Comment by ganewate** [comment]
Also experiencing this, have node 12.13.1 on Ubuntu 18.04 LTS. Just installing this plugin (with prereqs) causes homebridge to fail to start.

**Comment by seppelicous** [comment]
Got the same error with node 12.13.1. Now it is working after installing form-data module:
https://github.com/SeydX/homebridge-camera-ui/pull/13#issuecomment-536959074

Problem is, I am running home bridge in docker and assume, the installation is not persistent, when I drop the container for an upgrade.

**Comment by ganewate** [comment]
Top notch, that fixes it.

**Comment by SeydX** [comment]
v2.2 should fix this
