### ISSUE TITLE
Output file does not contain any stream - ffmpeg exit 1

### ISSUE THREAD

**Issue by palla89** [SeydX/homebridge-camera-ui#159]
**Describe the bug**

When using Homebridge and this plugin with two Yi Camera Outdoor with yihack5 firmware, at start they work in the UI and HomeKit, after some (random) time they just stop responding and when I open logs I see this:

**[6/14/2021, 5:11:37 PM] [CameraUI] [Plugin] Yicam1: Starting video stream: nativexnative, native fps, ??? kbps
[6/14/2021, 5:11:47 PM] [CameraUI] [Plugin] Yicam1: [error] Output file #0 does not contain any stream
[6/14/2021, 5:11:47 PM] [CameraUI] [Plugin] Yicam1: ffmpeg exited with code: 1 and signal: null (Error)
[6/14/2021, 5:11:47 PM] [CameraUI] [Plugin] Yicam1: Stopped video stream.**

**Logs**

`[6/14/2021,` 5:11:37 PM] [CameraUI] [Plugin] Yicam1: Starting video stream: nativexnative, native fps, ??? kbps
[6/14/2021, 5:11:47 PM] [CameraUI] [Plugin] Yicam1: [error] Output file #0 does not contain any stream
[6/14/2021, 5:11:47 PM] [CameraUI] [Plugin] Yicam1: ffmpeg exited with code: 1 and signal: null (Error)
[6/14/2021, 5:11:47 PM] [CameraUI] [Plugin] Yicam1: Stopped video `stream.`

Config.json camera related:

```
{
            "name": "CameraUI",
            "port": 8082,
            "atHomeSwitch": true,
            "theme": "auto",
            "language": "en",
            "debug": false,
            "mqtt": {
                "active": false
            },
            "http": {
                "active": false,
                "localhttp": false
            },
            "ssl": {
                "active": false
            },
            "cameras": [
                {
                    "name": "Yicam1",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://user:pass@192.168.2.65/ch0_0.h264",
                        "stillImageSource": "http://192.168.2.65:8080/cgi-bin/snapshot.sh?res=high&watermark=yes",
                        "vcodec": "copy",
                        "audio": false,
                        "debug": true
                    }
                },
                {
                    "name": "Yicam2",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://user:pass@192.168.2.14/ch0_0.h264",
                        "stillImageSource": "-i http://192.168.2.14:8080/cgi-bin/snapshot.sh?res=high&watermark=yes",
                        "vcodec": "copy",
                        "debug": true
                    }
                }
            ],
            "platform": "CameraUI"
        }
```

I tried copy as vcodec but also others, still problem. Can you give me an advice?

**Screenshots**

**Environment**
- Homebridge Version: latest
- Camera UI Version: latest
- Operating System: Synology DSM 6, using homebridge within docker container

**Comment by SeydX** [comment]
Try without `vcodec`

**Comment by palla89** [comment]
Unfortunately it didn't work :( 
They aren't working even after homebridge restart...  

```
[6/14/2021, 8:26:45 PM] [CameraUI] [Plugin] Yicam2: Starting video stream: 1280x720, 30 fps, 299 kbps
[6/14/2021, 8:26:56 PM] [CameraUI] [Plugin] Yicam2: [error] Output file #0 does not contain any stream
[6/14/2021, 8:26:56 PM] [CameraUI] [Plugin] Yicam2: ffmpeg exited with code: 1 and signal: null (Error)
[6/14/2021, 8:26:56 PM] [CameraUI] [Plugin] Yicam2: Stopped video stream.
```


I really can't understand why and what is wrong :/

What should I try?

**Comment by Davrizio** [comment]
I'm getting the same error with Yi Home cameras and the yihackV5 firmware. Stream plays fine in VLC and Ui but it will give me an error when playing in homekit. I do see the snapshot thumbnail in homekit though.

[Plugin] Front Room: [error] Output file #1 does not contain any stream

My config:

  "name": "Front Room",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://192.168.68.109/ch0_0.h264",
                        "audio": true

I've tried just -i as well and same result. Any luck with a solution?

**Comment by dlshumway** [comment]
I had the same error with an Annke POE camera and when I turned off Audio,
it started working.

**Comment by Davrizio** [comment]
Thanks @dlshumway ! That fixed it!

**Comment by dwerg85** [comment]
Had this same problem with a webcam attached to motioneye on a raspberry pi. Solved by the same fix suggested here.

**Comment by wardienet** [comment]
> I had the same error with an Annke POE camera and when I turned off Audio, it started working.
> […](#)
You Star thanks! I've been pulling my hair out trying to figure why that wasn't working, many options later, about to give up. Found this thread. Now works fine - just same about the sound but so be it. With a Hikvision 2K camera via NVR and I can get it through at 1280x720 30fps via the various export NVR feeds, not bad for a quick look on Home.
