### ISSUE TITLE
Camera Performance

### ISSUE THREAD

**Issue by Kung-Foo-Kamel** [SeydX/homebridge-camera-ui#161]
Hi Seydx,

Thanks for this plugin, for the most part it works quite well, just having issues when opening camera feeds, seems to be very slow and in some cases, the feed wont start and I have to close and start again.

Everything is over gigabit lan, I have tested a single instance of Homebridge in a VM and on a powerful workstation, doesnt seem to make any difference, my cameras all play almost instantly in VLC and from the Dahua Smart PSS software, I have  optimised the cameras encoding to 720p h264 15fps and 1500mbps, any lower and the feed looks like hot garbage, I have also tested direct copy and re-encoding, but nothing seems to speed up the feed, and in some cases the feed will just freeze.

Doesn't seem to matter if its the VM or my workstation, system will only be at 5% even when re-encoding, and I'm only trying to access one camera at a time, the web-UI will struggle to load all 9 cameras, but I expected that.

I'm not sure where the delay is coming from, I setup a cheap IP cam on its own, tested it to my iphone through the native app and its almost instant, then tested through VLC and its almost instant, then set it up in the plugin and its slow to load, both with copy and encode, is this the nature of Homekit video? or something else bottlenecking the feed?

Its not my network or my wifi, its all Ubiquiti and highend equipment and I have ran multiple tests trying to find the issue, all my cameras are good quality Dahua units, have tried H264 and H265, 265 wont do copy, and when trying to re-encode, it looks like FFMpeg will struggle at times, but H264 is fine.

Any advice on what I can try? as I have 9 cameras and multiple wall mounted ipads that I want to access them on.

Below is a typical setup I'm using:

{
                    "name": "Pool Area",
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://user:password@192.168.0.212:554//cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif",
                        "maxStreams": 4,
                        "vcodec": "copy",
                        "audio": true
                    }
                },

**Comment by Kung-Foo-Kamel** [comment]
I ended up removing your plugin and setting up this one -> https://github.com/Sunoo/homebridge-camera-ffmpeg

I used basically the same config, and its now much faster, with no error messages, not sure what is different in your plugin, but there is something that's causing it to under perform on my setup, could be related to the UI part of the plugin.

I have also found I can push much higher bit rates and it still only takes a second or two to start any stream when using transcoding, and the copy mode also accepts higher bit rates with no noticeable hiccups, previously I was having micro stutters in the streams, specially with higher bit rates.

**Comment by SeydX** [comment]
Hello, I'm glad to hear that you found a solution to your problem :)

For "HomeKit" camera.ui also uses the Camera-FFmpeg developed by Sunoo (only slightly modified) so I'm surprised that you have a better "performance" with the plugin.

Everything that Camera-FFmpeg has in terms of settings has also been ported to camera.ui.

The user interface would only then reduce the performance possibly if at the same time is also looked over the interface.

The user interface and the homebridge plugin are separate. So the problem with the performance should not be at the interface.

**Comment by Kung-Foo-Kamel** [comment]
Its odd, but the cameras are all responding faster, I have them all set to passthrough @ 720p 1.5mbit VBR now and they are definitely responding faster than before, I have 1 camera that I transcode from h265, it was a 6480x480 stream, and it was choking, I now have it set to a 4k resolution, 6mbit and transcoding to 720p 1.5mb and its max 2 second delay to start and only using 25% CPU, I couldn't do this before.

Definitely something weird going on with my setup, but its working now, I might spin up a new VM and test yours on a fresh setup and do a comparison, as I was seeing lots of error messages logged when using your plugin and I'm not seeing any now, if I get the same results as before, I will send you logs from both setups, maybe you might be able to pin point the issue.
