### ISSUE TITLE
How to remove this plugin ?

### ISSUE THREAD

**Issue by fastenspy** [SeydX/homebridge-camera-ui#22]
Hello, impossible for me to remove this plugin ?

`pi@raspberrypi:~ $ sudo npm remove homebridge-yi-camera
npm WARN pi@1.0.0 No repository field.

audited 961 packages in 83.766s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
`

**Comment by SeydX** [comment]
sudo npm uninstall homebridge-camera-ui
