### ISSUE TITLE
Passwort

### ISSUE THREAD

**Issue by Thotty1986** [SeydX/homebridge-camera-ui#225]
.. dear all, 

maybe I am Stupid but what is the password and user for login ?

**Comment by sorriso93** [comment]
master master. I also cannot find it in the wiki, maybe it is good to put in the instructions...

**Comment by seydx** [comment]
> master master. I also cannot find it in the wiki, maybe it is good to put in the instructions...

Its in the readme

[response.data.result](https://github.com/seydx/homebridge-camera-ui#defaults)
