### ISSUE TITLE
Connecting on port 80

### ISSUE THREAD

**Issue by aba0815** [SeydX/homebridge-camera-ui#27]
When switching parameter "yihackv4" to "true" the following error occured:
`2020-05-18T09:34:23.768Z CameraUI Error: connect ECONNREFUSED 192.168.2.124:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
2020-05-18T09:34:38.769Z CameraUI gartenkamera: api request 46 : GET http://192.168.2.124/cgi-bin/get_configs.sh?conf=system
[5/18/2020, 11:34:38 AM] [CameraUI] [ERROR] gartenkamera: An error occured while checking camera config!`

CameraUI tries to connect on port 80, but the camera is working at port 8080. Whats wrong?
Switching back to ""yihackv4": true," gives no more error and no connections at port 80.

The corresponding part of my config:
`{
            "platform": "CameraUI",
            "debug": true,
            "videoProcessor": "ffmpeg",
            "cameras": [
                {
                    "name": "gartenkamera",
                    "active": true,
                    "yihackv4": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://192.168.2.124/ch0_0.h264",
                        "stillImageSource": "http://192.168.2.124:8080/cgi-bin/snapshot.sh",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxBitrate": 300,
                        "vcodec": "copy",
                        "maxFPS": 10
                    },
                    "mqtt": {
                        "active": true,
                        "host": "192.168.2.148",
                        "port": 1883,
                        "username": "",
                        "password": "",
                        "topicPrefix": "yicam",
                        "topicSuffix": "motion",
                        "startMessage": "motion_start",
                        "stopMessage": "motion_stop",
                        "recordOnMovement": true,
                        "recordVideoSize": 60,
                        "interval": 0
                    }
                },
                {
                    "name": "nestkameranord",
                    "active": true,
                    "yihackv4": false,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://192.168.2.126/ch0_0.h264",
                        "stillImageSource": "http://192.168.2.126:8080/cgi-bin/snapshot.sh",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxBitrate": 300,
                        "vcodec": "copy",
                        "maxFPS": 10
                    }
                }`

**Comment by vitru** [comment]
Yes, same problem here. How does yihackv4 work for people? 8080 is the default port it uses for HTTPD.
