### ISSUE TITLE
Optimize Apple HomeKit?

### ISSUE THREAD

**Issue by wills721** [seydx/homebridge-camera-ui#276]
**Describe the bug**
Using the Camera UI directly my cameras are very responsive.  They appear in 1-2 seconds.  However,  the same Camera using Apple Home can sometimes take >15 seconds.  What is Apple doing that causes this to be so slow and is there a way to speed it up?

This is the FFMPEG command I find when Camera UI streams to my phone via HomeKit (with IPs and Users and Passwords removed)

 /usr/local/bin/ffmpeg -rtsp_transport udp -i rtsp://user:password@IP:554/h264Preview_01_sub -an -sn -dn -codec:v copy -pix_fmt yuv420p -color_range mpeg -f rawvideo -payload_type 99 -ssrc 16558985 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params wjJh5MqqZhD7+91mj7CCYLM4LY53Mx20u0A5vRor srtp://IP:54318?rtcpport=54318&pkt_size=1316 -vn -sn -dn -codec:a libfdk_aac -profile:a aac_eld -flags +global_header -f null -ar 16k -b:a 24k -ac 1 -payload_type 110 -ssrc 11860871 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params vLamlj3vEvU2kux8HCGU0SceMrtBZ+jNCdmF1GDT srtp://IP:5450?rtcpport=55450&pkt_size=188 -loglevel level+verbose -progress pipe:1

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Logs**
If available, attach the log where the bug is vissible

**Screenshots**

**Environment**
- Node.js Version: v14.18
- Homebridge Version: vX.X
- Camera UI Version: v4.2
- Operating System: Raspberry PI 4
- Browser: XXX

**Comment by seydx** [comment]
Fixed in v5.0.0-beta.36

``sudo npm i -g homebridge-camera-ui@5.0.0-beta.36``

**Comment by seydx** [comment]
Demo:


https://user-images.githubusercontent.com/34152761/147686500-eb53d35c-167a-450a-9a31-85bf6ecd4af1.MP4
