### ISSUE TITLE
Motion Detection via SMTP

### ISSUE THREAD

**Issue by marckagan** [seydx/homebridge-camera-ui#306]
I am trying to use Camera-UI with my Amcrest cameras with the ultimate goal of making it work with HSV.  My cameras only support SMTP email as a triggering mechanism for motion detection.  I looked at homebridge-smtp-motion which could / should work as an option but that would require me to setup my cameras in homebridge-camera-ffmpeg as well as Camera-UI as far as I can tell.  

Can you build this type of functionality into Camera-UI to enable the use of cameras that don't have support for HTTP or MQTT?

**Comment by seydx** [comment]
These are already built in. camera.ui supports mqtt, smtp, http and ftp (v5) as motion detection service

**Comment by seydx** [comment]
try updating to v5.0.0-beta.37

``sudo npm i -g homebridge-camera-ui@5.0.0-beta.37``

following config is needed for SMTP

```json
...
"http": {
    "active": true,
    "port": 6666,
    "localhttp": false
},
"smtp": {
    "active": true,
    "port": 2828,
    "space_replace": "+"
},
...
```
