### ISSUE TITLE
Ios14 homekit for Yi camera

### ISSUE THREAD

**Issue by Asutay88** [SeydX/homebridge-camera-ui#31]
Hello, is it possible to have select activity zone and face recognition options available in homekit for Yi camera? I already have a setup with motion alert working but couldn't figure out how to select activity zone and face recognition from homekit. Thanks.

![HomeKit](https://user-images.githubusercontent.com/72492794/95305972-a447c300-087e-11eb-8b18-13a80f1e063b.png)

**Comment by yonigold1** [comment]
> Hello, is it possible to have select activity zone and face recognition options available in homekit for Yi camera? I already have a setup with motion alert working but couldn't figure out how to select activity zone and face recognition from homekit. Thanks.
> 
> ![HomeKit](https://user-images.githubusercontent.com/72492794/95305972-a447c300-087e-11eb-8b18-13a80f1e063b.png)

Hey would you mind sharing how you got zone and face recognition setup? I'm curious and want to do it myself :)
