### ISSUE TITLE
Kamera Livestream ohne Funktion unter v5.0 Beta 55

### ISSUE THREAD

**Issue by Kai9555** [seydx/homebridge-camera-ui#315]
Hallo zusammen,

leider funktioniert der Livestream mit meiner TPLINK C100 weder in HomeKit noch in Camera UI, der Snapshot wird jedoch in HomeKit angezeigt. Die Beta wollte ich zwecks HSV testen. Im Übrigen ist der Streamtest in der Plugin Configuration erfolgreich (siehe Bild)
<img width="1477" alt="Bildschirmfoto 2022-01-08 um 12 25 49" src="https://user-images.githubusercontent.com/56715979/148642415-3739e86b-0f9f-457e-b821-bdc6b24866cd.png">

Hier meine Daten:

Homebridge: 1.4 Beta 4
Node.js: 16.13.1
NPM: v8.3.0

LOG:

> [08/01/2022, 12:21:35] [CameraUI] Kamera kleiner Keller: Pinging rtsp://me.com:xixsa7-binjub-vaJfoq
> [08/01/2022, 12:21:36] [CameraUI] Kamera kleiner Keller: Pinging rtsp://me.com:xixsa7-binjub-vaJfoq - failed
> [08/01/2022, 12:21:36] [CameraUI] Kamera kleiner Keller: Can not start prebuffering, camera not reachable. Trying again in 60s..
> [08/01/2022, 12:21:38] [CameraUI] Kamera kleiner Keller: Start stream requested: 1280x720, 30 fps, 299 kbps
> [08/01/2022, 12:21:38] [CameraUI] Kamera kleiner Keller: New stream added to active sessions
> [08/01/2022, 12:21:38] [CameraUI] Kamera kleiner Keller: Currently active streams: 1
> [08/01/2022, 12:21:38] [CameraUI] Kamera kleiner Keller: Incoming ping request for: rtsp://********@me.com:********@192.168.*******:554/stream1 - Timeout: 1s

Config:

 {

            "name": "CameraUI",
            "port": 1111,
            "debug": true,
            "mqtt": {
                "active": false
            },
            "http": {
                "active": false,
                "localhttp": false
            },
            "smtp": {
                "active": false
            },
            "ftp": {
                "active": false
            },
            "ssl": {
                "active": false
            },
            "cameras": [
                {
                    "name": "Kamera kleiner Keller",
                    "manufacturer": "TP Link",
                    "model": "C100",
                    "serialNumber": "123456",
                    "privacySwitch": true,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://********@me.com:**********@192.168.*****:554/stream1",
                        "subSource": "-i rtsp://********@me.com:**********@192.168.*****:554/stream2",
                        "readRate": false,
                        "rtspTransport": "http",
                        "maxStreams": 1,
                        "forceMax": false,
                        "vcodec": "copy",
                        "audio": true,
                        "debug": true
                    },
                    "videoanalysis": {
                        "active": false
                    }
                }
            ],
            "platform": "CameraUI"
        }

Irgend eine Idee?

**Comment by seydx** [comment]
Ja camera.ui kann die Kamera nicht anpingen weil es die Adresse falsch auflöst. Werde ich fixen danke

lg

**Comment by Kai9555** [comment]
> Ja camera.ui kann die Kamera nicht anpingen weil es die Adresse falsch auflöst. Werde ich fixen danke
> 
> lg

Wow wie schnell hast du denn bitte geantwortet 😆

Danke und VG

**Comment by seydx** [comment]
Sollte in Beta 56 gefixt sein, kannst du probieren bitte

lg

**Comment by Kai9555** [comment]
Funktioniert - perfekt 💪🏻
