### ISSUE TITLE
UI Interface outside the area on iPad Pro 12,9”

### ISSUE THREAD

**Issue by grzegorz914** [seydx/homebridge-camera-ui#325]
As you see on the screenshot the interface is outside the control area.
Tested with app ver. 5.x.x and iPad Pro 12,9”

![CF832849-5D81-4D0B-B31A-D133B4D0E204](https://user-images.githubusercontent.com/28867813/148978440-41c9bd1d-17e9-4d82-a50d-d57ebf1adea0.jpeg)

**Comment by seydx** [comment]
Hey @grzegorz914 

thx, already fixed in the next version, just looking for some other bugs before pushing it :)

**Comment by grzegorz914** [comment]
Nice, also the camera view screen do not have correct aspect ratio.
![9293DDC2-49E0-4589-B96E-D57371921A41](https://user-images.githubusercontent.com/28867813/148979056-9b6329fc-dd47-42a5-9984-0edfccd372dc.png)

**Comment by seydx** [comment]
> Nice, also the camera view screen do not have correct aspect ratio. ![9293DDC2-49E0-4589-B96E-D57371921A41](https://user-images.githubusercontent.com/28867813/148979056-9b6329fc-dd47-42a5-9984-0edfccd372dc.png)

Yes, as mentioned here https://github.com/seydx/homebridge-camera-ui/issues/124

Like the widgets on the dashboard, you can resize the camera tiles on Camview and camera.ui will store the size and positions for you in localStorage.

I will try to find another solution for this problem in a later version

**Comment by seydx** [comment]
@grzegorz914 

like here:

https://user-images.githubusercontent.com/34152761/148979915-9c5fe1ce-613e-4eb2-8d65-550f2a9c7d5c.mov

**Comment by grzegorz914** [comment]
Ah OK I see this possibility now, thanks.

**Comment by seydx** [comment]
@grzegorz914 

Just saw it, you can add camera.ui from Safari to home screen, it looks so much better as PWA instead of a normal web page :P

![IMG_F24975B0D8C6-1](https://user-images.githubusercontent.com/34152761/148985572-74a41353-b04f-48f5-b179-cf0418595a46.jpeg)

**Comment by grzegorz914** [comment]
Yes, I know this possibility, as a tip You can add Hyperlink to the plugin config in my screen.
![C20BD502-93F6-4E16-B97D-75F31D996A5B](https://user-images.githubusercontent.com/28867813/148986937-c17f5e79-a074-403d-8bb6-7ecc7c79d089.jpeg)

**Comment by grzegorz914** [comment]
In other things, are you think about add PTZ control?

**Comment by grzegorz914** [comment]
Yes, ONVIF is good standard and will be nice to have this as next feature.

**Comment by seydx** [comment]
> As you see on the screenshot the interface is outside the control area. Tested with app ver. 5.x.x and iPad Pro 12,9”
> 
> ![CF832849-5D81-4D0B-B31A-D133B4D0E204](https://user-images.githubusercontent.com/28867813/148978440-41c9bd1d-17e9-4d82-a50d-d57ebf1adea0.jpeg)

Fixed in v5.0.4

> Yes, I know this possibility, as a tip You can add Hyperlink to the plugin config in main screen. ![C20BD502-93F6-4E16-B97D-75F31D996A5B](https://user-images.githubusercontent.com/28867813/148986937-c17f5e79-a074-403d-8bb6-7ecc7c79d089.jpeg)

Added in v5.0.4

**Comment by grzegorz914** [comment]
Updated, all working correct.

**Comment by grzegorz914** [comment]
One more thing, the menu button is in background back the camera view:
![CF08269C-623F-48C0-93DF-387DC63FD27B](https://user-images.githubusercontent.com/28867813/149001739-690ddf6d-9429-4c3c-980f-186c90811d39.jpeg)

**Comment by seydx** [comment]
> One more thing, the menu button is in background back the camera view: ![CF08269C-623F-48C0-93DF-387DC63FD27B](https://user-images.githubusercontent.com/28867813/149001739-690ddf6d-9429-4c3c-980f-186c90811d39.jpeg)

v5.0.5-beta.0

**Comment by grzegorz914** [comment]
![53794A68-FD2B-4BF8-BBB1-2CAFEF0BCEF3](https://user-images.githubusercontent.com/28867813/149017625-5a284564-292d-43c2-8e0d-79cc861ba918.jpeg)

**Comment by seydx** [comment]
> ![53794A68-FD2B-4BF8-BBB1-2CAFEF0BCEF3](https://user-images.githubusercontent.com/28867813/149017625-5a284564-292d-43c2-8e0d-79cc861ba918.jpeg)

Yes I wanted to keep it a little transparent so that it does not disturb

**Comment by grzegorz914** [comment]
I think for better experiences You need reserve som space in top area for interface control elements.

**Comment by seydx** [comment]
> I think for better experiences You need reserve some space in top area for interface control elements.

I think I will add an "auto hide" function to hide the buttons after a certain time and show them again when tapping the screen

**Comment by grzegorz914** [comment]
This is also very good idea.
