### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by grzegorz914** [seydx/homebridge-camera-ui#326]
@seydx 

accidentally I get some times after Motion ON memory leak, this was happened in 5.x.x beta and release:

OS: Raspbian GNU/Linux Bullseye (11)
Node: v16.3.1
Hardware: RPI 4B

```
[12.01.2022, 07:44:27] [CameraUI] Tył: Motion ON
(node:9259) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added to [HAPConnection]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
[12.01.2022, 07:44:42] [CameraUI] Tył: Motion handler timeout.
[12.01.2022, 07:44:47] [CameraUI] Tył: Closing recording process
```

**Comment by seydx** [comment]
Hey, can u try v5.0.5-beta.6 pls

`sudo npm i -g homebridge-camera-ui@5.0.0-beta.6`

**Comment by grzegorz914** [comment]
I will do but need some time to test this  because memory leak not always happens.

**Comment by grzegorz914** [comment]
It’s appear again, same scenario after trigger motion on. The motion is triggered on over built in video analysis.

**Comment by seydx** [comment]
> HAPConnection

how many cameras do you have?

**Comment by seydx** [comment]
> It’s appear again, same scenario after trigger motion on. The motion is triggered on over built in video analysis.

how many cameras do you have?

**Comment by seydx** [comment]
v5.0.5-beta.7

can u enable `debug` in config.json and start homebridge with `--trace-warnings --unhandled-rejections=strict` please. That would help me a lot

<img width="486" alt="Bildschirmfoto 2022-01-13 um 03 20 12" src="https://user-images.githubusercontent.com/34152761/149254400-3dee3947-bf93-4ec9-94dc-d0d01cea7e5c.png">

**Comment by grzegorz914** [comment]
@seydx 

already other error beta 7
![505AB389-EDE5-4F69-874C-393D799E15F7](https://user-images.githubusercontent.com/28867813/149270136-d78f5f74-d61c-42b6-bf3f-897b805a843d.jpeg)
:

**Comment by seydx** [comment]
oh lol my bad, should be `clearTimeout()` instead of `this.clearTimeout()`

fixing..

**Comment by grzegorz914** [comment]
And what is this all not rewriting:

![398264F5-46CC-4169-96AF-CBD38D18AB67](https://user-images.githubusercontent.com/28867813/149270413-c761a203-a871-41ce-8f47-4f9cf8e12988.jpeg)

**Comment by seydx** [comment]
> And what is this all not rewriting:
> 
> ![398264F5-46CC-4169-96AF-CBD38D18AB67](https://user-images.githubusercontent.com/28867813/149270413-c761a203-a871-41ce-8f47-4f9cf8e12988.jpeg)

Thats from the internal history api, only shown if debug is enabled

**Comment by seydx** [comment]
@grzegorz914 

5.0.5-beta.8 online

`sudo npm i -g homebridge-camera-ui@5.0.5-beta.8`

**Comment by grzegorz914** [comment]
again some error:

```
[13.01.2022, 07:48:51] [CameraUI] GET /files/Prz%C3%B3d-241d97da2f-1642055942_c_CUI.mp4 206 40.866 ms - 7202828
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:98:16)
[13.01.2022, 07:48:51] [CameraUI] GET /api/recordings?page=4 200 4.714 ms - 1395
[13.01.2022, 07:48:52] [CameraUI] GET /files/Prz%C3%B3d-241d97da2f-1642055942_c_CUI.mp4 206 4.745 ms - 6875148
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:98:16)
[13.01.2022, 07:48:53] [CameraUI] GET /api/settings/general 304 5.110 ms - -
[13.01.2022, 07:48:53] [CameraUI] GET /files/Ty%C5%82-106e6be348-1642014617_c_CUI@2.jpeg 200 12.876 ms - 84779
[13.01.2022, 07:48:53] [CameraUI] GET /files/Ty%C5%82-fcd2b31583-1642014324_c_CUI@2.jpeg 200 2.680 ms - 85140
[13.01.2022, 07:48:53] [CameraUI] GET /files/Ty%C5%82-d7450e487f-1642014110_c_CUI@2.jpeg 200 2.711 ms - 86487
[13.01.2022, 07:48:53] [CameraUI] GET /files/Prz%C3%B3d-241d97da2f-1642055942_c_CUI.mp4 206 14.600 ms - 6481932
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:98:16)
[13.01.2022, 07:48:53] [CameraUI] GET /files/Ty%C5%82-e8f174ebb2-1642013411_c_CUI@2.jpeg 200 3.824 ms - 85445
[13.01.2022, 07:48:53] [CameraUI] GET /files/Ty%C5%82-1bec459342-1642012953_c_CUI@2.jpeg 200 3.563 ms - 85701
[13.01.2022, 07:48:54] [CameraUI] GET /files/Prz%C3%B3d-241d97da2f-1642055942_c_CUI.mp4 206 6.026 ms - 6154252
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:98:16)
[13.01.2022, 07:48:55] [CameraUI] GET /files/Prz%C3%B3d-241d97da2f-1642055942_c_CUI.mp4 206 14.382 ms - 5761036
```

**Comment by seydx** [comment]
> again some error:
> 
> ```
> [13.01.2022, 07:48:51] [CameraUI] GET /files/Prz%C3%B3d-241d97da2f-1642055942_c_CUI.mp4 206 40.866 ms - 7202828
> Error: write EPIPE
>     at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:98:16)
> [13.01.2022, 07:48:51] [CameraUI] GET /api/recordings?page=4 200 4.714 ms - 1395
> [13.01.2022, 07:48:52] [CameraUI] GET /files/Prz%C3%B3d-241d97da2f-1642055942_c_CUI.mp4 206 4.745 ms - 6875148
> Error: write EPIPE
>     at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:98:16)
> [13.01.2022, 07:48:53] [CameraUI] GET /api/settings/general 304 5.110 ms - -
> [13.01.2022, 07:48:53] [CameraUI] GET /files/Ty%C5%82-106e6be348-1642014617_c_CUI@2.jpeg 200 12.876 ms - 84779
> [13.01.2022, 07:48:53] [CameraUI] GET /files/Ty%C5%82-fcd2b31583-1642014324_c_CUI@2.jpeg 200 2.680 ms - 85140
> [13.01.2022, 07:48:53] [CameraUI] GET /files/Ty%C5%82-d7450e487f-1642014110_c_CUI@2.jpeg 200 2.711 ms - 86487
> [13.01.2022, 07:48:53] [CameraUI] GET /files/Prz%C3%B3d-241d97da2f-1642055942_c_CUI.mp4 206 14.600 ms - 6481932
> Error: write EPIPE
>     at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:98:16)
> [13.01.2022, 07:48:53] [CameraUI] GET /files/Ty%C5%82-e8f174ebb2-1642013411_c_CUI@2.jpeg 200 3.824 ms - 85445
> [13.01.2022, 07:48:53] [CameraUI] GET /files/Ty%C5%82-1bec459342-1642012953_c_CUI@2.jpeg 200 3.563 ms - 85701
> [13.01.2022, 07:48:54] [CameraUI] GET /files/Prz%C3%B3d-241d97da2f-1642055942_c_CUI.mp4 206 6.026 ms - 6154252
> Error: write EPIPE
>     at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:98:16)
> [13.01.2022, 07:48:55] [CameraUI] GET /files/Prz%C3%B3d-241d97da2f-1642055942_c_CUI.mp4 206 14.382 ms - 5761036
> ```

no thats already fixed in v5.0.5-beta.9, edited my post above

**Comment by grzegorz914** [comment]
I get also if stream start this, no res, no fps:

`[13.01.2022, 08:28:45] [CameraUI] Przód: Starting video stream: nativexnative, native fps, ??? kbps `

**Comment by seydx** [comment]
> I get also if stream start this, no res, no fps:
> 
> `[13.01.2022, 08:28:45] [CameraUI] Przód: Starting video stream: nativexnative, native fps, ??? kbps `

Yep thats right, because you have vcodec = copy - that just mean that camera.ui starts the stream with the native camera parameter

**Comment by grzegorz914** [comment]
OK, may be print log with:

`Starting video stream: native`

all other parameter are irrelevant.

**Comment by seydx** [comment]
> OK, may be print log with:
> 
> `Starting video stream: native`
> 
> all other parameter are irrelevant.

done in v5.0.5-beta.10

**Comment by seydx** [comment]
v5.0.5 online

any memory leaks so far?

**Comment by grzegorz914** [comment]
no, looks like all ok but continue testing.

**Comment by grzegorz914** [comment]
So, after 12h test No any memory leak,  looks like the problem is solved and can be closed.
