### ISSUE TITLE
Error in HB log not always

### ISSUE THREAD

**Issue by grzegorz914** [seydx/homebridge-camera-ui#327]
Some times in HB log get error:

```
bridge/camera.ui/recordings/Tył-0d04f2a0a9-1641978588_c_CUI.mp4'
Error: ENOENT: no such file or directory, stat '/var/lib/homebridge/camera.ui/recordings/Tył-0d04f2a0a9-1641978588_c_CUI.mp4'
```

**Comment by seydx** [comment]
That occurs if the ui can not find the camera recording anymore. Eg when u remove all recordings and switch to „notifications“ page, this „warning“ will be shown in the log which just simply indicates that the requested recording not available anymore

**Comment by grzegorz914** [comment]
OK, may be move to debug, it’s not relevant info?

**Comment by seydx** [comment]
allright, done in v5.0.5-beta.7

**Comment by seydx** [comment]
v5.0.5 online
