### ISSUE TITLE
Aspect ratio cams on dashboard screen iPhone

### ISSUE THREAD

**Issue by grzegorz914** [seydx/homebridge-camera-ui#329]
@seydx 

The aspect ratio for cams on dashboard screen on iPhone in landscape/portrait mode is not displayed correct, always 1:1.
On all other screen are displays correct.

![IMG_2088](https://user-images.githubusercontent.com/28867813/149308140-5041f6bd-34e7-4654-a200-26026606ca70.PNG)
![IMG_2089](https://user-images.githubusercontent.com/28867813/149308174-5b3eff62-cd4b-4a75-b51f-0c5f9feadf5e.PNG)

**Comment by seydx** [comment]
Hm, It looks like the resize handler has hung up

Her on my iphone

![10F80925-4207-4DE7-B4E9-EAD35235000A](https://user-images.githubusercontent.com/34152761/149321954-968c9836-fc20-4cbd-afe1-d232e3006671.png)

**Comment by grzegorz914** [comment]
Ah, OK in portrait mode it is difficult to find the lock button. 
I have done this in landscape mode and now all is OK.

Thanks
