### ISSUE TITLE
Unable to get feed through on camera.

### ISSUE THREAD

**Issue by Fookes74** [seydx/homebridge-camera-ui#333]
I've configured a test camera with info taken from the config used in ffmpeg plugin. The camera shows up and can be added in to Home app but no stream shows. Camera shows as offline. Looking at logs I see this:

Fmpeg prebuffer process exited with error! (null) - [rtsp @ 0x3f97410] method DESCRIBE failed: 404 Stream Not Foundrtsp://192.168.1.115/ch0_1.h264: Server returned 404 Not Found

Not sure what I'm doing wrong. There are some sections I'm unsure how to complete so this may be a factor. Any help would be appreciated.

**Comment by seydx** [comment]
Error found?

**Comment by Fookes74** [comment]
> Error found?

It seems so. I took the camera out, put back in identically and it worked. Not sure why it didn't first time. This is fantastic, btw. Great job.
