### ISSUE TITLE
Save recordings on ftp drive

### ISSUE THREAD

**Issue by Kai9555** [seydx/homebridge-camera-ui#337]
Hallo seydx,

erst einmal Respekt für das Plugin. Ist ja Wahnsinn was du hier auf die Beine gestellt hast!

Einrichtung und Verbindung zu HSV hat mit meiner TP Link C100 Kamera ohne Probleme funktioniert. Leider erhalte ich jedoch eine Fehlermeldung beim speichern der Aufnahme auf ein FTP Laufwerk. Es handelt sich natürlich um einen freien FTP Ordner ohne PW. Des Weiteren habe ich im LOG eine Fehlermeldung zum Motionsensor, die ich nicht ganz nachvollziehen kann, da die Bewegungserkennung und Aufzeichnung in HSV eigentlich ohne Probleme funktioniert.

Hier mein LOG:

```
[14/01/2022, 09:31:43] [CameraUI] Keller 1: Motion ON
[14/01/2022, 09:31:58] [CameraUI] Keller 1: Motion OFF - Motion handler timeout.
[14/01/2022, 09:32:01] [CameraUI] Keller 1: Closing recording process
[14/01/2022, 09:32:01] [CameraUI] Keller 1: An error occured during handling motion event
[14/01/2022, 09:32:01] [CameraUI] Error: FFmpeg snapshot process exited with error! (null) - ftp://192.168.2.2/Kameraufnahmen//Keller_1-49e631d120-1642149122_c_CUI.mp4: Input/output error
```

Wenn ich den FTP Ordner mit Benutzername und PW anlege erhalte ich den Fehler im LOG:

```
[14/01/2022, 10:07:05] [CameraUI] Error: FFmpeg snapshot process exited with error! (null) - [mov,mp4,m4a,3gp,3g2,mj2 @ 0x2650c20] moov atom not found - ftp://Nutzername:Passwort@192.168.2.2/Kameraufnahmen/Keller_1-27a740328f-1642151225_c_CUI.mp4: Invalid data found when processing input
```

Hier meien Config:

```
{
            "name": "CameraUI",
            "port": 1111,
            "debug": false,
            "mqtt": {
                "active": false
            },
            "http": {
                "active": false,
                "localhttp": false
            },
            "smtp": {
                "active": false
            },
            "ftp": {
                "active": false
            },
            "ssl": {
                "active": false
            },
            "cameras": [
                {
                    "name": "Keller 1",
                    "manufacturer": "TP Link",
                    "model": "C100",
                    "serialNumber": "123456",
                    "privacySwitch": true,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://*********,
                        "readRate": false,
                        "analyzeDuration": 1000000,
                        "maxStreams": 3,
                        "maxWidth": 0,
                        "maxHeight": 0,
                        "maxFPS": 0,
                        "forceMax": false,
                        "vcodec": "copy",
                        "acodec": "copy",
                        "audio": true,
                        "debug": false
                    },
                    "videoanalysis": {
                        "active": true
                    }
                }
            ],
            "platform": "CameraUI"
```

**Comment by seydx** [comment]
> Hallo seydx,
> 
> erst einmal Respekt für das Plugin. Ist ja Wahnsinn was du hier auf die Beine gestellt hast!
> 
> Einrichtung und Verbindung zu HSV hat mit meiner TP Link C100 Kamera ohne Probleme funktioniert. Leider erhalte ich jedoch eine Fehlermeldung beim speichern der Aufnahme auf ein FTP Laufwerk. Es handelt sich natürlich um einen freien FTP Ordner ohne PW. Des Weiteren habe ich im LOG eine Fehlermeldung zum Motionsensor, die ich nicht ganz nachvollziehen kann, da die Bewegungserkennung und Aufzeichnung in HSV eigentlich ohne Probleme funktioniert.
> 
> Hier mein LOG:
> 
> ```
> [14/01/2022, 09:31:43] [CameraUI] Keller 1: Motion ON
> [14/01/2022, 09:31:58] [CameraUI] Keller 1: Motion OFF - Motion handler timeout.
> [14/01/2022, 09:32:01] [CameraUI] Keller 1: Closing recording process
> [14/01/2022, 09:32:01] [CameraUI] Keller 1: An error occured during handling motion event
> [14/01/2022, 09:32:01] [CameraUI] Error: FFmpeg snapshot process exited with error! (null) - ftp://192.168.2.2/Kameraufnahmen//Keller_1-49e631d120-1642149122_c_CUI.mp4: Input/output error
> ```
> 
> Wenn ich den FTP Ordner mit Benutzername und PW anlege erhalte ich den Fehler im LOG:
> 
> ```
> [14/01/2022, 10:07:05] [CameraUI] Error: FFmpeg snapshot process exited with error! (null) - [mov,mp4,m4a,3gp,3g2,mj2 @ 0x2650c20] moov atom not found - ftp://Nutzername:Passwort@192.168.2.2/Kameraufnahmen/Keller_1-27a740328f-1642151225_c_CUI.mp4: Invalid data found when processing input
> ```
> 
> Hier meien Config:
> 
> ```
> {
>             "name": "CameraUI",
>             "port": 1111,
>             "debug": false,
>             "mqtt": {
>                 "active": false
>             },
>             "http": {
>                 "active": false,
>                 "localhttp": false
>             },
>             "smtp": {
>                 "active": false
>             },
>             "ftp": {
>                 "active": false
>             },
>             "ssl": {
>                 "active": false
>             },
>             "cameras": [
>                 {
>                     "name": "Keller 1",
>                     "manufacturer": "TP Link",
>                     "model": "C100",
>                     "serialNumber": "123456",
>                     "privacySwitch": true,
>                     "unbridge": true,
>                     "hsv": true,
>                     "prebuffering": true,
>                     "prebufferLength": 4,
>                     "videoConfig": {
>                         "source": "-i rtsp://*********,
>                         "readRate": false,
>                         "analyzeDuration": 1000000,
>                         "maxStreams": 3,
>                         "maxWidth": 0,
>                         "maxHeight": 0,
>                         "maxFPS": 0,
>                         "forceMax": false,
>                         "vcodec": "copy",
>                         "acodec": "copy",
>                         "audio": true,
>                         "debug": false
>                     },
>                     "videoanalysis": {
>                         "active": true
>                     }
>                 }
>             ],
>             "platform": "CameraUI"
> ```

Hallo @Kai9555 

Ja das passiert weil du die Aufnahme auf ein FTP Laufwerk speichern möchtest. Zurzeit kann camera.ui die Aufnahmen nur lokal abspeichern (speicherkarte etc sollte auch funktionieren)

ich ändere mal den issue etwas ab da es eher ein Feature Request ist und nehme es in meine Todo Liste auf.

Bis dato kannst du ja erstmal lokal abspeichern die Aufnahmen

lg

**Comment by seydx** [comment]
> @seydx
> 
> das hat zwar nichts mit dem Thema hier zu tun, aber ich wollte deswegen kein eigenes aufmachen.
> 
> Entweder ich stelle mich zu blöd an, aber ich verstehe die beiden Werte „verweilzeit“ und „Motion tricker“ im Zusammenhang zu HSV nicht ganz.
> 
> Ich möchte eigentlich nur das bei einer erkannten Bewegung die Aufnahme für 2 oder 3 Minuten läuft. Stattdessen habe ich tausend kleine Aufnahmeschnipsel bei jeder Bewegung.
> 
> hast du einen Tipp wie ich es konfigurieren kann?
> 
> danke dir

Hey @Kai9555 

Meinst du die Aufnahmen in Apple Home?

Ich schließe mal den Thread hier (hab ein neues aufgemacht wegen FTP etc)

**Comment by Kai9555** [comment]
> > @seydx
> > das hat zwar nichts mit dem Thema hier zu tun, aber ich wollte deswegen kein eigenes aufmachen.
> > Entweder ich stelle mich zu blöd an, aber ich verstehe die beiden Werte „verweilzeit“ und „Motion tricker“ im Zusammenhang zu HSV nicht ganz.
> > Ich möchte eigentlich nur das bei einer erkannten Bewegung die Aufnahme für 2 oder 3 Minuten läuft. Stattdessen habe ich tausend kleine Aufnahmeschnipsel bei jeder Bewegung.
> > hast du einen Tipp wie ich es konfigurieren kann?
> > danke dir
> 
> Hey @Kai9555
> 
> Meinst du die Aufnahmen in Apple Home?
> 
> Ich schließe mal den Thread hier (hab ein neues aufgemacht wegen FTP etc)

Ja die Aufnahmen in Apple Home. Ziel: Bewegung erkannt = starte Aufnahme für 2 Minuten. Bei erneuter Bewegung innerhalb der 2 Minuten = reset für weitere 2 Minuten. Habe es bis jetzt nicht geschafft. Aber  nicht so wichtig..ich warte auf eine ONVIF-integration. Die Bewegungserkennung über Bildananylse ist mir nicht zuverlässig genug.
