### ISSUE TITLE
Recording time camera.ui for HKSV

### ISSUE THREAD

**Issue by grzegorz914** [seydx/homebridge-camera-ui#340]
@seydx 

I have set recording time in camera.ui to 40sec but this have not impact, always record 20sec.

**Comment by seydx** [comment]
> @seydx
> 
> I have set recording time in camera.ui to 40sec but this have not impact, always record 20sec.

You mean in the UI? Recording time in the ui is only for recording through camera.ui (if HSV is not enabled)

**Comment by grzegorz914** [comment]
OK, now is clear. May be lock or hide this function if HSV is ON

**Comment by seydx** [comment]
> OK, now is clear. May be lock or hide this function if HSV is ON

i will link the recording time to "motionTimeout" to change the recording time also for HKSV

Marking this as enahncement

**Comment by seydx** [comment]
Added in v5.0.8

[example-config.json](https://github.com/seydx/homebridge-camera-ui/blob/a4739f30c5d009dc61329bc5d23b36304719bd6c/example-config.json#L56)

Note: The length of the recording could vary if prebuffering is active (recording time + prebuffering)
