### ISSUE TITLE
HSV Closed recording with reason "3" or "5"

### ISSUE THREAD

**Issue by benepixx** [seydx/homebridge-camera-ui#342]
Anybody got any ideas what error 3 is when HSV cancels recording?

[1/15/2022, 3:58:55 PM] [CameraUI] test 2: Closing recording process
[1/15/2022, 3:58:55 PM] [CameraUI] Resetting motion state because HSV closed recording with reason "3"
[1/15/2022, 3:58:55 PM] [CameraUI] test 2: FFMPEG socket closed during read for 8 bytes!
[1/15/2022, 3:58:55 PM] [CameraUI] test 2: Skip saving the recording, the file might be corrupted because the recording process was cancelled by HSV
[1/15/2022, 3:58:55 PM] [CameraUI] test 2: Prebuffer request ended
[1/15/2022, 3:58:55 PM] [CameraUI] test 2: FFmpeg recording process exited (expected)

**Comment by seydx** [comment]
@benepixx 

This is mostly due to a wrong config.json and/or camera settings

can you post your config.json pls and a screenshot of your camera settings (like bitrate, resolution, fps etc)

**Comment by benepixx** [comment]
{
            "name": "CameraUI",
            "port": 60000,
            "debug": true,
            "mqtt": {
                "active": false
            },
            "http": {
                "active": false,
                "localhttp": false
            },
            "smtp": {
                "active": false
            },
            "ftp": {
                "active": false
            },
            "ssl": {
                "active": false
            },
            "cameras": [
                {
                    "name": "test 2",
                    "manufacturer": "Dahua",
                    "model": "Smart Turret Cam",
                    "serialNumber": "0000",
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "forcePrebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://admin:XXXXX@XXXXXXXXX:554/cam/realmonitor?channel=1&subtype=0",
                        "subSource": "-i rtsp://admin:XXXXXXXXX@XXXXXXXXX:554/cam/realmonitor?channel=1&subtype=1",
                        "stillImageSource": "-i http://admin:XXXXXXXXX@XXXXXXXXX/cgi-bin/snapshot.cgi?channel=1",
                        "audio": false
                    },
                    "videoanalysis": {
                        "active": true
                    }
                }
            ],
            "platform": "CameraUI"
        
<img width="957" alt="Screenshot 2022-01-15 at 16 10 36" src="https://user-images.githubusercontent.com/53353052/149628965-e94cdfde-9dc2-4ff5-bc30-28f2bcfaaec9.png">
}

**Comment by seydx** [comment]
@benepixx 

### Camera settings:

**Main Stream:**
FPS: 30
I Frame Interval: 120 (this value must be 4x higher than FPS, eg FPS 30 * 4 = 120)

**Substream:**
Resolution: 640x360 (if possible)
I Frame Interval: 80

### Config

```json
{
  "name": "CameraUI",
  "port": 60000,
  "debug": true,
  "mqtt": {
    "active": false
  },
  "http": {
    "active": false,
    "localhttp": false
  },
  "smtp": {
    "active": false
  },
  "ftp": {
    "active": false
  },
  "ssl": {
    "active": false
  },
  "cameras": [
    {
      "name": "test 2",
      "manufacturer": "Dahua",
      "model": "Smart Turret Cam",
      "serialNumber": "0000",
      "unbridge": true,
      "hsv": true,
      "prebuffering": true,
      "forcePrebuffering": true,
      "prebufferLength": 4,
      "videoConfig": {
        "source": "-i rtsp://admin:XXXXX@XXXXXXXXX:554/cam/realmonitor?channel=1&subtype=0",
        "subSource": "-i rtsp://admin:XXXXXXXXX@XXXXXXXXX:554/cam/realmonitor?channel=1&subtype=1",
        "stillImageSource": "-i http://admin:XXXXXXXXX@XXXXXXXXX/cgi-bin/snapshot.cgi?channel=1",
        "rtspTransport": "tcp",
        "vcodec": "copy",
        "acodec": "libfdk_aac",
        "audio": false
      },
      "videoanalysis": {
        "active": true
      }
    }
  ],
  "platform": "CameraUI"
}
```

**Comment by benepixx** [comment]
Thanks so much you've saved me hours of head scratching there. :)

**Comment by Tombra1889** [comment]
I have the same Problem:

`[15/01/2022, 18:53:33] [CameraUI] Entry: Recording started
[15/01/2022, 18:53:41] [CameraUI] Entry: frame=  102 fps= 13 q=-1.0 size=     767kB time=00:00:08.00 bitrate= 785.4kbits/s speed=1.01x    
[15/01/2022, 18:53:42] [CameraUI] Entry: Closing recording process
[15/01/2022, 18:53:42] [CameraUI] Resetting motion state because HSV closed recording with reason "5"
[15/01/2022, 18:53:42] [CameraUI] Entry: FFMPEG socket closed during read for 8 bytes!
[15/01/2022, 18:53:42] [CameraUI] Entry: Skip saving the recording, the file might be corrupted because the recording process was cancelled by HSV
[15/01/2022, 18:53:42] [CameraUI] Entry: Prebuffer request ended
[15/01/2022, 18:53:42] [CameraUI] Entry: FFmpeg recording process exited (expected)
[15/01/2022, 18:53:48] [CameraUI] Entry: Motion OFF - Motion handler timeout.
`

<img width="470" alt="image" src="https://user-images.githubusercontent.com/60692414/149632476-e37033f3-eada-4ac0-b3e8-5de0621c30ce.png">


`{
            "name": "CameraUI",
            "port": 8583,
            "debug": true,
            "mqtt": {
                "active": false
            },
            "http": {
                "active": true,
                "port": 8582,
                "localhttp": false
            },
            "smtp": {
                "active": false
            },
            "ftp": {
                "active": false
            },
            "ssl": {
                "active": false
            },
            "cameras": [
                {
                    "name": "Entry",
                    "manufacturer": "INSTAR",
                    "model": "N-5907HD-PoE",
                    "motion": true,
                    "doorbell": true,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://user:pw@192.168.1.19/11",
                        "subSource": "-i rtsp://user:pw@192.168.1.19/12",
                        "stillImageSource": "-i http://192.168.66.19/tmpfs/snap.jpg?usr=user&pwd=pw",
                        "rtspTransport": "tcp",
                        "vcodec": "copy",
                        "acodec": "copy",
                        "audio": false,
                        "debug": true
                    },
                    "videoanalysis": {
                        "active": false
                    }
                }`

**Comment by seydx** [comment]
> 

Can you send me the whole log pls

what are all the options in „Video-Encoding“ ?

**Comment by ChrisBuHa** [comment]
@seydx I have the same problems recording the videos with HSV. 
Can you please check my settings? I would really appreciate it! 

 

{
            "name": "CameraUI",
            "debug": false,
            "mqtt": {
                "active": false
            },
            "http": {
                "active": false,
                "localhttp": false
            },
            "smtp": {
                "active": false
            },
            "ftp": {
                "active": false
            },
            "ssl": {
                "active": false
            },
            "cameras": [
                {
                    "name": "Kamera Garten",
                    "manufacturer": "Foscam",
                    "model": "F41",
                    "motion": true,
                    "switches": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://ChrisBuHa:XXXXXXXX@XXXXXXXXX:88/videoMain",
                        "subSource": "-i rtsp://ChrisBuHa:XXXXXXXX@XXXXXXXXX:88/videoSub",
                        "stillImageSource": "-i http://ChrisBuHa:XXXXXXXXX@XXXXXXXXX0:88/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=ChrisBuHa&pwd=XXXXXXX
",
                        "rtspTransport": "tcp",
                        "maxWidth": 0,
                        "maxHeight": 0,
                        "maxFPS": 0,
                        "vcodec": "libx264",
                        "audio": true
                    },
                    "videoanalysis": {
                        "active": true
                    }
                }
            ],
            "platform": "CameraUI"
        }



![video settings 1](https://user-images.githubusercontent.com/94866088/149633326-db3900c8-1e96-45ca-8fa5-736f9a090430.png)

**Comment by seydx** [comment]
> @seydx I have the same problems recording the videos with HSV. Can you please check my settings? I would really appreciate it!
> 
> { "name": "CameraUI", "debug": false, "mqtt": { "active": false }, "http": { "active": false, "localhttp": false }, "smtp": { "active": false }, "ftp": { "active": false }, "ssl": { "active": false }, "cameras": [ { "name": "Kamera Garten", "manufacturer": "Foscam", "model": "F41", "motion": true, "switches": true, "hsv": true, "prebuffering": true, "prebufferLength": 4, "videoConfig": { "source": "-i rtsp://ChrisBuHa:XXXXXXXX@XXXXXXXXX:88/videoMain", "subSource": "-i rtsp://ChrisBuHa:XXXXXXXX@XXXXXXXXX:88/videoSub", "stillImageSource": "-i http://ChrisBuHa:XXXXXXXXX@XXXXXXXXX0:88/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=ChrisBuHa&pwd=XXXXXXX ", "rtspTransport": "tcp", "maxWidth": 0, "maxHeight": 0, "maxFPS": 0, "vcodec": "libx264", "audio": true }, "videoanalysis": { "active": true } } ], "platform": "CameraUI" }
> 
> ![video settings 1](https://user-images.githubusercontent.com/94866088/149633326-db3900c8-1e96-45ca-8fa5-736f9a090430.png)

1)

- Set „Key Frame Interval“ to 100 on your main stream
- Set rate control mode to CBR

also start with Full HD for resolution and see if it works without issues. If yes, set resolution higher for main stream

2)

- Key Frame Interval to 44

NOTE: Key Frame Interval must be always four times higher then FPS (eg FPS 30x4 = 120)

**Comment by ChrisBuHa** [comment]
For Rate control mode only VBR is selectable. 
The other settings I have changed as recommended by you. 

![video settings 2](https://user-images.githubusercontent.com/94866088/149633742-e460f0c9-9725-4214-ba88-7c3cf7130e82.png)

**Comment by seydx** [comment]
> For Rate control mode only VBR is selectable. The other settings I have changed as recommended by you.
> 
> ![video settings 2](https://user-images.githubusercontent.com/94866088/149633742-e460f0c9-9725-4214-ba88-7c3cf7130e82.png)

ah ok, then set bitrate control to "none" and try if it works

**Comment by ChrisBuHa** [comment]
Unfortunately I still get the message that the recording process was cancelled.

**Comment by seydx** [comment]
> Unfortunately I still get the message that the recording process was cancelled.

Set `"vcodec": "copy"` in config.json and try without audio, if that works, enable audio again

**Comment by ChrisBuHa** [comment]
Although I spent hours yesterday evening, I did not get the HSV recording working.

The modification of the mainStream settings and subStream settings as recommended by you seem not to have any effect. My camera is limited to 25 fps but homekit always starts the stream with 30 fps, although I set `Maximum Framerate` to `0`.

Log of ipad stream:
![7A39A189-566E-4AD1-904A-E7B66631FAF7](https://user-images.githubusercontent.com/94866088/149653398-612199a4-1e41-4f77-821c-70635b92f52c.jpeg)

log of iPhone stream:
![14D15B43-5806-49F2-B5E1-5E0F80016512](https://user-images.githubusercontent.com/94866088/149653413-2e066202-eb9b-40ac-b587-ebfd9bbeedda.jpeg)


Obviously I am no expert in video encoding 😂 I am wondering why the streams start at all with 30fps when the camera is limited to 25 fps. 

In another forum I have read the fps for HSV either needs to be 30fps or 24 fps. 
But also limiting the fps to24 in the configuration menu of the camera does not effect homekit to start the stream with other than 30 fps.

**Comment by seydx** [comment]
> Although I spent hours yesterday evening, I did not get the HSV recording working.
> 
> when i try to set `vcodec` to `copy` then the live streams do not start on my iPhone and iPad any more. In the camera Ui web interface whereas the stream starts.
> 
> ![2B6E2718-E394-4F50-B19F-C2178685AF76](https://user-images.githubusercontent.com/94866088/149656015-95913b03-a385-484e-b29c-8beb01520f2d.jpeg)
> 
> Overall, the modification of the mainStream settings and subStream settings as recommended by you seem not to have any effect. My camera is limited to 25 fps but homekit always starts the stream with 30 fps, although I set `Maximum Framerate` to `0`.
> 
> Also limiting the fps with `Maximum Framerate` to `25` In camera ui plug in does not have an effect. In the ffmpeg plug in the limitation is working. If set to `25` the video starts with 25 frames/s.
> 
> Log of ipad stream: ![7A39A189-566E-4AD1-904A-E7B66631FAF7](https://user-images.githubusercontent.com/94866088/149653398-612199a4-1e41-4f77-821c-70635b92f52c.jpeg)
> 
> log of iPhone stream: ![14D15B43-5806-49F2-B5E1-5E0F80016512](https://user-images.githubusercontent.com/94866088/149653413-2e066202-eb9b-40ac-b587-ebfd9bbeedda.jpeg)
> 
> Obviously I am no expert in video encoding 😂 I am wondering why the streams start at all with 30fps when the camera is limited to 25 fps.
> 
> In another forum I have read the fps for HSV either needs to be 30fps or 24 fps. But also limiting the fps to24 in the configuration menu of the camera does not effect homekit to start the stream with other than 30 fps.

Anything above 20 FPS should be enough for HSV. Set „forceMax“ to true in config.json for the stream to take the entered values. The parameter like maxFPS etc is only for the Streaming process in Apple Home and not for HKSV

Can you disable „audio“ in your config.json and try again pls. Maybe this will fix it

**Comment by Tombra1889** [comment]
[16/01/2022, 15:32:47] [CameraUI] HTTP: New message: URL: /motion?Entry
[16/01/2022, 15:32:47] [CameraUI] Entry: Motion ON
[16/01/2022, 15:32:48] [CameraUI] Entry: Video fragments requested from HSV
[16/01/2022, 15:32:48] [CameraUI] Entry: Setting prebuffer stream as input
[16/01/2022, 15:32:48] [CameraUI] Entry: Prebuffer requested with a duration of -4s
[16/01/2022, 15:32:48] [CameraUI] Entry: Start recording...
[16/01/2022, 15:32:48] [CameraUI] Entry: Recording command: /usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg -hide_banner -analyzeduration 0 -probesize 942577 -f mp4 -i tcp://127.0.0.1:37257 -f mp4 -vcodec copy -an -movflags frag_keyframe+empty_moov+default_base_moof -max_muxing_queue_size 1024 tcp://127.0.0.1:39371
[16/01/2022, 15:32:48] [CameraUI] Entry: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'tcp://127.0.0.1:37257':
  Metadata:
    major_brand     : iso5
    minor_version   : 512
    compatible_brands: iso5iso6mp41
    encoder         : Lavf58.45.100
  Duration: 00:08:29.07, start: 504.933333
[16/01/2022, 15:32:48] [CameraUI] Entry: , bitrate: N/A
    Stream #0:0(und): Video: h264 (Baseline) (avc1 / 0x31637661), yuvj420p(pc), 1280x720, 14 kb/s, 24 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Output #0, mp4, to 'tcp://127.0.0.1:39371':
  Metadata:
    major_brand     : iso5
    minor_version   : 512
    compatible_brands: iso5iso6mp41
    encoder         : Lavf58.45.100
    Stream #0:0(und): Video: h264 (Baseline) (avc1 / 0x31637661), yuvj420p(pc), 1280x720, q=2-31, 14 kb/s, 24 fps, 30 tbr, 15360 tbn, 15360 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help

[16/01/2022, 15:32:48] [CameraUI] Entry: Recording started
[16/01/2022, 15:32:51] [CameraUI] Entry: frame=  102 fps= 30 q=-1.0 size=     921kB time=00:00:04.16 bitrate=1811.2kbits/s speed=1.22x    
[16/01/2022, 15:32:55] [CameraUI] Entry: frame=  202 fps= 27 q=-1.0 size=    1876kB time=00:00:08.30 bitrate=1851.5kbits/s speed= 1.1x    
[16/01/2022, 15:32:56] [CameraUI] Entry: Closing recording process
[16/01/2022, 15:32:56] [CameraUI] Resetting motion state because HSV closed recording with reason "5"
[16/01/2022, 15:32:56] [CameraUI] Entry: FFMPEG socket closed during read for 8 bytes!
[16/01/2022, 15:32:56] [CameraUI] Entry: Skip saving the recording, the file might be corrupted because the recording process was cancelled by HSV
[16/01/2022, 15:32:56] [CameraUI] Entry: Prebuffer request ended
[16/01/2022, 15:32:56] [CameraUI] Entry: FFmpeg recording process exited (expected)
[16/01/2022, 15:33:03] [CameraUI] Entry: Motion OFF - Motion handler timeout.

**Comment by ChrisBuHa** [comment]
Turned of audio and used the following config.json. 

Unfortunately the stream is still not recorded. 

![video settings 2](https://user-images.githubusercontent.com/94866088/149664659-1c35f624-db5b-4e1e-a8c1-b1db4b8a8643.png)
 

{
            "name": "CameraUI",
            "port": 8081,
            "debug": false,
            "mqtt": {
                "active": false
            },
            "http": {
                "active": false
            },
            "smtp": {
                "active": false
            },
            "ftp": {
                "active": false
            },
            "ssl": {
                "active": false
            },
            "cameras": [
                {
                    "name": "KameraGartentür",
                    "manufacturer": "Foscam",
                    "model": "F41",
                    "motion": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://ChrisBuHa:xxxxxxxx@xxxxxx:88/videoMain",
                        "subSource": "-i rtsp://ChrisBuHa:xxxxxxxx@xxxxxxxx:88/videoSub",
                        "stillImageSource": "-i http://ChrisBuHa:xxxxxx@xxxxxx:88/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=ChrisBuHa&pwd=xxxxxxxx",
                        "rtspTransport": "tcp",
                        "maxStreams": 2,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 25,
                        "maxBitrate": 802,
                        "forceMax": true,
                        "vcodec": "libx264",
                        "acodec": "libfdk_aac",
                        "stimeout": 10,
                        "audio": false
                    },
                    "videoanalysis": {
                        "active": true
                    }
                }
            ],
            "platform": "CameraUI"

**Comment by ChrisBuHa** [comment]
@seydx Do you have an idea why I get the following error message?

<img width="451" alt="video settings 2" src="https://user-images.githubusercontent.com/94866088/149672867-42fe8c22-ea73-4bed-8af8-6a6839690c91.png">

and

<img width="1554" alt="video settings 1" src="https://user-images.githubusercontent.com/94866088/149672899-d22ac634-d1e6-4377-b8f2-244fdb0d67ae.png">

The camera definitly supports H.264 and also H.265.

**Comment by seydx** [comment]
> @seydx Do you have an idea why I get the following error message?
> 
> <img alt="video settings 2" width="451" src="https://user-images.githubusercontent.com/94866088/149672867-42fe8c22-ea73-4bed-8af8-6a6839690c91.png">
> 
> and
> 
> <img alt="video settings 1" width="1554" src="https://user-images.githubusercontent.com/94866088/149672899-d22ac634-d1e6-4377-b8f2-244fdb0d67ae.png">
> 
> The camera definitly supports H.264 and also H.265.

Ah, yes but the given source is only h265. You must provide a h264 stream

**Comment by ChrisBuHa** [comment]
Ok thanks. Any idea how to provide h264 instead of h265 stream? 

Clould that also be the reason why with chosen  `vcodec` `copy` the live stream does not start and the recording is always cancelled by HSV?

**Comment by seydx** [comment]
> Ok thanks. Any idea how to provide h264 instead of h265 stream?
> 
> Clould that also be the reason why with chosen `vcodec` `copy` the live stream does not start and the recording is always cancelled by HSV?

Yes of course, this is 100% the reason.

You need to check your camera's own settings for h264 stream

**Comment by ChrisBuHa** [comment]
Just wanted to give a feedback here. 

Maybe this information will help other Foscam camera users. I believe they are quite popular in Europe. 

If you stream is encoded in H.265 just activate the "NVR connection" in the settings of the Foscam app to change it to H.264.

Now every think works fine!

**Comment by Tombra1889** [comment]
It now works reasonably well with the following configuration:
<img width="472" alt="image" src="https://user-images.githubusercontent.com/60692414/150512939-cb6cc631-10f3-4205-a41b-72bed2291b39.png">

the recordings are sometimes very short or broken off. Sometimes no people are recognized.

What does reason 3 and 5 mean specifically?

**Comment by seydx** [comment]
@Tombra1889 

Keyframe Interval = 4 x FPS

If your Fps is 24, the the keyframe interval must be 96

Set fps to 25 and Keyframe Interval to 100

**Comment by eperitus** [comment]
I am also getting a cancelled recording message.  Similar messages have been occurring for a couple of plugin versions now.  Live streaming works fine, but no recordings appear in the timeline.  

I have not changed anything about my config - it is the same one that is shown at https://github.com/seydx/homebridge-camera-ui/issues/336#issuecomment-1012732224

Here is the log from homebridge 1.4.0 with latest homebridge-camera-ui plugin:

```
[1/26/2022, 6:22:36 PM] [CameraUI] VIDEOANALYSIS: New message: Data: {"time":"2022-01-27T02:22:36.543Z","event":"dwellTime (60s)"} - Motion: resetted - Camera: FrontYardCam
[1/26/2022, 6:22:38 PM] [CameraUI] VIDEOANALYSIS: New message: Data: [{"zone":"region0","percent":32.64583206176758,"sensitivity":68,"dwell":60,"forceClose":3}] - Motion: detected - Camera: FrontYardCam
[1/26/2022, 6:22:38 PM] [CameraUI] FrontYardCam: Motion ON
[1/26/2022, 6:22:47 PM] [CameraUI] FrontYardCam: Closing recording process
[1/26/2022, 6:22:47 PM] [CameraUI] FrontYardCam: Motion OFF
[HDS ::ffff:192.168.7.48] Recording download stream 1 is still awaiting generator although stream was closed 10s ago! This is a programming mistake by the camera implementation which prevents freeing up resources.
[HDS ::ffff:192.168.7.48] Delegate yielded fragment after stream 1 was already closed!
[1/26/2022, 6:23:03 PM] [CameraUI] FrontYardCam: The recording process was aborted by HSV with reason "CANCELLED"
[HDS ::ffff:192.168.7.48] Delegate finished recording stream 1 without sending anything out.       Controller will CANCEL.
```

**Comment by WattageGuy** [comment]
> @seydx I am also getting a cancelled recording message. Similar messages have been occurring for a couple of plugin versions now. Live streaming works fine, but no recordings appear in the timeline.
> 
> I have not changed anything about my config - it is the same one that is shown at [#336 (comment)](https://github.com/seydx/homebridge-camera-ui/issues/336#issuecomment-1012732224)
> 
> Here is the log from homebridge 1.4.0 with latest homebridge-camera-ui plugin:
> 
> ```
> [1/26/2022, 6:22:36 PM] [CameraUI] VIDEOANALYSIS: New message: Data: {"time":"2022-01-27T02:22:36.543Z","event":"dwellTime (60s)"} - Motion: resetted - Camera: FrontYardCam
> [1/26/2022, 6:22:38 PM] [CameraUI] VIDEOANALYSIS: New message: Data: [{"zone":"region0","percent":32.64583206176758,"sensitivity":68,"dwell":60,"forceClose":3}] - Motion: detected - Camera: FrontYardCam
> [1/26/2022, 6:22:38 PM] [CameraUI] FrontYardCam: Motion ON
> [1/26/2022, 6:22:47 PM] [CameraUI] FrontYardCam: Closing recording process
> [1/26/2022, 6:22:47 PM] [CameraUI] FrontYardCam: Motion OFF
> [HDS ::ffff:192.168.7.48] Recording download stream 1 is still awaiting generator although stream was closed 10s ago! This is a programming mistake by the camera implementation which prevents freeing up resources.
> [HDS ::ffff:192.168.7.48] Delegate yielded fragment after stream 1 was already closed!
> [1/26/2022, 6:23:03 PM] [CameraUI] FrontYardCam: The recording process was aborted by HSV with reason "CANCELLED"
> [HDS ::ffff:192.168.7.48] Delegate finished recording stream 1 without sending anything out.       Controller will CANCEL.
> ```

Im also getting this problem with error:

Recording download stream 1 is still awaiting generator although stream was closed 10s ago! This is a programming mistake by the camera implementation which prevents freeing up resources.

Any solution?
