### ISSUE TITLE
Profile picture is not shown after upload

### ISSUE THREAD

**Issue by bondskin** [seydx/homebridge-camera-ui#351]
**Describe the bug**
Uploading a picture in Interface / Account / Profile does not show the pic right after the upload.
Only when the page is changed / updated, the new pic is shown

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**
Picture is shown right after the upload.

**Logs**
If available, attach the log where the bug is vissible

**Screenshots**

**Environment**
- Node.js Version: v16.3.2
- Homebridge Version: v1.4.0-beta.4
- Camera UI Version: v5.0.8
- Operating System: MacOS
- Browser: Safari

**Comment by seydx** [comment]
Fixed in v5.0.9-beta.0

`sudo npm i -g homebridge-camera-ui@5.0.9-beta.0`

**Comment by seydx** [comment]
v5.0.9 online
