### ISSUE TITLE
Debug mode for VideoAnalysis section, to tune sensitivity

### ISSUE THREAD

**Issue by macjl** [seydx/homebridge-camera-ui#356]
**Is your feature request related to a problem? Please describe.**
It’s difficult to fine tune the sensitivity of the VideoAnalysis motion sensor. 

**Describe the solution you'd like**
Provide a debug log of the % of image change in each frame, that we can rely to set the Sensitivity afterwards. This debug could be an optional parameter of VideoAnalysys section. 

**Describe alternatives you've considered**
Take a very long time to adjust sensitivity of each Camera…

**Comment by seydx** [comment]
Added in v5.0.9-beta.0

You will see following message if videoanalysis detects new motion

```
VIDEOANALYSIS: New message: Data: [{"zone":"region0","percent":87.91270446777344,"sensitivity":13,"dwell":128}] - Motion: detected - Camera: CameraName
```

The `data` field contains all necessary information you need, like the zone name, percent, sensitivity (according to the detected difference) and current dwell time (this is now adjustable within ui, was fixed at 60s before)

`sudo npm i -g homebridge-camera-ui@5.0.9-beta.0`

**Comment by macjl** [comment]
Tried it, thanks ! It's helping a lotfor knowing how much % change when a motion is detected

But maybe you could add a more agressive optional debug, that show this percentage even when there is no motion.
This will help to find the % of change that exists when there is no motion (camera glitch, normal movements, etc...)

What do you think about that ?

**Comment by seydx** [comment]
Hm im not sure if i understand.

>that show this percentage even when there is no motion.

The plugin should spam the log with info although no movement was detected?

**Comment by macjl** [comment]
I agree the log will be spammed. This option should be used just for testing purpose, in a short time period.

That's why I think this should not be the same option as 'debug', and add with a warning in the configuration.

I would understand you don't wand to implement it, because it will only be useful just for power users.

**Comment by seydx** [comment]
> I agree the log will be spammed. This option should be used just for testing purpose, in a short time period.
> 
> That's why I think this should not be the same option as 'debug', and add with a warning in the configuration.
> 
> I would understand you don't wand to implement it, because it will only be useful just for power users.

Instead of this, there is a log entry (debug level) which will always appear in the log if motion is detected (but blocked due to dwell time) and thats spamming the log (if debug enabled) while movement is detected.

So this should also be enough if i add the information into this line or? Everytime a motion is triggered (not regarding if its blocked by hsv or dwell time, it will appear in the log)

**Comment by macjl** [comment]
Yes ! I think that will do the trick !

**Comment by seydx** [comment]
v5.0.9-beta.1 online

**Comment by macjl** [comment]
Tried it. 
When setting sensitivity to 100%, I got the percentage every 0.5s.
With that setting, I was able to tune the sensitivity of the cam ! It's perfect :)

**Comment by seydx** [comment]
added in v5.0.9
