### ISSUE TITLE
Camera UI Maxing CPU on Raspberry Pi 3 B

### ISSUE THREAD

**Issue by tbird1706** [seydx/homebridge-camera-ui#358]
Running Homebridge on Raspberry Pi 3 B and seeing CPU usage at 100% while running Camera-UI on Homebridge. The stream itself works fine seemingly but the Pi is maxed as soon as it starts up. I am using Ubiquiti cameras and had only added 1 G3 Pro and the G4 Doorbell to the mix. Config for both is after environment.

- Node.js Version: v16.13.2
- Homebridge Version: v1.4.0-beta.7
- Camera UI Version: v5.0.8
- Operating System: Raspbian GNU/Linux Buster (10)
- Browser: Safari 15.2

`{
            "name": "CameraUI",
            "port": 8081,
            "debug": false,
            "mqtt": {
                "active": false
            },
            "http": {
                "active": false
            },
            "smtp": {
                "active": false
            },
            "ftp": {
                "active": false
            },
            "ssl": {
                "active": false
            },
            "cameras": [
                {
                    "name": "Doorbell",
                    "motion": true,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsps://192.168.10.1:7441/eL0Tmi7OaeBH8037?enableSrtp",
                        "rtspTransport": "tcp",
                        "maxStreams": 2,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "stimeout": 10,
                        "audio": false
                    },
                    "videoanalysis": {
                        "active": true
                    }
                },
                {
                    "name": "Driveway",
                    "motion": true,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsps://192.168.10.1:7441/u4jkNu7rv5RjyQgT?enableSrtp",
                        "rtspTransport": "tcp",
                        "maxStreams": 2,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "stimeout": 10,
                        "audio": false
                    },
                    "videoanalysis": {
                        "active": true
                    }
                }
            ],
            "platform": "CameraUI"
        }`

**Comment by seydx** [comment]
Hey @tbird1706 

This should not happen, I never got above 20% in normal condition. Can you see which process consumes so much CPU? E.g. via `htop` or `top`

And try with the following config

```json
{
  "name": "CameraUI",
  "port": 8081,
  "debug": false,
  "mqtt": {
    "active": false
  },
  "http": {
    "active": false
  },
  "smtp": {
    "active": false
  },
  "ftp": {
    "active": false
  },
  "ssl": {
    "active": false
  },
  "cameras": [
    {
      "name": "Doorbell",
      "motion": true,
      "unbridge": true,
      "hsv": true,
      "prebuffering": true,
      "prebufferLength": 4,
      "videoConfig": {
        "source": "-i rtsps://192.168.10.1:7441/eL0Tmi7OaeBH8037?enableSrtp",
        "rtspTransport": "tcp",
        "maxStreams": 2,
        "vcodec": "copy",
        "acodec": "libfdk_aac",
        "stimeout": 10,
        "audio": false
      },
      "videoanalysis": {
        "active": true
      }
    },
    {
      "name": "Driveway",
      "motion": true,
      "unbridge": true,
      "hsv": true,
      "prebuffering": true,
      "prebufferLength": 4,
      "videoConfig": {
        "source": "-i rtsps://192.168.10.1:7441/u4jkNu7rv5RjyQgT?enableSrtp",
        "rtspTransport": "tcp",
        "maxStreams": 2,
        "vcodec": "copy",
        "acodec": "libfdk_aac",
        "stimeout": 10,
        "audio": false
      },
      "videoanalysis": {
        "active": true
      }
    }
  ],
  "platform": "CameraUI"
}
```

**Comment by tbird1706** [comment]
Is the only change removing the additional command from "driveway"?

**Comment by seydx** [comment]
> Is the only change removing the additional command from "driveway"?

Yes and check via `top` or `htop` the process which does much cpu load

**Comment by tbird1706** [comment]
Running at 65% load now so that is better. I think your changes plus unbridging helped. Screenshot below on the processes taking the most CPU. I couldn't get the entire name to display.

![image](https://user-images.githubusercontent.com/23426983/149817164-b698c94b-deb7-4a64-9a48-f135ed441462.png)

**Comment by seydx** [comment]
> Running at 65% load now so that is better. I think your changes plus unbridging helped. Screenshot below on the processes taking the most CPU. I couldn't get the entire name to display.
> 
> ![image](https://user-images.githubusercontent.com/23426983/149817164-b698c94b-deb7-4a64-9a48-f135ed441462.png)

Great

Well, "videoanalysis" could be reduced significantly further if you put a "subSource" in config

Does your camera have a "second stream" ? Best with very low resolution and fps ? If yes, please put the source of the second stream in config.json under "subSource".

e.g.

```json
{
  "name": "Doorbell",
  "motion": true,
  "unbridge": true,
  "hsv": true,
  "prebuffering": true,
  "prebufferLength": 4,
  "videoConfig": {
    "source": "-i rtsps://192.168.10.1:7441/eL0Tmi7OaeBH8037?enableSrtp",
    "subSource": "-i rtsp://.....",    <--- here
    "rtspTransport": "tcp",
    "maxStreams": 2,
    "vcodec": "copy",
    "acodec": "libfdk_aac",
    "stimeout": 10,
    "audio": false
  },
  "videoanalysis": {
    "active": true
  }
}
```

**Comment by tbird1706** [comment]
<img width="366" alt="Screen Shot 2022-01-17 at 1 16 07 PM" src="https://user-images.githubusercontent.com/23426983/149820393-4d106539-09b6-483f-b6b9-ff470879b094.png">

looking good!

**Comment by codyc1515** [comment]
I experienced the same issue using a Raspberry Pi4. The sub stream fixed the issue for the most part by reducing the CPU utilisation down from 110% to 5%. The best fix would be ONVIF support.

**Comment by seydx** [comment]
Hey @codyc1515 

Could you submit a feature request regarding ONVIF?

**Comment by grzegorz914** [comment]
@seydx 
ONVIF spec is here: https://github.com/onvif/specs most function will be PTZ Control like Pan, Tilt, Zoom, Call Presets
