### ISSUE TITLE
Error: Cannot access 'user' before initialization

### ISSUE THREAD

**Issue by Garywoo** [SeydX/homebridge-camera-ui#36]
I'm receiving this error when visiting the web UI after updating the plugin. 

I'm using `"auth": "none"`.

I have tried `"reset": true` but this now just remains set to `true` constantly now, and the error still occurs.

**Comment by monza258** [comment]
Can you trie: 
"auth": "form",

**Comment by Garywoo** [comment]
I tried `"auth": "form"`, and left `"reset": true`. I logged in with the admin/admin default credentials. I then got guided to change my username and password. I then got the error:

> Stop! Unauthorised!

Clicking Login, and using the newly set username and password just keeps bringing me back to the unauthorised error.

![](https://user-images.githubusercontent.com/10392194/96284638-c73c4a80-0fd5-11eb-968e-4b66ef05bab6.png)

**Comment by SeydX** [comment]
#35

**Comment by SeydX** [comment]
@Garywoo 

v3.0.2-beta.2 published. Can u try it pls?

``sudo npm i -g --unsafe-perm homebridge-camera-ui@beta``

**Comment by SeydX** [comment]
@Garywoo 

Dont forget to set up a socketPort for the cameras to activate the livestream

See [Example](https://github.com/SeydX/homebridge-camera-ui/blob/2b59ce5ae51204c1920c3105c44a92c16ea8bf01/misc/example-config.json#L59)

**Comment by SeydX** [comment]
Should be fixed with v3.0.2

Feel free to reopen if it still occures
