### ISSUE TITLE
videoanalysis UI does not show sub-stream preview, could lead to incorrect regions defined due to mismatch aspect ratio

### ISSUE THREAD

**Issue by longzheng** [seydx/homebridge-camera-ui#367]
**Describe the bug**
The video analysis configuration UI shows a preview image using the camera's main stream `source`. It is recommended to specify a lower resolution sub-stream `subSource` for video analysis so that it is not so process intensive.

However some IP cameras such as my Dahua camera has a different aspect ratio for the main stream (3072x2048 3:2) and sub stream (704x576 11:9).

This means that when I defined my regions using the main stream as a preview, it would be slightly incorrect since the analysis ran on the sub-stream would include areas that I did not intend to include (in the physical world).

**Expected behavior**
The video analysis configuration UI should show the preview image using the camera's sub-stream (if it is set).

**Comment by seydx** [comment]
fixed in v5.0.10-beta.5

**Comment by seydx** [comment]
v5.0.10 is online
