### ISSUE TITLE
Trouble with HKSV and some cameras (others are fine)

### ISSUE THREAD

**Issue by randomranran** [seydx/homebridge-camera-ui#368]
Hi mate,

I've got all my cameras set up as "vcodec": "copy", "acodec": "copy", and all cameras play fine in live view with audio. But only 1 out of 3 cameras works perfectly in HKSV and the other 2 don't. They are all Unifi cameras and use the same codec, acc for audio and h264 for video, what I've noticed is the camera that works in the log I see "Resetting motion state because HSV closed recording with reason 3" and the other two that don't work I see "Resetting motion state because HSV closed recording with reason 5" What is the difference between 3 and 5?

**Comment by randomranran** [comment]
What may help you is on the one camera that works the keyframe is 2 and on the other two that don't work the key frame is 0.2.

All three cameras are 30 fps however and Unifi don't allow you to customise keyframes in their software, is there anyway this could be overridden in camera Ui or anyway the get over this?

**Comment by seydx** [comment]
Hey @randomranran 

tried also with `"vcodec": "libx264"` and `"acodec": "libfdk_aac"` ?

**Comment by seydx** [comment]
you need to set `"vcodec": "libx264"` so that camera.ui can change the interval
