### ISSUE TITLE
Expose Exclude Switch

### ISSUE THREAD

**Issue by Kai9555** [seydx/homebridge-camera-ui#369]
Wenn ich in Camera-UI "Expose Privacy Switch" aktiviere, wird auch der Exclude Switch mit ausgegeben, obwohl dieser in Camera-UI weiterhin deaktiviert ist. Mal abgesehen davon, dass mir nicht ganz klar ist wozu der Exlude Switch gedacht ist 😅 kann ich im LOG nichts weiter sehen. Wenn du etwas benötigst, lass es mich wissen.

Raspberry Pi  mit:
Homebridge 1.4.0 Beta 4
Camera-UI 5.0.9
Node 16.13.1
NPM 8.3.0

**Comment by seydx** [comment]
@Kai9555 

Oh stimmt konnte es reproduzieren, danke dir ^^

Es gibt ja 3 Schalter

- At Home (Accessory, Globaler Schalter)
  - Schaltet den "Zu Hase" Schalter ein/aus. Wenn At Home eingeschaltet ist werden jegliche Bewegungserkennung stumm bzw ausgeschaltet
- Exclude (Service, Kamera Schalter)
  - Schließt die Kamera von "At Home" aus wenn "Exclude" eingeschaltet ist (für diese Kamera wird dann weiterhin Bewegung erkannt)
- Privacy (Service, Kamera Schalter)
  - Wenn "At Home" eingeschaltet ist und "Privacy" eingeschaltet ist für die Kamera, wird der Stream und Snapshot durch ein Privacy Bild ersetzt

**Comment by Kai9555** [comment]
> @Kai9555
> 
> Oh stimmt konnte es reproduzieren, danke dir ^^
> 
> Es gibt ja 3 Schalter
> 
> * At Home (Accessory, Globaler Schalter)
>   
>   * Schaltet den "Zu Hase" Schalter ein/aus. Wenn At Home eingeschaltet ist werden jegliche Bewegungserkennung stumm bzw ausgeschaltet
> * Exclude (Service, Kamera Schalter)
>   
>   * Schließt die Kamera von "At Home" aus wenn "Exclude" eingeschaltet ist (für diese Kamera wird dann weiterhin Bewegung erkannt)
> * Privacy (Service, Kamera Schalter)
>   
>   * Wenn "At Home" eingeschaltet ist und "Privacy" eingeschaltet ist für die Kamera, wird der Stream und Snapshot durch ein Privacy Bild ersetzt

Alles klar 👌🏻 verstanden 👍🏻

Danke und schönen Abend noch.

**Comment by seydx** [comment]
fixed in v5.0.10-beta.5

**Comment by seydx** [comment]
v5.0.10 is online
