### ISSUE TITLE
raspberry pi cam

### ISSUE THREAD

**Issue by gecko74** [seydx/homebridge-camera-ui#370]
Hi

i have a raspberry zero w 2 with a pi cam v2 attached. 
have someone the right setting for this?
i have tried many settings…

the preview in homekit works, but no live stream in homekit
In the camera.ui web works the live stream too..

my current setting

               {
                    "name": "Eingang Cam",
                    "manufacturer": "Pi",
                    "model": "Pi Cam V2",
                    "motion": true,
                    "unbridge": true,
                    "hsv": false,
                    "prebuffering": false,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-f video4linux2 -i /dev/video0",
                        "stillImageSource": "-f video4linux2 -i /dev/video0",
                        "maxStreams": 2,
                        "vcodec": "h264_omx",
                        "acodec": "libfdk_aac",
                        "stimeout": 0,
                        "audio": false
                    },

**Comment by NeoRame** [comment]
Same her for zero W and pi cam module 1.3

**Comment by NeoRame** [comment]
and since the last update:

"FFmpeg exited with code: 1 and signal: null - (fatal) Option rtsp_ transport not found."

the stream and prieview didnt work anymore at config screen and in the interface

**Comment by seydx** [comment]
> and since the last update:
> 
> "FFmpeg exited with code: 1 and signal: null - (fatal) Option rtsp_ transport not found."
> 
> the stream and prieview didnt work anymore at config screen and in the interface

Yes because homebridge-config-ui-x schema adds default values, also for "rtspTransport", which will be removed with next version

just open the editor (not the config schema) and remove "stimeout" and "rtspTransport" from config

**Comment by gecko74** [comment]
> > and since the last update:
> > "FFmpeg exited with code: 1 and signal: null - (fatal) Option rtsp_ transport not found."
> > the stream and prieview didnt work anymore at config screen and in the interface
> 
> Yes because homebridge-config-ui-x schema adds default values, also for "rtspTransport", which will be removed with next version
> 
> just open the editor (not the config schema) and remove "stimeout" and "rtspTransport" from config

I removed both, but now live stream

**Comment by gecko74** [comment]
Ah i changed the vcodec to libx264 and it works.
