### ISSUE TITLE
HSV close recording with reason "3"

### ISSUE THREAD

**Issue by carinconc** [seydx/homebridge-camera-ui#371]
**Describe the bug**
Shortly after a motion is detected, the motion is reset by HSV due to reason "3".

**To Reproduce**
I get this error almost all the time (even if I generate the motion with the dummy switch). Videos in HSV are being recorded, but they are incomplete.

**Expected behavior**
Motions should not be reset by HSV.

**Logs**
[1/19/2022, 12:19:02 PM] [CameraUI] Garage 2: Recording started
[1/19/2022, 12:19:10 PM] [CameraUI] Garage 2: Closing recording process
[1/19/2022, 12:19:10 PM] [CameraUI] Resetting motion state because HSV closed recording with reason "3"
[1/19/2022, 12:19:10 PM] [CameraUI] Garage 2: FFMPEG socket closed during read for 8 bytes!
[1/19/2022, 12:19:10 PM] [CameraUI] Garage 2: Skip saving the recording, the file might be corrupted because the recording process was cancelled by HSV
[1/19/2022, 12:19:10 PM] [CameraUI] Garage 2: FFmpeg recording process exited (expected)

**Screenshots**
N/A

**Environment**
- Node.js Version: v16.13.2
- Homebridge Version: v16.13.2
- Camera UI Version: v16.13.2
- Operating System: Ubuntu 20.04
- Browser: Safari

**Comment by seydx** [comment]
Hey @carinconc 

The message means that HSV was not satisfied with the data of the camera and therefore canceled the recording.

It is mostly due to wrong config.json and/or camera settings

can you post a screenshot of the cameras own settings and your config.json pls

**Comment by carinconc** [comment]
Thanks for the quick reply: Here is my config.json  

"cameras": [
                {
                    "name": "Garage 2",
                    "manufacturer": "Reolink",
                    "model": "RLC-811A",
                    "serialNumber": "N/A",
                    "motion": true,
                    "doorbell": true,
                    "switches": true,
                    "useInterfaceTimer": false,
                    "motionTimeout": 0,
                    "unbridge": false,
                    "hsv": true,
                    "prebuffering": false,
                    "forcePrebuffering": true,
                    "prebufferLength": 5,
                    "videoConfig": {
                        "source": "-i rtmp://192.168.7.100/bcs/channel0_ext.bcs?channel=0&stream=2&user=XXXXXXXXXXX&password=XXXXXXXXXXXXXX",
                        "stillImageSource": "-i http://192.168.7.100/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=wuuPhkmUCeI9WG7C&user=XXXXXXXXX&password=XXXXXXXXXXXXXXXX",
                        "rtspTransport": "tcp",
                        "maxStreams": 3,
                        "maxWidth": 3840,
                        "maxHeight": 2160,
                        "maxFPS": 25,
                        "maxBitrate": 10000,
                        "forceMax": true,
                        "vcodec": "libx264",
                        "acodec": "libfdk_aac",
                        "stimeout": 10,
                        "audio": true,
                        "debug": true
                    },
                    "videoanalysis": {
                        "active": false
                    }
                }
            ],
            "platform": "CameraUI"
        }

**Comment by seydx** [comment]
@carinconc 

can you also post a screenshot from the camera's own settings (like resolution, fps etc etc)

**Comment by carinconc** [comment]
<img width="1320" alt="Screen Shot 2022-01-19 at 3 48 56 PM" src="https://user-images.githubusercontent.com/62186450/150219462-b186b9ce-b599-4346-9743-b588d3b55b00.png">

**Comment by Tombra1889** [comment]
try reduce the resolution to full-hd and the fps to 24.

**Comment by seydx** [comment]
@carinconc 

yes try it with a lower resolution pls
