### ISSUE TITLE
Videoanalysis: Force Close Timer

### ISSUE THREAD

**Issue by seydx** [seydx/homebridge-camera-ui#372]
Possibility to set the internal "forceClose" timer force videoanalysis via the interface (from 0 = disabled to 10min)

The "forceClose" timer ensures that a constant movement is automatically reset by camera.ui after 3min. And this ends the recording even if motion is still present.

**Comment by seydx** [comment]
added in v5.0.10-beta.5

**Comment by longzheng** [comment]
Thanks. I forgot to ticket this as discussed.

**Comment by seydx** [comment]
v5.0.10 is online
