### ISSUE TITLE
SMTP Body Text Detection

### ISSUE THREAD

**Issue by MikeDProducer** [seydx/homebridge-camera-ui#379]
**Is your feature request related to a problem? Please describe.**

Currently the SMTP feature can only recognize the email address being sent. The problem is my NVR does not let me assign a different sending email address for each camera. 

**Describe the solution you'd like**
When my NVR sends a motion email the body text of the automated email contains the camera name. I'd love it if the SMTP server in Camera.UI could pick this up to differentiate which camera the alert is coming from. 

**Describe alternatives you've considered**
There is an SMPT motion plugin for Homebridge that does this. It has not been updated for quite some time. I've considered getting this going again because it has worked for me in the past when using another camera plugin.

**Comment by seydx** [comment]
Added. Comes with v5.0.10

**Comment by seydx** [comment]
Checked, it works. But it takes ~2 seconds longer to send the motion alert. For the reason that an incoming email is a readable stream, I have to parse it before I can read the content.

**Comment by seydx** [comment]
v5.0.10 is online,

you can put a term into the "body" field (see [example-config](https://github.com/seydx/homebridge-camera-ui/blob/d4b9ae2f55af6fe44d7185a3a13b22901cfa43f6/example-config.json#L96)) and camera.ui will search the email body for this term (if it can not find the camera through the email adresse(s)
