### ISSUE TITLE
FFmpeg hangs up

### ISSUE THREAD

**Issue by efkayx** [SeydX/homebridge-camera-ui#38]
Hi,

How I'm gonna get the same behaviour as in the previous version? 
I do have 3 YI hacked cameras and in the previous 2.2.0 version, I've received by an motion information on the iphone (statusdisplay) with the screenshot of the cam pic. I'm running mosquitto locally and each YI camera has got his MQTT settings for motion mqtt information. Based on that a video is going to be created under the old situation with the v 2.2.0. What is the correct way to configure that? See below my adjusted configuration for the new version 3.0.2 copied from the revious version for each camera the necessary mqtt section:
Please not I'm just running one YI cam for testing purposes:

      {
            "platform": "CameraUI",
            "name": "CameraUI",
            "port": 3333,
            "auth": "form",
            "language": "EN",
            "debug": true,
            "reset": false,
            "mqtt": {
                "active": true,
                "host": "localhost",
                "port": 1883,
                "topic": "homebridge/motion",
                "on_message": "ON"
            },
            "options": {
                "videoProcessor": "ffmpeg",
                "interfaceName": "en1",
                "ffmpegExecPath": "/usr/local/bin/ffmpeg"
            },
            "cameras": [
                {
                    "name": "Garden",
                    "motion": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -err_detect ignore_err -re -i rtsp://x:x@192.168.10.84/ch0_1.h264",
                        "stillImageSource": "-i http://x:x@192.168.10.84:8080/cgi-bin/snapshot.sh?res=low&base64=no",
                        "maxStreams": 5,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 30,
                        "maxBitrate": 1024,
                        "vcodec": "copy",
                        "packetSize": 1316,
                        "audio": false,
                        "debug": true
                    },
                    "mqtt": {
                        "active": true,
                        "host": "localhost",
                        "port": 1883,
                        "username": "",
                        "password": "",
                        "topicPrefix": "yicam2",
                        "topicSuffix": "motion",
                        "startMessage": "motion_start",
                        "stopMessage": "motion_stop",
                        "recordOnMovement": true,
                        "recordVideoSize": 60,
                        "interval": 0
                    }
                }
            ]

Many thanks,

efkayx

**Comment by SeydX** [comment]
Hey @efkayx 

The previous version was build for yi hacked cameras, so it was possible to config individual mqtt‘s for each cam

V3 is build for all rtsp cameras with ONE mqtt config

You need to config your yi hacked camera, below my config

![DF3046B3-3E79-4899-86F3-184EC61FFFE9](https://user-images.githubusercontent.com/34152761/96304571-a20f0280-0ffc-11eb-97e5-a0c757bf041f.png)


Topic prefix must be **homebridge**
Topic suffix must be **motion**

Motion start message uses following prefix

<camera nam>@<message>

Camera name must be the same as defined in your config and message the same as defined also in your config under 
**on_message**

Note

You can use different prefix/suffix/message, just adjust in your config, see [Example](https://github.com/SeydX/homebridge-camera-ui/blob/9dd744cf8025a0d35117b7c3798dba80dd3d61e9/misc/example-config.json#L24)

**Comment by efkayx** [comment]
Hi @SeydX ,

thank so much. This was the trick. BTW fantastic work here after the last release. Really kudos to you.
A couple of experience so far, but I have some feeling the MQTT feature (MOTION ON) is not inlign with the information and actually recording the videos. I do see a lot notifications and not recording. Do you have some ideas in regards of acting in-sync. Before with the 2 version it was fully working and the rtsp streams could be recorded and stored.
Nothing has changed from my side and using the 3 YI cam, which sometimes one of the yi cam are triggering something and the other one in the same place not. So I put both cams each other to see the MQTT behaviour. 
I'm running MACOS 10.16, static linked ffmpeg (latest version) and nodejs 14.14.0.

Also what I've noticed by the restart of homebridge and the plugin himself. Maybe it is coming due to the fact I've enabled debug and do see more.

2020-10-18T08:43:46.154Z CameraUIMqtt Received a new MQTT message online (homebridge/status)
2020-10-18T08:43:46.155Z CameraUIMqtt Received a new MQTT message Garden@OFF (homebridge/motion)
2020-10-18T08:43:46.155Z CameraUIHandler Motion event triggered.
2020-10-18T08:43:46.155Z CameraUIHandler Switch motion detect off. Garden
2020-10-18T08:43:46.156Z CameraUIMqtt Received a new MQTT message {
"start":"2020-10-18T10:38:00+0200",
"end":"2020-10-18T10:39:01+0200",
"files":[ ]
}
 (homebridge/files)
(node:35405) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'db' of undefined
    at Object.handleMotion (/usr/local/lib/node_modules/homebridge-camera-ui/app/lib/handler.js:78:29)
    at Handler.motionHandler (/usr/local/lib/node_modules/homebridge-camera-ui/src/helper/handler.js:91:15)
    at Handler.automationHandler (/usr/local/lib/node_modules/homebridge-camera-ui/src/helper/handler.js:56:23)
    at MqttClient.<anonymous> (/usr/local/lib/node_modules/homebridge-camera-ui/src/helper/mqtt.js:35:17)
    at MqttClient.emit (events.js:315:20)
    at MqttClient._handlePublish (/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/mqtt/lib/client.js:1271:12)
    at MqttClient._handlePacket (/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/mqtt/lib/client.js:410:12)
    at work (/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/mqtt/lib/client.js:321:12)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:35405) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35405) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020-10-18T08:43:46.174Z CameraUIInterface Configuring handler
2020-10-18T08:43:46.174Z CameraUIInterface Configuring webhook

Apart from this information everything is working fine but the information gave you on top.

So far this is phenomenal with the new 3 release and again thanks very much for this hard work. 

Cheers,

EfkayX

**Comment by SeydX** [comment]
Hey,

to record the stream (snapshot/recording) you need to login in the user interface and go to settings.

You can adjust almost everything there.

To activate recording, just go to settings > recordings and switch activate to on, u can also adjust the type of recording (snapshot/recording) and much more. Give it a try.

Note: to handle incoming notifications, you need to switch off 'At Home' (ui > settings > general), otherwise the ui will not handle incoming notifications because someone already at home and there is no need for recording something etc.

The issue u have is because the plugin received a mqtt notification BEFORE it has finished initialising database etc.

Will fix this :)

**Comment by SeydX** [comment]
@efkayx 

Fix for the issue (incoming mqtt/http message before ui finished initialisation) will come with next version!

**Comment by SeydX** [comment]
@efkayx 

v3.0.7 is online and should fix the issue

**Comment by efkayx** [comment]
@SeydX this is awesome. Thanks very much. I will test it tonight and will give you feedback. 

Another thing what I've noticed is to adjust the config per webcam:

                    "name": "Garden",
                    "manufacturer": "Yi",
                    "model": "Yi Home 1080p",
                    "serialNumber": "9FUSY21J0M5L26190916",
                    "firmwareRevision": "4.5.0.0C_201910080934",
                    "motion": true,
                    "yihack": true,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -err_detect ignore_err -i rtsp://x:x@192.168.10.84/ch0_1.h264",
                        "stillImageSource": "-i http://x:x@192.168.10.84:8080/cgi-bin/snapshot.sh?res=low&base64=no",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 480,
                        "maxFPS": 30,
                        "maxBitrate": 200,
                        "vcodec": "copy",
                        "encoderOptions": "-copytb 0",
                        "packetSize": 188,
                        "audio": false,
                        "debug": true,
                        "socketPort": 8200


I'm using right now 640x480 and the events and the stored mp4 are now more inline. Sometimes I'm getting data not found to click on the MP4 and it seems there are a lot of ffmpeg process in stuck. Once I'm killing them it triggers the notification event in the UI but no MP4 data is available. So i think it also has to do something with the wifi speed connections at some how and why the ffmpeg process hangs is for me unclear at the moment. Will investigat further but reducing the maxHeight and maxWidth was already a huge benefit

![grafik](https://user-images.githubusercontent.com/4146446/96421801-7efc7280-11f7-11eb-9812-75d44791d2cf.png)

You see based on this hanging ffmpeg process, I killed it in the task process (MACOS) and then it creates the event which was several hours ago and of course now MP4 file 

Will investigate further.

Thanks,

EfkayX

**Comment by SeydX** [comment]
Hey @efkayx 

v3.0.8 is online and should fix the issue with hanging ffmpeg process. Could you try it pls?

**Comment by efkayx** [comment]
Hi @SeydX,

yes it is installed and also plugged in several YI cams (5 in total) right now to see how the performance lookslike and as well the behaviour of the hanging ffmpeg proccesses. From now on it looks great and I do not see any ffmpeg processes hanging anymore. Will continue to monitor further :-) Great work and thanks very much.

Cheers,

efkayX

**Comment by SeydX** [comment]
Check also ur CPU usage with so much cams, decoding streams for the web is a bit heave on eg Raspberry with more than 3 cams

**Comment by efkayx** [comment]
@efkayx No worries. I'm running a dedicated MacMini 2018 server with 16GB Ram and plugged in with a 1Gbit Ethernet cable.
So the hardware isn't the bottleneck of the server where homebridge is running :-)

**Comment by SeydX** [comment]
Ohh very nice 😃

**Comment by efkayx** [comment]
@SeydX still running a lot of ffmpeg's stock in the process watcher:

![grafik](https://user-images.githubusercontent.com/4146446/96456262-8f741380-121e-11eb-9c5a-7cd9cf57f87f.png)


![grafik](https://user-images.githubusercontent.com/4146446/96456342-a87cc480-121e-11eb-91b6-15e4e71db96a.png)


after killing the ffmpeg process manually and this populates the case what I mentioned on top.

![grafik](https://user-images.githubusercontent.com/4146446/96456549-e974d900-121e-11eb-8edc-206fd8e40f4d.png)


no preview and no mp4 files. So it was better for a certain time but then humbling up again as shown in the screenshot on top


Cheers,

efkayX

**Comment by SeydX** [comment]
Hm thats weird, a debug from the ffmpeg command would be nice, but i need to implement it first

**Comment by SeydX** [comment]
@efkayx 

Does this occurs only with recording a video? Or also on recording a snapshot and does it ALWAYS happen?? Or sometimes?

**Comment by efkayx** [comment]
@SeydX 
I'm just using the settings always record (by movement( a video and the record length is one minute. 
I also recognized sometimes there is now preview in the notifications page for one individual notification items and sometimes there is a preview and if you click on you realize there is no mp4 available.
Switching back to the server and found 3 ffmpeg processes hanging. Once I'm killing them the web.ui informs me with a sounds an notification is happened, which was already several hours ago and then of course no valid mp4 file is available.

I let run the server almost 24hrs and during this time it happens roundabout 20 ffmpeg processes hanging. It is not frequent and I also try to get a better understanding based on what this is gonna happen and why it is happen. I would say 90% wise it works great so far and having already in the notification list and 600 recordings/events in the last 24hrs and the system performs great even though in the debug log level it will take some time to build up the webpage with the >600 entries at the moment.

I will monitor this further to get a bit of a pattern out of it and let see maybe I can find something.


identified two process hanging:
![grafik](https://user-images.githubusercontent.com/4146446/96613095-d5a0a400-12fe-11eb-8efe-fb9d78f094c0.png)

View in the web.ui. Below preview and two of them are missing as these are the process as seen in the task manager
![grafik](https://user-images.githubusercontent.com/4146446/96612993-bace2f80-12fe-11eb-8032-1aa866f2eb6c.png)


Killing the ffmpeg process:

log file in homebridge:
2020-10-20T16:06:38.881Z CameraUIInterface Garden: Snapshot stored to /Users/x/.homebridge/recordings/Garden-2f8ba1ae64-1603209420_1_m@2.jpeg.
2020-10-20T16:06:38.881Z CameraUIInterface CameraUI - Garden: Video requested: 640 x 480
2020-10-20T16:06:38.886Z CameraUIInterface Garden: Video command: ffmpeg -rtsp_transport tcp -err_detect ignore_err -nostdin -y -i rtsp://x:x@192.168.10.84/ch0_1.h264 -t 60 -strict experimental -threads 0 -c:v copy -s 640x480 -movflags +faststart -crf 23 /Users/x/.homebridge/recordings/Garden-2f8ba1ae64-1603209420_1_m.mp4
2020-10-20T16:06:41.585Z CameraUIInterface Garden: Snapshot stored to /Users/x/.homebridge/recordings/Garden-f8d60ef745-1603209989_1_m@2.jpeg.
2020-10-20T16:06:41.585Z CameraUIInterface CameraUI - Garden: Video requested: 640 x 480
2020-10-20T16:06:41.588Z CameraUIInterface Garden: Video command: ffmpeg -rtsp_transport tcp -err_detect ignore_err -nostdin -y -i rtsp://x:x@192.168.10.84/ch0_1.h264 -t 60 -strict experimental -threads 0 -c:v copy -s 640x480 -movflags +faststart -crf 23 /Users/x/.homebridge/recordings/Garden-f8d60ef745-1603209989_1_m.mp4


Web.ui:
![grafik](https://user-images.githubusercontent.com/4146446/96613385-303a0000-12ff-11eb-9d14-575b7ac5018a.png)

**Comment by SeydX** [comment]
I think the ffmpeg process hangs and can not callback

I have a telegram group with other user testing the plugin. I would debug the process with you.

Können auch uns auf Deutsch unterhalten da :)

Falls du Lust hast können wir uns da gerne weiter unterhalten, so könne ich dir auch einzelne Dateien zum ersetzen schicken und wir könnten es schneller debuggen

https://t.me/joinchat/AAAAAFMcxceAf7yrSivmvg

**Comment by SeydX** [comment]
Hey @efkayx 

v3.1.0 is online. Could u try it pls

**Comment by SeydX** [comment]
I am closing this issue and create a new one to inform the user about this problem (maybe it only occures only on mac)
