### ISSUE TITLE
Add ONVIF support

### ISSUE THREAD

**Issue by codyc1515** [seydx/homebridge-camera-ui#380]
**Is your feature request related to a problem?**
Motion Detection for HKSV on low powered devices, such as Raspberry Pi, can consume 100% (or more) of CPU time.

**Describe the solution you'd like**
Adding ONVIF support would entirely eliminate the need to detect motion by analysing each frame as ONVIF has motion detection support.

**Describe alternatives you've considered**
It is possible to use a lesser quality stream (if available). However this still adds unnecessary overhead (5-10% CPU time for one camera) given that the camera is already doing the processing for motion detection anyway.

**Additional context**
N/A

**Comment by seydx** [comment]
This is definitely planned. Just need to get a camera with the right ONVIF profile :P

**Comment by codyc1515** [comment]
No problem at all. I have a TP-Link C200 which has support and more than happy to help with any prototyping requirements you might have. I would add the support but this is a fairly large programme and I am not familiar enough with it, sorry.

**Comment by AssetBurned** [comment]
There is a project to convert a Raspberry PI into on https://github.com/BreeeZe/rpos. Not really the best video on how to install it but one could be found here https://www.youtube.com/watch?v=uSIi94PUUDU.

**Comment by Kai9555** [comment]
I didn't even dare to ask if ONVIF is planned in the future :) That's definitely a good thing and more reliable than frame-by-frame analysis.

I think the TP Link Tapo 100 is very common and popular, as is the Tapo 200. @codyc1515 By the way: With my C200, I unfortunately have no access via ONVIF to the motion detection via my Synology Surveillance Station. With the C100, however, it works without any problems. Maybe my C200 is just defective?!

@seydx: Do you need a camera for implementation? If I can support you, I'll send you a Tapo c100. The Supports ONVIF Profile S.

**Comment by thebalto2002** [comment]
Very excited for this feature.  I am planning on using BlueIris to detect motion and alert via ONVIF.  Please let me know if you want any help with implementation and testing with BlueIris.

**Comment by fade2metal** [comment]
Maybe the code of this plugin could help you developing onvif integration for camera ui: https://github.com/koush/scrypted/tree/main/plugins/onvif

I would really like to get this feature because mail motion detection doesn't always work as expected (There is no "no motion" event)

**Comment by mihailescu2m** [comment]
Maybe this helps: https://github.com/kopiro/homebridge-tapo-camera/pull/12/commits

**Comment by seydx** [comment]
Hey thx all, currently working on the next major release with plugin support and much more

Just need a ring camera and a camera with onvif support to write a plugin for these cameras before releasing v6 😜

**Comment by mihailescu2m** [comment]
Just as a solution until this is implemented:
You can use onvif2mqtt to publish motion detection messages from onvif to a mqtt topic, and use that topic in camera.ui. So you don't need video analysis to do motion detection anymore.

**Comment by Melvin-P-NL** [comment]
ONVIF support would be very welcome. We use the Hikvision DS-2CD2352-I, which supports that. It does not support HTTP Listening, unfortunately.

I’m currently using the video analysis in Camera UI, which works fine but asks a lot of the CPU indeed.

Also installed ‘Hikvision Nvr Events’ in HOOBS, but I don’t get it working.

I think video analyses works best for now, but I would certenly try ONVIF when availavle. Just let me know if I could test something for you.

**Comment by seydx** [comment]
The next major release is almost done, ring is also implemented, next one would be onvif

Just need a onvif capable camera to implement it 😅

**Comment by Melvin-P-NL** [comment]
I do have a couple (Hikvision) and can’t wait for ONVIF support. No problem to test for you and we could even work together with screen sharing. Even fine to perform Homebridge/Camera UI reinstalls if needed.

**Comment by benjaminbogdanovic** [comment]
> Just as a solution until this is implemented:
> 
> You can use onvif2mqtt to publish motion detection messages from onvif to a mqtt topic, and use that topic in camera.ui. So you don't need video analysis to do motion detection anymore.

How reliable is onvif2mqtt proving to be? Are you running it on via docker or on baremetal?

**Comment by emerbrito** [comment]
> The next major release is almost done, ring is also implemented, next one would be onvif
> 
> Just need a onvif capable camera to implement it 😅

Hey, were you able to get your hands on a onvif camera? If not I would be happy to help you get one as a contribution to the project. Lots of cheap/good options on Amazon.

Feel free to reach out and we will figure it out.
 Also let me know if you need beta testers for Onvif implementation.

**Comment by codyc1515** [comment]
Looks like this project is abandoned. Closing.
