### ISSUE TITLE
homebridge-camera-ui install succeeds, but it does not work, does not follow homebridge directory structure

### ISSUE THREAD

**Issue by chrisswanda** [seydx/homebridge-camera-ui#384]
I have been trying to install homebridge-camera-ui via hombridge, using the plugin search and via the terminal, and the install location is not consistent with other plugins.  The install works, but you cannot access the UI or get anything to show up via the Homebridge UI.

For example, installing via Plugins...

`[1/22/2022, 7:40:01 AM] [Homebridge UI] [homebridge-camera-ui] ENOENT: no such file or directory, open '/homebridge/node_modules/homebridge-camera-ui/homebridge-ui/public/index.html'`

I have no `/homebridge/node_modules/homebridge-camera-ui/` directory.  But the plugin shows that it is installed.

<img width="678" alt="Screen Shot 2022-01-22 at 07 50 03" src="https://user-images.githubusercontent.com/45573533/150641044-5d9bf050-5cb0-4ca5-b48b-306de31be9d9.png">

When I install via the terminal, it fails with:

`3123 verbose stack Error: process terminated
3123 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:194:39
3123 verbose stack     at process.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/signal-handling.js:51:5)
3123 verbose stack     at process.emit (node:events:402:35)
3124 verbose cwd /homebridge
3125 verbose Linux 5.10.63-v7+
3126 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "homebridge-camera-ui@latest"
3127 verbose node v16.13.2
3128 verbose npm  v8.1.2
3129 error process terminated
3130 error signal SIGTERM
3131 verbose exit 1`

But yet in Plugins I see it installed but no options to configure anything.

<img width="866" alt="Screen Shot 2022-01-22 at 07 53 47" src="https://user-images.githubusercontent.com/45573533/150641159-38c0eb14-ad20-4ca6-9eb9-7665ac674ab5.png">

Ideally, I would like to install and manage camera.ui via Homebridge, but I cannot get an installation to work or when it does, it is not exposed via Homebridge.

<img width="446" alt="Screen Shot 2022-01-22 at 07 55 17" src="https://user-images.githubusercontent.com/45573533/150641207-a6c3aacc-e22b-4bc3-bab8-bbe2e39d799c.png">

Am I fundamentally missing something?

**Comment by seydx** [comment]
@chrisswanda 

weird, i dont think that this is related to camera ui, maybe a npm issue or related to homebridge-config-ui-x ?

Try reinstalling via homebridge config ui x or

`sudo npm i -g homebridge-camera-ui@latest`

**Comment by chrisswanda** [comment]
Strange, I tried all morning with no success.  

Walked away from things for a while and came back to it.  I tore down my docker container, did a fresh pull.  

Installation via Homebridge fails, so pulled via the command line inside of Homebridge terminal, and now I can configure it via Homebridge-UI.  

Funny thing is I had done this numerous times prior to opening this issue.  Dunno.  Thanks for responding, closing out.

**Comment by frangeris** [comment]
Same happened to me, after two restart from homebridge server the configuration settled
