### ISSUE TITLE
Doorbell switch is exposed even when configured as false 

### ISSUE THREAD

**Issue by iuliusmaximilian** [seydx/homebridge-camera-ui#385]
The doorbell switch is exposed even when configured as false:

motion : true
doorbell : false
switches : true
hsv : true

Both motion and doorbell switches are exposed.

5.0.12 and before…

**Comment by seydx** [comment]
Hey @iuliusmaximilian 

thx for reporting, i will take a look

**Comment by seydx** [comment]
fixed in v5.0.13-beta.1

**Comment by iuliusmaximilian** [comment]
Tested successfully - thanks!

**Comment by grzegorz914** [comment]
@seydx 
this same happens for motion sensor, is exposed even in config is disabled.

`motion: false`

in home app is exposed

**Comment by seydx** [comment]
> @seydx this same happens for motion sensor, is exposed even in config is disabled.
> 
> `motion: false`
> 
> in home app is exposed

also fixed in the current beta

**Comment by grzegorz914** [comment]
In b.2 not fixed

**Comment by seydx** [comment]
> In b.2 not fixed

Hm sure? It works for me. Do you have `"motion": false` in your config.json? If `"motion"` is not set in config most likely homebridge-config-ui-x has set it to `true` because it is set in config.schema.json as `"default": true`

**Comment by grzegorz914** [comment]
![2C44DB61-1E33-4430-B86D-B062AC545751](https://user-images.githubusercontent.com/28867813/150673339-53ddd2b3-7f83-4794-974d-74790daedf63.jpeg)

**Comment by seydx** [comment]
@grzegorz914 

Ah ok sry i missunderstood. I thought you mean the motion "switch"

Yes, that's right because you have HSV enabled and HSV will create its own motion sensor if not given by the camera

**Comment by grzegorz914** [comment]
OK, understood now.

**Comment by grzegorz914** [comment]
Please look all on prebuffer length, alway after open config is set to sec x 1000

**Comment by seydx** [comment]
> Please look also on prebuffer length, alway after open config is set to sec x 1000

oh ok, thx for reporting

**Comment by seydx** [comment]
fixed in beta 3
