### ISSUE TITLE
After the update Camera Ui, goes into shutdown mode on startup (HOOBS)

### ISSUE THREAD

**Issue by motogon** [seydx/homebridge-camera-ui#387]
**Describe the bug**

After the update Camera Ui ,  goes into shutdown mode on startup

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Logs**
If available, attach the log where the bug is vissible

hoobs -d |grep homebridge-camera-ui
[23.01.2022, 14:03:07] The plugin "homebridge-camera-ui" requires a Homebridge version of ^1.4.0 which does not satisfy the current Homebridge version of 1.3.4. You may need to update this plugin (or Homebridge) to a newer version. You may faceunexpected issues or stability problems running this plugin.
[23.01.2022, 14:03:07] The plugin "homebridge-camera-ui" requires Node.js version of >=14.18.2 which does not satisfy the current Node.js version of v14.15.1. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF
Error loading plugin "homebridge-camera-ui"
Loaded plugin 'homebridge-camera-ui'
Error loading plugin "homebridge-camera-ui"
Loaded plugin 'homebridge-camera-ui'
[Get Plugin Type] Plugin Name: homebridge-camera-ui
[Cache Hit] package/homebridge-camera-ui@5.0.12
[Get Plugin Type] Plugin Name: homebridge-camera-ui
shutdown

**Screenshots**

**Environment**
- Node.js Version: v14.15.1
- HOOBS 3.3.12 ( linux )
- Homebridge Version: vX.X
- Camera UI Version: v5.0.12
- Operating System: Ubuntu 20.04.3 LTS
- Browser: FF

**Comment by seydx** [comment]
Hey @motogon , I think this has something to do with HOOBS?

Version 5 of camera.ui is an ESM package and needs v1.4 of Homebridge (also for HSV). HOOBS might need to update/customize Homebridge?

Your HOOBS runs with Homebridge v1.3.4

**Comment by motogon** [comment]
The installed version of HOOBS is the last one, there are no new updates for this branch . 

ps version of Camera Ui 5.0.8 - works fine .

**Comment by seydx** [comment]
> The installed version of HOOBS is the last one, there are no new updates for this branch .
> 
> ps version of Camera Ui 5.0.8 - works fine .

Then you have to continue to use the version or update your HOOBS/Homebridge.

Version 1.4 of Homebridge includes changes that are needed to run homebridge-camera-ui without errors.
