### ISSUE TITLE
Can‘t activate http in v5.0.13

### ISSUE THREAD

**Issue by Tombra1889** [seydx/homebridge-camera-ui#388]
After saving and restarting it is back to false.

**Comment by seydx** [comment]
> After saving and restarting it is back to false.

Thanks for reporting, i will check it

**Comment by seydx** [comment]
@Tombra1889  can you try v5.0.14-beta.0 pls

**Comment by nitaybz** [comment]
Beta version works... it is solved now, thanks

**Comment by seydx** [comment]
> Beta version works... it is solved now, thanks

Great, i think i will push it later tonight, just looking for other bugs/changes :)

**Comment by seydx** [comment]
v5.0.14 online
