### ISSUE TITLE
Continue codec problems

### ISSUE THREAD

**Issue by platini76** [seydx/homebridge-camera-ui#389]
hello guys, I have since the start many problems on ezviz codec (seems to be codec)
inside ezviz app cams are perfect.
but in camera ui the result is all grey or this in photo..
<img width="1098" alt="Schermata 2022-01-23 alle 14 11 24" src="https://user-images.githubusercontent.com/10352902/150680223-eac30407-59c8-4fb6-8a28-939175852fb1.png">
any solution?

**Comment by seydx** [comment]
@platini76 

can you post your config.json pls

**Comment by platini76** [comment]
{
            "name": "CameraUI",
            "port": 8282,
            "theme": "auto",
            "language": "auto",
            "debug": false, 
            "mqtt": {
                "active": false,
                "tls": false,
                "port": 1883
            },
            "http": {
                "active": false,
                "tls": false,
                "port": 1883
            },
            "ssl": {
                "active": false
            },
            "cameras": [
                {
                    "name": "Cam Terrazzo",
                    "manufacturer": "Ezviz",
                    "model": "C3X",
                    "serialNumber": "E75104062",
                    "unbridge": false,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://admin:AIMVDO@192.168.0.146:554/H.264",
                        "maxStreams": 2,
                        "vcodec": "h264",
                        "stimeout": 0,
                        "audio": true,
                        "stillImageSource": "-rtsp_transport tcp -re -i rtsp://admin:AIMVDO@192.168.0.146:554/H.264",
                        "subSource": "-rtsp_transport tcp -re -i rtsp://admin:AIMVDO@192.168.0.146:554/H.264"
                    },
                    "motionTimeout": 15,
                    "prebufferLength": 4,
                    "hsv": true
                },
                {
                    "name": "Cam Ballatoio",
                    "manufacturer": "Ezviz",
                    "model": "C3X",
                    "serialNumber": "E75103968",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://admin:UPOKDT@192.168.0.147/h264_stream",
                        "maxStreams": 2,
                        "vcodec": "h264",
                        "stimeout": 0,
                        "audio": true,
                        "stillImageSource": "-rtsp_transport tcp -re -i rtsp://admin:UPOKDT@192.168.0.147/h264_stream",
                        "subSource": "-rtsp_transport tcp -re -i rtsp://admin:UPOKDT@192.168.0.147/h264_stream"
                    },
                    "motionTimeout": 15,
                    "prebufferLength": 4,
                    "hsv": true
                }
            ],
            "platform": "CameraUI",
            "atHomeSwitch": false,
            "options": {
                "videoProcessor": "/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"
            },
            "smtp": {
                "active": false,
                "port": 2727,
                "space_replace": "+"
            },
            "ftp": {
                "active": false,
                "useFile": false,
                "port": 5050
            }
        },

**Comment by seydx** [comment]
@platini76 

any reason why you dont "copy" the stream ? and prebuffering also not enabled?

**Comment by platini76** [comment]
no, I am a noob... please suggest a proper config..

**Comment by seydx** [comment]
@platini76 

ok try this config.json

NOTE: i enabled `"unbridged"` for the cameras and changed the names of the cameras. Please dont change back! The previously added cameras will be gone from HomeKit (because they were in bridged mode). After using this config.json and restarting Homebridge, you need to add the cameras again into Home (via "+" in Apple Home).

The PIN will be displayed in the log

```json
{
  "platform": "CameraUI",
  "name": "CameraUI",
  "port": 8282,
  "atHomeSwitch": false,
  "debug": false,
  "smtp": {
    "active": false,
    "port": 2727,
    "space_replace": "+"
  },
  "ftp": {
    "active": false,
    "useFile": false,
    "port": 5050
  },
  "mqtt": {
    "active": false,
    "tls": false,
    "port": 1883
  },
  "http": {
    "active": false,
    "localhost": false,
    "port": 7575
  },
  "ssl": {
    "active": false
  },
  "options": {
    "videoProcessor": "/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"
  },
  "cameras": [
    {
      "name": "Camera Terrazzo",
      "manufacturer": "Ezviz",
      "model": "C3X",
      "serialNumber": "E75104062",
      "unbridge": true,
      "motion": true,
      "motionTimeout": 15,
      "hsv": true,
      "prebuffering": true,
      "prebufferLength": 4,
      "videoConfig": {
        "source": "-i rtsp://admin:AIMVDO@192.168.0.146:554/H.264",
        "subSource": "-i rtsp://admin:AIMVDO@192.168.0.146:554/H.264",
        "stillImageSource": "-i rtsp://admin:AIMVDO@192.168.0.146:554/H.264",
        "rtspTransport": "tcp",
        "maxStreams": 2,
        "vcodec": "copy",
        "acodec": "libfdk_aac",
        "audio": false
      }
    },
    {
      "name": "Camera Ballatoio",
      "manufacturer": "Ezviz",
      "model": "C3X",
      "serialNumber": "E75103968",
      "unbridge": true,
      "motion": true,
      "motionTimeout": 15,
      "hsv": true,
      "prebuffering": true,
      "prebufferLength": 4,
      "videoConfig": {
        "source": "-i rtsp://admin:UPOKDT@192.168.0.147/h264_stream",
        "subSource": "-i rtsp://admin:UPOKDT@192.168.0.147/h264_stream",
        "stillImageSource": "-i rtsp://admin:UPOKDT@192.168.0.147/h264_stream",
        "rtspTransport": "tcp",
        "maxStreams": 2,
        "vcodec": "copy",
        "acodec": "libfdk_aac",
        "audio": false
      }
    }
  ]
}
```

**Comment by platini76** [comment]
I try to do this config... and I will let you know... thanks!!!! very much...

there is an error..
[24/01/2022, 00:28:00] [CameraUI] Camera Terrazzo: Camera does not support H264 stream (hevc (Main), yuvj420p(pc, bt709), 1920x1088, 25 tbr, 90k tbn, 25 tbc). To use prebuffering anyway, enable "forcePrebuffering" in config. Caution: This can lead to a higher CPU load!

**Comment by seydx** [comment]
Disable H265 in your cameras own settings. H265 is not supported. Change it to H264

**Comment by platini76** [comment]
before your message... it seems the same...

<img width="725" alt="Schermata 2022-01-24 alle 00 37 21" src="https://user-images.githubusercontent.com/10352902/150702944-604c44eb-6443-45a7-87fe-1d1c98e5e177.png">


after your message.... is there a way to disable h265 in app? I don't thin so...

**Comment by seydx** [comment]
Check the cameras own settings or app

**Comment by platini76** [comment]
camera does not have settings webpage... and app doesn't allow to do this.

**Comment by seydx** [comment]
can you send a screenshot from the cameras own settings or the app? (like fps, resolution, bitrate etc)

**Comment by platini76** [comment]
![IMG_0438](https://user-images.githubusercontent.com/10352902/150704444-8fcd2d15-5cd1-41fc-8f20-4f2023aa30cf.PNG)
![IMG_E781D536A412-1](https://user-images.githubusercontent.com/10352902/150704448-3472d943-4f3f-4286-8224-c8d611bcb0d8.jpeg)
![IMG_E781D536A412-2](https://user-images.githubusercontent.com/10352902/150704449-bd57f8b3-b176-44e9-b360-58b5e002588a.jpeg)

**Comment by seydx** [comment]
@platini76 

maybe this can help?

https://www.youtube.com/watch?v=LfHD5ib3C64&ab_channel=TURBOHDX

**Comment by platini76** [comment]
thanks! it seems to be solved... I will look again later..
why you did not support h265?

**Comment by seydx** [comment]
@platini76 

changed to h264 now?

**Comment by platini76** [comment]
yes.... image seems ok but some errors like before written and cpu high.. like 50/60% for 2 camera

**Comment by seydx** [comment]
> yes.... image seems ok but some errors like before written and cpu high.. like 50/60% for 2 camera

Set following camera settings if possible

Main Stream:

Resolution: 1920x1080
FPS: 30
Keyframe Interval: 120
Bitrate: 2048 kbps (CBR)

Second/Sub Stream
Resolution: 640x360
FPS: 10

Add the source from second stream into „subSource" in your config.json and restart homebridge

**Comment by platini76** [comment]
<img width="401" alt="Schermata 2022-01-24 alle 13 49 08" src="https://user-images.githubusercontent.com/10352902/150786676-fa9c548f-dc4b-43e0-a721-a559a64e740e.png">
<img width="404" alt="Schermata 2022-01-24 alle 13 48 53" src="https://user-images.githubusercontent.com/10352902/150786680-bcb08bf8-9ee3-4a2c-831c-cb3530328390.png">


these are controls allowed by ezviz studio.

no others...

**Comment by seydx** [comment]
@platini76 

Change the "Bitrate max" in your main stream from "4096" to "2048" and the "Intervallo" to "100"

**Comment by platini76** [comment]
<img width="774" alt="Schermata 2022-01-24 alle 22 30 24" src="https://user-images.githubusercontent.com/10352902/150868140-8c7e8438-b56a-4832-9c6a-e5708426a772.png">

these must be the same?

**Comment by seydx** [comment]
@platini76 

if your camera provides a low resolution sub stream, then enter this to the „Video Substream Source“

otherwise it can be the same as your source

**Comment by platini76** [comment]
I made changes ad you suggest...

which can be the link rstp for subsource in this case?

**Comment by seydx** [comment]
@platini76 

You have to find the source of the second stream (low resolution sub stream) yourself and when you have found it you can add it in config.json under "subSource".

**Comment by platini76** [comment]
thanks! do you have an idea on that?
I search on internet and I find only this:
-i rtsp://admin:XXXXXX@192.168.0.147:554/Streaming/Channels/201

with 201 as sub and 101 as first channel
but it did not work
