### ISSUE TITLE
How to configure motion notification through HTTP or SMTP?

### ISSUE THREAD

**Issue by asaundd** [seydx/homebridge-camera-ui#390]
I want to try using my camera's built in-motion detection but I'm struggling to understand how this should be configured. My camera is configured, shows up in HomeKit, and I do receive motion notifications for videoanalysis triggers in HomeKit, but I want to see if I can get the camera's built-in motion notifications enabled instead.

My camera has SMTP notification enabled and successfully sends messages through a gmail account. However it's unclear how to configure camera.ui to catch this notification and forward to HomeKit. I've tried plugging in the same to/from email accounts in the camera alarm SMTP settings but that doesn't seem to catch anything.

I believe my camera has HTTP motion detection stream as well, but the HTTP alarm fields in camera.ui are disabled, even though I have HTTP enabled and showing as online under the main system settings section.

I'm running homebridge-camera-ui@5.0.14-beta.0 on a Mac.

```
{
  "debug": false,
  "port": 8081,
  "atHomeSwitch": false,
  "options": {
    "videoProcessor": "/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"
  },
  "ssl": {
    "active": false
  },
  "http": {
    "active": true,
    "port": 8559,
    "localhttp": false
  },
  "smtp": {
    "active": true,
    "port": 587,
    "space_replace": "+"
  },
  "ftp": {
    "active": false,
    "useFile": false,
    "port": 5050
  },
  "mqtt": {
    "active": false,
    "tls": false,
    "port": 1883
  },
  "cameras": [
    {
      "name": "Test02",
      "motionTimeout": 15,
      "prebuffering": true,
      "videoConfig": {
        "source": "-i rtsp://user:pw@ip:port/Streaming/Channels/101/",
        "stillImageSource": "-i rtsp://user:pw@ip:port/Streaming/Channels/101/",
        "stimeout": 10,
        "audio": false,
        "debug": true,
        "subSource": "-i rtsp://user:pw@ip:port/Streaming/Channels/102/",
        "rtspTransport": "",
        "vcodec": "copy"
      },
      "mqtt": {},
      "smtp": {
        "email": "",
        "from": ""
      },
      "videoanalysis": {
        "active": true
      },
      "hsv": true,
      "prebufferLength": 4,
      "unbridge": true
    }
  ]
}
```

**Comment by seydx** [comment]
Hey @asaundd 

Your camera must be able to use a custom SMTP server to send an email. This SMTP server must be the one of camera.ui. If your camera can ONLY send an email via Gmail this will not work.

If your camera can use a custom SMTP server, then you just have to enter the IP address of the device where camera.ui is running as server address and the port you defined in config.json. The recipient email must contain the camera name.

E.g. if your camera is called "My Camera", then the email address must be "My+Camera@camera.ui" (everything that comes AFTER the "@" is not important.

If your camera is just called "Camera", then the email address is e.g. "Camera@blabla.com" and so on

There is a small bug with the HTTP server. You have to update to the latest beta version to enable the HTTP server.

This is my SMTP setting for the camera

<img width="819" alt="Bildschirmfoto 2022-01-23 um 20 00 22" src="https://user-images.githubusercontent.com/34152761/150693729-fab70c3e-c7d1-4ed2-a9ca-5b90355c99f4.png">

**Comment by asaundd** [comment]
Thank you - SMTP notifications are working now! It shows a "read ECONNRESET" for each notification but I think that's expected, right?

For HTTP, I did update to 5.0.14-beta.0 and HTTP is enabled, but the HTTP fields under the camera settings are still grayed out. But if I understand correctly, it sounds like those settings are for camera.ui to receive the notification from my physical camera, right? There's no way to configure camera.ui to listen in to my physical camera's HTTP alertStream endpoint for motion detection?

**Comment by seydx** [comment]
> Thank you - SMTP notifications are working now! It shows a "read ECONNRESET" for each notification but I think that's expected, right?
> 
> For HTTP, I did update to 5.0.14-beta.0 and HTTP is enabled, but the HTTP fields under the individual camera settings in camera.ui are still grayed out. But if I understand correctly, it sounds like those settings are for camera.ui to receive the notification from my physical camera, right? There's no way to configure camera.ui to listen in to my physical camera's HTTP alertStream endpoint for motion detection?

no thats not expected, can you post the full log pls?

The input fields for http in the camera.ui interface are disabled. These input fields should just inform you which link you need to use to trigger a motion via HTTP

Atm, there is no way to listen to a custom http event. Can you provide more information regarding the alertStream endpoint pls

**Comment by asaundd** [comment]
Not much more than that in the logs. Each SMTP line is a different notification from the physical camera. But after playing with it I think SMTP is not ideal since there is not a "no motion" or "reset" notification to tell camera.ui to stop recording. 

```
[1/23/2022, 2:47:08 PM] [CameraUI] SMTP: w7dxz4qg6qydf3yb 192.168.4.59 read ECONNRESET
[1/23/2022, 2:47:18 PM] [CameraUI] Test02: Stopping stream..
[1/23/2022, 2:47:18 PM] [CameraUI] Test02: Prebuffer request ended
[1/23/2022, 2:47:18 PM] [CameraUI] Test02: Stream exit (expected)
[1/23/2022, 2:47:27 PM] [CameraUI] SMTP: bdssttps36l3odic 192.168.4.59 read ECONNRESET
[1/23/2022, 2:47:44 PM] [CameraUI] SMTP: b6wbfuqicsbzd5yf 192.168.4.59 read ECONNRESET
[1/23/2022, 2:48:26 PM] [CameraUI] SMTP: u6s3lum4vszczx27 192.168.4.59 read ECONNRESET
```

In config.json I have this is this:
```
  "smtp": {
    "active": true,
    "port": 587,
    "space_replace": "+"
  }
...
      "smtp": {
        "email": "Test02",
        "from": "LTS"
      },

```

And my physical camera configured looks like this:
![Screen Shot 2022-01-23 at 2 48 16 PM](https://user-images.githubusercontent.com/98277490/150695582-73153a7a-df30-43d7-99bd-fd0de0642a7b.png)


Here's some info on the alertStream on HIKVISION cameras (search for "ISAPI/Event/notification/alertStream"): http://mega-avr.net/file/programmy/IP-camera/HIKVISION/2.SDK/ISAPI/HIKVISION%20ISAPI_2.5-IPMD%20Service.pdf

**Comment by seydx** [comment]
> Not much more than that in the logs. Each SMTP line is a different notification from the physical camera. But after playing with it I think SMTP is not ideal since there is not a "no motion" or "reset" notification to tell camera.ui to stop recording.
> 
> ```
> [1/23/2022, 2:47:08 PM] [CameraUI] SMTP: w7dxz4qg6qydf3yb 192.168.4.59 read ECONNRESET
> [1/23/2022, 2:47:18 PM] [CameraUI] Test02: Stopping stream..
> [1/23/2022, 2:47:18 PM] [CameraUI] Test02: Prebuffer request ended
> [1/23/2022, 2:47:18 PM] [CameraUI] Test02: Stream exit (expected)
> [1/23/2022, 2:47:27 PM] [CameraUI] SMTP: bdssttps36l3odic 192.168.4.59 read ECONNRESET
> [1/23/2022, 2:47:44 PM] [CameraUI] SMTP: b6wbfuqicsbzd5yf 192.168.4.59 read ECONNRESET
> [1/23/2022, 2:48:26 PM] [CameraUI] SMTP: u6s3lum4vszczx27 192.168.4.59 read ECONNRESET
> ```
> 
> In config.json I have this is this:
> 
> ```
>   "smtp": {
>     "active": true,
>     "port": 587,
>     "space_replace": "+"
>   }
> ...
>       "smtp": {
>         "email": "Test02",
>         "from": "LTS"
>       },
> ```
> 
> And my physical camera configured looks like this: ![Screen Shot 2022-01-23 at 2 48 16 PM](https://user-images.githubusercontent.com/98277490/150695582-73153a7a-df30-43d7-99bd-fd0de0642a7b.png)
> 
> Here's some info on the alertStream on HIKVISION cameras (search for "ISAPI/Event/notification/alertStream"): http://mega-avr.net/file/programmy/IP-camera/HIKVISION/2.SDK/ISAPI/HIKVISION%20ISAPI_2.5-IPMD%20Service.pdf

Yes thats right. Its not possible to reset the motion via SMTP. But you could try MQTT if your camera supports it. Here in the Issues was one that had motion detection via MQTT with Hikvision

I think the ECONRESET is related to Email Encryption. Thats not supported and should be disabled.

**Comment by asaundd** [comment]
Disabling encryption fixed the ECONRESET error. Nice! Coffee on me.

I don't think my HIKVISION cameras support MQTT but I think there are some programs out there that will convert the alertStream events. I'll look into that. Thanks again!
