### ISSUE TITLE
Question:  Is there an optimal setup to run Camera.ui on?

### ISSUE THREAD

**Issue by plgrimsley** [seydx/homebridge-camera-ui#391]
I've just discovered Camera.UI, I've previously run Homebridge for home automation alone.

I run my Homebridge instance as a Ubuntu Server VM on an ESXi 6.7 server running on a Dell R720 server.  As it was previously only used for home automation and integration with HomeKit, the VM only has 32gb of storage and had 2gb Ram.  I have a video card that I use with my MacOS VM which runs security spy.  

So far, while I can get all the features of HSV to work, the video is really choppy and inconsistent.  I've optimised my camera feeds as much as possible (key frames etc) but have to sacrifice bit rate and even resolution in order to get a half decent video service via Camera.ui.  I also had to turn one of my cameras to H.264 from H.265.  I'm only running 4 cameras, so surely it isn't so taxing on my system?

My question is:  Is there anything I should do to make my VM more powerful in order to run Camera.ui? Or is there an optimal setup?  Are my problems due to running in Ubuntu Server? Perhaps I should shut the MacOS instance down and passthrough my video card to the Ubuntu server that runs Homebridge? 

Camera.UI has opened my eyes, I'd really like to ditch the power hungry ESXi all together and run on a pi4 or similar, but the experience has to be consistent.

Please help. Thank you.

**Comment by seydx** [comment]
Hey @plgrimsley 

Glad you like camera.ui. 

With the right settings, camera.ui can actually run with all setups without any problems. I have two systems running

System 1:
3 cameras via Intel NUC (~10% CPU usage and ~230mb memory usage).

System 2:
5 cameras via Raspberry Pi 4 2GB Ram (~15-20% CPU usage and ~230mb memory usage).

If the stream is not good enough, it is always likely due to wrong config.json and/or camera settings

Could you please post your config.json AND a screenshot of the camera's own settings (bitrate, FPS, resolution etc.)

**Comment by plgrimsley** [comment]
Thanks for the quick response, much appreciated.

Yes, here is my config.json

{
            "name": "CameraUI",
            "port": 7001,
            "atHomeSwitch": true,
            "debug": false,
            "mqtt": {
                "active": false,
                "tls": false,
                "port": 1883
            },
            "http": {
                "active": false,
                "tls": false,
                "port": 1883
            },
            "smtp": {
                "active": false,
                "port": 2727,
                "space_replace": "+"
            },
            "ftp": {
                "active": false,
                "useFile": false,
                "port": 5050
            },
            "ssl": {
                "active": false
            },
            "options": {
                "videoProcessor": "/usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"
            },
            "cameras": [
                {
                    "name": "Driveway",
                    "manufacturer": "SIBO",
                    "model": "SB-MG03AR-1080P",
                    "serialNumber": "EF000000000C42A1",
                    "motion": true,
                    "doorbell": false,
                    "motionTimeout": 15,
                    "motionDoorbell": true,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "forcePrebuffering": false,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://USER:PASSWD@192.168.3.143:554/0/h264major",
                        "subSource": "-i rtsp://USER:PASSWD@192.168.3.143:554/1/h264major",
                        "stillImageSource": "-i rtsp://USER:PASSWD@192.168.3.143:554/1/h264",
                        "readRate": true,
                        "rtspTransport": "tcp",
                        "maxStreams": 2,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 0,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "audio": false
                    },
                    "smtp": {
                        "email": "Driveway"
                    },
                    "videoanalysis": {
                        "active": true
                    }
                },
                {
                    "name": "East",
                    "manufacturer": "RevoTech",
                    "model": "H8EV200-N4",
                    "serialNumber": "1347362",
                    "motion": true,
                    "doorbell": false,
                    "motionTimeout": 15,
                    "motionDoorbell": true,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "forcePrebuffering": false,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://USER:PASSWD@192.168.3.144:5544/live0.264",
                        "subSource": "-i rtsp://USER:PASSWD@192.168.3.144:5544/live1.264",
                        "stillImageSource": "-i rtsp://USER:PASSWD@192.168.3.144:5544/live0.264",
                        "readRate": true,
                        "rtspTransport": "tcp",
                        "maxStreams": 2,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 0,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "audio": false
                    },
                    "smtp": {
                        "email": "East"
                    },
                    "videoanalysis": {
                        "active": true
                    }
                },
                {
                    "name": "West",
                    "motion": true,
                    "doorbell": false,
                    "motionTimeout": 15,
                    "motionDoorbell": true,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i  rtsp://USER:PASSWD@192.168.3.207:554/live/ch0",
                        "subSource": "-i  rtsp://USER:PASSWD@192.168.3.207:554/live/ch1",
                        "stillImageSource": "-i  rtsp://USER:PASSWD@192.168.3.207:554/live/ch1",
                        "readRate": true,
                        "rtspTransport": "tcp",
                        "maxStreams": 2,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 0,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "audio": false
                    },
                    "smtp": {
                        "email": "West"
                    },
                    "videoanalysis": {
                        "active": true
                    }
                }
            ],
            "platform": "CameraUI"
        },
![Screenshot 2022-01-23 at 18 59 10](https://user-images.githubusercontent.com/28228935/150693673-cd6c5492-9d34-4e0b-bac9-391390fce994.png)

![Screenshot 2022-01-23 at 19 00 07](https://user-images.githubusercontent.com/28228935/150693699-68796142-659a-4a37-8d79-9d6d777e3709.png)

The first screenshot is my SIBOHD PTZ, the second is the RevoTech.

I also have a WansView camera but there arent any changeble settings on that camera.

I have quite a few other plugins running in Homebridge.  I previously ran the Homebridge Camera FFmpeg Plugin, its still installed but disabled.

**Comment by plgrimsley** [comment]
Its probably worth mentioning, all cameras are ethernet none are used wirelessly.

**Comment by seydx** [comment]
Try this config.json

```json
{
  "name": "CameraUI",
  "port": 7001,
  "atHomeSwitch": true,
  "debug": false,
  "mqtt": {
    "active": false,
    "tls": false,
    "port": 1883
  },
  "http": {
    "active": false,
    "localhost": false,
    "port": 7575
  },
  "smtp": {
    "active": false,
    "port": 2727,
    "space_replace": "+"
  },
  "ftp": {
    "active": false,
    "useFile": false,
    "port": 5050
  },
  "ssl": {
    "active": false
  },
  "options": {
    "videoProcessor": "/usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"
  },
  "cameras": [
    {
      "name": "Driveway",
      "manufacturer": "SIBO",
      "model": "SB-MG03AR-1080P",
      "serialNumber": "EF000000000C42A1",
      "motion": true,
      "doorbell": false,
      "motionTimeout": 15,
      "motionDoorbell": true,
      "unbridge": true,
      "hsv": true,
      "prebuffering": true,
      "forcePrebuffering": false,
      "prebufferLength": 4,
      "videoConfig": {
        "source": "-i rtsp://USER:PASSWD@192.168.3.143:554/0/h264major",
        "subSource": "-i rtsp://USER:PASSWD@192.168.3.143:554/1/h264major",
        "stillImageSource": "-i rtsp://USER:PASSWD@192.168.3.143:554/1/h264",
        "readRate": false,
        "rtspTransport": "tcp",
        "maxStreams": 2,
        "maxWidth": 1920,
        "maxHeight": 1080,
        "maxFPS": 0,
        "vcodec": "copy",
        "acodec": "libfdk_aac",
        "audio": false
      },
      "smtp": {
        "email": "Driveway"
      },
      "videoanalysis": {
        "active": true
      }
    },
    {
      "name": "East",
      "manufacturer": "RevoTech",
      "model": "H8EV200-N4",
      "serialNumber": "1347362",
      "motion": true,
      "doorbell": false,
      "motionTimeout": 15,
      "motionDoorbell": true,
      "unbridge": true,
      "hsv": true,
      "prebuffering": true,
      "forcePrebuffering": false,
      "prebufferLength": 4,
      "videoConfig": {
        "source": "-i rtsp://USER:PASSWD@192.168.3.144:5544/live0.264",
        "subSource": "-i rtsp://USER:PASSWD@192.168.3.144:5544/live1.264",
        "stillImageSource": "-i rtsp://USER:PASSWD@192.168.3.144:5544/live0.264",
        "readRate": false,
        "rtspTransport": "tcp",
        "maxStreams": 2,
        "maxWidth": 1920,
        "maxHeight": 1080,
        "maxFPS": 0,
        "vcodec": "copy",
        "acodec": "libfdk_aac",
        "audio": false
      },
      "smtp": {
        "email": "East"
      },
      "videoanalysis": {
        "active": true
      }
    },
    {
      "name": "West",
      "motion": true,
      "doorbell": false,
      "motionTimeout": 15,
      "motionDoorbell": true,
      "unbridge": true,
      "hsv": true,
      "prebuffering": true,
      "prebufferLength": 4,
      "videoConfig": {
        "source": "-i rtsp://USER:PASSWD@192.168.3.207:554/live/ch0",
        "subSource": "-i rtsp://USER:PASSWD@192.168.3.207:554/live/ch1",
        "stillImageSource": "-i rtsp://USER:PASSWD@192.168.3.207:554/live/ch1",
        "readRate": false,
        "rtspTransport": "tcp",
        "maxStreams": 2,
        "maxWidth": 1920,
        "maxHeight": 1080,
        "maxFPS": 0,
        "vcodec": "copy",
        "acodec": "libfdk_aac",
        "audio": false
      },
      "smtp": {
        "email": "West"
      },
      "videoanalysis": {
        "active": true
      }
    }
  ],
  "platform": "CameraUI"
}
```

Camera settings looks fine, just change the FPS from the second camera (image) from 10 to 25 or 30 (main stream)

**Comment by plgrimsley** [comment]
Thank you, I've added pasted that back in (with the correct user and passwords) but the cameras are gone from HomeKit.  I wonder might they have been running bridged previously?   I can't seem to see how to add the cameras back in ubbridged.  Forgive me if this is HomeKit 101.  Usually unbridged accessories show up when you click + and add accessory.

**Comment by seydx** [comment]
> Thank you, I've added pasted that back in (with the correct user and passwords) but the cameras are gone from HomeKit. I wonder might they have been running bridged previously? I can't seem to see how to add the cameras back in ubbridged. Forgive me if this is HomeKit 101. Usually unbridged accessories show up when you click + and add accessory.

If they were previously in bridged mode and are now unbridged, change the names of the cameras in config.json and restart HB. After that you should be able to find them in Home App via "+".

**Comment by plgrimsley** [comment]
Thanks so much for your help. All three cameras are now running unbridged and load up immediately when viewed in Home.  
I think this is going to drastically cut my electricity bill, and give me the enhanced features of HSV!  Brilliant work.

**Comment by seydx** [comment]
Glad it worked :)
