### ISSUE TITLE
Typo in error string

### ISSUE THREAD

**Issue by AssetBurned** [seydx/homebridge-camera-ui#392]
**Describe the bug**
Looking at this logged error string, there seems to be a space missing between "No route to hostrtsp://"

**To Reproduce**
setup a camera that can not be reached

**Expected behavior**
error string should be "No route to host rtsp://" with a space before the protocol

**Logs**
[23/01/2022, 19:08:05] [CameraUI] MI: FFmpeg prebuffer process exited with error! (null) - [tcp @ 0x36414e0] Connection to tcp://192.168.0.134:8554?timeout=0 failed: No route to hostrtsp://192.168.0.134:8554/mainstream: No route to host

**Environment**
- Node.js Version: v16.13.1
- Homebridge Version: v1.4.0
- Camera UI Version: v5.0.13
- Operating System: HomeBridge OS
- Browser: Safari

**Comment by seydx** [comment]
Thx for reporting, fixed in the next version

**Comment by AssetBurned** [comment]
No problem. :-)
Maybe slightly changing the "HSV requires a home hub and iCloud plan with at least 200GB of storage." Would be a good thing too. Not sure if i am the only one who was initially thinking that the device running (in my case Homebridge on a Raspberry) needs to have 200GB free.

**Comment by seydx** [comment]
fixed in v5.0.14
