### ISSUE TITLE
Causes homebridge to quit and restart

### ISSUE THREAD

**Issue by kerwinf** [seydx/homebridge-camera-ui#394]
[23/01/2022, 12:37:25] [CameraUI] Patio View: Skip motion trigger. At Home is active and Patio View is not excluded!
[23/01/2022, 12:37:36] Error: spawn ENOMEM
    at ChildProcess.spawn (node:internal/child_process:412:11)
    at spawn (node:child_process:698:9)
    at Object.execFile (node:child_process:325:17)
    at exec (node:child_process:226:25)
    at /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/systeminformation/lib/processes.js:700:11
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
[23/01/2022, 12:37:36] Got SIGTERM, shutting down Homebridge...
[23/01/2022, 12:37:37] [CameraUI] VIDEOANALYSIS: New message: Data: {"time":"2022-01-23T20:37:37.516Z","event":"killed"} - Motion: resetted - Camera: Patio View

**Comment by seydx** [comment]
Hey @kerwinf 

What kind of system do you have?

Can you type `htop` or `top` in terminal and send me a screenshot of the "homebridge" or "homebridge-camera-ui" process?

"ENOMEM" means that there is no memory available for execution

**Comment by kerwinf** [comment]
9143 pi        20   0  436856 330056  37932 R  44.7  34.8   3:52.85 homebridge
 top - 13:13:21 up 319 days, 23:17,  0 users,  load average: 5.74, 9.44, 8.79
Tasks: 157 total,   6 running, 111 sleeping,   0 stopped,  40 zombie
%Cpu(s): 29.3 us,  8.7 sy,  0.0 ni, 59.9 id,  0.1 wa,  0.0 hi,  2.1 si,  0.0 st
MiB Mem :    926.1 total,    452.4 free,    299.8 used,    173.9 buff/cache
MiB Swap:    100.0 total,     14.2 free,     85.8 used.    562.8 avail Mem

**Comment by seydx** [comment]
@kerwinf 

raspberry 3 ? can you also post your config.json please

And reboot the Raspberry

**Comment by kerwinf** [comment]
Sorry I didn’t say this earlier. Thank you so much for all your hard work and for such fast responses! Here is my config.json with ***** marking out in addresses etc.

{
    "bridge": {
        "name": "Homebridge D6B7",
        "username": “**:**:**:**:**:**”,
        "port": *****,
        "pin": “*******”,
        "advertiser": "bonjour-hap",
        "bind": [
            "eth0"
        ]
    },
    "accessories": [
        {
            "name": "Roomba",
            "model": "e5",
            "blid": “*****”,
            "robotpwd": “*****”,
            "ipaddress": "Roomba-*****.local",
            "autoRefreshEnabled": true,
            "keepAliveEnabled": false,
            "cacheTTL": 30,
            "accessory": "Roomba"
        }
    ],
    "platforms": [
        {
            "platform": "TplinkSmarthome",
            "name": "TplinkSmarthome",
            "plugin_map": {
                "plugin_name": "homebridge-tplink-smarthome"
            }
        },
        {
            "platform": "SmtpSensor",
            "port": "2525",
            "sensors": [
                {
                    "name": "Front Door Motion",
                    "keyword": "tripFront"
                },
                {
                    "name": "Patio Motion",
                    "keyword": "tripPatio"
                },
                {
                    "name": "Garage Motion",
                    "keyword": "tripGarage"
                },
                {
                    "name": "Bedroom Motion",
                    "keyword": "tripBedroom"
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-smtpsensor"
            }
        },
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "email": “*****”,
            "password": “*****”,
            "platform": "myQ"
        },
        {
            "name": "CameraUI",
            "port": 8081,
            "atHomeSwitch": true,
            "debug": false,
            "mqtt": {
                "active": false,
                "tls": false,
                "port": 1883
            },
            "http": {
                "active": false,
                "tls": false,
                "port": 1883
            },
            "smtp": {
                "active": false,
                "port": 2727,
                "space_replace": "+"
            },
            "ftp": {
                "active": false,
                "useFile": false,
                "port": 5050
            },
            "ssl": {
                "active": false
            },
            "options": {
                "videoProcessor": "/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"
            },
            "cameras": [
                {
                    "name": "Front Door View",
                    "manufacturer": "Eufy",
                    "model": "Indoor Camera 2K",
                    "serialNumber": "FD01",
                    "motion": true,
                    "doorbell": true,
                    "switches": true,
                    "motionTimeout": 15,
                    "motionDoorbell": true,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://*****/live0",
                        "subSource": "-i rtsp://*****/live0",
                        "stillImageSource": "-i http://*****/++image?cameraNum=1",
                        "rtspTransport": "tcp",
                        "maxStreams": 2,
                        "maxWidth": 0,
                        "maxHeight": 0,
                        "maxFPS": 0,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "stimeout": 10,
                        "audio": true
                    },
                    "videoanalysis": {
                        "active": true
                    }
                },
                {
                    "name": "Garage View",
                    "manufacturer": "Eufy",
                    "model": "Indoor Camera 2K",
                    "serialNumber": "G01",
                    "motion": true,
                    "switches": false,
                    "motionTimeout": 15,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://*****/live0",
                        "subSource": "-i rtsp://*****/live0",
                        "stillImageSource": "-i http://*****/++image?cameraNum=2",
                        "rtspTransport": "tcp",
                        "maxStreams": 2,
                        "maxWidth": 0,
                        "maxHeight": 0,
                        "maxFPS": 0,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "stimeout": 10,
                        "audio": true
                    },
                    "videoanalysis": {
                        "active": true
                    }
                },
                {
                    "name": "Patio View",
                    "manufacturer": "Eufy",
                    "model": "Indoor Camera 2K",
                    "serialNumber": "P01",
                    "motion": true,
                    "switches": false,
                    "motionTimeout": 15,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://*****/live0",
                        "subSource": "-i rtsp://*****/live0",
                        "stillImageSource": "-i http://*****/++image?cameraNum=3",
                        "rtspTransport": "tcp",
                        "maxStreams": 2,
                        "maxWidth": 0,
                        "maxHeight": 0,
                        "maxFPS": 0,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "stimeout": 10,
                        "audio": true
                    },
                    "videoanalysis": {
                        "active": true
                    }
                },
                {
                    "name": "Dining Room View",
                    "manufacturer": "Eufy",
                    "model": "Indoor Pan & Tilt",
                    "serialNumber": "DR01",
                    "motion": true,
                    "switches": false,
                    "motionTimeout": 15,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://*****/live0",
                        "subSource": "-i rtsp://*****/live0",
                        "stillImageSource": "-i http://*****/++image?cameraNum=7",
                        "rtspTransport": "tcp",
                        "maxStreams": 2,
                        "maxWidth": 0,
                        "maxHeight": 0,
                        "maxFPS": 0,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "stimeout": 10,
                        "audio": true
                    },
                    "videoanalysis": {
                        "active": true
                    }
                },
                {
                    "name": "My Room View",
                    "manufacturer": "Eufy",
                    "model": "Indoor Pan & Tilt 2K",
                    "serialNumber": "M01",
                    "motion": true,
                    "switches": false,
                    "motionTimeout": 15,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://*****/live0",
                        "subSource": "-i rtsp://*****/live0",
                        "stillImageSource": "-i http://*****/++image?cameraNum=4",
                        "rtspTransport": "tcp",
                        "maxStreams": 2,
                        "maxWidth": 0,
                        "maxHeight": 0,
                        "maxFPS": 0,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "stimeout": 10,
                        "audio": true
                    },
                    "videoanalysis": {
                        "active": true
                    }
                }
            ],
            "platform": "CameraUI"
        }
    ]
}

**Comment by seydx** [comment]
can you try v5.0.14 pls

**Comment by kerwinf** [comment]
So far it’s looking good. Thank you for the work and update.

**Comment by seydx** [comment]
your raspberry is out of memory, try closing other processes or disable videoanalysis pls

you can also trigger "motion" via smtp, http, mqtt or ftp

**Comment by kerwinf** [comment]
Since I am running only homebridge with only a few plug-ins, I will have to revert back to using camera-ffmpeg as it doesn’t have this problem. Thanks for your effort.
