### ISSUE TITLE
Ability to specify a different "hksvSource" for HKSV recording stream

### ISSUE THREAD

**Issue by longzheng** [seydx/homebridge-camera-ui#397]
**Is your feature request related to a problem? Please describe.**
I currently have my cameras set up like this
```javascript
"cameras": [
    {
        "name": "Front",
        "motion": true,
        "motionTimeout": 0,
        "unbridge": true,
        "hsv": true,
        "prebuffering": false,
        "videoConfig": {
            "source": "-i rtsp://192.168.1.4:554/cam/realmonitor?channel=7&subtype=0",
            "maxBitrate": 800,
            "forceMax": true,
            "rtspTransport": "tcp",
            "audio": true,
        },
```

The purpose of the `maxBirate` and `forceMax` is to increase the bitrate of the HomeKit streams when watching the cameras live, because 300Kbps is practically too low and introduces too many artifacts.

I wouldn't mind using my original source bitrate of 4Mbps, but based on my testing it's too high for viewing the streams out of home over 4G mobile, it's too laggy.

However, I **would** like HKSV to use the streams directly without transcoding for performance/efficiency reasons. I've confirmed HKSV works well with `vcodec: 'copy'`.

**Describe the solution you'd like**
I would like a way to specify/override how the source is supplied to HKSV recordings.

I am thinking if there was an optional `hksvSource` similar to `subSource` then I could specify a value like
```javascript
"hksvSource": "-i -vcodec copy rtsp://192.168.1.4:554/cam/realmonitor?channel=7&subtype=0",
```

to ensure that it copies my video stream directly.

I'm assuming/hoping the `-c:v` bitrate arguments you append will get ignored, but if it does not, then maybe another way to disable the "bitrate" for a HKSV like a `"disableHksvBitrate": true` or something.

**Comment by seydx** [comment]
Added in `v5.0.21-beta.7`

<img width="1164" alt="cui_hksvSource" src="https://user-images.githubusercontent.com/34152761/164578395-c97ba071-6696-47cb-9234-3aef8de304cd.png">

**Comment by seydx** [comment]
Changed in `v5.0.21-beta.10`

HKSV has its own config block now

<img width="1236" alt="cui_hksvSource2" src="https://user-images.githubusercontent.com/34152761/164780783-2261bd29-957a-471a-b420-fb32d89c5e91.png">

**Comment by seydx** [comment]
v5.0.21 online
