### ISSUE TITLE
Update within camera.ui caused removal

### ISSUE THREAD

**Issue by krizzziz** [seydx/homebridge-camera-ui#399]
**Describe the bug**
I noticed within the settings that there was an update available of the camera.ui program. I used the update button and after updating the camera.ui was removed totally from my Homebridge environment.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**
That I would have had a fully updated camera.ui app and not fully removes.

**Logs**
If available, attach the log where the bug is vissible

**Screenshots**

**Environment**
- Node.js Version: vX.X
- Homebridge Version: v1.4
- Camera UI Version: vX.X
- Operating System: Raspian
- Browser: Safari

**Comment by seydx** [comment]
@krizzziz 

its propably because "unbridge" is turned on by default.

change the camera names in your config.json, restart homebridge and add the cameras again to apple Home with "+" within home app

the required PIN is your homebridge PIN

**Comment by krizzziz** [comment]
@seydx 

Probably I did not state clearly enough wat my problem is. It's not that the camera's are gone from the camera.ui plugin. The plugin itself completely disappeared from my Homebridge setup.

The error message I am getting now in the homebridge log is

`No plugin was found for the platform "CameraUI" in your config.json. Please make sure the corresponding plugin is installed correctly.`

**Comment by seydx** [comment]
> @seydx
> 
> Probably I did not state clearly enough wat my problem is. It's not that the camera's are gone from the camera.ui plugin. The plugin itself completely disappeared from my Homebridge setup.
> 
> The error message I am getting now in the homebridge log is
> 
> `No plugin was found for the platform "CameraUI" in your config.json. Please make sure the corresponding plugin is installed correctly.`

The plugin does not seem to be installed correctly. Did you install it via homebridge-config-ui-x?

Maybe try it via the terminal

`sudo npm i -g homebridge-camera-ui@latest --unsafe-perm`

**Comment by seydx** [comment]
ah ok sry my bad, didnt read the title, you have installed it through camera.ui

Try to install via homebridge-config-ui-x

**Comment by krizzziz** [comment]
When using ‘ sudo npm i -g homebridge-camera-ui@latest --unsafe-perm’

I get

`pi@raspberrypi:~ $ sudo npm i -g homebridge-camera-ui@latest --unsafe-perm
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/lib/node_modules/homebridge-camera-ui
npm ERR! dest /usr/lib/node_modules/.homebridge-camera-ui-BgvKeg4a
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/lib/node_modules/homebridge-camera-ui' -> '/usr/lib/node_modules/.homebridge-camera-ui-BgvKeg4a'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-24T18_59_25_900Z-debug.log
pi@raspberrypi:~ $  `

**Comment by seydx** [comment]
try this

`sudo rm -R /usr/lib/node_modules/homebridge-camera-ui`
`sudo rm -R /usr/lib/node_modules/.homebridge-camera-ui*`
`sudo npm i -g homebridge-camera-ui@latest --unsafe-perm`

**Comment by krizzziz** [comment]
Solved, back online. Thanks
