### ISSUE TITLE
Camera working in UI, but does not show up in HomeKit

### ISSUE THREAD

**Issue by bjornand1** [seydx/homebridge-camera-ui#400]
Hi, hope someone can help: I have been connecting two non-HomeKit cameras (Dafang and KingCam) through the Homebridge Camera FFmpeg plugin, and that has been working well. Wanting to get HomeKit Secure Video supported for these camera, I have now disabled that plugin and installed the homebridge-camera-ui plugin. I have used the same parameters in the config and I can now see the cameras in the camera.ui interface.

However, the cameras do not appear in HomeKit, and I see no obvious reason for this. Any ideas?

**Comment by seydx** [comment]
> Hi, hope someone can help: I have been connecting two non-HomeKit cameras (Dafang and KingCam) through the Homebridge Camera FFmpeg plugin, and that has been working well. Wanting to get HomeKit Secure Video supported for these camera, I have now disabled that plugin and installed the homebridge-camera-ui plugin. I have used the same parameters in the config and I can now see the cameras in the camera.ui interface.
> 
> However, the cameras do not appear in HomeKit, and I see no obvious reason for this. Any ideas?

This is due to homebridge. Please change the names of the cameras and restart homebridge.

Then you can add the cameras via the Apple Home app with "+".

The PIN to add the cameras is the same as for homebridge.

**Comment by bjornand1** [comment]
Thanks, @seydx, for your quick reply! I tried this, but when I try to add an accessory with the Homebridge code, I only see the bridge. I presume it should appear as a new camera?

**Comment by seydx** [comment]
Followed the steps above? The camera should appear in the list as a camera.

Is `"undbridged"` enabled in your config.json ?

**Comment by bjornand1** [comment]
Tried again, but went through "Other options", then it appeared, thanks! HSV for a KingCam - unbelievable!

**Comment by seydx** [comment]
> Tried again, but went through "Other options", then it appeared, thanks! HSV for a KingCam - unbelievable!

Great :)

**Comment by bjornand1** [comment]
And Now I got my Dafang camera to work as well, sort of... It is very slow, both in the Camera UI and HomeKit. Any settings that should be tweaked to make it more responsive?

**Comment by seydx** [comment]
> And Now I got my Dafang camera to work as well, sort of... It is very slow, both in the Camera UI and HomeKit. Any settings that should be tweaked to make it more responsive?

can you post your config.json pls

**Comment by bjornand1** [comment]
Sure, for the Dafang camera it is as follows (I should also say that the KingCam is proving to be a bit flaky, it works in the Camera UI, bit now says "No response" in HomeKit despite working earlier.

{
      "name": "CatCamUI",
      "manufacturer": "Dafang",
      "model": "CatCam",
      "motion": true,
      "unbridge": true,
      "hsv": true,
      "prebuffering": true,
      "prebufferLength": 4,
      "videoConfig": {
        "source": "-re -i rtsp://192.168.1.50:8554/unicast",
        "maxStreams": 2,
        "vcodec": "copy",
        "acodec": "libfdk_aac",
        "audio": false,
        "stillImageSource": "-re -i rtsp://192.168.1.50:8554/unicast",
        "subSource": "-re -i rtsp://192.168.1.50:8554/unicast"
      },

**Comment by seydx** [comment]
> {
> "name": "CatCamUI",
> "manufacturer": "Dafang",
> "model": "CatCam",
> "motion": true,
> "unbridge": true,
> "hsv": true,
> "prebuffering": true,
> "prebufferLength": 4,
> "videoConfig": {
> "source": "-re -i rtsp://192.168.1.50:8554/unicast",
> "maxStreams": 2,
> "vcodec": "copy",
> "acodec": "libfdk_aac",
> "audio": false,
> "stillImageSource": "-re -i rtsp://192.168.1.50:8554/unicast",
> "subSource": "-re -i rtsp://192.168.1.50:8554/unicast"
> }

try this config.json

```json
{
  "name": "CatCamUI",
  "manufacturer": "Dafang",
  "model": "CatCam",
  "motion": true,
  "unbridge": true,
  "hsv": true,
  "prebuffering": true,
  "prebufferLength": 4,
  "videoConfig": {
    "source": "-i rtsp://192.168.1.50:8554/unicast",
    "subSource": "-i rtsp://192.168.1.50:8554/unicast",
    "stillImageSource": "-i rtsp://192.168.1.50:8554/unicast",
    "rtspTransport": "tcp",
    "maxStreams": 2,
    "vcodec": "copy",
    "acodec": "libfdk_aac",
    "audio": false
  }
}
```

**Comment by bjornand1** [comment]
Thanks yet again for your help! Yes, that helped a bit, the Dafang camera now shows up in the UI, and sometimes it gets a still in HomeKit, but not video.

**Comment by seydx** [comment]
@bjornand1 

try

```json
{
  "name": "CatCamUI",
  "manufacturer": "Dafang",
  "model": "CatCam",
  "motion": true,
  "unbridge": true,
  "hsv": true,
  "prebuffering": true,
  "prebufferLength": 4,
  "videoConfig": {
    "source": "-i rtsp://192.168.1.50:8554/unicast",
    "subSource": "-i rtsp://192.168.1.50:8554/unicast",
    "stillImageSource": "-i rtsp://192.168.1.50:8554/unicast",
    "rtspTransport": "tcp",
    "maxStreams": 2,
    "vcodec": "libx264",
    "acodec": "libfdk_aac",
    "audio": false
  }
}
```

**Comment by bjornand1** [comment]
Hmm now I get this error message:

The plugin "homebridge-camera-ui" requires Node.js version of >=14.18.2 which does not satisfy the current Node.js version of v14.16.1. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF

**Comment by seydx** [comment]
> Hmm now I get this error message:
> 
> The plugin "homebridge-camera-ui" requires Node.js version of >=14.18.2 which does not satisfy the current Node.js version of v14.16.1. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF

This can be ignored and its not a new "error"

**Comment by bjornand1** [comment]
OK, but I also see this:

CatCamUI: Videoanalysis timed out... killing ffmpeg session

**Comment by seydx** [comment]
> OK, but I also see this:
> 
> CatCamUI: Videoanalysis timed out... killing ffmpeg session

can you post a screenshot from the cameras own settings pls (like fps, bitrate, resolution etc)

**Comment by bjornand1** [comment]
<img width="778" alt="image" src="https://user-images.githubusercontent.com/36516146/150763138-09d68421-db99-4ac7-8829-3aa5768b582d.png">

**Comment by bjornand1** [comment]
Does this help?

**Comment by seydx** [comment]
> Does this help?

Does your stream has also a second/sub stream?

And use this settings (if possible)

```
Resolution: 1920x1080
FPS: 30
Keyframe Interval: 120 (Keyframe Interval = FPS x 4)
Bitrate: 2048 kbps (CBR)
```

**Comment by bjornand1** [comment]
OK, I changed the parameters as you suggested, but now I get this error message:

CatCamUI: FFmpeg prebuffer process exited with error! (null) - [mp3float @ 0x5638ef127300] Header missing -  - [tee @ 0x5638ef164dc0] dimensions not set - Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument -  -

**Comment by seydx** [comment]
Can you enable "debug" in your config.json pls, restart HB and post me the whole log from startup till error

**Comment by bjornand1** [comment]
Absolutely! I turned on debug mode, but where do I find the log?

**Comment by bjornand1** [comment]
[1/24/2022, 11:26:06 AM] [CameraUI] CatCamUI: Can not determine stream codecs, probe timed out
[1/24/2022, 11:26:14 AM] [CameraUI] CatCamUI: FFmpeg prebuffer process exited with error! (null) - [mp3float @ 0x564dec3f9300] Header missing -  - [tee @ 0x564dec437680] dimensions not set - Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument -  - 
[1/24/2022, 11:26:22 AM] [CameraUI] CatCamUI: FFmpeg videoanalysis process exited with error! (null) - [mp3float @ 0x55922e91a300] Header missing -  - Output file #0 does not contain any stream - 
[1/24/2022, 11:26:22 AM] [CameraUI] CatCamUI: FFmpeg videoanalysis process exited with error! (null) - [mp3float @ 0x55922e91a300] Header missing -  - Output file #0 does not contain any stream - 
[1/24/2022, 11:26:22 AM] [CameraUI] CatCamUI: Restart videoanalysis session..
[1/24/2022, 11:26:27 AM] [Homebridge UI] Starting terminal session
[1/24/2022, 11:26:30 AM] [CameraUI] CatCamUI: FFmpeg prebuffer process exited with error! (null) - [mp3float @ 0x55cb78437300] Header missing -  - [tee @ 0x55cb784756c0] dimensions not set - Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument -  - 
[1/24/2022, 11:26:30 AM] [CameraUI] CatCamUI: Prebufferring process closed
[1/24/2022, 11:26:30 AM] [CameraUI] CatCamUI: Restart prebuffer session..
[1/24/2022, 11:26:34 AM] [CameraUI] CatCamUI: Videoanalysis scheduled for restart at 4AM: 993 minutes
[1/24/2022, 11:26:39 AM] [CameraUI] CatCamUI: FFmpeg videoanalysis process exited with error! (null) - [mp3float @ 0x56156dd08300] Header missing -  - Output file #0 does not contain any stream - 
[1/24/2022, 11:26:39 AM] [CameraUI] CatCamUI: FFmpeg videoanalysis process exited with error! (null) - [mp3float @ 0x56156dd08300] Header missing -  - Output file #0 does not contain any stream - 
[1/24/2022, 11:26:39 AM] [CameraUI] CatCamUI: Restart videoanalysis session..
[CatCamUI 9BD7] The image snapshot handler for the given accessory is slow to respond! See https://git.io/JtMGR for more info.
[1/24/2022, 11:26:46 AM] [CameraUI] CatCamUI: Failed to fetch snapshot. Showing "offline" image instead.
[1/24/2022, 11:26:46 AM] [CameraUI] CatCamUI: [mp3float @ 0x560e7fc09300] Header missing -  - Output file #0 does not contain any stream - 
[1/24/2022, 11:26:50 AM] [CameraUI] CatCamUI: Videoanalysis scheduled for restart at 4AM: 993 minutes
[1/24/2022, 11:26:54 AM] [CameraUI] CatCamUI: FFmpeg prebuffer process exited with error! (null) - [mp3float @ 0x559b0cc99300] Header missing -  - [tee @ 0x559b0ccd7700] dimensions not set - Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument -  - 
[1/24/2022, 11:26:54 AM] [CameraUI] CatCamUI: Prebufferring process closed
[1/24/2022, 11:26:54 AM] [CameraUI] CatCamUI: Restart prebuffer session..

**Comment by bjornand1** [comment]
These repeat after startup has finished

**Comment by seydx** [comment]
> These repeat after startup has finished

can you open VLC pls and send me a screenshot from the media settings

VLC > Window > Media information

<img width="1301" alt="Bildschirmfoto 2022-01-24 um 11 32 37" src="https://user-images.githubusercontent.com/34152761/150767223-9c6e6aee-b090-4d45-b6c8-6a808d08aca2.png">

**Comment by bjornand1** [comment]
Hmm, I am on a Mac, but I do have VLC installed. Not sure how I can open camera stream there, though?

**Comment by bjornand1** [comment]
<img width="1004" alt="Screen Shot 2022-01-24 at 11 39 20" src="https://user-images.githubusercontent.com/36516146/150768419-a336ff24-9125-4cde-afde-b2d204441160.png">
<img width="1062" alt="Screen Shot 2022-01-24 at 11 40 08" src="https://user-images.githubusercontent.com/36516146/150768474-d4b1498b-22f3-4231-8a4b-27333c0dc471.png">
<img width="1044" alt="Screen Shot 2022-01-24 at 11 40 16" src="https://user-images.githubusercontent.com/36516146/150768481-0c770d7e-ed66-4ea6-a921-643b25c8516e.png">

**Comment by seydx** [comment]
> Hmm, I am on a Mac, but I do have VLC installed. Not sure how I can open camera stream there, though?

https://user-images.githubusercontent.com/34152761/150771277-26d2886c-7a45-43e4-9126-f268f0e9fb15.mov

**Comment by bjornand1** [comment]
Sorry for late reply, was in a meeting. But now I get this:

<img width="426" alt="CleanShot 2022-01-24 at 13 35 27@2x" src="https://user-images.githubusercontent.com/36516146/150783924-ef5ca7a8-ab10-4556-a819-40917d276f48.png">

I can still see the stream in the browser window, though.

**Comment by seydx** [comment]
> Sorry for late reply, was in a meeting. But now I get this:
> 
> <img alt="CleanShot 2022-01-24 at 13 35 27@2x" width="426" src="https://user-images.githubusercontent.com/36516146/150783924-ef5ca7a8-ab10-4556-a819-40917d276f48.png">
> 
> I can still see the stream in the browser window, though.

Stop homebridge and try again

**Comment by seydx** [comment]
> So I restarted Homebridge, and now I don't get an error message in VLC. But there is no video showing in VLC, but I get this info:
> 
> <img alt="CleanShot 2022-01-24 at 14 01 36@2x" width="532" src="https://user-images.githubusercontent.com/36516146/150787542-5856f74b-a83c-430e-832a-2603cd33578b.png">

Your stream is not a H264 stream, can you change it in your cameras own settings from mjpeg to H264? If not, you need to disable "prebuffering" in your config.json and set "vcodec" to "libx264"

**Comment by bjornand1** [comment]
Hmm, there are controls in the camera settings to start/stop the H264 RTSP and MJPEG RTSP streams, and I have tried starting the former and stopping the latter. That does not seem to help, so I turned off prebuffering and changed the vcodec  setting, but with no success.

**Comment by bjornand1** [comment]
I am wondering if an issue could be safety certificate? Trying to access the camera though Chrome/Firefox, I partly get a safety warning and partly get asked a username/password (which are not required in Safari, where I can access it straight away)?

**Comment by bjornand1** [comment]
Sure, this message keeps repeating:

[1/24/2022, 4:03:50 PM] [CameraUI] CatCamUI: FFmpeg videoanalysis process exited with error! (null) - [tcp @ 0x560d4fd5f7c0] Connection to tcp://192.168.1.50:8554?timeout=0 failed: Connection refused - rtsp://192.168.1.50:8554/unicast: Connection refused - 
[1/24/2022, 4:03:50 PM] [CameraUI] CatCamUI: FFmpeg videoanalysis process exited with error! (null) - [tcp @ 0x560d4fd5f7c0] Connection to tcp://192.168.1.50:8554?timeout=0 failed: Connection refused - rtsp://192.168.1.50:8554/unicast: Connection refused -

**Comment by seydx** [comment]
> Sure, this message keeps repeating:
> 
> [1/24/2022, 4:03:50 PM] [CameraUI] CatCamUI: FFmpeg videoanalysis process exited with error! (null) - [tcp @ 0x560d4fd5f7c0] Connection to tcp://192.168.1.50:8554?timeout=0 failed: Connection refused - rtsp://192.168.1.50:8554/unicast: Connection refused - [1/24/2022, 4:03:50 PM] [CameraUI] CatCamUI: FFmpeg videoanalysis process exited with error! (null) - [tcp @ 0x560d4fd5f7c0] Connection to tcp://192.168.1.50:8554?timeout=0 failed: Connection refused - rtsp://192.168.1.50:8554/unicast: Connection refused -

This has something to do with your camera or the camera source. FFmpeg can't connect to the camera source and that's why the errors occur.

**Comment by bjornand1** [comment]
Yes, I was starting to think so. Do you have any ideas how I could change things at the camera to make it work? It used to work with the Homebridge Camera FFmpeg plugin, before I started changing things to make it work under the Homebridge Camera Ui plugin?

**Comment by bjornand1** [comment]
I rebooted the camera and now I get a different error message:

CatCamUI: FFmpeg videoanalysis process exited with error! (null) - [mp3float @ 0x558821a46300] Header missing -  - Output file #0 does not contain any stream -

**Comment by seydx** [comment]
> <img alt="image" width="778" src="https://user-images.githubusercontent.com/36516146/150763138-09d68421-db99-4ac7-8829-3aa5768b582d.png">

Lets try something else, can you put a "video username" & "video password" and try the stream within VLC again with following source pls

Example
video username: admin
video password: admin

VLC
source: rtsp://admin:admin@192.168.1.50:8554/unicast

**Comment by bjornand1** [comment]
Thanks, I will try that in the morning!

**Comment by bjornand1** [comment]
What do you know, that works, not the stream plays in VLC!

**Comment by bjornand1** [comment]
But now I see that this only works if I set the resolution to 1280X720, increasing it the stream fails. Here are the media information data:

<img width="536" alt="CleanShot 2022-01-25 at 07 38 16@2x" src="https://user-images.githubusercontent.com/36516146/150924748-e425c38c-ac26-47ff-9be9-113029a217e9.png">

But where must I add the username and password to allow access to the camera?

**Comment by seydx** [comment]
> But now I see that this only works if I set the resolution to 1280X720, increasing it the stream fails. Here are the media information data:
> 
> <img alt="CleanShot 2022-01-25 at 07 38 16@2x" width="536" src="https://user-images.githubusercontent.com/36516146/150924748-e425c38c-ac26-47ff-9be9-113029a217e9.png">
> 
> But where must I add the username and password to allow access to the camera?

Just change the video source to

rtsp://admin:admin@192.168.1.50:8554/unicast

(Assuming username is admin and pw is also admin)

**Comment by bjornand1** [comment]
Ah, easy, but I still get this error:

[1/25/2022, 7:59:45 AM] [CameraUI] CatCamTest: Videoanalysis timed out... killing ffmpeg session

**Comment by bjornand1** [comment]
Followed by:

[1/25/2022, 8:00:40 AM] [CameraUI] CatCamTest: Videoanalysis timed out... killing ffmpeg session
[1/25/2022, 8:00:40 AM] [CameraUI] CatCamTest: FFmpeg videoanalysis process exited with error! (SIGKILL) - [mp3float @ 0x562ef985b380] Header missing - 
[1/25/2022, 8:00:40 AM] [CameraUI] CatCamTest: FFmpeg videoanalysis process exited with error! (SIGKILL) - [mp3float @ 0x562ef985b380] Header missing -

**Comment by bjornand1** [comment]
OK, something happening. In the UI dashboard, I now see at least a still image from the camera! It also detects motion, but it times out trying to stream, and it shows as No response in the Home app.

**Comment by bjornand1** [comment]
And furthermore, now and then I can actually get the stream to work in the UI dashboard! But it seems a bit unstable, it can easily be interrupted. In HomeKit, however, there is always the No response message.

**Comment by bjornand1** [comment]
Rebooting the camera again, it seems I can get it to work now and then. It seems the problem is the camera's performance itself.

**Comment by seydx** [comment]
> Rebooting the camera again, it seems I can get it to work now and then. It seems the problem is the camera's performance itself.

Yeah i think so too, you can disable prebuffering and videoanalysis to avoid additional load
