### ISSUE TITLE
Video anomaly 

### ISSUE THREAD

**Issue by frizby66** [seydx/homebridge-camera-ui#401]
**Describe the bug**
HSV recordings have anomalies which cause frames to jump randomly. At the same time, live streams pause…meaning the live stream works (according to HomeKit) but the image is not refreshing (static image). 

**To Reproduce**
Works ok after restart but issue returns after several hours (more than 12).

**Expected behavior**
No anomalies. 

**Logs**
No log, will upload the next time anomaly happens. 

**Screenshots**
https://share.icloud.com/photos/07ej3BalcAhsb0zq-Bfa1pvBA

**Environment**
- Node.js Version: v17.4
- Homebridge Version: v1.4.0
- Camera UI Version: v5.0.14
- Operating System: Ubuntu
- Browser: Safari

**Comment by seydx** [comment]
@frizby66 

can you post your config.json pls

**Comment by frizby66** [comment]
"cameras": [
                {
                    "name": "Main Entrance Door",
                    "manufacturer": "EZVIZ",
                    "model": "C6C",
                    "motion": true,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-re -threads 4 -i rtsp://admin:xxxxxx@192.168.2.180:554/h264_stream",
                        "subSource": "-re -threads 4 -i rtsp://admin:xxxxxxx@192.168.2.180:554/Streaming/Channels/2",
                        "rtspTransport": "tcp",
                        "maxStreams": 2,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "stimeout": 10,
                        "audio": false,
                        "stillImageSource": "-re -i rtsp://admin:6Lansdowne@192.168.2.180:554/h264_stream",
                        "readRate": true,
                        "debug": true
                    },
                    "videoanalysis": {
                        "active": true
                    },
                    "motionTimeout": 15,
                    "mqtt": {},
                    "smtp": {
                        "email": "Main Entrance Door"
                    }
                }
            ],
            "platform": "CameraUI",
            "atHomeSwitch": false,
            "options": {
                "videoProcessor": "/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"
            }”

unable to post pic of camera config as hikvision, so no web interface available. Everything works fine initially, however issue happens after several house.

**Comment by seydx** [comment]
@frizby66 

try following config.json

```json
{
  "name": "Main Entrance Door",
  "manufacturer": "EZVIZ",
  "model": "C6C",
  "motion": true,
  "unbridge": true,
  "hsv": true,
  "prebuffering": true,
  "prebufferLength": 4,
  "motionTimeout": 15,
  "videoConfig": {
    "source": "-i rtsp://admin:xxxxxx@192.168.2.180:554/h264_stream",
    "subSource": "-i rtsp://admin:xxxxxxx@192.168.2.180:554/Streaming/Channels/2",
    "stillImageSource": "-i rtsp://admin:xxxxxx@192.168.2.180:554/h264_stream",
    "rtspTransport": "tcp",
    "maxStreams": 2,
    "vcodec": "copy",
    "acodec": "libfdk_aac",
    "stimeout": 10,
    "audio": false,
    "readRate": false,
    "debug": true
  },
  "mqtt": {},
  "smtp": {
    "email": "Main Entrance Door"
  },
  "videoanalysis": {
    "active": true
  }
}
```

**Comment by frizby66** [comment]
Updated…will monitor and let you know.

**Comment by seydx** [comment]
closing the issue here, if anything unusual comes up you can post here
