### ISSUE TITLE
Question - timing configuration for pictures

### ISSUE THREAD

**Issue by andre1210** [seydx/homebridge-camera-ui#403]
I'm using this plugin for a long time and I like it very much. 
My use case is as following:
I have reed contacts at garden doors and send an MQTT message on issuing. 
camera-ui shall take a screenshot and send and telegram message.
This is working as expected (I'm using the current version v5.0.14)

With my new cameras (Reolink RCL-410W) a have a delay in rtsp and rtmp stream from about 2-3 seconds.
So if the reed contact triggers, homebridge-camera-ui takes immediate the screenshot, but the camera stream has to this time a picture from 2-3 seconds before and I can see nobody on the picture.
I observed the smaller I configure the framerate in the camera (e.g. 6-10) frames, the greater is the delay. Very strange.
But for other software (zoneminder) I need a small frame rate.

My question is: Could it be possible to configure a delay between triggering from mqtt and taking the picture?

Thank you
regards
Andre

**Comment by seydx** [comment]
added in v5.0.25 

add eg `"motionDelay": 5` in config.json

<img width="1228" alt="cui_motionDelay" src="https://user-images.githubusercontent.com/34152761/164950564-fedbea9b-3452-4dd9-a0b3-e08cf76d25a4.png">

**Comment by andre1210** [comment]
Thank you for implementing this
