### ISSUE TITLE
Error when loading settings menu from Config-UI-X

### ISSUE THREAD

**Issue by cyberralf83** [seydx/homebridge-camera-ui#406]
**Describe the bug**
Whenever I try to access the settings menu from the config-ui-x plugins page the gear just spends. 

**Expected behavior**
It should load the settings menu for me to configure, right?

**Logs**
[Homebridge UI] [homebridge-camera-ui] file:///usr/lib/node_modules/homebridge-camera-ui/homebridge-ui/server.js:28
    const cameraUI = config?.platforms?.find((plugin) => plugin?.platform === 'CameraUI');
                            ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at async link (internal/modules/esm/module_job.js:42:21)

**Screenshots**

**Environment**
- Node.js Version: v16.13.2
- Homebridge Version: 1.4.0 Config-UI-X: v4.42.0
- Camera UI Version:  v5.0.14
- Operating System: Bullseye
- Browser: Chrome

**Comment by seydx** [comment]
should be fixed in the current beta, can you give it a try pls

v5.0.15-beta.1

**Comment by seydx** [comment]
v5.0.15 online

**Comment by cyberralf83** [comment]
works, thanks!
