### ISSUE TITLE
CPU Load

### ISSUE THREAD

**Issue by istationonline** [seydx/homebridge-camera-ui#407]
**Describe the bug**
Since installing this plug-in cpu load is constant 97% 

**To Reproduce**
Continuous

**Expected behavior**
Don't expect this amount of load

**Logs**
If available, attach the log where the bug is vissible

**Screenshots**

**Environment**
- Node.js Version: 	v16.13.0
- Homebridge Version: 1.4.0
- Camera UI Version: v5.0.14
- Operating System: Raspbian GNU/Linux
- Browser: XXX

![image](https://user-images.githubusercontent.com/59316784/150846888-491c81b2-63de-4bbf-80c1-18f1f16ac956.png)

**Comment by istationonline** [comment]
"bridge": {
        "name": "Homebridge 6291",
        "username": "0E:99:62:8E:62:91",
        "port": 51021,
        "pin": "927-46-394",
        "bind": [
            "eth0"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "controllers": [
                {
                    "address": "172.16.106.1",
                    "name": "HomeCKP",
                    "password": "",
                    "refreshInterval": 5,
                    "username": "HomeKit"
                }
            ],
            "motionDuration": 10,
            "platform": "UniFi Protect"
        },
        {
            "name": "Camera FFmpeg",
            "platform": "Camera-ffmpeg"
        },
        {
            "country": "GB",
            "language": "en-GB",
            "auth_mode": "token",
            "platform": "LGThinQ",
            "refresh_token": "b4c0af014503fde0a4ca43305212895e59f4806906474dcb42a0e07e625d7797664c7d9ba5eb7967dbb531646dbf176c",
            "username": "",
            "password": "",
            "devices": [
                {
                    "id": "f50b6752-8339-1d5f-866f-f8b95a9f8f0a",
                    "name": "ThinkQ Washer",
                    "type": "WASHER",
                    "washer_trigger": true,
                    "washer_door_lock": true,
                    "ac_mode": "BOTH",
                    "ac_swing_mode": "BOTH",
                    "ac_temperature_sensor": false,
                    "ac_led_control": false,
                    "ac_fan_control": false
                }
            ],
            "refresh_interval": 30,
            "thinq1": true,
            "_bridge": {
                "username": "0E:97:63:CF:8A:3C",
                "port": 44807
            }
        },
        {
            "name": "CameraUI",
            "debug": false,
            "mqtt": {
                "active": false,
                "tls": false,
                "port": 1883
            },
            "http": {
                "active": false,
                "port": 1883,
                "localhttp": false
            },
            "smtp": {
                "active": false,
                "port": 2727,
                "space_replace": "+"
            },
            "ftp": {
                "active": false,
                "useFile": false,
                "port": 5050
            },
            "ssl": {
                "active": false
            },
            "cameras": [
                {
                    "name": "DoorBell",
                    "motion": true,
                    "doorbell": true,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsps://172.16.106.1:7441/kj45RFrNFl9REYnf?enableSrtp",
                        "rtspTransport": "tcp",
                        "vcodec": "copy",
                        "audio": true,
                        "stillImageSource": "-i rtsps://172.16.106.1:7441/kj45RFrNFl9REYnf?enableSrtp",
                        "subSource": "-i rtsps://172.16.106.1:7441/kj45RFrNFl9REYnf?enableSrtp"
                    },
                    "videoanalysis": {
                        "active": true
                    },
                    "motionTimeout": 15,
                    "smtp": {
                        "email": "DoorBell"
                    },
                    "mqtt": {}
                },
                {
                    "name": "Drive",
                    "motion": true,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsps://172.16.106.1:7441/LwAUkK1BkAiDzzxB?enableSrtp",
                        "rtspTransport": "tcp",
                        "vcodec": "copy",
                        "audio": true,
                        "stillImageSource": "-i rtsps://172.16.106.1:7441/LwAUkK1BkAiDzzxB?enableSrtp",
                        "subSource": "-i rtsps://172.16.106.1:7441/LwAUkK1BkAiDzzxB?enableSrtp"
                    },
                    "videoanalysis": {
                        "active": true
                    },
                    "motionTimeout": 15,
                    "smtp": {
                        "email": "Drive"
                    },
                    "mqtt": {}
                },
                {
                    "name": "Side",
                    "motion": true,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsps://172.16.106.1:7441/mmWzJqxib5Fy34vz?enableSrtp",
                        "rtspTransport": "tcp",
                        "vcodec": "copy",
                        "audio": true,
                        "stillImageSource": "-i rtsps://172.16.106.1:7441/mmWzJqxib5Fy34vz?enableSrtp",
                        "subSource": "-i rtsps://172.16.106.1:7441/mmWzJqxib5Fy34vz?enableSrtp"
                    },
                    "videoanalysis": {
                        "active": true
                    },
                    "motionTimeout": 15,
                    "smtp": {
                        "email": "Side"
                    },
                    "mqtt": {}
                },
                {
                    "name": "Back",
                    "motion": true,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsps://172.16.106.1:7441/tuRzRvZsAjeD5e0o?enableSrtp",
                        "rtspTransport": "tcp",
                        "vcodec": "copy",
                        "audio": true,
                        "stillImageSource": "-i rtsps://172.16.106.1:7441/tuRzRvZsAjeD5e0o?enableSrtp",
                        "subSource": "-i rtsps://172.16.106.1:7441/tuRzRvZsAjeD5e0o?enableSrtp"
                    },
                    "videoanalysis": {
                        "active": true
                    },
                    "motionTimeout": 15,
                    "smtp": {
                        "email": "Back"
                    },
                    "mqtt": {}
                }
            ],
            "_bridge": {
                "username": "0E:74:88:72:66:2A",
                "port": 37197
            },
            "platform": "CameraUI",
            "port": 8081,
            "atHomeSwitch": false,
            "options": {
                "videoProcessor": "/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"
            }
        }
    ],
    "disabledPlugins": [
        "homebridge-lgwebos-tv",
        "homebridge-unifi-protect"
    ]
}

**Comment by seydx** [comment]
@istationonline 

Can you also post a screenshot of the camera's own settings please

The config.json seems ok

The subStream should use a stream with low resolution and FPS 

```
Resolution: 640x360
FPS: 10
```

**Comment by istationonline** [comment]
Camera setting in camera.ui or Unify?

**Comment by seydx** [comment]
> Camera setting in camera.ui or Unify?

unify

**Comment by istationonline** [comment]
![image](https://user-images.githubusercontent.com/59316784/150850324-69716121-3622-491d-9798-d9533381974c.png)

![image](https://user-images.githubusercontent.com/59316784/150850353-8e69ef5a-bfcb-4b34-b162-78b303af1a10.jpeg)

![image](https://user-images.githubusercontent.com/59316784/150850372-f5bcb824-0d90-46de-ae60-e00be557b10f.png)

**Comment by seydx** [comment]
@istationonline 

put the "low stream" source into "subSource" in your config.json and restart hb pls

**Comment by istationonline** [comment]
That seems to have resolved the problem.. thanks for the prompt support.. 

![image](https://user-images.githubusercontent.com/59316784/150852200-eac857df-7352-4c0e-a518-8b84240ab920.png)

**Comment by paqpaqpaq** [comment]
Can 25-35 be considered a normal CPU load with camera.ui running?
Without it, CPU in idle is normally between 3-5%

**Comment by seydx** [comment]
> Can 25-35 be considered a normal CPU load with camera.ui running? Without it, CPU in idle is normally between 2-3%

it depends on the amount of the cameras and the entered subSource in your config.json

On a raspberry pi 4 with 2 GB ram and 5 cameras with videoanalysis enabled and low resolution subSource i have ~15-20% cpu load

**Comment by seydx** [comment]
> ok wow... no I am on 1 cam on a 3B+ subsource is only 640x480

hm for only 1 camera its pretty much i think, even on a raspi 3..

Try to decrease all settings like fps etc. for the sub-stream. You can also set a lower resolution if its possible in the cameras own settings
