### ISSUE TITLE
HSV "UNEXPECTED_FAILURE"

### ISSUE THREAD

**Issue by kotyzaf** [seydx/homebridge-camera-ui#408]
Hello,

I would like to ask you for help. I have a problem with setup the HSV recording on my two Reolink RLC 810 cameras. I tried a many different settings, but nothing works. Everything else working fine, but the HSV recording not. Did someone successfully set this type of camera with HSV recording or can somebody help me with it?

**My config is:**
{
            "name": "CameraUI",
            "port": 8081,
            "atHomeSwitch": false,
            "debug": false,
            "mqtt": {
                "active": false,
                "tls": false,
                "port": 1883
            },
            "http": {
                "active": false,
                "port": 7272,
                "localhttp": false
            },
            "smtp": {
                "active": true,
                "port": 2727,
                "space_replace": "+"
            },
            "ftp": {
                "active": false,
                "useFile": false,
                "port": 5050
            },
            "ssl": {
                "active": false
            },
            "options": {
                "videoProcessor": "/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"
            },
            "cameras": [
                {
                    "name": "Back Yard Camera",
                    "manufacturer": "Reolink",
                    "model": "RLC-810",
                    "motion": true,
                    "motionTimeout": 15,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "forcePrebuffering": false,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://XXXXXXX@XXXXXXX//h264Preview_01_sub",
                        "subSource": "-i rtsp://XXXXXXX@XXXXXXX//h264Preview_01_sub",
                        "stillImageSource": "-i rtsp://XXXXXXX@XXXXXXX//h264Preview_01_sub",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 20,
                        "maxBitrate": 299,
                        "forceMax": false,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "audio": true
                    },
                    "smtp": {
                        "email": "Back Yard Camera"
                    },
                    "videoanalysis": {
                        "active": false
                    },
                    "mqtt": {}
                },
                {
                    "name": "Front Yard Camera",
                    "motion": true,
                    "motionTimeout": 15,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://XXXXXXX@XXXXXXX//h264Preview_01_sub",
                        "subSource": "-i rtsp://XXXXXXX@XXXXXXX//h264Preview_01_sub"",
                        "stillImageSource": "-i rtsp://XXXXXXX@XXXXXXX//h264Preview_01_sub",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 20,
                        "maxBitrate": 299,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "audio": true
                    },
                    "smtp": {
                        "email": "Front Yard Camera"
                    },
                    "videoanalysis": {
                        "active": false
                    },
                    "mqtt": {}
                }
            ],
            "platform": "CameraUI"
        }

**Camera settings (I am using sub stream, because main stream is H.265):**

<img width="1440" alt="Snímek obrazovky 2022-01-24 v 20 02 34" src="https://user-images.githubusercontent.com/98350365/150847195-0c95508d-8ae4-4043-8039-06af7bc8cf56.png">
<img width="1440" alt="Snímek obrazovky 2022-01-24 v 20 02 50" src="https://user-images.githubusercontent.com/98350365/150847264-ff5dadd6-7f7a-494d-9549-f63d291d95a6.png">

Thank you for any help.

**Comment by seydx** [comment]
@kotyzaf 

Try following camera settings for your main stream

```
Resolution: 1920x1080
FPS: 30
Interframe Space: 4
Bitrate: 2048 kbps
```

The parameter for your second/sub stream is ok, please enter the source of your second/sub stream in your config.json into "subSource"

and try following config.json

```json
{
  "name": "CameraUI",
  "port": 8081,
  "atHomeSwitch": false,
  "debug": false,
  "mqtt": {
    "active": false,
    "tls": false,
    "port": 1883
  },
  "http": {
    "active": false,
    "port": 7272,
    "localhttp": false
  },
  "smtp": {
    "active": true,
    "port": 2727,
    "space_replace": "+"
  },
  "ftp": {
    "active": false,
    "useFile": false,
    "port": 5050
  },
  "ssl": {
    "active": false
  },
  "options": {
    "videoProcessor": "/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"
  },
  "cameras": [
    {
      "name": "Back Yard Camera",
      "manufacturer": "Reolink",
      "model": "RLC-810",
      "motion": true,
      "motionTimeout": 15,
      "unbridge": true,
      "hsv": true,
      "prebuffering": true,
      "forcePrebuffering": false,
      "prebufferLength": 4,
      "videoConfig": {
        "source": "-i rtsp://admin:Reolink13518661066542@192.168.90.247:554//h264Preview_01_sub",
        "subSource": "-i rtsp://admin:Reolink13518661066542@192.168.90.247:554//h264Preview_01_sub",
        "stillImageSource": "-i rtsp://admin:Reolink13518661066542@192.168.90.247:554//h264Preview_01_sub",
        "rtspTransport": "tcp",
        "vcodec": "copy",
        "acodec": "libfdk_aac",
        "audio": false
      },
      "smtp": {
        "email": "Back Yard Camera"
      },
      "videoanalysis": {
        "active": false
      },
      "mqtt": {}
    },
    {
      "name": "Front Yard Camera",
      "motion": true,
      "motionTimeout": 15,
      "unbridge": true,
      "hsv": true,
      "prebuffering": true,
      "prebufferLength": 4,
      "videoConfig": {
        "source": "-rtsp_transport tcp -i rtsp://admin:gysfuc-8ruzfe-tywsUq@192.168.90.74:554//h264Preview_01_sub",
        "subSource": "-rtsp_transport tcp -i rtsp://admin:gysfuc-8ruzfe-tywsUq@192.168.90.74:554//h264Preview_01_sub",
        "stillImageSource": "-rtsp_transport tcp -i rtsp://admin:gysfuc-8ruzfe-tywsUq@192.168.90.74:554//h264Preview_01_sub",
        "rtspTransport": "tcp",
        "vcodec": "copy",
        "acodec": "libfdk_aac",
        "audio": false
      },
      "smtp": {
        "email": "Front Yard Camera"
      },
      "videoanalysis": {
        "active": false
      },
      "mqtt": {}
    }
  ],
  "platform": "CameraUI"
}
```

**Comment by kotyzaf** [comment]
Thank you for your fast response. 
That's the thing. I am not able to change resolution of the main stream lower than 2304x1296 and on the other hand the sub stream higher than 640x360. It is the limitation from Reolink. Because of that I am using only sub stream in config, because the main stream is in high resolution and H.265.

Thank you.

**Comment by seydx** [comment]
> Thank you for your fast response. That's the thing. I am not able to change resolution of the main stream lower than 2304x1296 and on the other hand the sub stream higher than 640x360. It is the limitation from Reolink. Because of that I am using only sub stream in config, because the main stream is in high resolution and H.265.
> 
> Thank you.

Ah ok, so the source/subSource/stillImageSource is from the sub source of your camera?

If you use the sub source as main source for camera.ui, you should set FPS of your sub source to something greater than 20

**Comment by kotyzaf** [comment]
Yes that is correct, all of that is sub source

Unfortunately not, the highest fps is 15.

**Comment by seydx** [comment]
@kotyzaf 

ok update to `v5.0.15-beta.1` and try the following config.json please

```json
{
  "name": "CameraUI",
  "port": 8081,
  "atHomeSwitch": false,
  "debug": false,
  "mqtt": {
    "active": false,
    "tls": false,
    "port": 1883
  },
  "http": {
    "active": false,
    "port": 7272,
    "localhttp": false
  },
  "smtp": {
    "active": true,
    "port": 2727,
    "space_replace": "+"
  },
  "ftp": {
    "active": false,
    "useFile": false,
    "port": 5050
  },
  "ssl": {
    "active": false
  },
  "options": {
    "videoProcessor": "/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"
  },
  "cameras": [
    {
      "name": "Back Yard Camera",
      "manufacturer": "Reolink",
      "model": "RLC-810",
      "motion": true,
      "motionTimeout": 15,
      "unbridge": true,
      "hsv": true,
      "prebuffering": true,
      "forcePrebuffering": false,
      "prebufferLength": 4,
      "videoConfig": {
        "source": "-i rtsp://admin:Reolink13518661066542@192.168.90.247:554//h264Preview_01_sub",
        "subSource": "-i rtsp://admin:Reolink13518661066542@192.168.90.247:554//h264Preview_01_sub",
        "stillImageSource": "-i rtsp://admin:Reolink13518661066542@192.168.90.247:554//h264Preview_01_sub",
        "rtspTransport": "tcp",
        "vcodec": "libx264",
        "acodec": "libfdk_aac",
        "audio": false
      },
      "smtp": {
        "email": "Back Yard Camera"
      },
      "videoanalysis": {
        "active": false
      },
      "mqtt": {}
    },
    {
      "name": "Front Yard Camera",
      "motion": true,
      "motionTimeout": 15,
      "unbridge": true,
      "hsv": true,
      "prebuffering": true,
      "prebufferLength": 4,
      "videoConfig": {
        "source": "-rtsp_transport tcp -i rtsp://admin:gysfuc-8ruzfe-tywsUq@192.168.90.74:554//h264Preview_01_sub",
        "subSource": "-rtsp_transport tcp -i rtsp://admin:gysfuc-8ruzfe-tywsUq@192.168.90.74:554//h264Preview_01_sub",
        "stillImageSource": "-rtsp_transport tcp -i rtsp://admin:gysfuc-8ruzfe-tywsUq@192.168.90.74:554//h264Preview_01_sub",
        "rtspTransport": "tcp",
        "vcodec": "libx264",
        "acodec": "libfdk_aac",
        "audio": false
      },
      "smtp": {
        "email": "Front Yard Camera"
      },
      "videoanalysis": {
        "active": false
      },
      "mqtt": {}
    }
  ],
  "platform": "CameraUI"
}
```

**Comment by kotyzaf** [comment]
I tried it. No fault in log anymore but I don't have any video in cloud to view. 

[24/01/2022, 20:40:33] [CameraUI] SMTP: New message: Data (email to): [{"address":"Back+Yard+Camera@camera.com","args":false}]
[24/01/2022, 20:40:33] [CameraUI] Back Yard Camera: Motion ON
[24/01/2022, 20:40:48] [CameraUI] Back Yard Camera: Motion OFF - Motion handler timeout.
[24/01/2022, 20:40:50] [CameraUI] Back Yard Camera: Closing recording process
[24/01/2022, 20:41:32] [CameraUI] SMTP: New message: Data (email to): [{"address":"Front+Yard+Camera@camera.com","args":false}]
[24/01/2022, 20:41:32] [CameraUI] Front Yard Camera: Motion ON
[24/01/2022, 20:41:47] [CameraUI] Front Yard Camera: Motion OFF - Motion handler timeout.
[24/01/2022, 20:41:49] [CameraUI] Front Yard Camera: Closing recording process

**Comment by kotyzaf** [comment]
Ok a little update. It is working now. I see the recorded videos in HomeKit from both cameras. Thank you very much for a help.

**Comment by seydx** [comment]
> Ok a little update. It is working now. I see the recorded videos in HomeKit from both cameras. Thank you very much for a help.

Very good, glad to hear, closing this issue then

**Comment by kotyzaf** [comment]
Thanks and please can I ask you what was the change in this version, or It was maybe the change of config? I see different codec for video and -rtsp transport on the second camera. It is possible that this config will work with non beta version or I must stay on beta? Thank you.

**Comment by seydx** [comment]
> Thanks and please can I ask you what was the change in this version, or It was maybe the change of config? I see different codec for video and -rtsp transport on the second camera. It is possible that this config will work with non beta version or I must stay on beta? Thank you.

Stay atm on beta pls, it contains several bugfixes

once v5.0.15 is online, you can update

**Comment by seydx** [comment]
> I tried it. No fault in log anymore but I don't have any video in cloud to view.
> 
> [24/01/2022, 20:40:33] [CameraUI] SMTP: New message: Data (email to): [{"address":"[Back+Yard+Camera@camera.com](mailto:Back+Yard+Camera@camera.com)","args":false}] [24/01/2022, 20:40:33] [CameraUI] Back Yard Camera: Motion ON [24/01/2022, 20:40:48] [CameraUI] Back Yard Camera: Motion OFF - Motion handler timeout. [24/01/2022, 20:40:50] [CameraUI] Back Yard Camera: Closing recording process [24/01/2022, 20:41:32] [CameraUI] SMTP: New message: Data (email to): [{"address":"[Front+Yard+Camera@camera.com](mailto:Front+Yard+Camera@camera.com)","args":false}] [24/01/2022, 20:41:32] [CameraUI] Front Yard Camera: Motion ON [24/01/2022, 20:41:47] [CameraUI] Front Yard Camera: Motion OFF - Motion handler timeout. [24/01/2022, 20:41:49] [CameraUI] Front Yard Camera: Closing recording process

Check this

https://github.com/seydx/homebridge-camera-ui/wiki/HSV#1-no-hsv-recordings
