### ISSUE TITLE
Reolink-RLC 822A

### ISSUE THREAD

**Issue by agsenna** [seydx/homebridge-camera-ui#409]
hi there,

i use this code for the Reolink Camera and the "stillImageSource" 
after i changed from http// to https// the stllimage works perfekt but the rest doesn't
(see the code at the end).

i get this error message 

24/01/2022, 22:08:35] [CameraUI] CAMERA NAME: FFmpeg exited with code: 1 and signal: null - [tcp @ 0x322cac0] [error] Connection to tcp://192.168.181.94:554?timeout=0 failed: Connection refused - [error] rtsp://USER:XXX@192.168.181.94:554/h264Preview_01_main: Connection refused
[24/01/2022, 22:08:35] [CameraUI] CAMERA NAME: Stopped video stream.

and here is the code:

"name": "CAMERA NAME",                    "motion": true,                    "motionTimeout": 15,                    "unbridge": true,                    "hsv": true,                    "prebuffering": true,                    "prebufferLength": 4,                    "videoConfig": {                        "source": "-rtsp_transport tcp -re -i rtsp://USER:XXX@192.168.181.94:554/h264Preview_01_main",                        "subSource": "-rtsp_transport tcp -re -i rtsp://USER:XXX@192.168.181.94:554/h264Preview_01_main",                        "stillImageSource": "-i https://192.168.181.94/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=wuuPhkmUCeI9WG7C&user=XXX&password=XXX",                        "maxStreams": 2,                        "vcodec": "copy",                        "acodec": "libfdk_aac",                        "audio": false                    },                    "smtp": {                        "email": "CAMERA NAME"                    },                    "videoanalysis": {                        "active": true                    },                    "mqtt": {}

thank you in advance georgios

**Comment by iGranDav** [comment]
Hi, 

As a RLC 822A owner I can help 🙂 this camera is a 4K one so the main stream doesn't support h264 but h265. Since camera UI currently only support rtsp over h264 here is the configuration you need to apply in your `videoConfig`:

```json
"videoConfig": {
                        "source": "-i rtsp://user:password@192.168.181.94:554/h264Preview_01_sub",
                        "subSource": "-i rtsp://user:password@192.168.181.94:554/h264Preview_01_sub",
                        "stillImageSource": "-i  https://192.168.181.94/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=wuuPhkmUCeI9WG7C&user=XXX&password=XXX",
                        "rtspTransport": "tcp",
                        "maxStreams": 2,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "stimeout": 10,
                        "audio": false
                    }
```

**Comment by seydx** [comment]
Please adopt the config as described above

**Comment by agsenna** [comment]
i've done it but still doesn't work. i'm gonna try something else and i will come back to you. thank you georgios

**Comment by iGranDav** [comment]
If you have the latest firmware version `v3.1.0.764_21121707` or above (for users in the future) you need to enable `RTSP`.

Simplest way is to use the web interface using https `https://<your camera ip address>` then:
- click on settings (top right gear icon)
- click on `Network Settings`
- `Port Settings` (yes that's somewhat related to ports)
- Enable `RTSP`

I had this issue yesterday after updating my cameras 🙂

**Comment by agsenna** [comment]
THANK YOU!!!
it's working you are great!

georgios_
