### ISSUE TITLE
Logging is quite verbose.. is there a way to only show errors?

### ISSUE THREAD

**Issue by marksthomas** [seydx/homebridge-camera-ui#416]
Hi,

Great plugin, and works fantastic. I have three IP cameras (Reolink) working great with HSV, so thank you for that.

The logging is quite verbose on Homekit. Is there a way to configure it to only show errors? I don't really need to see all the movement logs - only when something goes wrong.

Cheers
<img width="934" alt="Screenshot 2022-01-27 at 14 05 48" src="https://user-images.githubusercontent.com/32539594/151374510-8b7f2f30-d0e4-46dc-a1cb-aa6c2269c0a3.png">
.

**Comment by seydx** [comment]
Added in `v5.0.21-beta.7`

<img width="1152" alt="cui_logLevel" src="https://user-images.githubusercontent.com/34152761/164578707-370d57fd-515f-4019-91e3-cf693da64e3e.png">

**Comment by seydx** [comment]
v5.0.21 online
