### ISSUE TITLE
Doorbell Notification

### ISSUE THREAD

**Issue by istationonline** [seydx/homebridge-camera-ui#417]
Previously used HomeBridge unify protect plug-in. When doorbell pushed, HomePods would chime. This does not function with camera.ui. 

Is this feature available, if so what config is required?

**Comment by alpol017** [comment]
Also need this !

**Comment by MichlW** [comment]
You need to activate the doorbell sensor in camera-ui. From there you can trigger the doorbell in several ways, i.e. with MQTT or (like me) from the doorbell trigger switch.

With that setup I can configure my HomePods to ring the bell when the doorbell is used.
