### ISSUE TITLE
HSV recording time and detection

### ISSUE THREAD

**Issue by AragornSRB** [seydx/homebridge-camera-ui#418]
Hi,first off all thanks for great plugin :).this is more a question regarding HSV.My two Dahua camera are working great with this plugin and only thing I noticed is that HSV record about 80% of movement (sometimes dont record me coming home) and sometimes record to short(record about 10s of 20s movment or similar timings).Is this problem with HSV or my set up?Dahua DVR record everything properly and detect every movement.

**Comment by jackwburger** [comment]
Same here the end and most important of the motion is not recorded. My camera, ezviz cn3 records it fine. 
- Also what is the minimal config for HSV?, it seems you need to setup Videoanalisis also. This can be a nice manual or how to topic.

**Comment by seydx** [comment]
What does camera.ui use for motion detection? Video analytics? SMTP? MQTT? HTTP?

If you use "Videoanalysis" you can adjust the sensitivity via the interface

see also

https://github.com/seydx/homebridge-camera-ui/wiki/Videoanalysis#dwell-time

https://github.com/seydx/homebridge-camera-ui/wiki/Videoanalysis#reset-motion-after
