### ISSUE TITLE
Streaming video is lagging more and more behind the actual one every hour

### ISSUE THREAD

**Issue by sergoo-lbt** [seydx/homebridge-camera-ui#423]
I determined that the included pre-buffering was to blame for everything. Is there any solution for this problem? Homebridge version 1.4.0, node.js- 16.13.2, Camera UI- 5.0.16.

**Comment by seydx** [comment]
can you post your config.json pls

**Comment by sergoo-lbt** [comment]
> can you post your config.json pls

{
            "name": "CameraUI",
            "port": 8081,
            "atHomeSwitch": false,
            "debug": false,
            "mqtt": {
                "active": false,
                "tls": false,
                "port": 1883
            },
            "http": {
                "active": false,
                "port": 7272,
                "localhttp": false
            },
            "smtp": {
                "active": false,
                "port": 2727,
                "space_replace": "+"
            },
            "ftp": {
                "active": false,
                "useFile": false,
                "port": 5050
            },
            "ssl": {
                "active": false
            },
            "options": {
                "videoProcessor": "/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"
            },
            "cameras": [
                {
                    "name": "VideoCamera",
                    "manufacturer": "FuckingChina",
                    "model": "FishEye",
                    "serialNumber": "222-11-222",
                    "motion": true,
                    "motionTimeout": 15,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "forcePrebuffering": false,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://admin:@ip/unicast",
                        "subSource": "-rtsp_transport tcp -i rtsp://admin:@ip/unicast",
                        "stillImageSource": "-i rtsp://admin:@ip/unicast",
                        "rtspTransport": "tcp",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "forceMax": true,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "stimeout": 10,
                        "audio": false
                    },
                    "smtp": {
                        "email": "VideoCamera"
                    },
                    "videoanalysis": {
                        "active": true
                    },
                    "mqtt": {}
                },
                {
                    "name": "HiWatch",
                    "manufacturer": "Hikvision",
                    "model": "HiWatch",
                    "serialNumber": "222-11-222",
                    "motion": true,
                    "motionTimeout": 15,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": false,
                    "forcePrebuffering": false,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://admin:pass@ip/unicast",
                        "subSource": "-i rtsp://admin:pass@ip/unicast",
                        "stillImageSource": "-i rtsp://admin:…….@ip/unicast",
                        "rtspTransport": "tcp",
                        "maxStreams": 2,
                        "forceMax": true,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "audio": true
                    },
                    "smtp": {
                        "email": "HiWatch"
                    },
                    "videoanalysis": {
                        "active": true
                    },
                    "mqtt": {}
                }
            ],
            "platform": "CameraUI"

**Comment by sergoo-lbt** [comment]
It is worth noting that the problem is only with the hiwatch camera and now I do not use pre-buffering on the hiwatch camera, because of the long delay.

**Comment by sergoo-lbt** [comment]
@seydx, i took a picture of how it looks on the video. You need to focus on turning the lights on and off. The delay is very significant.

**Comment by seydx** [comment]
@sergoo-lbt 

can you try v5.0.17-beta.4 and following config.json pls

```json
{
  "name": "CameraUI",
  "port": 8081,
  "atHomeSwitch": false,
  "debug": false,
  "mqtt": {
    "active": false,
    "tls": false,
    "port": 1883
  },
  "http": {
    "active": false,
    "port": 7272,
    "localhttp": false
  },
  "smtp": {
    "active": false,
    "port": 2727,
    "space_replace": "+"
  },
  "ftp": {
    "active": false,
    "useFile": false,
    "port": 5050
  },
  "ssl": {
    "active": false
  },
  "options": {
    "videoProcessor": "/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"
  },
  "cameras": [
    {
      "name": "VideoCamera",
      "manufacturer": "FuckingChina",
      "model": "FishEye",
      "serialNumber": "222-11-222",
      "motion": true,
      "motionTimeout": 15,
      "unbridge": true,
      "hsv": true,
      "prebuffering": true,
      "forcePrebuffering": false,
      "prebufferLength": 4,
      "videoConfig": {
        "source": "-i rtsp://admin:@ip/unicast",
        "subSource": "-rtsp_transport tcp -i rtsp://admin:@ip/unicast",
        "stillImageSource": "-i rtsp://admin:@ip/unicast",
        "rtspTransport": "tcp",
        "maxStreams": 2,
        "maxWidth": 1280,
        "maxHeight": 720,
        "forceMax": true,
        "vcodec": "copy",
        "acodec": "libfdk_aac",
        "stimeout": 10,
        "audio": false
      },
      "smtp": {
        "email": "VideoCamera"
      },
      "videoanalysis": {
        "active": true
      },
      "mqtt": {}
    },
    {
      "name": "HiWatch",
      "manufacturer": "Hikvision",
      "model": "HiWatch",
      "serialNumber": "222-11-222",
      "motion": true,
      "motionTimeout": 15,
      "unbridge": true,
      "hsv": true,
      "prebuffering": true,
      "forcePrebuffering": false,
      "prebufferLength": 4,
      "videoConfig": {
        "source": "-i rtsp://admin:pass@ip/unicast",
        "subSource": "-i rtsp://admin:pass@ip/unicast",
        "stillImageSource": "-i rtsp://admin:…….@ip/unicast",
        "rtspTransport": "tcp",
        "vcodec": "copy",
        "acodec": "libfdk_aac",
        "audio": false
      },
      "smtp": {
        "email": "HiWatch"
      },
      "videoanalysis": {
        "active": true
      },
      "mqtt": {}
    }
  ],
  "platform": "CameraUI"
}
```

**Comment by sergoo-lbt** [comment]
> @sergoo-lbt
> 
> can you try v5.0.17-beta.4 and following config.json pls
> 
> ```json
> {
>   "name": "CameraUI",
>   "port": 8081,
>   "atHomeSwitch": false,
>   "debug": false,
>   "mqtt": {
>     "active": false,
>     "tls": false,
>     "port": 1883
>   },
>   "http": {
>     "active": false,
>     "port": 7272,
>     "localhttp": false
>   },
>   "smtp": {
>     "active": false,
>     "port": 2727,
>     "space_replace": "+"
>   },
>   "ftp": {
>     "active": false,
>     "useFile": false,
>     "port": 5050
>   },
>   "ssl": {
>     "active": false
>   },
>   "options": {
>     "videoProcessor": "/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"
>   },
>   "cameras": [
>     {
>       "name": "VideoCamera",
>       "manufacturer": "FuckingChina",
>       "model": "FishEye",
>       "serialNumber": "222-11-222",
>       "motion": true,
>       "motionTimeout": 15,
>       "unbridge": true,
>       "hsv": true,
>       "prebuffering": true,
>       "forcePrebuffering": false,
>       "prebufferLength": 4,
>       "videoConfig": {
>         "source": "-i rtsp://admin:@ip/unicast",
>         "subSource": "-rtsp_transport tcp -i rtsp://admin:@ip/unicast",
>         "stillImageSource": "-i rtsp://admin:@ip/unicast",
>         "rtspTransport": "tcp",
>         "maxStreams": 2,
>         "maxWidth": 1280,
>         "maxHeight": 720,
>         "forceMax": true,
>         "vcodec": "copy",
>         "acodec": "libfdk_aac",
>         "stimeout": 10,
>         "audio": false
>       },
>       "smtp": {
>         "email": "VideoCamera"
>       },
>       "videoanalysis": {
>         "active": true
>       },
>       "mqtt": {}
>     },
>     {
>       "name": "HiWatch",
>       "manufacturer": "Hikvision",
>       "model": "HiWatch",
>       "serialNumber": "222-11-222",
>       "motion": true,
>       "motionTimeout": 15,
>       "unbridge": true,
>       "hsv": true,
>       "prebuffering": true,
>       "forcePrebuffering": false,
>       "prebufferLength": 4,
>       "videoConfig": {
>         "source": "-i rtsp://admin:pass@ip/unicast",
>         "subSource": "-i rtsp://admin:pass@ip/unicast",
>         "stillImageSource": "-i rtsp://admin:…….@ip/unicast",
>         "rtspTransport": "tcp",
>         "vcodec": "copy",
>         "acodec": "libfdk_aac",
>         "audio": false
>       },
>       "smtp": {
>         "email": "HiWatch"
>       },
>       "videoanalysis": {
>         "active": true
>       },
>       "mqtt": {}
>     }
>   ],
>   "platform": "CameraUI"
> }
> ```

Yes. Of course.  It will be done!🤝🏻

**Comment by sergoo-lbt** [comment]
@seydx , I have updated the plugin. Immediately after restarting homebridge, everything works fine. The more time passes after the launch of homebridge, the more the ether lag appears from the actual one. 10 hours after the reboot, the lag is about 30-40 seconds.

**Comment by sergoo-lbt** [comment]
Updated on 5.0.18. I will continue to monitor

**Comment by seydx** [comment]
any news on this?

**Comment by sergoo-lbt** [comment]
> any news on this?

Updated to 5.0.21 b6. The delay is about 7 seconds. It's probably my camera's problem. Sorry…

**Comment by seydx** [comment]
> > any news on this?
> 
> Updated to 5.0.21 b6. The delay is about 7 seconds. It's probably my camera's problem. Sorry…

Allright then 👍
