### ISSUE TITLE
Access error message after updating Homebridge on Synology to non-Docker version

### ISSUE THREAD

**Issue by bjornand1** [seydx/homebridge-camera-ui#424]
Hi, I have had this plugin working well with Homebridge installed in Docker on Synology. After transferring the instance to a non-Docker version on Synology DSM 7, I get an error message:

[1/31/2022, 10:57:19 AM] Error: EACCES: permission denied, mkdir '/homebridge'

I have narrowed down the error to the Camera UI plugin, as there are no issues when disabling it. I have tried changing the path to the new homebridge folder, but still get the error. Any ideas how to solve this?

**Comment by seydx** [comment]
See also https://github.com/seydx/homebridge-camera-ui/issues/424
