### ISSUE TITLE
Publish MQTT message on motion

### ISSUE THREAD

**Issue by megapearl** [seydx/homebridge-camera-ui#425]
**Describe the bug**
I don't know if this is a bug or not implemented, how to setup camera.ui to publish a MQTT message when camera.ui detect motion?

**To Reproduce**
Setup MQTT on camera.ui, setup Camera Alarm MQTT topic and messages.

**Expected behavior**
Updated MQTT topic when detected motion by Camera.UI

**Logs**

**Screenshots**

**Environment**
OS: Debian 10 with docker Alpine Linux (3.12.9)
Homebridge: v4.42.0
Node JS: v16.13.2
Npm: v8.1.2

**Comment by mynameisdaniel32** [comment]
I'm also seeing this, I don't think the messages are publishing in this current version. The test buttons don't seem to work, nor is it sending on motion events.

Test buttons definitely worked in previous versions.

My MQTT doorbell notifications work fine still, so I'm sure MQTT is connected okay.

**Comment by megapearl** [comment]
I don’t know if this is the other way around? So when publishing a MQTT message from for example your camera that camera.ui triggers an action (record for example).
It’s somehow unclear for me, that’s why I created this ‘bug’ or feature request.

**Comment by mynameisdaniel32** [comment]
Reading into it a bit more I think you're right, it's for external motion triggers, at least that's how the docs are written.

Although I'm sure I tested the test buttons were posting at some point as I have that configured somewhere else...

I too would really like the ability to go the other way so I can use camera.ui's motion detection to trigger other things via MQTT.

**Comment by eRJe79** [comment]
You an publish a webhook when motion was detected.

To do this, you first need to provide the webhook URL that is listening, for each camera (settings - cameras - <camera> - notification - Webhook URL

Then under settings - notifications enable Webhook (at the bottom).

Now the camera detects motion you get something like this:

```
{
  "id": "7da1a10038",
  "camera": "Front Camera",
  "fileName": "Front_Camera-7da1a10038-1643728440_c_CUI.mp4",
  "name": "Front_Camera-7da1a10038-1643728440_c_CUI",
  "extension": "mp4",
  "recordStoring": true,
  "recordType": "Video",
  "trigger": "custom",
  "room": "Standard",
  "time": "2022-02-01 16:14:00",
  "timestamp": 1643728440,
  "label": "Custom"
}
```

**Comment by megapearl** [comment]
I tried that, but it isn't working for me, seems like Camera.UI does a GET request, we need a POST request.

**Comment by megapearl** [comment]
Tried that already, but I'm facing other difficulties, (self signed certificates not working) created a seperate topic for it.

**Comment by seydx** [comment]
Added in `v5.0.21-beta.7`

<img width="1445" alt="cui_mqtt" src="https://user-images.githubusercontent.com/34152761/164578521-0f6cf0f2-f449-4d0c-99e6-817233750065.png">

**Comment by seydx** [comment]
v5.0.21 online
