### ISSUE TITLE
Video stream in Home App doesn’t playback most of the time

### ISSUE THREAD

**Issue by devinbaeten** [seydx/homebridge-camera-ui#428]
When attempting to view the camera stream from within the Home App the stream never loads, in the logs it shows the stream has started and when I exit the viewer in the app it logs the stream as stopped. 

Occasionally the stream will work perfectly, but most of the time this issue is present.

I have two cameras setup with HSV enabled and they both face the same issue. Sometimes just one camera's stream works, sometimes both, sometimes none.

Audio is enabled for both.

**Comment by chip131001** [comment]
I observe the same behavior with me.

**Comment by Cocco17** [comment]
Same thing here.. using a Unifi G3 Flex and Eufy Pan&Tilt 2K.
Maybe the setting must be reviewed? 

'''JSON

                    "name": "Name",
                    "manufacturer": "UniFi",
                    "model": "G3 Flex",
                    "motion": false,
                    "motionTimeout": 5,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://User:Pw@IP:554/s1",
                        "subSource": "-i rtsp://User:Pw@IP:554/s1",
                        "stillImageSource": "-i http://IP/snap.jpeg",
                        "readRate": true,
                        "rtspTransport": "tcp",
                        "maxStreams": 5,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 0,
                        "vcodec": "copy",
                        "acodec": "copy",
                        "audio": true,
                        "debug": true
'''

**Comment by seydx** [comment]
@devinbaeten @chip131001 

try without audio and check if it works, also check the config.json below



> Same thing here.. using a Unifi G3 Flex and Eufy Pan&Tilt 2K. Maybe the setting must be reviewed? Example for G3:
> 
> ```
>                 "name": "Name",
>                 "manufacturer": "UniFi",
>                 "model": "G3 Flex",
>                 "motion": false,
>                 "motionTimeout": 5,
>                 "unbridge": true,
>                 "hsv": true,
>                 "prebuffering": true,
>                 "prebufferLength": 4,
>                 "videoConfig": {
>                     "source": "-i rtsp://User:Pw@IP:554/s1",
>                     "subSource": "-i rtsp://User:Pw@IP:554/s1",
>                     "stillImageSource": "-i http://IP/snap.jpeg",
>                     "readRate": true,
>                     "rtspTransport": "tcp",
>                     "maxStreams": 5,
>                     "maxWidth": 1920,
>                     "maxHeight": 1080,
>                     "maxFPS": 0,
>                     "vcodec": "copy",
>                     "acodec": "copy",
>                     "audio": true,
>                     "debug": true
> ```

```json
"videoConfig": {
  "source": "-i rtsp://User:Pw@IP:554/s1",
  "subSource": "-i rtsp://User:Pw@IP:554/s1",
  "stillImageSource": "-i http://IP/snap.jpeg",
  "readRate": false,
  "rtspTransport": "tcp",
  "maxStreams": 5,
  "vcodec": "copy",
  "acodec": "libfdk_aac",
  "audio": true,
  "debug": true
}
