### ISSUE TITLE
No audio in HSV or camera.ui dashboard. 

### ISSUE THREAD

**Issue by MarkyMarkn** [seydx/homebridge-camera-ui#429]
Hi, hope you can help.

I'm not getting any audio from either of my cameras (both Reolink) within HSV or the camera.ui dashboard.  
I've tried setting libfdk_aac and aac in the audio codec option but no change.  Video playback is fine, as is iCloud recording.
(and the volume is turned up!)

Note: If I use the _Homebridge Camera FFmpeg_ plug-in audio works fine.  

Any ideas?  Otherwise this plug-in is, frankly, awesome :-)

Thanks.  I'm a newbie to GitHub so please point me in the right direction if the answer lies elsewhere!

Snippet of my config, if needed:
{
            "name": "CameraUI",
            "port": 8081,
            "atHomeSwitch": false,
            "debug": false,
            "mqtt": {
                "active": false,
                "tls": false,
                "port": 1883
            },
            "http": {
                "active": false,
                "port": 7272,
                "localhttp": false
            },
            "smtp": {
                "active": false,
                "port": 2727,
                "space_replace": "+"
            },
            "ftp": {
                "active": false,
                "useFile": false,
                "port": 5050
            },
            "ssl": {
                "active": false
            },
            "options": {
                "videoProcessor": "/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"
            },
            "cameras": [
                {
                    "name": "Front",
                    "manufacturer": "Reolink",
                    "model": "RLC-512W",
                    "motion": true,
                    "motionTimeout": 15,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtmp://10.xxx/bcs/channel0_main.bcs?channel=0&stream=0&user=xxx&password=xxxx",
                        "subSource": "-i rtmp://10.xxx/bcs/channel0_sub.bcs?channel=0&stream=0&user=xxxx&password=xxxxx",
                        "stillImageSource": "-i rtmp://10.xxx/bcs/channel0_main.bcs?channel=0&stream=0&user=xxxx&password=xxxx",
                        "maxStreams": 2,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "audio": true,
                        "debug": true
                    },
                    "smtp": {
                        "email": "Front"
                    },
                    "videoanalysis": {
                        "active": true
                    },
                    "mqtt": {},
                    "recordOnMovement": false
                },
                {
                    "name": "Garage",
                    "manufacturer": "Reolink",
                    "model": "RLC-520",
                    "motion": true,
                    "motionTimeout": 15,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtmp://10.xxx/bcs/channel0_main.bcs?channel=0&stream=0&user=xxx&password=xxx",
                        "subSource": "-i rtmp://10.xxx/bcs/channel0_sub.bcs?channel=0&stream=0&user=xxx&password=xxx",
                        "stillImageSource": "-i rtmp://10.xxx/bcs/channel0_main.bcs?channel=0&stream=0&user=xxx&password=xxx",
                        "maxStreams": 2,
                        "forceMax": false,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "audio": true,
                        "debug": true
                    },
                    "smtp": {
                        "email": "Garage"
                    },
                    "videoanalysis": {
                        "active": true
                    },
                    "mqtt": {},
                    "recordOnMovement": false
                }
            ],
            "platform": "CameraUI"

**Comment by MarkyMarkn** [comment]
Can anyone help?

**Comment by ucfhall** [comment]
Having this issue as well. Koush must be busy.

**Comment by ucfhall** [comment]
> Can anyone help?

Mark, try using RTSP, and hard-code 1920x1080 as the maximum height and width and force maximums. This seems to be an issue with RTMP.

**Comment by ucfhall** [comment]
Mark,
Try this...in the camera stream settings, reduce the resolution of the Clear stream to 2304x1296, or whatever is the lowest setting.
Use this for the config:
"forcePrebuffering": false,
"prebufferLength": 4,
"videoConfig": {
"source": "-rtsp_transport tcp -re -i rtsp://user:password@10.xxx:554/h265Preview_01_main",
"subSource": "-rtsp_transport tcp -re -i rtsp://user:password@10.xxx:554/h264Preview_01_sub",
"stillImageSource": "-i http://10.xxx/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=abc&user=user&password=password",
"maxStreams": 2,
"maxWidth": 1280,
"maxHeight": 720,
"maxFPS": 20,
"forceMax": true,
"vcodec": "copy",
"acodec": "libfdk_aac",
"audio": true,
"debug": true
                    },

**Comment by ucfhall** [comment]
So this broke HKSV recording for me...

**Comment by Shanghai-maglev** [comment]
Same issue here. No audio when using the camera.ui https web interface. I have audio in my recordings but not in the web app.

**Comment by Hunter-MDK** [comment]
> Same issue here. No audio when using the camera.ui https web interface. I have audio in my recordings but not in the web app.

Same issue here, recordings have audio but streams do not. Direct camera feeds to ffplay have audio as well. I believe my recordings may have been silent prior to using libfdk_aac.
