### ISSUE TITLE
Privacy-mode is not working

### ISSUE THREAD

**Issue by jacksonjao** [seydx/homebridge-camera-ui#430]
Hi, thank you for your effort. it is awesome! I wanted to comment something is happening. I am from Colombia and I'm sorry for my english.

**Describe the bug**
Privacy mode is not working with Tapo C200

**To Reproduce**
When I press privacy mode it doesn't do anything.

**Expected behavior**
The camera shouldn't continue showing video.

**Comment by seydx** [comment]
@jacksonjao @mgiacomo72 

the "privacy mode" only works when "at home" is switched on
