### ISSUE TITLE
DSM 7 compatibility

### ISSUE THREAD

**Issue by teksup** [seydx/homebridge-camera-ui#431]
**Describe the bug**
Can't get working with DSM 7 (fresh install of homebridge). It worked in DSM6.x

**To Reproduce**
Tried all manner of configurations

**Expected behavior**
We expect with the typical settings required by the latest version it would work.

**Logs**
Error received is:

CAMERA1: RTSP stream exited with error! (null) - Unrecognized option 'rtsp_transport'. Error splitting the argument list: - Option not found

**Screenshots**
"cameras": [
                {
                    "name": "CAMERA1",
                    "manufacturer": "Make",
                    "model": "Model",
                    "serialNumber": "000001",
                    "motion": false,
                    "motionTimeout": 15,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": false,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://xxxxxx:xxxxxx@192.168.168.31:8451/videoMain",
                        "subSource": "-i rtsp://xxxxxx:xxxxxx@192.168.168.31:8451/videoSub",
                        "stillImageSource": "-i rtsp://xxxxxx:xxxxxx@192.168.168.31:8451/videoMain",
                        "rtspTransport": "tcp",
                        "maxStreams": 2,
                        "maxBitrate": 300,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "audio": false,
                        "debug": true
                    },
                    "smtp": {
                        "email": "CAMERA1"
                    },
                    "videoanalysis": {
                        "active": false
                    },
                    "mqtt": {}
                }
            ],
            "platform": "CameraUI",
            "options": {
                "videoProcessor": "ffmpeg"
            }

**Environment**
- Node.js Version: v12
- Homebridge Version: v1.4.0
- Camera UI Version: v5.0.16
- Operating System: DSM 7
- Browser: Safari, Firefox, chrome

**Comment by seydx** [comment]
its because of your installed ffmpeg version, try to re-install ffmpeg

**Comment by teksup** [comment]
Which is the correct version of FFmpeg that works with Camera Ui?

Thank you for your help.

Kim

**Comment by seydx** [comment]
> Which is the correct version of FFmpeg that works with Camera Ui? Thank you for your help. Kim
> […](#)

v4.3.1, v4.4, v5

**Comment by teksup** [comment]
Is the FFMpeg the one installed in Homebridge, or the FFMpeg package in the Synology NAS?
