### ISSUE TITLE
Homekit Secure Video (HSV) setting not remembered

### ISSUE THREAD

**Issue by megapearl** [seydx/homebridge-camera-ui#433]
**Describe the bug**
When switching on 'Homekit Secure Video' and save using save button lower right, and restarting camera.ui (using homebridge OR settings -> system -> restart in camera.ui interface) the setting is not remembered and is OFF again.

**To Reproduce**
Swith on 'Homekit Secure Video' save the setting and restart camera.ui.

**Expected behavior**
The setting should be still on after restarting camera.ui

**Logs**

**Screenshots**
<img width="608" alt="image" src="https://user-images.githubusercontent.com/3420660/152175780-a18cc5a1-d5af-4816-a4a5-c120c3edbc93.png">

**Environment**
- Node.js Version: v16.13.2
- Homebridge Version: v1.4.0 (HAP v0.10.0)
- Camera UI Version: v5.0.16-latest
- Operating System: Debian 10 with Docker Alpine Linux (3.12.9)
- Browser Version: Edge 97.0.1072.76 (Official build) (64-bit) on Windows 11

**Comment by megapearl** [comment]
*bump*

**Comment by seydx** [comment]
fixed in v5.0.17-beta.3
