### ISSUE TITLE
MQTT triggered recordings not starting/working

### ISSUE THREAD

**Issue by r-sherwood** [seydx/homebridge-camera-ui#438]
**Describe the bug**
No recordings are created/started after a MQTT trigger, or manual "Trigger Motion" through the UI.

**To Reproduce**
Trigger Motion through MQTT or UI

**Expected behavior**
A ffmpeg process should be started to record the video stream.
Recordings should be in the recordings directory.
Recordings should be under recordings.

**Logs**
[03/02/2022, 15:39:09] [CameraUI] MQTT: {"camera":"ESP32-Cam-Passage","topic":"mqttGenericBridge/AlarmEscalation/state","data":"on","json":false,"message":"on","state":true,"try":0}
[03/02/2022, 15:39:09] [CameraUI] ESP32-Cam-Passage: {"error":false,"message":"Handling through extern controller.."}
[03/02/2022, 15:39:09] [CameraUI] ESP32-Cam-Passage: Motion ON
[03/02/2022, 15:40:03] [CameraUI] MQTT: New message: Topic: mqttGenericBridge/AlarmEscalation/state - Data: off - Type: string
[03/02/2022, 15:40:03] [CameraUI] MQTT: {"camera":"ESP32-Cam-Passage","topic":"mqttGenericBridge/AlarmEscalation/state","data":"off","json":false,"message":"on","try":0}
[03/02/2022, 15:40:03] [CameraUI] MQTT: {"camera":"ESP32-Cam-Passage","topic":"mqttGenericBridge/AlarmEscalation/state","data":"off","json":false,"message":"off","state":true,"try":1}
[03/02/2022, 15:40:03] [CameraUI] ESP32-Cam-Passage: {"error":false,"message":"Handling through extern controller.."}
[03/02/2022, 15:40:03] [CameraUI] ESP32-Cam-Passage: Motion OFF

**Screenshots**
Recordings are enabled
![Screenshot 2022-02-03 at 15 43 44](https://user-images.githubusercontent.com/1226390/152365429-e146fc14-3fea-49a2-85a4-85bc3fd7a7f8.png)

**Environment**
- Node.js Version: v14.19.0
- Homebridge Version: v1.4
- Camera UI Version: v5.0.16
- Operating System: raspbian buster
- Browser: FF 95.0.2

**Config**
```
{
                    "name": "ESP32-Cam-Passage",
                    "manufacturer": "espressif",
                    "model": "ESP32-Cam",
                    "motion": true,
                    "doorbell": false,
                    "switches": false,
                    "motionTimeout": 60,
                    "unbridge": true,
                    "hsv": true,
                    "videoConfig": {
                        "source": "-f mjpeg -i http://[IP]/mjpeg/1",
                        "stillImageSource": "-f mjpeg -i http://[IP]/mjpeg/1",
                        "maxStreams": 5,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 10,
                        "maxBitrate": 4000,
                        "forceMax": true,
                        "vcodec": "h264_v4l2m2m",
                        "stimeout": "",
                        "debug": true,
                        "subSource": "-i http://[IP]/jpg"
                    },
                    "mqtt": {
                        "motionTopic": "mqttGenericBridge/AlarmEscalation/state",
                        "motionMessage": "on",
                        "motionResetTopic": "mqttGenericBridge/AlarmEscalation/state",
                        "motionResetMessage": "off"
                    },
                    "videoProcessor": "/usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg",
                    "videoanalysis": {
                        "active": false
                    },
                    "smtp": {
                        "email": "ESP32-Cam-Passage"
                    },
                    "prebufferLength": 4,
                    "prebuffering": false,
                    "recordOnMovement": false
                }
```

**Comment by jiehanzheng** [comment]
Have a similar issue with SMTP-triggered motion, as well as manual "Trigger Motion" through the UI.

@r-sherwood Were you able to find a workaround?

**Comment by r-sherwood** [comment]
Sorry, don't have a workaround.
But it worked in past versions. You can try to revert back a few versions.

**Comment by seydx** [comment]
@r-sherwood @jiehanzheng 

If HSV is activated, the recording is not saved until HSV has processed it. In your case it looks as if HSV does not record a video at all.

You could delete the cameras from Apple Home and your config.json, rename the cameras in config.json and add them again in Apple Home (and configure HSV again).

Also keep in mind that the HSV setting is set to "Stream & Record".

**Comment by r-sherwood** [comment]
Is HSV the only option to record? Do I need a hub (Homepod/AppleTV) to store HSV recordings?
Have also tried with HSV disabled - without success.

**Comment by seydx** [comment]
No you dont need HSV to record, just enable "Recording" within interface and you are good to go

**Comment by r-sherwood** [comment]
That's the point.
It has worked in previous betas before v5.0.16 and stopped recording with the final release.
HSV turned on automatically after some homebridge restarts, some how. 
Even with HSV disabled a recording is not possible.

The only log entry is:

`[02/05/2022, 10:36:45] [CameraUI] ESP32-Cam-Stairwell: Motion ON`


My current config:

 {
   "debug": false,
   "port": 8181,
   "atHomeSwitch": false,
   "options": {
     "videoProcessor": "/usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"
   },
   "ssl": {
     "active": false,
     "key": "",
     "cert": ""
   },
   "http": {
     "active": false,
     "port": 8282,
     "localhttp": false
   },
   "smtp": {
     "active": false,
     "port": 2727,
     "space_replace": "+"
   },
   "ftp": {
     "active": false,
     "useFile": false,
     "port": 5050
   },
   "mqtt": {
     "active": true,
     "tls": false,
     "host": "127.0.0.1",
     "port": 1883,
     "username": "xxx",
     "password": "xxx"
   },
   "cameras": [
     {
       "name": "ESP32-Cam-Stairwell",
       "manufacturer": "espressif",
       "model": "ESP32-Cam",
       "motion": true,
       "doorbell": true,
       "switches": false,
       "motionTimeout": 60,
       "motionDoorbell": false,
       "unbridge": true,
       "hsv": false,
       "videoConfig": {
         "source": "-f mjpeg -i http://IP/mjpeg/1",
         "stillImageSource": "-i http://IP/jpg",
         "maxStreams": 5,
         "maxWidth": 1280,
         "maxHeight": 720,
         "maxFPS": 20,
         "maxBitrate": 4000,
         "forceMax": true,
         "vcodec": "h264_v4l2m2m",
         "debug": false,
         "subSource": "-f mjpeg -i http://IP/mjpeg/1"
       },
       "mqtt": {
         "motionTopic": "mqttGenericBridge/AlarmEscalation/state",
         "motionMessage": "on",
         "doorbellTopic": "mqttGenericBridge/EingangstuerA_S3/state",
         "doorbellMessage": "closed",
         "motionResetTopic": "off"
       },
       "prebuffering": false,
       "videoProcessor": "/usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg",
       "videoanalysis": {
         "active": false
       },
       "smtp": {
         "email": "ESP32-Cam-Stairwell"
       },
       "prebufferLength": 4
     },
   ]
 }

**Comment by r-sherwood** [comment]
Looks like it's been working again with v5.0.27
