### ISSUE TITLE
How to get audio from RTSP stream to work with this plugin

### ISSUE THREAD

**Issue by yonigold1** [seydx/homebridge-camera-ui#442]
I'm having trouble getting my audio stream working with this plugin.
This is the stream given to me by my cameras UI: `-i rtsp://192.168.2.19/ch0_0.aac`

and i put that right into the audio stream configuration.

![image](https://user-images.githubusercontent.com/34217684/152660825-5f10831c-ee23-4192-ac49-5747ab6d4adc.jpeg)

![image](https://user-images.githubusercontent.com/34217684/152660838-71b6665b-80b1-4fa3-bdc0-0092bc79d079.jpeg)

**Comment by edm00se** [comment]
@yonigold1 what was the fix?
