### ISSUE TITLE
Aufnehmen bei Bewegung durch UI permanent wieder deaktiviert.

### ISSUE THREAD

**Issue by Mehmet89** [seydx/homebridge-camera-ui#446]
Ich aktiviere bei jeder Kamera die Einstellung. Beim nächsten Login ist die Einstellung wieder deaktiviert. Auch mit einem Neustart kann ich den Fehler reproduzieren.

**Comment by seydx** [comment]
Duplicate

https://github.com/seydx/homebridge-camera-ui/issues/432
