### ISSUE TITLE
Doorbell triggers with motion switch has no effect

### ISSUE THREAD

**Issue by kerwinf** [seydx/homebridge-camera-ui#448]
Doorbell chimes with motion even when unchecked, Trigger doorbell with motion, in settings. Possibly a bug in HomeKit as well. I always get a notification that someone rang the bell but it rarely chimes my HomePod mini. 

I would like a switch to be exposed for the doorbell so that it is active or not. There are times when I want to capture motion but not ring the bell as well as trigger the bell without triggering motion by using the dummy switches.

**Comment by seydx** [comment]
There is an option in apple home to stop triggering doorbell on motion event and you also need to disable trigger doorbell with motion if you dont want triggering doorbell

>I would like a switch to be exposed for the doorbell so that it is active or not. There are times when I want to capture motion but not ring the bell as well as trigger the bell without triggering motion by using the dummy switches.

will add this to my todo list
