### ISSUE TITLE
QUESTION: How do I setup notifications for HomeKit?

### ISSUE THREAD

**Issue by nexusle** [SeydX/homebridge-camera-ui#45]
In version 2.x I'm able to get notifications from HomeKit by monitoring a FTP target. My cams write images on movement to a folder on my FTP server. With version 3 it seems the FTP feature is dropped. 

How are notifications handled now? With MQTT I've no experiences. What do I need? 

Are there other possibilities for notifications from HomeKit?

**Comment by monza258** [comment]
You can use FTP-Motion Plugin by from sonoo.

[Plugin](https://github.com/Sunoo/homebridge-ftp-motion)

If you need help to configure it, you can ask me here. 😉

**Comment by nexusle** [comment]
@monza258 

Thanks for the hint...

I've installed the Plugin and configured it as I mentioned:

HTTP Port in camera-ui is 7777

This Port I setup in FTP Motion Addon

My camera names have spaces in the name. Is it possible, to use them in FTP motion addon, or must I change the names?

**Comment by nexusle** [comment]
@SeydX 

The thing @monza258 mentioned isn't working at this moment for me. Do you have a time line for getting online the MQTT wiki page?

Notification about movement on my home are essential for me. It would be great to get this feature back.

**Comment by SeydX** [comment]
I will finish it in the next few days

**Comment by monza258** [comment]
> @monza258 
> 
> 
> 
> Thanks for the hint...
> 
> 
> 
> I've installed the Plugin and configured it as I mentioned:
> 
> 
> 
> HTTP Port in camera-ui is 7777
> 
> 
> 
> This Port I setup in FTP Motion Addon
> 
> 
> 
> My camera names have spaces in the name. Is it possible, to use them in FTP motion addon, or must I change the names?

Hi, I think it's not working with spaces. Pls change the names. 

See attached my settings in my cam

![image](https://user-images.githubusercontent.com/37027557/96496730-e511e580-1249-11eb-84f8-294512f911c1.jpeg)

Serveradresse: ip from your Server (think your Pi)
Server Port: you have set in ftp-plugin (ftp_port)
Pfad: exactly name of camera you have set in camera-Ui

And it runs.

**Comment by nexusle** [comment]
It's a little bit different. 

The FTP is my OMV NAS. 192.168.1.10

The other things I'll change

**Comment by monza258** [comment]
Ok, normally it must work. Can you test the ftp connection on your camera? Same name as camera you have set in ftp-motion plugin and camera-ui ? 

Http port in ftp-plugin must be the same as you have set in camera-ui.

**Comment by nexusle** [comment]
Maybe I missunderstood some things...

What exactly does this Plugin?? I need a plugin that monitors a folder for each camera in my home. For example I have setup my camera in livingroom to write to /FTP-Kameras/Wohnzimmer. Camera-UI in version 2 have monitored this folder, recognized changes and send a notification. 

With this plugin as mentioned a hoped I get this behavior back. 

I've attaches some screenshots of my config:

![14B5A14D-E922-4F7C-B6A7-E6D81E4262A3](https://user-images.githubusercontent.com/341913/96505119-f7921c00-1255-11eb-985f-45216a083b0f.png)
![855E83F1-1155-4FA7-8D37-3B4FABF6037C](https://user-images.githubusercontent.com/341913/96505121-f82ab280-1255-11eb-8d22-e0b8d410b09f.png)
![F44ED917-5EB5-4B2B-A828-45C37026AE56](https://user-images.githubusercontent.com/341913/96505107-f3fe9500-1255-11eb-8328-fd7e2977acb4.png)
![FFFD9E47-0166-4152-9511-5F90B60AB7CC](https://user-images.githubusercontent.com/341913/96505113-f5c85880-1255-11eb-9cf7-b2ca4d39c8a9.png)
![7B6A2E75-1020-4DBB-B83A-1AA980D13FF0](https://user-images.githubusercontent.com/341913/96505115-f660ef00-1255-11eb-9148-2fc59fbe741d.png)
![31DC1D27-69A1-40FA-A00B-27AEBE6C3B3A](https://user-images.githubusercontent.com/341913/96505116-f6f98580-1255-11eb-8f2c-088cb5a72a69.jpeg)

**Comment by SeydX** [comment]
**homebridge-ftp-motion** should exactly do the same

https://github.com/Sunoo/homebridge-ftp-motion#readme

**FTP port** can be 5000 if it is not already choosen by an another process

**HTTP port** should be the port defined for **camera ui http server**, look below

https://github.com/SeydX/homebridge-camera-ui/blob/master/misc/example-config.json#L29

**Comment by nexusle** [comment]
For what is the plugin FTP port used? In the camera section of the motion plugin I set port 25.

**Comment by SeydX** [comment]
The ftp port is used to create a ftp server

Let me explain

In your native camera settings, you choose the ftp port from homebridge-ftp-motion (eg 5000) and the camera name as path (the camera name must be the same name as defined in your camera ui config)

Now, on movement detection, the camera will send the picture to homebridge-ftp-motion anf the path you defined is an additional information for the plugin to identify the camera (it is not used to store something), and these will doing several things

1. homebridge-ftp-motion will save the picture for you in the given path under config.json (e.g. /FTP/Wohnzimmer/ )

2. The homebridge-ftp-motion will send a request to the http server (port 7777) with the camera name. 

CameraUI will get this request and trigger a movement detection which is used from HomeKit and the Web Interface

**Comment by monza258** [comment]
See attached a example config. 

```
{
    "bridge": {
        "name": "Homebridge4",
        "username": "FF:11:3D:E3:CE:91",
        "manufacturer": "homebridge",
        "model": "homebridge4",
        "port": 51225,
        "pin": "031-45-178"
    },
    "description": "Home Smart Home",
    "platforms": [
       
        {
            "name": "CameraUI",
            "port": 3333,
            "auth": "form",
            "language": "de",
            "debug": false,
            "reset": false,
            "mqtt": {
                "active": false,
                "host": "192.168.0.126",
                "port": 1883,
                "topic": "homebridge/motion",
                "on_message": "ON"
            },
            "http": {
                "active": true,
                "port": 7777,
                "localhttp": false
            },
            "ssl": {
                "active": false,
                "key": "/path/to/key/server.key",
                "cert": "/path/to/cert/server.crt"
            },
            "options": {
                "videoProcessor": "ffmpeg",
                "interfaceName": "eth0",
                "ffmpegExecPath": "/usr/bin/ffmpeg"
            },
            "cameras": [
                {
                    "name": "Wohnzimmer",
                    "manufacturer": "XXX",
                    "model": "XXX",
                    "serialNumber": "12345",
                    "firmwareRevision": "1.0",
                    "motion": true,
                    "doorbell": true,
                    "switches": true,
                    "motionTimeout": 1,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://admin:admin@192.168.0.175:554/11",
                        "stillImageSource": "-rtsp_transport tcp -re -i rtsp://admin:admin@192.168.0.175:554/11",
                        "maxStreams": 2,
                        "maxWidth": 1024,
                        "maxHeight": 768,
                        "maxFPS": 20,
                        "vcodec": "copy",
                        "socketPort": 8100
                    }
                }
            ],
            "platform": "CameraUI"
        },
        {
            "name": "FTP Motion",
            "ftp_port": 5000,
            "http_port": 7777,
            "cameras": [
                {
                    "name": "Wohnzimmer",
                    "cooldown": 30,
                    "tls": false
                }
            ],
            "platform": "ftpMotion"
        }
    ],
    "accessories": []
}

```

**Comment by nexusle** [comment]
Ok, it works now...

I missunderstood the thing with an "external" FTP server. Now, as I know that nothing will be transfered/stores, I've setup the local FTP server. Now it works like expected.

Thanks!
