### ISSUE TITLE
Enable/disable HSV notifications for certain cameras

### ISSUE THREAD

**Issue by iuliusmaximilian** [seydx/homebridge-camera-ui#456]
Feature request to enable/disable HSV notifications for certain cameras by an additional Switch. The scenario is to define more complex conditions by automations to enable/disable that notifications shall sent. The Switch is not means to trigger the notification itself, it's to enable/disable if a HSV recognition has been detected a notifications is sent. Best case would be of this could enable/disable only the HSV notification but HSV recording itself is recorded anyway.

**Comment by ucfhall** [comment]
Wouldn’t this have to be done within HomeKit itself?

**Comment by seydx** [comment]
Yes you can do it within apple home
