### ISSUE TITLE
No notifications after update from 4.2.10 to 5.0.16

### ISSUE THREAD

**Issue by andre1210** [seydx/homebridge-camera-ui#458]
I'm have 2 cameras configured that I trigger via mqtt to send a picture as telegram notification.
With 4.2.10 everything works fine. 
I tried twice to update to version 5. 
After update I get no notifications any more. Not in camera-ui web interface and not via telegram.
After update I reconfigured the telegram settings, activated notifications (in Notification settings and for each camera). 
But on mqtt message
[14.2.2022, 14:31:29] [CameraUI] Einfahrt ZM: Motion ON
is logged, but nothing else.
If I downgrade to 4.2.10 everything is working as usual.
What am I doing wrong?

**Comment by ucfhall** [comment]
I'm having the exact same issue.

**Comment by andre1210** [comment]
Does no one have a hint for me. I have to stay on 4.2.10

**Comment by seydx** [comment]
Do you have enabled notifications? and camera specific notification options like telegram etc?

<img width="1396" alt="1" src="https://user-images.githubusercontent.com/34152761/162626723-c5b3582f-5953-4029-89f6-55ab50db85d1.png">

<img width="1396" alt="2" src="https://user-images.githubusercontent.com/34152761/162626731-2d000b2f-9f9b-41fd-a10d-60183d3cdb0a.png">

**Comment by ucfhall** [comment]
@seydx Yes I do.
<img width="1323" alt="Screen Shot 2022-04-10 at 2 29 06 PM" src="https://user-images.githubusercontent.com/25730816/162634175-94b40eac-f48a-47f5-b3da-00ece83f3764.png">
![Untitled](https://user-images.githubusercontent.com/25730816/162634217-0eb2effd-4b6f-44bf-aae1-fc397410499b.jpg)

**Comment by seydx** [comment]
> @seydx Yes I do.
> <img alt="Screen Shot 2022-04-10 at 2 29 06 PM" width="1323" src="https://user-images.githubusercontent.com/25730816/162634175-94b40eac-f48a-47f5-b3da-00ece83f3764.png">
> ![Untitled](https://user-images.githubusercontent.com/25730816/162634217-0eb2effd-4b6f-44bf-aae1-fc397410499b.jpg)

Checked also Settings > Cameras > CAMERANAME > Notifications > Telegram ?

**Comment by ucfhall** [comment]
Yes and the Telegram-specific settings match that of the other camera. I should note that it’s also native notifications that are having this issue as well. Which man’s the native recordings aren’t working either. 

On Apr 10, 2022, at 23:25, seydx ***@***.***> wrote:

﻿
@seydx Yes I do.



Checked also Settings > Cameras > CAMERANAME > Notifications > Telegram ?

**Comment by seydx** [comment]
@ucfhall 

can you enable debug and trigger a motion pls, i need the full log (with debug enabled)

**Comment by ucfhall** [comment]
Posted in issue 445

On Apr 10, 2022, at 23:37, seydx ***@***.***> wrote:

﻿
@ucfhall

can you enable debug and trigger a motion pls, i need the full log (with debug enabled)

**Comment by ShadyRover** [comment]
Same problem. But message about sending to Telegram not appeared in log

**Comment by seydx** [comment]
@ucfhall @ShadyRover 

can you send me your database.json (should be located in " /var/lib/homebridge/camera.ui/database/database.json)

**Comment by ShadyRover** [comment]
Database in attach. My config:
`{
  "debug": false,
  "port": 8081,
  "atHomeSwitch": false,
  "options": {
    "videoProcessor": "ffmpeg"
  },
  "ssl": {
    "active": false
  },
  "http": {
    "active": false,
    "port": 7272,
    "localhttp": false
  },
  "smtp": {
    "active": true,
    "port": 2727,
    "space_replace": "+"
  },
  "ftp": {
    "active": false,
    "useFile": false,
    "port": 5050
  },
  "mqtt": {
    "active": false,
    "tls": false,
    "port": 1883
  },
  "cameras": [
    {
      "name": "Main Entrance Door",
      "manufacturer": "EZVIZ",
      "model": "C6C",
      "motion": true,
      "unbridge": true,
      "hsv": true,
      "prebuffering": true,
      "prebufferLength": 4,
      "motionTimeout": 5,
      "videoConfig": {
        "source": "-i rtsp://root:pass@xx.xx.xx.xx:1111/ISAPI/Streaming/Channels/101",
        "subSource": "-i rtsp://root:pass@xx.xx.xx.xx:1111/ISAPI/Streaming/Channels/102",
        "stillImageSource": "-i rtsp://root:pass@xx.xx.xx.xx:1111/ISAPI/Streaming/Channels/102",
        "rtspTransport": "tcp",
        "maxStreams": 2,
        "vcodec": "copy",
        "acodec": "libfdk_aac",
        "stimeout": 10,
        "audio": false,
        "readRate": false,
        "debug": true
      },
      "mqtt": {},
      "smtp": {
        "email": "email@xxxx.com",
        "from": "Door",
        "body": ""
      },
      "videoanalysis": {
        "active": true
      },
      "recordOnMovement": false
    },
    {
      "name": "Backside",
      "manufacturer": "Hikvision",
      "model": "C6C",
      "motion": true,
      "unbridge": true,
      "hsv": true,
      "prebuffering": true,
      "prebufferLength": 4,
      "motionTimeout": 5,
      "videoConfig": {
        "source": "-i rtsp://root:pass@xx.xx.xx.xx:1111/ISAPI/Streaming/Channels/101",
        "subSource": "-i rtsp://root:pass@xx.xx.xx.xx:1111/ISAPI/Streaming/Channels/102",
        "stillImageSource": "-i rtsp://root:pass@xx.xx.xx.xx:1111/ISAPI/Streaming/Channels/102",
        "rtspTransport": "tcp",
        "maxStreams": 2,
        "vcodec": "copy",
        "acodec": "libfdk_aac",
        "stimeout": 10,
        "audio": false,
        "readRate": false,
        "debug": true
      },
      "mqtt": {},
      "smtp": {
        "email": "Backside"
      },
      "videoanalysis": {
        "active": true
      },
      "recordOnMovement": false
    },
    {
      "name": "Leftside",
      "manufacturer": "Hikvision",
      "model": "C6C",
      "motion": true,
      "unbridge": true,
      "hsv": true,
      "prebuffering": true,
      "prebufferLength": 4,
      "motionTimeout": 5,
      "videoConfig": {
        "source": "-i rtsp://root:pass@xx.xx.xx.xx:1111/ISAPI/Streaming/Channels/101",
        "subSource": "-i rtsp://root:pass@xx.xx.xx.xx:1111/ISAPI/Streaming/Channels/102",
        "stillImageSource": "-i rtsp://root:pass@xx.xx.xx.xx:1111/ISAPI/Streaming/Channels/102",
        "rtspTransport": "tcp",
        "maxStreams": 2,
        "vcodec": "copy",
        "acodec": "libfdk_aac",
        "stimeout": 10,
        "audio": false,
        "readRate": false,
        "debug": true
      },
      "mqtt": {},
      "smtp": {
        "email": "Leftside"
      },
      "videoanalysis": {
        "active": true
      },
      "recordOnMovement": false
    }
  ]
}`
[database.json.zip](https://github.com/seydx/homebridge-camera-ui/files/8496458/database.json.zip)

Email and telegram notifications not working

**Comment by andre1210** [comment]
Thank you, now it works.
One question: On version 4.x I got one notification on motion topic and another notification on motion reset topic.
e.g. on "open" and again on "closed"
With 5.0.27 I get a notification on "open", but not on the reset topic.

Here a log example:
On Motion topic this is logged:
[27.4.2022, 13:41:14] [CameraUI] MQTT: New message: Topic: homebridge/blau/fahrradschuppen - Data: auf - Type: string
[27.4.2022, 13:41:14] [CameraUI] Carport ZM: Movement delay (2s) is active, wait before triggering the event - Trigger: motion - State: true - Event: mqtt
[27.4.2022, 13:41:16] [CameraUI] Carport ZM: Motion ON
[27.4.2022, 13:41:21] [CameraUI] Carport ZM: Motion OFF - Motion handler timeout.

On Motion reset topic this is logged, but no notification:
[27.4.2022, 13:41:32] [CameraUI] MQTT: New message: Topic: homebridge/blau/fahrradschuppen - Data: zu - Type: string
[27.4.2022, 13:41:32] [CameraUI] Carport ZM: Movement delay (2s) is active, wait before triggering the event - Trigger: motion - State: false - Event: mqtt

What is wrong in my configuration?
