### ISSUE TITLE
Updating Homebridge

### ISSUE THREAD

**Issue by Mikellas** [SeydX/homebridge-camera-ui#46]
Tried installing and i get the below error

The plugin "homebridge-camera-ui" requires a Homebridge version of ^1.2.0 which does not satisfy the current Homebridge version of 1.1.6. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.

As far as i know i have latest stable version for now.Do i need to update so i can use the plugin?

**Comment by SeydX** [comment]
Hey @Mikellas 

It should also work with v1.1.6

The latest version of Homebridge is 1.2.3 (it is not tagged as @latest on npm, idk why)

Nvm, u can install the latest version via

sudo npm i homebridge@1.2.3 -g --unsafe-perm

**Comment by Mikellas** [comment]
Thanks ill give it a try!
