### ISSUE TITLE
Cannot connect to HSV video stream unless on the same network.

### ISSUE THREAD

**Issue by pilcherd** [seydx/homebridge-camera-ui#467]
**Describe the bug**
I have a working setup talking to a camera via RTSP and the camera showing in Apple HomeKit.  This is great.  This is running on an IoT network, with Homebridge, cameras and my iOS device connected on the same network.

Unfortunately when I move my iOS device to another (my primary) VLAN network, I cannot see the full video on any Apple device.  I can see the preview window and that is live, but access to full video is not permitted.  When I click on it to view it, the display times out with no response error.

I have a second non-HomeBridge camera (Eufy) setup on the same IoT network with HomeKit HSV and that works fine, so the network rules to permit access to the video stream etc. must be good and this is why I believe the issue to be related to camera.ui.

**To Reproduce**
I have two networks. Each one a different VLAN.  I have rules setup to permit full access from LAN to IoT VLAN (where the cameras are).  I have a rule to enable Established and related connections back.  mDNS is setup to enable devices to be discovered across network.  This is unifi hardware.

**Expected behavior**
I would expect the camera to display when I click on the preview.

**Logs**
[2/21/2022, 3:19:11 PM] [CameraUI] Backyard: Starting video stream: native
[2/21/2022, 3:19:41 PM] [CameraUI] Backyard: Stopped video stream.

iOS: No Response This camera is not responding.

Homebridge v1.4.0 with homebridge-camera-ui v5.0.16

PS, I think it's amazing any of this works at all, and thank you for the amazing work of this project!

**Comment by seydx** [comment]
As you can see in the log camera.ui starts the stream successfully, but the home app does not show it.

Most likely it is due to the Home App from Apple

**Comment by adrianjagielak** [comment]
@pilcherd  Did you ever fixed it?
