### ISSUE TITLE
Authorization Failed

### ISSUE THREAD

**Issue by natesor** [seydx/homebridge-camera-ui#468]
Hello, 

For some reason i keep getting this error on all my cameras:

[CameraUI] Stairs Right: FFmpeg videoanalysis process exited with error! (null) - [rtsp @ 0x44173c0] method DESCRIBE failed: 401 Unauthorized  - rtsp://10.0.0.19:00554/ch01/0: Server returned 401 Unauthorized (authorization failed)

I have a Swann DVR that I am trying to add in via RTSP.

Any idea what the cause might be?

**Comment by pilcherd** [comment]
401 is normally wrong username/password. Some RTSP cameras have a different user/pass for the RTSP feed to the regular camera tools. Perhaps look for that?

Also, on my camera the URL includes the RTSP username/password. E.g.

rtsp://USERNAME:PASSWORD@10.0.0.19:00554/ch01/0
