### ISSUE TITLE
Device or resource busy

### ISSUE THREAD

**Issue by nicolasdeloigne** [seydx/homebridge-camera-ui#472]
Hi,

Thanks for the great job on this plugin.
I encounter a problem, and really don't know how to proceed.

I use a webcam, on a USB port of my raspberry. 
Then, to create the link with camera.ui, I declare the "i- /dev/video0".
Works fine, except that it can't handle video analysis because the flux cannot be use for both streaming on HomeKit and video analysis. The error message is "Device or resource busy"

Thanks in advance,
Have a nice day

**Comment by tzwada** [comment]
I have same problem. Then I clean installed Raspbian OS, Homebridge, Homebridge UI and this plug in (homebridge-camera-ui). At the time, I could see video from /dev/video0 on the homebridge-camera-ui status screen. Then I register the camera on Apple Home app on my iPhone. Register itself was successful but no video displayed. Then I revisit the plugin status screen but the Homebridge displays "device or resource busy" as use to be.

**Comment by seydx** [comment]
Hey this is not because of camera.ui, it is because of the camera. It does not allow multiple connections

Maybe turn on prebuffering? So there is only one connection to the camera and all other connections go to prebuffering.

**Comment by tzwada** [comment]
> Hey this is not because of camera.ui, it is because of the camera. It does not allow multiple connections

I will try to check if other camera has same issue. I'll double check the prebuffering settings, also. One thing I feel wired is that the problem never occurred by using homebridge-camera-ffmpeg plugin. Only camera.ui plugin occurs this issue.

**Comment by seydx** [comment]
> > Hey this is not because of camera.ui, it is because of the camera. It does not allow multiple connections
> 
> I will try to check if other camera has same issue. I'll double check the prebuffering settings, also. One thing I feel wired is that the problem never occurred by using homebridge-camera-ffmpeg plugin. Only camera.ui plugin occurs this issue.

Be sure that camera.ui establish only one connection to the camera, either enable prebuffering OR disable prebuffering AND videoanalysis

**Comment by tzwada** [comment]
@seydx Sorry for late. I have tried these settings but no success.

1. enable prebuffering
2. disable videoanalysis

Here is the settings of #2:
{
    "bridge": {
        "name": "Homebridge",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": XXX,
        "pin": "XXX-XX-XXX"
    },
    "platforms": [
        {
            "name": "CameraUI",
            "port": XXX,
            "atHomeSwitch": false,
            "logLevel": "info",
            "mqtt": {
                "active": false,
                "tls": false,
                "port": XXX
            },
            "http": {
                "active": false,
                "port": XXX,
                "localhttp": false
            },
            "smtp": {
                "active": false,
                "port": XXX,
                "space_replace": "+"
            },
            "ftp": {
                "active": false,
                "useFile": false,
                "port": XXX
            },
            "ssl": {
                "active": false
            },
            "options": {
                "videoProcessor": "/usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"
            },
            "cameras": [
                {
                    "name": "livingCam",
                    "motion": false,
                    "motionTimeout": 15,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "forcePrebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i /dev/video0",
                        "subSource": "-i /dev/video0",
                        "stillImageSource": "-i /dev/video0",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "vcodec": "h264_omx",
                        "acodec": "-acodec",
                        "audio": false,
                        "debug": true
                    },
                    "smtp": {
                        "email": "cam"
                    },
                    "videoanalysis": {
                        "active": false
                    },
                    "mqtt": {}
                }
            ],
            "_bridge": {
                "username": "XX:XX:XX:XX:XX:XX",
                "port": XXX
            },
            "platform": "CameraUI"
        }
    ]
}

Here is the error of the screen.
![スクリーンショット_2022-04-25_22_18_12](https://user-images.githubusercontent.com/7919609/166197881-ec259575-84c0-4ab3-870a-81b391c90755.png)

When I enabled pre-buffering then disabled video analysis, the camera worked on above screen. However, once I registered the camera into Apple Home app, then above error started. It seems, the camera.ui works as long as not registering it onto Apple Home app.

I haven't tried disable both pre-buffering and video analysis, yet. I'll test the configuration.

**Comment by tzwada** [comment]
@seydx Sorry for late. I tried disabling both pre-buffering and video analysis. Then the problem was FIXED!!
Now I can see the video not only the configuration but also Apple Home app. Thank you!!
