### ISSUE TITLE
Hoobs Install - unhandled rejection: Error: Cannot find module 'es-abstract...

### ISSUE THREAD

**Issue by kkissane0328** [seydx/homebridge-camera-ui#475]
Not able to get basic install to go through before adding Cameras. local](http://localhost:8081 throws 404 after launching

Hoobs: 4.1.22
Node: 16.14.0
Homebridge: 1.4.0

Config

{
    "platform": "CameraUI",
    "name": "CameraUI",
    "port": 8081,
    "debug": true,
    "atHomeSwitch": false,
    "options": {
        "videoProcessor": "/var/lib/hoobs/camerauibridge/node_modules/ffmpeg-for-homebridge/ffmpeg"
    },
    "ssl": {
        "active": false
    },
    "http": {
        "active": false,
        "port": 7272,
        "localhttp": false
    },
    "smtp": {
        "active": false,
        "port": 2727,
        "space_replace": "+"
    },
    "ftp": {
        "active": false,
        "useFile": false,
        "port": 5050
    },
    "mqtt": {
        "active": false,
        "tls": false,
        "port": 1883
    }
}

Logging Error 

`2/28/2022, 11:43:59 AMCamera Ui Bridge starting
2/28/2022, 11:44:25 AMCamera Ui BridgeLoaded plugin 'homebridge-camera-ui'
2/28/2022, 11:44:25 AMCamera Ui BridgeLoading 1 platforms...
2/28/2022, 11:44:26 AMCamera Ui BridgeCameraUIConfig changed through interface, saving...
2/28/2022, 11:44:26 AMCamera Ui BridgeBridge is running on port 51876.
2/28/2022, 11:44:26 AMCamera Ui BridgeCameraUIAccessories refreshed and config.json saved!
2/28/2022, 11:44:26 AMCamera Ui BridgeConfiguration change
2/28/2022, 11:44:40 AMCamera Ui BridgeWARNINGunhandled rejection: Error: Cannot find module 'es-abstract/2019/RequireObjectCoercible'
Require stack:
- /var/lib/hoobs/camerauibridge/node_modules/array.prototype.findindex/index.js
- /var/lib/hoobs/camerauibridge/node_modules/node-telegram-bot-api/src/telegram.js
2/28/2022, 11:44:40 AMCamera Ui BridgeWARNINGunhandled rejection: Error: Cannot find module 'es-abstract/2019/RequireObjectCoercible'
Require stack:
- /var/lib/hoobs/camerauibridge/node_modules/array.prototype.findindex/index.js
- /var/lib/hoobs/camerauibridge/node_modules/node-telegram-bot-api/src/telegram.js
2/28/2022, 11:45:02 AMCamera Ui BridgeConfiguration change
2/28/2022, 11:45:02 AMcamerauibridge stopping
2/28/2022, 11:45:07 AMCamera Ui Bridge starting
2/28/2022, 11:45:16 AMCamera Ui BridgeLoaded plugin 'homebridge-camera-ui'
2/28/2022, 11:45:16 AMCamera Ui BridgeLoading 1 platforms...
2/28/2022, 11:45:16 AMCamera Ui BridgeCameraUIConfig changed through interface, saving...
2/28/2022, 11:45:16 AMCamera Ui BridgeCameraUIInitializing camera.ui with PID: 28282
2/28/2022, 11:45:16 AMCamera Ui BridgeCameraUIConfiguring server...
2/28/2022, 11:45:16 AMCamera Ui BridgeBridge is running on port 51876.
2/28/2022, 11:45:16 AMCamera Ui BridgeCameraUIAccessories refreshed and config.json saved!
2/28/2022, 11:45:16 AMCamera Ui BridgeConfiguration change
2/28/2022, 11:45:25 AMCamera Ui BridgeCameraUIConfiguring socket...
2/28/2022, 11:45:25 AMCamera Ui BridgeCameraUIConfiguring database...
2/28/2022, 11:45:25 AMCamera Ui BridgeCameraUIConfiguring event controller...
2/28/2022, 11:45:27 AMCamera Ui BridgeWARNINGunhandled rejection: Error: Cannot find module 'es-abstract/2019/RequireObjectCoercible'
Require stack:
- /var/lib/hoobs/camerauibridge/node_modules/array.prototype.findindex/index.js
- /var/lib/hoobs/camerauibridge/node_modules/node-telegram-bot-api/src/telegram.js
2/28/2022, 11:45:27 AMCamera Ui BridgeWARNINGunhandled rejection: Error: Cannot find module 'es-abstract/2019/RequireObjectCoercible'
Require stack:
- /var/lib/hoobs/camerauibridge/node_modules/array.prototype.findindex/index.js
- /var/lib/hoobs/camerauibridge/node_modules/node-telegram-bot-api/src/telegram.js`

**Comment by seydx** [comment]
I am not familiar with HOOBS, maybe I should ask HOOBS?

Can also test v5.0.17-beta.0
