### ISSUE TITLE
Ping and /change not work

### ISSUE THREAD

**Issue by Mikellas** [SeydX/homebridge-camera-ui#48]
Hi ,

I must be doing something really wrong as i can see any cameras in the ui ( but all offline)
The weirdest thing of all is that now i have duplicates in my HOME app

Heres my config

 {
            "name": "CameraUI",
            "port": 3333,
            "auth": "none",
            "language": "en",
            "debug": false,
            "reset": false,
            "mqtt": {
                "active": false
            },
            "http": {
                "active": false,
                "localhttp": false
            },
            "ssl": {
                "active": false
            },
            "cameras": [
                {
                    "name": "Master Bedroom",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://XXXXXXXX/unicast",
                        "stillImageSource": "-i rtsp://XXXXXXXX/unicast",
                        "audio": true,
                        "socketPort": 8100
                    }
                },
                {
                    "name": "Aeglis Room",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://XXXXXXXX/unicast",
                        "stillImageSource": "-i rtsp://XXXXXXXX/unicast",
                        "audio": true,
                        "socketPort": 8100
                    }
                },
                {
                    "name": "Office",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://XXXXXXXX/unicast",
                        "stillImageSource": "-i rtsp://XXXXXXXX/unicast",
                        "audio": true,
                        "socketPort": 8100
                    }
                }
            ],
            "platform": "CameraUI"

**Comment by SeydX** [comment]
Duplicates? Remove your cache folder (cachedAccessories) and restart homebridge

**Comment by Mikellas** [comment]
Hi Seydx,
Do you mean this file?
![image](https://user-images.githubusercontent.com/62306024/96489372-0d004980-1248-11eb-835a-943dc04e2434.jpg)

**Comment by Mikellas** [comment]
This is what i meant by duplicates
![DBD10E6F-0075-44CF-8F18-23CE236A2DD6](https://user-images.githubusercontent.com/62306024/96492558-800bbf00-124c-11eb-8e2e-1c10409b415f.jpeg)

**Comment by SeydX** [comment]
Yes, but this will delete all your homebridge accessories so you need to bind it again to homekit

**Comment by Mikellas** [comment]
So that means i will need to recreate automations relevant to Homebridge etc?
Is there another way maybe?

**Comment by SeydX** [comment]
@Mikellas 

Do you using a another plugin next to camera ui? Maybe homebridge-camera-ffmpeg?

You should be able to only remove the cameras by tapping on them > details > Remove

**Comment by Mikellas** [comment]
Cant remove camera no option for it
![Uploading A6CF0EE1-319F-4BAD-9075-C65F3D2F51D9.png…]

Yes i do use ffmpeg for the same cameras

**Comment by SeydX** [comment]
With ffmpeg do you the homebridge camera plugin (homebridge-camera-ffmpeg) ?

If yes, pls remove it from your config and from homekit

**Comment by Mikellas** [comment]
So i understand clearly do you want me to remove ffmpeg completely ?

**Comment by monza258** [comment]
Yes that means Seydx. You don't need the homebridge-ffmpeg plugin for using Homebridge-camera-ui.

**Comment by SeydX** [comment]
If you using HOMEBRIDGE-CAMERA-FFMPEG, pls remove it

NOT FFMPEG

**Comment by Mikellas** [comment]
Ok cool didnt know 
I removed it now cameras display correctly but im getting error 1 from ffmpeg now and cameras arent responding in the GUI or in Homekit

**Comment by monza258** [comment]
Can you trie to reinstall ffmpeg. 

sudo apt-get install ffmpeg

sudo reboot

**Comment by Mikellas** [comment]
Reinstalled FFmpeg

Still getting the below error when trying to view cameras in Homekit

[CameraUI] ffmpeg exited with code: 1 and signal: null (Error) Aeglis Room
[10/19/2020, 10:04:36 PM] [CameraUI] Aeglis Room: Stopped video stream.

**Comment by SeydX** [comment]
@Mikellas 

Can u set audio to false pls and try again

**Comment by Mikellas** [comment]
@SeydX Cool that did the trick in Homekit.Live video and snapshots work now

 Camera Ui still says that all cameras are offline though,no errrors in debug

**Comment by SeydX** [comment]
@Mikellas can u post your config.json pls??

**Comment by Mikellas** [comment]
{
            "name": "CameraUI",
            "port": 3333,
            "auth": "none",
            "language": "en",
            "debug": true,
            "reset": false,
            "mqtt": {
                "active": false
            },
            "http": {
                "active": false,
                "localhttp": false
            },
            "ssl": {
                "active": false
            },
            "cameras": [
                {
                    "name": "Master Bedroom",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://192.168.88.165:8554/unicast",
                        "stillImageSource": "-rtsp_transport tcp -i rtsp://192.168.88.165:8554/unicast",
                        "forceMax": true,
                        "vcodec": "copy",
                        "audio": false,
                        "socketPort": 8100
                    }
                },
                {
                    "name": "Aeglis Room",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://192.168.88.167:8554/unicast",
                        "stillImageSource": "-rtsp_transport tcp -i rtsp://192.168.88.167:8554/unicast",
                        "forceMax": true,
                        "vcodec": "copy",
                        "audio": false,
                        "socketPort": 8200
                    }
                },
                {
                    "name": "Office",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://192.168.88.169:8554/unicast",
                        "stillImageSource": "-rtsp_transport tcp -i rtsp://192.168.88.169:8554/unicast",
                        "forceMax": true,
                        "vcodec": "copy",
                        "audio": false,
                        "socketPort": 8300
                    }
                }
            ],
            "platform": "CameraUI"
        }

**Comment by SeydX** [comment]
the problem is the socketPort you use in your config.json

each camera must have an UNIQUE socketPort, you have set the same socketPort for all cams

**Comment by Mikellas** [comment]
@SeydX You probably saw my previous json post? Update above shows the actual ones i use now (8100,8200,8300)

**Comment by SeydX** [comment]
Hmmm.. Can u show me your browser console pls? Example (Google Chrome)

![browser_console](https://user-images.githubusercontent.com/34152761/96505346-450e8900-1256-11eb-8932-80240138efa5.gif)

**Comment by Mikellas** [comment]
![image](https://user-images.githubusercontent.com/62306024/96505559-f74a4e80-125e-11eb-8168-e2306fd30c9f.png)

**Comment by SeydX** [comment]
Ok thats good so far

Can you put **DEBUG=CameraUI*** into your homebridge environment file?

If you are using Config UI X you can do it like below

![hb_debug](https://user-images.githubusercontent.com/34152761/96505898-0c22e400-1257-11eb-83aa-f9f49a547418.gif)

Or you can edit the environment file manually, the file shoud be located under

/etc/default/**homebridge**

```
# Defaults / Configuration options for homebridge
# The following settings tells homebridge where to find the config.json file and where to persist the data (i.e. pairing and others)
HOMEBRIDGE_OPTS=-I -U /var/lib/homebridge

#To enable web terminals via homebridge-config-ui-x
HOMEBRIDGE_CONFIG_UI_TERMINAL=1

# If you uncomment the following line, homebridge will log more 
# You can display this via systemd's journalctl: journalctl -f -u homebridge
DEBUG=CameraUI
```

**Comment by Mikellas** [comment]
I did it with the fist way you told me but no logs turn up for your plugin while i use the gui
I can see the rest plugins reports i can send but i believe it wont help you in any way

One thing i forgot to mention though is that i have authentication mode to none because i tried using the form and the default admin credentials didnt work even after resetting

**Comment by SeydX** [comment]
That the authentication form is on "none" should not be the problem. But more important is why the default login data (admin:admin) did not work.

How did you set log for config-ui-x? systemd or file?

Could you post the config-ui-x part from your config.json pls

**Comment by Mikellas** [comment]
"platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "auto",
            "sudo": false,
            "sessionTimeout": 28800,
            "log": {
                "method": "native",
                "path": "C:\\Users\\Nicolas Server\\.homebridge\\homebridge.log"
            },
            "platform": "config"

**Comment by Mikellas** [comment]
I had to check debug in the actual plugin settings and i got below whenever i try to view a camera 

GET /cameras 200 1848.304 ms - -
GET /stylesheets/modules/bootstrap.min.css 304 1.194 ms - -
GET /stylesheets/style.css 304 3.974 ms - -
GET /plugins/toast/toast.min.css 304 3.242 ms - -
GET /fonts/fontawesome.css 304 2.659 ms - -
GET /plugins/lightcase/lightcase.css 304 2.056 ms - -
GET /javascripts/modules/jquery.min.js 304 2.020 ms - -
GET /javascripts/modules/i18next.min.js 304 1.333 ms - -
GET /images/web/logo_transparent-256.png 304 1.308 ms - -
GET /images/user/anonym.png?r=0.39356361793593186 200 3.178 ms - 25100
GET /javascripts/modules/velocity.min.js 304 1.455 ms - -
GET /javascripts/modules/velocity.ui.min.js 304 1.964 ms - -
GET /javascripts/modules/jquery.visible.min.js 304 3.381 ms - -
GET /javascripts/modules/socket.io.slim.js 304 2.364 ms - -
GET /javascripts/modules/safearea.min.js 304 4.548 ms - -
GET /javascripts/modules/bootstrap.bundle.min.js 304 3.210 ms - -
GET /javascripts/utils/detectswipe.js 304 2.606 ms - -
GET /plugins/toast/toast.min.js 304 3.795 ms - -
GET /javascripts/main.js 304 2.155 ms - -
GET /plugins/lightcase/lightcase.js 304 1.698 ms - -
GET /javascripts/utils/socket.js 304 2.715 ms - -
GET /worker.js 304 2.177 ms - -
GET /javascripts/utils/filter.js 304 1.642 ms - -
GET /javascripts/views/cameras.js 304 0.968 ms - -

**Comment by SeydX** [comment]
Did you restart homebridge after setting DEBUG=CameraUI*

Note: it must be exactly **CameraUI*** (with the star char at the end)

**Comment by Mikellas** [comment]
![image](https://user-images.githubusercontent.com/62306024/96511974-7e4ff480-1268-11eb-892d-fe0e48639e9d.png)

**Comment by Mikellas** [comment]
Am i supposed to be getting logs while browsing the UI or something?

**Comment by SeydX** [comment]
Nah thats wrong, as you seen in the GIF, in config-ui-x you must define ONLY **CameraUI*** (without DEBUG=)

**Comment by Mikellas** [comment]
omg sorry about that..

2020-10-19T21:14:01.129Z CameraUIInterface {
  userID: false,
  message: 'session redirect',
  originalUrl: '/',
  authenticated: false,
  noAuth: false
}
2020-10-19T21:14:01.129Z CameraUIInterface {
  userID: false,
  message: 'ensure authenticated',
  originalUrl: '/',
  authenticated: false,
  noAuth: false



Below once i try to log in

**Comment by SeydX** [comment]
Could you try first without authentification pls to debug the not working livestreams

**Comment by Mikellas** [comment]
2020-10-19T21:18:40.248Z CameraUIInterface Master Bedroom: Offline
2020-10-19T21:18:40.531Z CameraUISocket admin disconnected!
2020-10-19T21:18:40.531Z CameraUISocket { admin: { devices: 0 } }
2020-10-19T21:18:40.753Z CameraUISocket admin connected!
2020-10-19T21:18:40.753Z CameraUISocket { admin: { devices: 1 } }
2020-10-19T21:18:40.764Z CameraUISocket {
  username: 'admin',
  currentUrl: '/camera/Master%20Bedroom',
  targetUrl: false,
  back: false
}

**Comment by Mikellas** [comment]
2020-10-19T21:20:40.998Z CameraUIInterface {
  userID: '3be9895a-be63-44a9-8b75-4495ef5d9b7e',
  message: 'session redirect',
  originalUrl: '/camviews',
  authenticated: false,
  noAuth: true
}
2020-10-19T21:20:40.998Z CameraUIInterface {
  userID: '3be9895a-be63-44a9-8b75-4495ef5d9b7e',
  message: 'ensure authenticated',
  originalUrl: '/camviews',
  authenticated: false,
  noAuth: true
}
2020-10-19T21:20:40.998Z CameraUIInterface admin (Master): Authentication skipped!
2020-10-19T21:20:40.998Z CameraUIApp {
  userID: '3be9895a-be63-44a9-8b75-4495ef5d9b7e',
  message: 'locals',
  url: '/camviews',
  authenticated: false,
  noAuth: true
}
2020-10-19T21:20:40.998Z CameraUIInterface Trying to ping Master Bedroom
2020-10-19T21:20:41.526Z CameraUIInterface Master Bedroom: Offline
2020-10-19T21:20:41.528Z CameraUIInterface Trying to ping Aeglis Room
2020-10-19T21:20:42.042Z CameraUIInterface Aeglis Room: Offline
2020-10-19T21:20:42.043Z CameraUIInterface Trying to ping Office
2020-10-19T21:20:42.550Z CameraUIInterface Office: Offline
2020-10-19T21:20:42.740Z CameraUISocket admin disconnected!
2020-10-19T21:20:42.740Z CameraUISocket { admin: { devices: 1 } }
2020-10-19T21:20:42.740Z CameraUISocket admin disconnected!
2020-10-19T21:20:42.740Z CameraUISocket { admin: { devices: 0 } }
2020-10-19T21:20:42.961Z CameraUISocket admin connected!
2020-10-19T21:20:42.961Z CameraUISocket { admin: { devices: 1 } }
2020-10-19T21:20:42.967Z CameraUISocket admin connected!
2020-10-19T21:20:42.967Z CameraUISocket { admin: { devices: 2 } }
2020-10-19T21:20:43.037Z CameraUISocket {
  username: 'admin',
  currentUrl: '/camviews',
  targetUrl: false,
  back: false

This when i press on CamViews

**Comment by SeydX** [comment]
hm as i thought, the plugin can not ping the cameras, i will check this thanks!

**Comment by Mikellas** [comment]
No problem if you need anything else let me know camera models etc

**Comment by SeydX** [comment]
I fixed the not found error, looking now for the ping issue

**Comment by SeydX** [comment]
v3.0.9 is online

could you try pls?

**Comment by Mikellas** [comment]
Hi,

I have tried and all is good!!
Doesn this mean i can enable sound as well?

Thanks

**Comment by Mikellas** [comment]
It was the camera settings after all 
All seems ok now
