### ISSUE TITLE
Mqtt Motion Not triggered

### ISSUE THREAD

**Issue by Luftloch80** [SeydX/homebridge-camera-ui#49]
Hey this Is my config for Version v2
  "mqtt": {
                        "active": true,
                        "host": "192.168.0.50",
                        "port": 1883,
                        "topicPrefix": "siedle",
                        "topicSuffix": "cmnd",
                        "startMessage": "ring_E_D",
                        "stopMessage": "motion_stop",
                        "recordOnMovement": false,
                        "recordVideoSize": 10,
                        "interval": 1
                    }

And this for v3

 "mqtt": {
                "active": true,
                "host": "192.168.0.50",
                "port": 1883,
                "topic": "siedle/cmnd",
                "on_message": "ring_E_D"
            },

But no motion is triggered when ring_E_D is sent to topic siedle/cmnd

**Comment by SeydX** [comment]
The message to trigger the camera movement detection has this prefix

CAMERANAME@MSG

CAMERANAME: must be exact the same name as defined in the config.json for the specific camera u want to trigger

MSG: on_message defined in config.json

**Comment by Luftloch80** [comment]
Okay. I get this command ring_E_D if someone rings my door not from the camera itself. With last Version it was working perfect

**Comment by SeydX** [comment]
@Luftloch80 

What kind of cameras do you have? Can u post me the mqtt config from the cameras pls (not from config.json)

**Comment by Luftloch80** [comment]
I have a reolink cam without mqtt.  I have a mqtt gateway for my siedle doorbell which triggers mqtt messages. 
But i will do a workaround with a homebridge-mqttthing Motion Sensor

**Comment by SeydX** [comment]
Allright, let me know if u need help

As i said, the mqtt client needs to trigger the suffix/prefix (homebridge/motion if not changed in config) with the following message (CAMERNAME@MESSAGE or only CAMERNAME)
