### ISSUE TITLE
Direct stream url

### ISSUE THREAD

**Issue by giusanny** [seydx/homebridge-camera-ui#493]
Hi,
as motioneye can do, it will be nice to have a direct url to see a camera live streaming without filling user and password in the intranet.

I have a wall mounted display (with a web browser) where I have no keyboard and want to see a camera using http://ip:8081/camview how could i do it?

**Comment by seydx** [comment]
Added in `v5.0.21-beta.7`

To access only the feed, you can use following path: `/cameras/:name/feed`

<img width="1439" alt="cui_feed" src="https://user-images.githubusercontent.com/34152761/164577709-82bf64a7-f194-4eee-85d4-0c1ea160b56b.png">

**Comment by giusanny** [comment]
great news thanks!

**Comment by seydx** [comment]
v5.0.21 online

**Comment by giusanny** [comment]
Hi, it still needs to put username and password, i cannot use it in the wall display where i don't have a keyboard. 

How can i access directly to the stream feed inside my home network without the need of user and password? 

p.s. Expose the stream feed with or without user and pwd can be an option in camera configuration for example (for a future feature)
