### ISSUE TITLE
Motion Sensor when object detected by HSV

### ISSUE THREAD

**Issue by fade2metal** [seydx/homebridge-camera-ui#494]
Apple isn‘t giving the user any chance to use person detection/object detection as automation trigger. I can get a notification but with that notification I can‘t trigger an Alarm System or Light or anything else

I don‘t know if I get it right but I think your camera ui plugin could be the solution.
In the logs I saw that your plugin gets info when HSV is recording video/sends notification to me.
It would be really great to use that information to trigger an additional motion sensor that is able to trigger automations in Homekit.

Do you think that could be possible?

**Comment by seydx** [comment]
Hm there should be already a motion sensor exposed with your camera to apple homekit which will be triggered if motion is detected

**Comment by seydx** [comment]
See

![0054DEC5-CED6-4689-94F0-A7B269A3170B](https://user-images.githubusercontent.com/34152761/162642640-45dafc1a-5036-416d-a40c-7d8498b7def8.png)

**Comment by fade2metal** [comment]
I meant Object detection not motion detection. 

My question was: can you get logs from HSV when a video is recorded. 
HSV only records a video, when a specific object is detected.
This object detection would be nice to use as a trigger in homekit.

(Switch on Light only when Person is detected but not when animal is detected)
