### ISSUE TITLE
Strange error (EACCES)

### ISSUE THREAD

**Issue by Lammiwinks** [seydx/homebridge-camera-ui#498]
Hi Team,

Getting an error trying to add a camera via Homebridge (docker on Pi4). 

Error: EACCES: permission denied, mkdir “/var/lib/homebridge”. This actually sends a sigterm to Homebridge and it goes into a reboot loop. 

With just the plugin installed and no cameras it all works fine. 

Any ideas on how to fix? Have tried re-installing the plugin.

**Comment by seydx** [comment]
Can you post the full log pls

**Comment by seydx** [comment]
I don't have much experience with Docker, but what is the exact path to your Homebridge config.json?

**Comment by seydx** [comment]
camera.ui can not create the folder structure by itself as it looks, then you have to create it

just create `/var/lib/homebridge` director and it should work again

**Comment by Lammiwinks** [comment]
Sorry about the late reply. To update - I reformatted my Pi and reinstalled homebridge which solved this.

**Comment by grzegorz914** [comment]
Same error is if homebridge installed on Mac OS

**Comment by grzegorz914** [comment]
on macOS /var is a private directory and can’t be used to store any data, @seydx can you change this to use Users/username/camera.ui
