### ISSUE TITLE
NOT AN ISSUE - 

### ISSUE THREAD

**Issue by jeylites** [SeydX/homebridge-camera-ui#5]
Hi, 

It seems to be an interesting project.  But I'm trying to understand what's the benefit of using this plugin vs the standard [@KhaosT camera ffmpeg plugin](https://www.npmjs.com/package/homebridge-camera-ffmpeg) apart from the MQTT motion functionality?

Does it support OMX acceleration?

**Comment by SeydX** [comment]
@jeylites 

Hey, sry for the late reply

The benefit from this plugin is the motion sensor and the GUI.

The Plugin offers to way of using the motion sensor (mqtt and ftp)

And over the GUI you have access to the camera from any device

(Im currently working on redesigning the gui, so stay tuned)
