### ISSUE TITLE
Privacy Mode does not turn off

### ISSUE THREAD

**Issue by pumabaer** [seydx/homebridge-camera-ui#500]
**Describe the bug**
When I turn on the privacy mode, the replacement image appears.
In the snapshots and in the stream.
When I turn off the mode again the stream is back to normal but the snapshot still shows the replacement image.

Only a restart of Homebridge solves this problem for me.

Is there a solution to this problem?

**To Reproduce**
Switch privacy mode on and off again

**Screenshots**
![C2D594C7-C0B4-4BC8-900B-B72B595FFC28](https://user-images.githubusercontent.com/30412987/161148070-2e7cce92-cfed-43ef-852b-40af741c944e.jpeg)

**Environment**
- Node.js Version: v16.13.2
- Homebridge Version: v1.4.0
- Camera UI Version: v5.0.16
- Operating System: Ubuntu Server 20.04.3 LTS

**Comment by seydx** [comment]
Double checked this and its working for me

After disabled "Privacy Mode", just re open the stream und close, the snapshot should be changed, otherwise force close the home app

**Comment by pumabaer** [comment]
Unfortunately, still does not work.
Have also checked it several times.

The first snapshot after opening the stream is correct, then again the "privacy mode" image.

I may have to reinstall Camera UI.

**Comment by seydx** [comment]
I found the bug, will be fixed in next beta (v5.0.17-beta.1)

**Comment by seydx** [comment]
v5.0.17-beta.1 is online

**Comment by pumabaer** [comment]
Thank you, in the beta version it works now!
