### ISSUE TITLE
FTP: Satisfy Parameters Error { error: 'Socket not writable' }

### ISSUE THREAD

**Issue by jjss520** [seydx/homebridge-camera-ui#506]
New message: File Name: testftp.txt - File Path: /testftp.txt - Path Split []
[CameraUI] FTP: Satisfy Parameters Error { error: 'Socket not writable' }

 "ftp": {
                "active": true,
                "useFile": false,
                "port": 5050
            },

FTP 
server address
 10.10.10.10
The port number
 5050
user account
user password
confirm password
Storage path MC500L

FTP Absolute Path
abe MC500L
FTP Server must be enabled to trigger a movement through file upload!

What's the problem？thank you

**Comment by seydx** [comment]
can you post a screenshot from your camera ftp settings pls

**Comment by seydx** [comment]
try anonymous (disable authentication and try again (camera ftp settings))
