### ISSUE TITLE
Frequent time out errors

### ISSUE THREAD

**Issue by Hackintoshbigsur** [seydx/homebridge-camera-ui#514]
Describe the bug
Every few seconds “Driveway Cam: Videoanalysis timed out… killing ffmpeg session”
Then after 5 or 6 times if this it says “Driveway Cam: Prebuffer timed out… killing ffmpeg session”
The restarts homebridge get.
To Reproduce
Steps to reproduce the behavior
No idea

Expected behavior
Live stream when needed, motion detection, HomeKit secure video, and hksv motion video recordings.
Logs
If available, attach the log where the bug is vissible

Environment

Node.js Version: v14.17
Homebridge Version: v1.4.0
Camera UI Version: v5.0.16
Operating System: Windows 10 
Browser: Chromium edge

**Comment by seydx** [comment]
https://github.com/seydx/homebridge-camera-ui/issues/470
