### ISSUE TITLE
This plugin slows down Homebridge

### ISSUE THREAD

**Issue by grzegorz914** [seydx/homebridge-camera-ui#521]
**Describe the bug**
After updating to 5.0.17 the plugin start report slow down after start stream in HK.

**To Reproduce**
Start streaming

**Logs**
`[16.04.2022, 03:08:57] [homebridge-camera-ui] This plugin slows down Homebridge. The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Przód E6F3' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.`

**Comment by seydx** [comment]
Can not reproduce the error, when does the error appear? Only at the beginning? At every restart? Can you reproduce it?

**Comment by grzegorz914** [comment]
Every time after go to Home app and open live stream:

```
[16.04.2022, 05:20:48] [CameraUI] Przód: Starting video stream: native
[16.04.2022, 05:20:57] [homebridge-camera-ui] This plugin slows down Homebridge. The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Przód E6F3' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[16.04.2022, 05:20:57] [CameraUI] Przód: Stopped video stream.
```

**Comment by grzegorz914** [comment]
Revert back to 5.0.16 solves the problem.

**Comment by seydx** [comment]
Hm, stream still works though?

**Comment by grzegorz914** [comment]
Yes, all working as excepted, only the warning in log.

**Comment by seydx** [comment]
@grzegorz914 

I suppose you don't use "[child bridge](https://github.com/homebridge/homebridge/wiki/Child-Bridges)" ?

**Comment by grzegorz914** [comment]
No, I’m use child bridge.

**Comment by seydx** [comment]
are you using ffmpeg from camera.ui or your own?

if you use ffmpeg from camera.ui the log should say something like

`Stream command: /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg ...`

With v5.0.17 ffmpeg was updated to v5, nothing else was changed that could show this "warning" in the log

Could you also post your config.json from the camera please

**Comment by grzegorz914** [comment]
I’m use my own ffmpeg because use rpi4+ with  bullseye 64Bit system.
With built-in ffmpeg stream stop working  after 5sec but the behavior in log is same for both ffmpeg(build-in and my own).

```
 {
                    "name": "Przód",
                    "manufacturer": "Boavision",
                    "model": "IPD-E2A5L18-BS",
                    "serialNumber": "071D3E366E30",
                    "motion": false,
                    "useInterfaceTimer": false,
                    "motionTimeout": 90,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 5,
                    "videoConfig": {
                        "source": "-i rtsp://192.168.1.26/1/h264major",
                        "subSource": "-i rtsp://192.168.1.26/1/h264minor",
                        "stillImageSource": "-i http://192.168.1.26/jpgmulreq/1/image.jpg?key=1576599413929&lq=1",
                        "readRate": false,
                        "rtspTransport": "tcp",
                        "maxStreams": 2,
                        "forceMax": false,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "stimeout": 0,
                        "audio": false,
                        "debug": false
                    },
                    "smtp": {
                        "email": "Przod"
                    },
                    "videoanalysis": {
                        "active": true
                    },
                    "mqtt": {}
                }
```

**Comment by seydx** [comment]
can you try v5.0.18 pls

**Comment by grzegorz914** [comment]
Same behavior and after 5sec the stream camera stop responding. I move back to 5.0.16

**Comment by grzegorz914** [comment]
Moved back to 5.0.16 all working fine.

**Comment by seydx** [comment]
> Same behavior and after 5sec the stream camera stop responding. I move back to 5.0.16

stream stops responding only with the built-in ffmpeg version? or also with yours

**Comment by grzegorz914** [comment]
Also with my own.

**Comment by seydx** [comment]
> Also with my own.

any errors in the log why the stream stop responding?

**Comment by grzegorz914** [comment]
No any error, only the slow down warning

**Comment by grzegorz914** [comment]
Confirm, 5.0.19-beta.0 working fine

**Comment by seydx** [comment]
> Confirm, 5.0.19-beta.0 working fine

v5.0.19-beta.1 is already online (there was a little bug in beta.0)

**Comment by grzegorz914** [comment]
Installed, tested, working fine

**Comment by seydx** [comment]
v5.0.19 is online
