### ISSUE TITLE
Recording ends too soon - possible switch to camera’s built in detection

### ISSUE THREAD

**Issue by PNWOregon** [seydx/homebridge-camera-ui#522]
**Describe the bug**
Recordings are ending too soon and not capturing the hole “event”. 

**To Reproduce**
If the “object” is triggering motion and remains in the cameras view for greater than 13 seconds the recording ends while the “object” remains in view (and moving). 

**Expected behavior**
The camera continues to capture the entirety of the event while the “object“ remains in view. 

Also of note. if I attempt to alter the videoanalysis settings the recordings become inconsistent and then do not record as expected. 

Lastly. I have an Amcrest doorbell and I happen to like it’s built in motion detection. Is there a way to utilize it instead of the videoanalysis through camera.ui?

Thanks for taking your time to help!

**Comment by seydx** [comment]
Camera.ui supports multiple ways of motion detection.

If you want to use the built in motion detection from your camera, you can use SMTP (email) or FTP

**Comment by PNWOregon** [comment]
That would be amazing! I’ll have to try to find a guid as I’m not very well versed in this kinda stuff. Thank you for your quick response! I’m just happy to know it’s an option.

**Comment by seydx** [comment]
SMTP:
https://github.com/seydx/homebridge-camera-ui/wiki/SMTP-Config

FTP:
https://github.com/seydx/homebridge-camera-ui/wiki/FTP-Config

MQTT:
https://github.com/seydx/homebridge-camera-ui/wiki/MQTT-Config

**Comment by PNWOregon** [comment]
Wonderful thank you!

and just out of curiosity what settings in the videoanalysis settings should I adjust to allow for longer record times?

**Comment by seydx** [comment]
https://github.com/seydx/homebridge-camera-ui/wiki/Videoanalysis

Reset motion after: 0
Dwell time: 60

**Comment by PNWOregon** [comment]
I’ll try that first before diving into it. Thanks again. I’ll adjust those settings now and report back here for anyone else looking for the same thing.

**Comment by PNWOregon** [comment]
I’ve been adjusting and playing with the settings of the course of the past 2 weeks and no matter the setting(s) the recording still ends early, prior to the object leaving the cameras view. 

Is there anything else I could do to make it record properly/longer?

**Comment by facundodelavega** [comment]
> I’ve been adjusting and playing with the settings of the course of the past 2 weeks and no matter the setting(s) the recording still ends early, prior to the object leaving the cameras view.
> 
> Is there anything else I could do to make it record properly/longer?

Did you get it worked out? I have the same issue and I don't know how to fix it
