### ISSUE TITLE
after updating to 5.0.19, returnAudioTarget does not work

### ISSUE THREAD

**Issue by chip131001** [seydx/homebridge-camera-ui#523]
**Describe the bug**
after updating to 5.0.19, returnAudioTarget does not work. Same settings work with 5.0.16.

**Screenshots**
![image](https://user-images.githubusercontent.com/38818613/163687255-54a2a7bb-c6d9-44c9-96d3-6be4c1de7211.png)

**Environment**
- Node.js Version: v16.14.2
- Homebridge Version: v1.4.0

`"name": "CameraUI",
            "port": 8081,
            "atHomeSwitch": false,
            "debug": true,
            "mqtt": {
                "active": false,
                "tls": false,
                "port": 1883
            },
            "http": {
                "active": false,
                "port": 7272,
                "localhttp": false
            },
            "smtp": {
                "active": false,
                "port": 2727,
                "space_replace": "+"
            },
            "ftp": {
                "active": false,
                "useFile": false,
                "port": 5050
            },
            "ssl": {
                "active": false
            },
            "options": {
                "videoProcessor": "/home/pi/bin/ffmpeg"
            },
            "cameras": [
                {
                    "name": "Eingang",
                    "motion": true,
                    "doorbell": true,
                    "motionTimeout": 15,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": false,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://192.168.178.183:8554/eingang -f alsa -ar 16000 -thread_queue_size 1024 -i default",
                        "subSource": "-i rtsp://192.168.178.183:8554/eingang",
                        "stillImageSource": "-i http://192.168.178.35:88/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=skunz&pwd=E4ooK5MH6qK3&",
                        "rtspTransport": "tcp",
                        "analyzeDuration": 0,
                        "probeSize": 2000,
                        "returnAudioTarget": "-f alsa plughw:CARD=P610,DEV=0 -ar 16000 -thread_queue_size 1024",
                        "maxStreams": 2,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "mapvideo": "0:v",
                        "mapaudio": "1:a",
                        "audio": true,
                        "debug": true,
                        "debugReturn": true
                    },
                    "smtp": {
                        "email": "Eingang"
                    },
                    "videoanalysis": {
                        "active": false
                    },
                    "mqtt": {}
                }
            ],
            "platform": "CameraUI"`

**Comment by seydx** [comment]
@chip131001 

can you disable `"debugReturn"` and try again pls

**Comment by chip131001** [comment]
@seydx 
Unfortunately that doesn't work either

**Comment by seydx** [comment]
nvm, i found the bug, will be fixed in the next beta in few mins

**Comment by seydx** [comment]
fixed in v5.0.20-beta.0

**Comment by chip131001** [comment]
> fixed in v5.0.20-beta.0

Works again. Thank you.
