### ISSUE TITLE
No luck solving 'The recording process was aborted by HSV with reason "CANCELLED"' any help appreciated 

### ISSUE THREAD

**Issue by elevengene** [seydx/homebridge-camera-ui#532]
I can't get HomeKit to record video, sometimes it can detect "all motion", and have had some pre buffering issues. 

I've followed other issues here, but haven't been able to get the Camera.ui settings along with the specific camera settings to successfully record, it got to the point that my Homebridge instance was bottlenecking and causing problems with the rest of my accessories.... So I am giving up for now, hopefully someone can help:

Attached are my camera settings and logs, hope someone can help me figure this out. 
<img width="897" alt="Screen Shot 2022-04-19 at 10 43 06 AM" src="https://user-images.githubusercontent.com/104060304/164177476-7d614076-7bfe-4b27-9d70-a30b46056be1.png">

Logs:
{
  "debug": true,
  "port": 8081,
  "atHomeSwitch": false,
  "options": {
    "videoProcessor": "/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"
  },
  "ssl": {
    "active": false
  },
  "http": {
    "active": false,
    "port": 7272,
    "localhttp": false
  },
  "smtp": {
    "active": false,
    "port": 2727,
    "space_replace": "+"
  },
  "ftp": {
    "active": false,
    "useFile": false,
    "port": 5050
  },
  "mqtt": {
    "active": false,
    "tls": false,
    "port": 1883
  },
  "cameras": [
    {
      "name": "Right Gate Test",
      "motion": true,
      "motionTimeout": 15,
      "unbridge": true,
      "hsv": true,
      "prebuffering": true,
      "forcePrebuffering": true,
      "prebufferLength": 4,
      "videoConfig": {
        "source": "-i rtsp://user:password@192.168.1.108:554/H264?ch=1&subtype=0",
        "subSource": "-i rtsp://user:password@192.168.1.108:554/H264?ch=1&subtype=1",
        "stillImageSource": "-i rtsp://user:password@192.168.1.108:554/H264?ch=1&subtype=2",
        "readRate": true,
        "forceMax": true,
        "vcodec": "copy",
        "acodec": "libfdk_aac",
        "audio": false,
        "debug": true
      },
      "smtp": {
        "email": "Right Gate Test"
      },
      "videoanalysis": {
        "active": true
      },
      "mqtt": {}
    },
    {
      "name": "Front Right Test",
      "motion": true,
      "motionTimeout": 15,
      "unbridge": true,
      "hsv": true,
      "prebuffering": true,
      "prebufferLength": 4,
      "videoConfig": {
        "source": "-i rtsp://user:password@192.168.1.107:554/H264?ch=1&subtype=1",
        "subSource": "-i rtsp://user:password@192.168.1.107:554/H264?ch=1&subtype=1",
        "stillImageSource": "-i rtsp://user:password@192.168.1.107:554/H264?ch=1&subtype=1",
        "maxStreams": 2,
        "vcodec": "copy",
        "acodec": "libfdk_aac",
        "audio": false
      },
      "smtp": {
        "email": "Front Right Test"
      },
      "videoanalysis": {
        "active": true
      },
      "mqtt": {}
    }
  ]
}

thanks

**Comment by seydx** [comment]
Hey @elevengene 

Try following camera settings: 

### Main Stream

```
Resolution: 1920x1080
FPS: 25
Keyframe Interval (I Frame Interval): 100 (Keyframe Interval = FPS x 4)
Bitrate: 2048 kbps (CBR)
```

### Sub Stream

```
Resolution: 640x360
FPS: 10
Keyframe Interval (I Frame Interval): 40 (Keyframe Interval = FPS x 4)
Bitrate: 2048 kbps (CBR)
```

And following config.json

```json
{
  "debug": true,
  "port": 8081,
  "atHomeSwitch": false,
  "options": {
    "videoProcessor": "/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"
  },
  "ssl": {
    "active": false
  },
  "http": {
    "active": false,
    "port": 7272,
    "localhttp": false
  },
  "smtp": {
    "active": false,
    "port": 2727,
    "space_replace": "+"
  },
  "ftp": {
    "active": false,
    "useFile": false,
    "port": 5050
  },
  "mqtt": {
    "active": false,
    "tls": false,
    "port": 1883
  },
  "cameras": [
    {
      "name": "Right Gate Test",
      "motion": true,
      "motionTimeout": 15,
      "unbridge": true,
      "hsv": true,
      "prebuffering": true,
      "forcePrebuffering": true,
      "prebufferLength": 4,
      "videoConfig": {
        "source": "-i rtsp://admin:Q4fJmMjf@192.168.1.108:554/H264?ch=1&subtype=0",
        "subSource": "-i rtsp://admin:Q4fJmMjf@192.168.1.108:554/H264?ch=1&subtype=1",
        "stillImageSource": "-i rtsp://admin:Q4fJmMjf@192.168.1.108:554/H264?ch=1&subtype=2",
        "rtspTransport": "tcp",
        "vcodec": "copy",
        "acodec": "libfdk_aac",
        "audio": false,
        "debug": true
      },
      "smtp": {
        "email": "Right Gate Test"
      },
      "videoanalysis": {
        "active": true
      },
      "mqtt": {}
    },
    {
      "name": "Front Right Test",
      "motion": true,
      "motionTimeout": 15,
      "unbridge": true,
      "hsv": true,
      "prebuffering": true,
      "prebufferLength": 4,
      "videoConfig": {
        "source": "-i rtsp://admin:Q4fJmMjf@192.168.1.107:554/H264?ch=1&subtype=1",
        "subSource": "-i rtsp://admin:Q4fJmMjf@192.168.1.107:554/H264?ch=1&subtype=1",
        "stillImageSource": "-i rtsp://admin:Q4fJmMjf@192.168.1.107:554/H264?ch=1&subtype=1",
        "rtspTransport": "tcp",
        "vcodec": "copy",
        "acodec": "libfdk_aac",
        "audio": false,
        "debug": true
      },
      "smtp": {
        "email": "Front Right Test"
      },
      "videoanalysis": {
        "active": true
      },
      "mqtt": {}
    }
  ]
}
```

**Comment by elevengene** [comment]
Cool, ill give this a shot, thanks for the quick response!🙏🏻

PS. accidentally put my camera credentials 🤦🏻 in the original post ( I have since removed them, any chance you can remove the credentials from your comment)🙏🏻

**Comment by seydx** [comment]
> Cool, ill give this a shot, thanks for the quick response!🙏🏻

any news on this?

**Comment by elevengene** [comment]
> > Cool, ill give this a shot, thanks for the quick response!🙏🏻
> 
> any news on this?

Changed my settings for each camera and it worked.... thanks!

Does it make sense that HSV only records from one camera at a time? 

I walked from one camera to the other and I was only recorded on the first camera that noticed me...
I waited a minute and walked the opposite direction: and again the first camera that noticed me  (which was the second camera in the previous instance) had a recording while the second camera didn't

**Comment by seydx** [comment]
> Does it make sense that HSV only records from one camera at a time?

No camera.ui / HSV can handle multiple motion events at same time
