### ISSUE TITLE
Privacy mode is not working 

### ISSUE THREAD

**Issue by fullphat** [seydx/homebridge-camera-ui#534]
**Describe the bug**
I've enabled the Privacy Switch for one of my cameras (a Tapo TC70) but when I enable the switch nothing happens.  I see this was raised and closed in #430 but I don't know where to find the "At Home" setting or switch.

**To Reproduce**
As per above

**Expected behavior**
I would expect some plugin-generated image to appear rather than the camera's RTSP stream

**Logs**
N/A

**Screenshots**
N/A

**Environment**
- Node.js Version: v16.14.2
- Homebridge Version: v1.4.0
- Camera UI Version: v5.0.19
- Operating System: MacOS Big Sur
- Browser: Safari

**Comment by seydx** [comment]
Hey @fullphat 

You can expose the "At Home" Switch to HomeKit by enabling "atHomeSwitch" in your config.json

see https://github.com/seydx/homebridge-camera-ui/blob/bde4af5e041602dac0c821eaa9d1a593518f42f1/example-config.json#L16

You can also enable/disable the At Home Switch within UI > Settings > Interface > General > At Home

**Comment by fullphat** [comment]
Works a treat!  What else does the At Home switch do when it's enabled?

**Comment by seydx** [comment]
If At Home switch is enabled (and the camera is NOT excluded from "at home), the incoming motion events for the camera will be ignored and you will not receive any notifications from the camera as long as at home is enabled

**Comment by fullphat** [comment]
Thanks!
