### ISSUE TITLE
Publish MQTT Message on Motion ON and OFF

### ISSUE THREAD

**Issue by mynameisdaniel32** [seydx/homebridge-camera-ui#537]
**Is your feature request related to a problem? Please describe.**
This is an expansion from https://github.com/seydx/homebridge-camera-ui/issues/425, we can now get MQTT messages about motion events (thank you!), but only at the conclusion of the recording/motion.

It'd be very useful to get motion events posted to MQTT on motion start. This would allow the Camera UI motion detection to be used to automate other things via MQTT (i.e. lights).

**Describe the solution you'd like**
For Motion ON and Motion OFF events to be able to be posted to an MQTT topic.
i.e. to be able to use these motion events:

**Describe alternatives you've considered**
It might be possible to do this via HomeKit automations using the associated motion sensor, but I'd rather go directly to MQTT.

**Additional context**
These Motion events are the ones I'd like to have available via MQTT.
![image](https://user-images.githubusercontent.com/24840952/164894228-720fcd36-a33f-4061-ba57-f3928c0db3a3.png)

**Comment by seydx** [comment]
Added in `v5.0.23-beta.0`

- **MQTT:** When motion is detected, two MQTT messages are now published on following topics:
  1. **camera.ui/notifications**: Contains all notifications AFTER motion has been detected AND recorded.
  2. **camera.ui/motion** _(can be changed in the interface):_ Contains motion event (before something is recorded).

**Comment by seydx** [comment]
v5.0.24 is online
