### ISSUE TITLE
WARNING  Garten: The recording process has been running for 3 minutes and is now being forced closed!

### ISSUE THREAD

**Issue by chip131001** [seydx/homebridge-camera-ui#541]
Hello,
I get the following warning.
Recording stops. How can I change this? This was not the case in previous versions.
![Ohne Titel](https://user-images.githubusercontent.com/38818613/165365839-2d9bc84e-bad2-423f-a1a0-b6fa75449275.jpg)

**Comment by seydx** [comment]
@chip131001 

<img width="1532" alt="Bildschirmfoto 2022-04-26 um 22 51 46" src="https://user-images.githubusercontent.com/34152761/165390232-80d92f0f-2bf1-4be9-9aef-da5429038135.png">

change this to 0

**Comment by chip131001** [comment]
> @chip131001
> 
> <img alt="Bildschirmfoto 2022-04-26 um 22 51 46" width="1532" src="https://user-images.githubusercontent.com/34152761/165390232-80d92f0f-2bf1-4be9-9aef-da5429038135.png">
> 
> change this to 0

i did that But nothing changes.

**Comment by seydx** [comment]
> > @chip131001
> > <img alt="Bildschirmfoto 2022-04-26 um 22 51 46" width="1532" src="https://user-images.githubusercontent.com/34152761/165390232-80d92f0f-2bf1-4be9-9aef-da5429038135.png">
> > change this to 0
> 
> i did that But nothing changes.

Oh ok i will ckeck it

**Comment by frankiesoc** [comment]
hello,
I have the same problem.
I also set the "motion detection" to 0 as described.
