### ISSUE TITLE
Privacy switch no longer disables live view

### ISSUE THREAD

**Issue by kerwinf** [seydx/homebridge-camera-ui#542]
Switching the privacy switch on or off no longer disables the live camera stream.

**Comment by slimemold** [comment]
I just enabled the privacy switch on my cameras, and I'm seeing this as well. Privacy switch doesn't seem to do anything.

I'm using homebridge-camera-ui v5.0.27.

**Comment by alexandreghez** [comment]
It seems that the switch "at Home" must be set to true for the privacy switch run correctly

**Comment by slimemold** [comment]
Thanks, @alexandreghez. That works for me.

The unfortunate side effect of the "at home" button being on is that motion detection (and hence HSV recording) seems to get disabled unless you expose the camera's "exclude" switch and turn that on. But the exclude switch being on also makes the privacy switch not work.

So the end result for my use case is to have some automation that always makes the exclude switch state be the opposite of the privacy switch state. I'd like to hide the exclude switch, but it's part of the camera, so it seems that you can't hide (or move) the exclude switch without hiding (or moving) also the camera and the privacy switch.

**Comment by seydx** [comment]
Currently working on the next major release, any suggestions here related to privacy/at home/exclude switch?

**Comment by kerwinf** [comment]
It would be great if they worked independently.

**Comment by slimemold** [comment]
I second @kerwinf's comment.

My use case is maybe not normal...I actually don't use the camera.ui at all, and solely use this plugin to get my Foscam cameras onto HomeKit and HSV.

My wish would be either to decouple the "at home" button from the privacy mode...OR have the ability to somehow not need that "exclude" button.

I would also like to thank you for your hard work. This plugin has been working very very well for me!

**Comment by stanthewizzard** [comment]
Hello
I would like to know how you dot the at home button ?
Then I would like to have some cam with privacy and other not. How do you achieve that ?
Thanks for helps

**Comment by chalmerscameron** [comment]
@alexandreghez how does one find the 'at-home' switch?

**Comment by marn06** [comment]
> @alexandreghez how does one find the 'at-home' switch?

![image](https://github.com/seydx/homebridge-camera-ui/assets/3353498/cf144684-df2e-495a-b3f0-6380b3788c6c)
