### ISSUE TITLE
TP Link Tapo C310 - Error -> The recording process was aborted by HSV with reason "CANCELLED"

### ISSUE THREAD

**Issue by derpate1989** [seydx/homebridge-camera-ui#549]
Hi, 

I have installed CameraUI and added my Tapo C310 cam. The live Stream works Fine in HomeKit. But HSV dont record any activities. I see a push on my Screen with activity, but when i will Open the push i see a black Screen and no Records. 

![image](https://user-images.githubusercontent.com/93314730/167628483-4e8b2ef0-4503-448b-9f05-3f7a80549f88.jpeg)

Log 
![image](https://user-images.githubusercontent.com/93314730/167628509-6d5c3828-3c3e-49b3-894c-ac47d593cfd2.jpeg)

My Config 

 "cameras": [
                {
                    "name": "Tapo Cam Garten",
                    "manufacturer": "Tapo",
                    "model": "C310",
                    "motion": true,
                    "motionTimeout": 15,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "hksvConfig": {
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 30,
                        "vcodec": "libx264"
                    },
                    "videoConfig": {
                        "source": "-i rtsp://user:pwd@192.168.178.151:554/stream1",
                        "subSource": "-i rtsp://user:pwd@192.168.178.151:554/stream1",
                        "stillImageSource": "-i rtsp://user:pwd@192.168.178.151:554/stream1",
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "maxFPS": 30,
                        "vcodec": "libx264",
                        "acodec": "libfdk_aac",
                        "audio": true,
                        "debug": true
                    },
                    "smtp": {
                        "email": "Tapo Cam Garten"
                    },

**Comment by seydx** [comment]
@derpate1989 

can you post a screenshot from the cameras own settings pls (like fps, bitrate etc)

**Comment by derpate1989** [comment]
Hey :) sure 

Hardware Specs from tplink for c310 

![image](https://user-images.githubusercontent.com/93314730/167773396-db07b378-5926-40fc-b662-93c08d4caa08.jpeg)
![image](https://user-images.githubusercontent.com/93314730/167773435-3838658a-253f-455f-87fc-af76b8e37150.jpeg)

And my camera Settings in her App 

![image](https://user-images.githubusercontent.com/93314730/167773475-98272731-d67c-49b2-a6e9-08eabfa0fade.png)
![image](https://user-images.githubusercontent.com/93314730/167773497-e09128f6-813f-4de9-a8f5-1333423b3781.png)

I have change the Frame Rate to 15fps, but hsv dont record anything.

**Comment by seydx** [comment]
@derpate1989 

Change FPS to 25 or 30

**Comment by derpate1989** [comment]
The Camera can only 15fps. In CameraUI i have try 15 /25 and 30. all 3 with Same issue. 

My last config, Camera works Fine in HomeKit, but without records. 

![image](https://user-images.githubusercontent.com/93314730/167781427-cae602bd-87ac-4418-88ec-e42dc9ad1cb8.jpeg)

**Comment by derpate1989** [comment]
The Camera can only 15fps. In CameraUI i have try 15 /25 and 30. all 3 with Same issue. 

My last config, Camera works Fine in HomeKit, but without records. 

![image](https://user-images.githubusercontent.com/93314730/167781640-4626e939-cacb-4081-a0ee-5829aeaff6bc.jpeg)

**Comment by seydx** [comment]
@derpate1989 

change maxFPS to 25 or 30 and disable audio (hksvConfig)

**Comment by derpate1989** [comment]
Ok i have change the Frame and hsv Audio Settings. With this Settings, HomeKit send no notification after activity in the "Alert Zone".

**Comment by derpate1989** [comment]
I have change the config and it works 😂 i dont know how 😅 

My Change: 

I deleted all hsv config
I use udp as transport protocoll

**Comment by derpate1989** [comment]
My Config, Motion detect, audio, stream and record works fine. 

"cameras": [
                {
                    "name": "Tapo Cam Garten",
                    "manufacturer": "Tapo",
                    "model": "C310",
                    "motion": true,
                    "motionTimeout": 15,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://user:password@192.168.178.151:554/stream1",
                        "subSource": "-i rtsp://user:password@192.168.178.151:554/stream1",
                        "stillImageSource": "-i rtsp://user:password@192.168.178.151:554/stream1",
                        "rtspTransport": "udp",
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "audio": true,
                        "debug": true
                    },
                    "smtp": {
                        "email": "Tapo Cam Garten"
                    },
                    "videoanalysis": {
                        "active": true
                    },
                    "mqtt": {}****

**Comment by remibou78** [comment]
Hello @derpate1989 I've exactly the same problem like you ! Could you help me please ?
