### ISSUE TITLE
Is H.265 supported?  

### ISSUE THREAD

**Issue by muzzman1** [SeydX/homebridge-camera-ui#55]
Thanks for everything!  
I have a couple HIKVision cameras that default to H.265 and once that happens, Homebridge no longer will stream the video.  The snapshots work, but the video wont until I explicitly go into the camera and select H.264 as the stream.

**Comment by SeydX** [comment]
Hey @muzzman1 

Do you mean livestream on Dashboard/Homekit

Or Recording on movement?

**Comment by muzzman1** [comment]
Hi
    I just want to be able to livestream from homekit.

--

**Comment by jeylites** [comment]
@muzzman1 

can you copy your config here? Have you checked if the RTSP URL is correct?

**Comment by muzzman1** [comment]
Yes URL is good but when the camera is sending  h.265 HomeKit won’t stream. Only stills
    When I set it to h.264 works perfect in HomeKit.
    Unless there’s a way to make ffmpeg work with h.265 I guess I will leave the camera on h.264.

Thanks.

—
AACC Inc.
Ammar A.
________________________________
