### ISSUE TITLE
Stream going black and resetting

### ISSUE THREAD

**Issue by vascott1** [seydx/homebridge-camera-ui#550]
I just added a Wyze v3 cam using camera.ui for a short time it was recording using hksv Then it just stopped. I removed the camera and added it back. Now every 12 seconds the preview goes black and then comes back. This only happens on the home app main screen. I am attaching a video. It was not doing this before.

I also have a Reolink camera and that is not behaving the same way. 

I'm new to camera UI and must say it is great so far. Just need some help to iron out some glitches. 

Thanks.

**Environment**
- Node.js Version: v16.15
- Homebridge Version: v1.4.1
- Camera UI Version: v5.0.27
- Operating System: Raspbian GNU/Linux Buster (10)
- Browser: safari

 https://user-images.githubusercontent.com/47582187/167977648-619e9820-2592-49fa-96b4-3e8ef743bf3d.MOV

**Comment by seydx** [comment]
Hey @vascott1 

thats not a camera.ui issue, its a apple homekit bug (which is fixed in the current beta i think (?))

**Comment by vascott1** [comment]
That’s good news actually. Thanks. Was hoping it could be fixed but I can work with it until the next release.   
  

  
Thanks for the quick answer.
  
  
  
  
  
  
  

  
  
>
