### ISSUE TITLE
InvalidPathError

### ISSUE THREAD

**Issue by bisquit2003** [seydx/homebridge-camera-ui#552]
Hello. Installed hb on windows 11 node.js, restored from a backup of hb macos, there were problems with ffmpeg, but fixed it. Now the bug is in the patch. How to fix it, please tell me

**Logs**
[CameraUI]  ERROR  InvalidPathError: The following path is invalid (should be X:\...): /Users/savelevajuliya/.homebridge/camera.ui/recordings

**Environment**
- Node.js Version: last
- Homebridge Version: last
- Camera UI Version: last
- Operating System: win 11
- Browser: any

**Comment by seydx** [comment]
Thx,will fix it

**Comment by T-Will** [comment]
I am seeing the same error here, similar scenario (restored HB from a MacOS backup moving to Windows 10). No longer getting the ffmpeg error, but now getting the InvalidPathError above.
