### ISSUE TITLE
Camera not exposed to Homekit

### ISSUE THREAD

**Issue by ablyes** [seydx/homebridge-camera-ui#556]
Hi guys, 

I'm using camera-ui as homebridge plugin. 
Any change to get some help for this configuration ? I can't see any error on logs with debug level. 
I can see the camera on camera-ui dashboard. But i can't get it on homekit. 
For info, I deactivated the HKS, because i don't own a 200go plan. 
I also gave a try with HKS set to true. I can't see the camera on homekit. 
One more thing : when i try simply "Homebridge Camera FFmpeg", I can see the camera exposed to homekit.
`{
            "name": "CameraUI",
            "port": 8081,
            "atHomeSwitch": true,
            "logLevel": "debug",
            "mqtt": {
                "active": false,
                "tls": false,
                "port": 1883
            },
            "http": {
                "active": false,
                "port": 7272,
                "localhttp": false
            },
            "smtp": {
                "active": false,
                "port": 2727,
                "space_replace": "+"
            },
            "ftp": {
                "active": false,
                "port": 5050,
                "useFile": false
            },
            "ssl": {
                "active": false
            },
            "options": {
                "videoProcessor": "/usr/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"
            },
            "cameras": [
                {
                    "name": "Portail",
                    "manufacturer": "Hikvision",
                    "model": "DS-2CD2T45G0P-I",
                    "serialNumber": "DS-XXXXX",
                    "motion": true,
                    "useInterfaceTimer": false,
                    "motionTimeout": 15,
                    "unbridge": true,
                    "hsv": false,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "hksvConfig": {
                        "source": "-i rtsp://admin:password@192.168.1.111:554/Streaming/channels/101"
                    },
                    "videoConfig": {
                        "source": "-i rtsp://admin:password@192.168.1.111:554/Streaming/channels/101",
                        "subSource": "-i rtsp://admin:admin:password@192.168.1.111:554/Streaming/channels/102",
                        "stillImageSource": "-i rtsp://admin:password@192.168.1.111:554/Streaming/channels/101",
                        "maxStreams": 2,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "vcodec": "h264",
                        "acodec": "libfdk_aac",
                        "audio": false
                    },
                    "smtp": {
                        "email": "Portail"
                    },
                    "videoanalysis": {
                        "active": true
                    }
                }
            ],
            "platform": "CameraUI"
        }`

v5.0.27
Thank you.

**Comment by seydx** [comment]
its a homebridge cache issue, change the camera name in your config.json and restart homebridge

**Comment by ablyes** [comment]
Just the camera name ? 
i did it without success. 
What about the serial number ?

**Comment by ablyes** [comment]
I used different kind of configurations. 
I'm still not able to expose to homekit, and logs are very poor. At least, i can't see any error or warn that could explain the situation.

**Comment by Techsticles** [comment]
> its a homebridge cache issue, change the camera name in your config.json and restart homebridge

That was it for me.  Thanks!

**Comment by AniGerm** [comment]
Hello,
I have almost the same issue. I changed my configuration and now all my cameras just disappear. I tried to change the name, reinstalled the plugin, but the cameras won’t show up in HomeKit. Through the CameraUI interface everything just works fine. I really hope anyone has an idea! Thanks:)

**Comment by karlquint** [comment]
> its a homebridge cache issue, change the camera name in your config.json and restart homebridge

Solved it for me as well. Before that, tried everything but with the same camera name it didn't show in Home.
