### ISSUE TITLE
Generic motion notifications while AppleTV in use with 15.5

### ISSUE THREAD

**Issue by xorguy** [seydx/homebridge-camera-ui#558]
**Describe the bug**
If the AppleTV is in use I get for any kind of movement a notification for generic movement even having set to only specific kind of movement. Only happens when AppleTV is in use. 

**To Reproduce**
Have camera added to Home app with notifications only to specific ones, like people, then upgrade AppleTV to 15.5.

**Expected behavior**
Only specified kind of notifications are received while AppleTV is in use and idle.

**Environment**
- Node.js Version: v16.15
- Homebridge Version: v1.4.1
- Camera UI Version: v5.0.27 (latest)
- Operating System: Docker

**Comment by mynameisdaniel32** [comment]
Also started seeing exactly this recently, currently on OS 15.5.1

**Comment by seydx** [comment]
I think this is due to Apple and the current iOS/tvOS version
