### ISSUE TITLE
Camera not reachable

### ISSUE THREAD

**Issue by GPL71** [seydx/homebridge-camera-ui#567]
Ingresso: Can not start prebuffering, camera not reachable. Trying again in 60s..

I've this messagge in homebridge
In HOME app I've a watermark on camera screen "CAMERA OFFLINE"

All was working without problem..

Homebridge and camera.ui is updated

**Comment by seydx** [comment]
Are you sure your camera is reachable? Can you ping the camera from terminal

**Comment by emimontoro** [comment]
I'm getting the same issue. And by entering in the URL manually I can get the image of the camera

**Comment by NambaAsuka** [comment]
Getting the same issue today. It works fine at first, then start showing “Can not start prebuffering, camera not reachable. Trying again in 60s..”. I was able to stream with the same link in VLC, so not sure what went wrong after a while.
