### ISSUE TITLE
Day incorrect when viewing recordings

### ISSUE THREAD

**Issue by Melvin-P-NL** [seydx/homebridge-camera-ui#571]
Hi all. So much love for this app, thanks a lot!

Got a small issue. When viewing recordings in HomeKit, the day is incorrect (+1), however the date is correct. For example, it says ‘Thursday’ June 1 for today.

It does not occur with a native HomeKit camera, so should be related to HOOBS/Camera UI.

**Comment by seydx** [comment]
Where do you mean it exactly? Could you make a screenshot of it please

**Comment by Melvin-P-NL** [comment]
Thanks for your reply. I mean when playing a recorded video in the Home app.

The day of the week was one day ahead, while the date was correct. This was not the case with a native HomeKit camera.

However, I installed the iOS 16 beta on my iPhone, and now it’s correct. I’ll check as soon as possible on my macOS 12 or iOS 15 device.
![5A7F2D24-9DC0-4941-9A22-C3B2AB8B440D](https://user-images.githubusercontent.com/106488334/173181343-56f2ce75-7bfe-4408-ad3f-3893e0454b91.jpeg)

**Comment by seydx** [comment]
> Thanks for your reply. I mean when playing a recorded video in the Home app.
> 
> The day of the week was one day ahead, while the date was correct. This was not the case with a native HomeKit camera.
> 
> However, I installed the iOS 16 beta on my iPhone, and now it’s correct. I’ll check as soon as possible on my macOS 12 or iOS 15 device. ![5A7F2D24-9DC0-4941-9A22-C3B2AB8B440D](https://user-images.githubusercontent.com/106488334/173181343-56f2ce75-7bfe-4408-ad3f-3893e0454b91.jpeg)

Hm that is up to Apple because camera.ui can not influence the date for HomeKit
