### ISSUE TITLE
"No motion" http link is different on wiki page and on settings page. 

### ISSUE THREAD

**Issue by utezduyar** [seydx/homebridge-camera-ui#573]
The wiki page `https://github.com/seydx/homebridge-camera-ui/wiki/HTTP-Config` indicates the link as `http://IP:HTTPPORT/motion/reset?My%20Camera` but the settings page of camera.ui indicates it as `http://IP:HTTPPORT/reset?My%20Camera`. 
![Screenshot 2022-06-01 at 11 24 40 AM](https://user-images.githubusercontent.com/8062069/171372980-ffc7bd40-c3a8-4e42-882e-a762550a626f.png)

**Comment by seydx** [comment]
Thx will merge the pr soon
