### ISSUE TITLE
Can’t see recordings

### ISSUE THREAD

**Issue by BertoTavira** [SeydX/homebridge-camera-ui#59]
Hi, first thanks for such amazing plugin, congratulations, one of the best 👍 

I have mi Yi can working, I can see notifications and small clips (not always) from camera and notifications sections, but if I click on recordings I get an error:
![5B7115D8-C807-4B3F-9B21-15735F75EF91](https://user-images.githubusercontent.com/74494230/99194689-482b6500-2781-11eb-9f51-5b0d36bbd17e.jpeg)

Also the notifications compared to recordings inside SD are different.

What am I missing? Any help is appreciated :)

**Comment by BertoTavira** [comment]
I think I got it, error disappeared when I changed the path for recordings.

It was 
> /var/lib/homebridge/recordings

and I changed it to:
> /homebridge/node_modules/homebridge-camera-ui/app/public/recordings

**Comment by BertoTavira** [comment]
Hi again, sorry for asking in this closed topic if I shouldn’t but,

I unbridged the camera and it disappeared from UI. Is this the expected behaviour?

**Comment by SeydX** [comment]
Hey @BertoTavira 

Currently yes. I will look into this if i can add a another solution to accept also unbridged accessories

**Comment by BertoTavira** [comment]
Thanks man! Again, awesome work 👏🏼👍🏼
