### ISSUE TITLE
Recording process aborted by HSV

### ISSUE THREAD

**Issue by derpate1989** [seydx/homebridge-camera-ui#597]
Hi, i have 2 tplink Tapo Cams. My C310 works fine with CameraUI and HomeKit recording. My C100 can only stream in HomeKit. Homebridge show me following after a motion. In HomeKit is stream and recording on. Motion Zone are set in HomeKit and Camera UI. 

![image](https://user-images.githubusercontent.com/93314730/175695413-174b61f4-a9ad-4df0-92ff-a7e8ee2104ee.jpeg)

My config (Same with C310 and C310 works Fine)

![image](https://user-images.githubusercontent.com/93314730/175695513-dc643437-582c-4ece-802d-23e156f337dd.jpeg)

You have any ideas?

**Comment by ucfhall** [comment]
@derpate1989 try lowering the bitrate and frame rate in your camera configuration. I had this issue with my Reolink RLC-810A's and that fixed it for me. HKSV has VERY limited video quality capacity.

**Comment by mkz212** [comment]
Probable solution: #855
