### ISSUE TITLE
macOS permission denied, mkdir /var/lib/homebridge

### ISSUE THREAD

**Issue by grzegorz914** [seydx/homebridge-camera-ui#603]
@seydx 

On the macOS we get Error: EACCES: permission denied, mkdir “/var/lib/homebridge” and the bridge crashes because */var* is a private directory on macOS and can’t be used to store any data, can you change this to /Users/USER_NAME/camera.ui?

**Comment by anhtuanng98** [comment]
same

**Comment by allkindsofralph** [comment]
I am getting the same issue on synology
