### ISSUE TITLE
Issue with rtsp stream from security spy

### ISSUE THREAD

**Issue by farberm** [seydx/homebridge-camera-ui#619]
When I use the following stream in vlc I can see the feed.

rtsp://username:password@ipaddress/++stream?cameraNum=3&codec=h264 

When I enter the following for the Viseo source in Camera.ui I get

-rtsp_transport tcp -re -i rtsp://username:password@ipaddress/++stream?cameraNum=3&codec=h264 

RTSP stream exited with error! (null)

rtsp.....
Invalid data found when processing input error

Not sure what I am doing wrong since show in vlc without issues

**Comment by kerwinf** [comment]
I use this plugin and also SecuritySpy as your topic shows. For the stream setup I use in the plugin the only difference is the -I, otherwise it stays the same. Try changing yours to:
-i rtsp://username:password@ipaddress/++stream?cameraNum=3&codec=h264
