### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'get')

### ISSUE THREAD

**Issue by brainstorm** [seydx/homebridge-camera-ui#622]
**Describe the bug**

When re-starting homebridge, occasionally the following fatal error appears, making automatic homebridge-camera-ui auto-respawn harder to automate:

```shell
(...)
[7/31/2022, 6:06:59 PM] TypeError: Cannot read properties of null (reading 'get')
    at file:///data/data/com.termux/files/usr/lib/node_modules/homebridge-camera-ui/src/accessories/camera.js:280:57
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/31/2022, 6:06:59 PM] TypeError: Cannot read properties of null (reading 'get')
    at file:///data/data/com.termux/files/usr/lib/node_modules/homebridge-camera-ui/src/accessories/camera.js:280:57
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/31/2022, 6:06:59 PM] TypeError: Cannot read properties of null (reading 'get')
    at file:///data/data/com.termux/files/usr/lib/node_modules/homebridge-camera-ui/src/accessories/camera.js:280:57
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/31/2022, 6:06:59 PM] Got SIGTERM, shutting down Homebridge...
[7/31/2022, 6:07:04 PM] [CameraUI] Galaxy S4 Camera: Setting up camera, please be patient...
[7/31/2022, 6:07:04 PM] [CameraUI] Nexus 4 Camera: Setting up camera, please be patient...
[7/31/2022, 6:07:04 PM] [CameraUI] Homebridge Nexus 4 Camera: Setting up camera, please be patient...
[Nexus 4 Camera E819] The image snapshot handler for the given accessory is slow to respond! See https://homebridge.io/w/JtMGR for more info.
[Homebridge Nexus 4 Camera 2B23] The image snapshot handler for the given accessory is slow to respond! See https://homebridge.io/w/JtMGR for more info.
[Galaxy S4 Camera 3FF7] The image snapshot handler for the given accessory is slow to respond! See https://homebridge.io/w/JtMGR for more info.
```

**To Reproduce**

[Install LineageOS on a Nexus 4, install termux](https://github.com/alexanderhale/home-assistant), nodejs, and npm install homebridge-camera-ui. Add three cameras and perhaps the error above manifests.

**Expected behavior**

I would expect that homebridge-camera-ui has a consistent state on each (re)start/stop of the service. Or at least that queues are either flushed/discarded upon start to or that `.get`(s) know how to deal with null or corrupted objects in the queue(s) without shutting down homebridge.

At first I thought that just removing the empty `cachedAccessories` solved the problem:

```shell
~ $ cat ~/.homebridge/accessories/cachedAccessories
[]
~ $ rm ~/.homebridge/accessories/cachedAccessories
~ $ homebridge -D
(...)
```

But the problem seems to be elsewhere, perhaps some corrupted database entry or queue object?

**Environment**
- Node.js Version: v18.4.0
- Homebridge Version: v1.5.0
- Camera UI Version:
```shell
  $ npm list -g
/data/data/com.termux/files/usr/lib
├── corepack@0.11.2
├── homebridge-camera-ui@5.0.27
├── homebridge-config-ui-x@4.50.0
├── homebridge@1.5.0
└── npm@8.12.1
```
- Operating System: `Linux localhost 3.4.113-lineageos-ge3e5c40db2e SMP PREEMPT Fri Jun 17 03:59:18 MSK 2022 armv7l Android`

**Comment by romeolazar** [comment]
I have this issue. how can I fix this? without reinstalling it from scratch!

**Comment by Olivierbkk** [comment]
same here, any fix?

**Comment by LemminatorGer** [comment]
Hi 
i have the same issue: 
Is there an fix anywehere ? 
`TypeError: Cannot read properties of null (reading 'get')
    at file:///var/lib/homebridge/node_modules/homebridge-camera-ui/src/accessories/camera.js:280:57
    at processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by brainstorm** [comment]
https://github.com/seydx/homebridge-camera-ui/issues/896#issuecomment-2120777099 seems like a reasonable patch, have you tried it?

**Comment by Olivierbkk** [comment]
yes I tried and it seems to work, so far so good
