### ISSUE TITLE
Stream on internal fails, but on cell works.

### ISSUE THREAD

**Issue by netechsys** [seydx/homebridge-camera-ui#635]
I have a few cameras configured, all the same configuration, and I am getting the snap shots fine, but streaming fails from internal. 

If I am on my Wi-Fi, using the Home application, I can see the snap shots and they update every 10 seconds just fine. If I select a camera for a live stream, it will attempt to connect but fails after about 60 seconds. If I drop off my local network, and onto my cellular connection, I can connect and live stream just fine. 

Here is the configuration for one of the cameras I am trying to use:

 {
                    "name": "Driveway",
                    "manufacturer": "Dahua",
                    "model": "HFW4300S",
                    "serialNumber": "xxxxxxxx",
                    "motion": true,
                    "motionTimeout": 120,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://xxxxxxx@10.250.254.21:554/",
                        "subSource": "-rtsp_transport tcp -i rtsp://xxxxxxx@10.250.254.21:554/",
                        "stillImageSource": "-rtsp_transport tcp -i rtsp://xxxxxxx@10.250.254.21:554/",
                        "maxStreams": 4,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 20,
                        "maxBitrate": 2048,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "audio": false,
                        "debug": false
                    }

This is strange, and I can't figure out what I'm missing. Any help would be greatly appreciated!

**Comment by andrasg** [comment]
I have the same issue. Camera video is working fine in camera.ui interface, but does not load in Home app. If I disconnect my phone from wifi, Home app starts loading camera video too.

**Comment by asdfng** [comment]
I am also experiencing this issue.

**Comment by asdfng** [comment]
Has anyone figured this out?

**Comment by ben-pelletier** [comment]
I have this issue only if i'm connected to a VPN to my home network and am also on the home WiFi. For example on VPN when away from home stream works, return home phone auto connects to wifi... check stream and its stuck.
