### ISSUE TITLE
Local camera offline

### ISSUE THREAD

**Issue by DavidKP6** [SeydX/homebridge-camera-ui#64]
**Describe the bug**
The camera is working ok on homebridge and it stream ok in homekit BUT it´s always offline on camera.ui web interface
The soketPort is define for the camera.

**To Reproduce**
use local camera (in the same rpi running homebridge and cameraui
video source: "source": "-re -f video4linux2 -i /dev/video0" 

**Expected behavior**
I hope it shows the stream as it works on homekit, but it doesn´t.

**Logs**

**Installation warn (several times tray during some weeks):**
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v5.0.0/bcrypt_lib-v5.0.0-napi-v3-linux-arm-glibc.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for bcrypt@5.0.0 and node@14.15.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/bcrypt/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  AR(target) Release/obj.target/../node-addon-api/nothing.a
  COPY Release/nothing.a
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  COPY Release/bcrypt_lib.node
  COPY /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/bcrypt/build'

> ffmpeg-for-homebridge@0.0.9 install /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge
> node install.js

**Get this error on homebridge log when launching cameraui web interface**

[11/23/2020, 10:01:14 AM] [CameraUI] [Interface] Cámara Salón: An error occured during pinging
[11/23/2020, 10:01:14 AM] [CameraUI] TypeError: Cannot read property 'includes' of undefined
    at Object.getHost (/usr/local/lib/node_modules/homebridge-camera-ui/app/lib/ping.js:36:13)
    at Object.ping (/usr/local/lib/node_modules/homebridge-camera-ui/app/lib/ping.js:9:25)
    at Object.pingCamera (/usr/local/lib/node_modules/homebridge-camera-ui/app/models/cameras.js:37:28)
    at /usr/local/lib/node_modules/homebridge-camera-ui/app/controller/dashboard.js:14:26
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/express/lib/router/index.js:335:12)
[11/23/2020, 10:01:14 AM] [CameraUI] [Interface] Cámara Salón: Offline
GET /dashboard 200 1770.244 ms - -

**Screenshots**

**Environment**
- Node.js Version: v14.15.0
- Homebridge Version: -tested on v1.2.3, v.1.3.0-beta.25 and stable version 1.1.6
- Camera UI Version: v3.4.1
Operating System: Raspbian GNU/Linux 10 (buster)
            Kernel: Linux 5.4.72-v7+
      Architecture: arm
-Browser any

**Comment by SeydX** [comment]
@DavidKP6 

It seems there is a problem with pinging your camera, can you post your config pls

**Comment by DavidKP6** [comment]
> 
> 
> @DavidKP6
> 
> It seems there is a problem with pinging your camera, can you post your config pls

Of course:

"platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "CameraUI",
            "port": 8181,
            "auth": "none",
            "theme": "dark-green",
            "language": "en",
            "debug": true,
            "reset": false,
            "mqtt": {
                "active": false
            },
            "http": {
                "active": false,
                "localhttp": false
            },
            "ssl": {
                "active": false
            },
            "cameras": [
                {
                    "name": "Cámara Salón",
                    "manufacturer": "David",
                    "model": "raspiCam China 1.0",
                    "serialNumber": "1.0",
                    "firmwareRevision": "1.0",
                    "motion": true,
                    "doorbell": true,
                    "switches": true,
                    "motionTimeout": 15,
                    "unbridge": false,
                    "videoConfig": {
                        "source": "-re -f video4linux2 -i /dev/video0",
                        "stillImageSource": "-re -f video4linux2 -ss 0.9 -i /dev/video0 -vframes 1",
                        "maxStreams": 10,
                        "maxHeight": 720,
                        "maxFPS": 25,
                        "maxBitrate": 1500,
                        "forceMax": true,
                        "vcodec": "h264_omx",
                        "packetSize": 1316,
                        "videoFilter": "crop=1024:576",
                        "debug": true,
                        "socketPort": 7777
                    }
                }
            ],
            "platform": "CameraUI"

Thank you very much @SeydX , awesome work (even if it doesn´t fully work to me, it really looks great)

**Comment by DavidKP6** [comment]
I´m waiting a new pi zw to add the camera extarnaly and a Yi camera too, but I think it´s still intersting have a local working camera too. (if it´s possible, of course)

**Comment by DavidKP6** [comment]
I have added a Hacked Yi camera and it Works perfectly (with the sound bug, as mentioned un other bug report).

I guess the plugin is designed to work just with rtsp streams.

Thanks

**Comment by SeydX** [comment]
@DavidKP6 

can u try v3.1.5 pls. It should fix the ping issue of local cameras

**Comment by DavidKP6** [comment]
> @DavidKP6
> 
> can u try v3.1.5 pls. It should fix the ping issue of local cameras

installing....

**Comment by DavidKP6** [comment]
> @DavidKP6
> 
> can u try v3.1.5 pls. It should fix the ping issue of local cameras

Working

Now fully working local cameras... excelent work.
