### ISSUE TITLE
"At home button" 

### ISSUE THREAD

**Issue by muelli1967** [seydx/homebridge-camera-ui#642]
I am not using HomeKit for detecting if the members of my house are at home. 

would it be possible to trigger the "at home" button that is featured by the camera-UI from a different source. As far as I am aware at the moment this button can only be triggered manually within HomeKit as far as I am aware. Correct? 

Thank you!

**Comment by aron8132** [comment]
This would be a great feature. If there is a "at home" button accessory, we can trigger it with a Shortcut automation.

**Comment by aron8132** [comment]
![Névtelen](https://user-images.githubusercontent.com/22430957/200043695-0306660b-6793-4b87-93c2-ae8041e5a89d.png)
I couldn't find it on the UI, but if you set this true in the config, it will appear in Home.

**Comment by norb-HB** [comment]
> I am not using HomeKit for detecting if the members of my house are at home.
> 
> would it be possible to trigger the "at home" button that is featured by the camera-UI from a different source. As far as I am aware at the moment this button can only be triggered manually within HomeKit as far as I am aware. Correct?
> 
> Thank you!

I don't know if this applies to your needs: I use Homebridge People Geofence  and Locative for IOS to trigger absence/presence in HK. Based on that I have further automations like switching 'at home'.
