### ISSUE TITLE
enabling audio causes live stream to fail

### ISSUE THREAD

**Issue by yonigold1** [SeydX/homebridge-camera-ui#65]
Hey! @SeydX FANTASTIC plugin!! I will 100% be donating as soon as I can figure this issue out!!!! 

So I have 2 Yi 1080p Dome Cams (hacked) and I have set up the RTSP stream and the video works however as soon as I enable audio and try to put the audio RTSP stream it fails to play the stream in HomeKit and in CameraUI.
How should I go about getting the audio to work? 

**Here is the config for one of the cameras (this config is set to audio **disabled** and that's when the live stream works)** 
                   "name": "Front of House",
                    "videoConfig": {
                        "source": "-i rtsp://192.168.2.35/ch0_0.h264",
                        "audio": false,
                        "debug": true

**here is the config for the same camera when the audio is enabled** 
                    "name": "Front of House",
                       "videoConfig": {
                        "source": "-i rtsp://192.168.2.35/ch0_0.h264",
                        "audio": true,
                        "debug": true

**once i do that and restart homebridge as soon as i open the homekit cam i get this error in homebridge:**
 [Camera FFmpeg] FFmpeg exited with code: 1 and signal: null (Error)
 [Camera FFmpeg] [Front of House] Stopped video stream.

**Now i know I'm missing something because in the Yi Hack has a UI by going to its IP and when i go to the RTSP tab there is enable audio and a stream dedicated to it but i do not know where to input that into the config of this plugin. 
Here is what the RTSP stream for the audio of my camera looks like:**

rtsp://192.168.2.35/ch0_2.aac

Please help me out. :)

**Comment by SeydX** [comment]
@yonigold1 

Your config is not wrong. Yi hacked cams has some trouble with playing audio. I habe also a yi hacked cam and cant figure out how to solve this yet.

What u can try is to play the RTSP stream via VLC and check if there is audio working.

If not, its because of the yi hack. If yes, there must be something wrong with the plugin

**Comment by yonigold1** [comment]
Thanks so much for the quick response! I tried yesterday night but I'll try again today! but maybe (and I'm noobish so imma just try to suggest something this could be the stupidest thing ever but its worth a shot LOL) maybe there is a way for the plugin to make the streams into 1 so it can play it, if not maybe that's a thing the Dev of the Yi hack can implement in a future update. :D 

I also have another quick question, in ios 14 apple added activity zones for cameras how can I add that to my Yi Hacked cam? is it possible? as I really would like this as I get packages stolen from my doorstep and want to get notified when their is movement in a certain part of my front porch. In addition to this how can I record footage from my cam in the home app as well because I know that is possible too in ios 14. and finally is it possible to talk through the cameras through the home app with your plugin?

**Comment by SeydX** [comment]
Thats a thing that the yi hack developer must do ^^

Activity zones can not be created in with homebridge cameras. Also recording via HomeKit is not possible at the moment via Homebridge.

Homekit Secure Cameras are currently in development (https://github.com/homebridge/HAP-NodeJS/issues/741) and when its become available i will implement it.

At the moment, only the Camera UI can record snapshots/videos on movement

**Comment by RW188** [comment]
I am also having this issue using a Keekoon K002, but also have realised there isn't audio within the feed when viewed through VLC.
