### ISSUE TITLE
ios16 - cameras not showing up 

### ISSUE THREAD

**Issue by anschroe** [seydx/homebridge-camera-ui#654]
I lost a number of my cameras in HomeKit when upgrading to ios16 - not sure what happened.  Reinstalled CameraUI and doublechecked the config.  Everything shows up fine in the camera.ui host interface, but they do not show up in the Home app when I add an accessory.   UPDATE: I’m sorry - this is a cache issue that I cleared.  Closing my own issue…

**Comment by anschroe** [comment]
I will note that I’m on ios16.1 - is this the new HomeKit framework that’s breaking things?

**Comment by kevindesousa** [comment]
I have the same
