### ISSUE TITLE
Cameras fail to be imported, causes very high cpu usage

### ISSUE THREAD

**Issue by recoi1er** [seydx/homebridge-camera-ui#661]
**Describe the bug**
Have 3 wyze v2 cams and they will not work in this plugin, get error messages in your UI saying error 500 (your log doesn't work anymore but HOOBS log shows stuff

**To Reproduce**
setup cameras in config based on your config examples, they dont work 

**Expected behavior**
Expect that the cameras at least show up in your ui webpage

**Logs**
10/13/2022, 4:19:01 PMCamera Ui BridgeLoaded plugin 'homebridge-camera-ui'
10/13/2022, 4:19:02 PMCamera Ui BridgeLoading 1 platforms...
10/13/2022, 4:19:02 PMCamera Ui BridgeCameraUIConfig changed through interface, saving...
10/13/2022, 4:19:02 PMCamera Ui BridgeBridge is running on port 51896.
10/13/2022, 4:19:02 PMCamera Ui BridgeCameraUIFront Door Cam: Configuring unbridged accessory...
10/13/2022, 4:19:02 PMCamera Ui BridgeCameraUIFront Door Cam: Setting up accessory...
10/13/2022, 4:19:05 PMCamera Ui BridgeCameraUIShop Cam: Configuring unbridged accessory...
10/13/2022, 4:19:05 PMCamera Ui BridgeCameraUIShop Cam: Setting up accessory...
10/13/2022, 4:19:05 PMCamera Ui BridgeCameraUIGarage Cam: Configuring unbridged accessory...
10/13/2022, 4:19:05 PMCamera Ui BridgeCameraUIGarage Cam: Setting up accessory...
10/13/2022, 4:19:05 PMCamera Ui BridgeCameraUIAccessories refreshed and config.json saved!
10/13/2022, 4:19:05 PMCamera Ui BridgeFront Door Cam F9E3 is running on port 43975.
10/13/2022, 4:19:05 PMCamera Ui BridgeShop Cam 8D72 is running on port 38229.
10/13/2022, 4:19:05 PMCamera Ui BridgeGarage Cam 3F72 is running on port 36839.

10/13/2022, 4:19:37 PMCamera Ui BridgeCameraUIFront Door Cam: Setting up camera, please be patient...
10/13/2022, 4:19:37 PMCamera Ui BridgeCameraUIShop Cam: Setting up camera, please be patient...
10/13/2022, 4:19:37 PMCamera Ui BridgeCameraUIGarage Cam: Setting up camera, please be patient...
10/13/2022, 4:19:38 PMCamera Ui BridgeCameraUIFront Door Cam: An error occured during pinging camera, skipping..
10/13/2022, 4:19:38 PMCamera Ui BridgeCameraUI ERROR  Error: ping.probe: there was an error while executing the ping program. . Check the path or permissions...
10/13/2022, 4:19:40 PMCamera Ui BridgeCameraUIGarage Cam: An error occured during pinging camera, skipping..
10/13/2022, 4:19:40 PMCamera Ui BridgeCameraUI ERROR  Error: ping.probe: there was an error while executing the ping program. . Check the path or permissions...
10/13/2022, 4:19:46 PMCamera Ui BridgeCameraUIShop Cam: An error occured during pinging camera, skipping..
10/13/2022, 4:19:46 PMCamera Ui BridgeCameraUI ERROR  Error: ping.probe: there was an error while executing the ping program. . Check the path or permissions...
10/13/2022, 4:19:52 PMCamera Ui BridgeCameraUIcamera.ui v5.0.27 is listening on port 8081 (http)

10/13/2022, 4:20:07 PMCamera Ui BridgeCameraUI ERROR  Shop Cam: Videoanalysis timed out... killing ffmpeg session
10/13/2022, 4:20:07 PMCamera Ui BridgeCameraUIShop Cam: Restart videoanalysis session..
10/13/2022, 4:20:24 PMCamera Ui BridgeCameraUI ERROR  Garage Cam: Videoanalysis timed out... killing ffmpeg session
10/13/2022, 4:20:24 PMCamera Ui BridgeCameraUIGarage Cam: Restart videoanalysis session..

10/13/2022, 4:20:37 PMCamera Ui BridgeCameraUI ERROR  Shop Cam: Videoanalysis timed out... killing ffmpeg session
10/13/2022, 4:20:37 PMCamera Ui BridgeCameraUIShop Cam: Restart videoanalysis session..
10/13/2022, 4:20:52 PMCamera Ui BridgeCameraUI ERROR  Shop Cam: Prebuffer timed out... killing ffmpeg session
10/13/2022, 4:20:52 PMCamera Ui BridgeCameraUI ERROR  Shop Cam: FFmpeg videoanalysis process exited with error! (null) - Output file #0 does not contain any stream 
10/13/2022, 4:20:52 PMCamera Ui BridgeCameraUIShop Cam: Restart prebuffer session..
10/13/2022, 4:20:52 PMCamera Ui BridgeCameraUI ERROR  Shop Cam: FFmpeg videoanalysis process exited with error! (null) - Output file #0 does not contain any stream 
10/13/2022, 4:20:52 PMCamera Ui BridgeCameraUIShop Cam: Restart videoanalysis session..
10/13/2022, 4:20:53 PMCamera Ui BridgeCameraUI ERROR  Garage Cam: Videoanalysis timed out... killing ffmpeg session
10/13/2022, 4:20:53 PMCamera Ui BridgeCameraUIGarage Cam: Restart videoanalysis session..

**Screenshots**
not sure what's needed here, adding the json instead

{
    "platform": "CameraUI",
    "logLevel": "info",
    "port": 8081,
    "atHomeSwitch": false,
    "options": {
        "videoProcessor": "/var/lib/hoobs/camerauibridge/node_modules/ffmpeg-for-homebridge/ffmpeg"
    },
    "ssl": {
        "active": false
    },
    "http": {
        "active": false,
        "port": 7272,
        "localhttp": false
    },
    "smtp": {
        "active": false,
        "port": 2727,
        "space_replace": "+"
    },
    "ftp": {
        "active": false,
        "useFile": false,
        "port": 5050
    },
    "mqtt": {
        "active": false,
        "tls": false,
        "port": 1883
    },
    "name": "CameraUI",
    "theme": "auto",
    "language": "en",
    "cameras": [
        {
            "name": "Front Door Cam",
            "motionTimeout": 15,
            "videoConfig": {
                "source": "-i rtsp://user:pw@192.168.1.52/live",
                "stillImageSource": "-i rtsp://user:pw@192.168.1.52/live",
                "stimeout": 10,
                "audio": false,
                "subSource": "-i rtsp://user:pw@192.168.1.52/live",
                "rtspTransport": "tcp",
                "vcodec": "copy",
                "acodec": "libfdk_aac"
            },
            "smtp": {
                "email": "Front Door Cam"
            },
            "videoanalysis": {
                "active": true
            },
            "unbridge": true,
            "manufacturer": "Wyze",
            "model": "WyzeCam V2",
            "serialNumber": "redacted",
            "prebufferLength": 4,
            "hsv": true,
            "prebuffering": true,
            "motion": true,
            "subtype": "camera"
        },
        {
            "name": "Shop Cam",
            "motionTimeout": 15,
            "videoConfig": {
                "source": "-i rtsp://user:pw@192.168.1.53/live",
                "stillImageSource": "-i rtsp://user:pw@192.168.1.53/live",
                "stimeout": 10,
                "audio": false,
                "subSource": "-i rtsp://user:pw@192.168.1.53/live",
                "rtspTransport": "tcp",
                "vcodec": "copy",
                "acodec": "libfdk_aac"
            },
            "smtp": {
                "email": "Shop Cam"
            },
            "videoanalysis": {
                "active": true
            },
            "unbridge": true,
            "manufacturer": "Wyze",
            "model": "WyzeCam V2",
            "serialNumber": "redacted",
            "prebufferLength": 4,
            "hsv": true,
            "prebuffering": true,
            "motion": true,
            "subtype": "camera"
        },
        {
            "name": "Garage Cam",
            "motionTimeout": 15,
            "videoConfig": {
                "source": "-i rtsp://user:pw@192.168.1.51/live",
                "stillImageSource": "-i rtsp://user:pw@192.168.1.51/live",
                "stimeout": 10,
                "subSource": "-i rtsp://user:pw@192.168.1.51/live",
                "rtspTransport": "tcp",
                "vcodec": "copy",
                "acodec": "libfdk_aac",
                "audio": false
            },
            "smtp": {
                "email": "Garage Cam"
            },
            "videoanalysis": {
                "active": true
            },
            "unbridge": true,
            "manufacturer": "Wyze",
            "model": "WyzeCam V2",
            "serialNumber": "redacted",
            "prebufferLength": 4,
            "hsv": true,
            "prebuffering": true,
            "motion": true,
            "subtype": "camera"
        }
    ]
}

**Environment**
- Node.js Version: v16.17.1
- Homebridge Version: v1.50
- Camera UI Version: v5.0.27
- Operating System: HOOBS 4.2.8
- Browser: Safari / Edge

**Comment by platini76** [comment]
same problem here..

   {
            "name": "CameraUI",
            "port": 8282,
            "atHomeSwitch": false,
            "logLevel": "debug",
            "mqtt": {
                "active": false,
                "tls": false,
                "port": 1883
            },
            "http": {
                "active": false,
                "port": 7575,
                "localhttp": false
            },
            "smtp": {
                "active": false,
                "port": 2727,
                "space_replace": "+"
            },
            "ftp": {
                "active": false,
                "useFile": false,
                "port": 5050
            },
            "ssl": {
                "active": false
            },
            "options": {
                "videoProcessor": "/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"
            },
            "cameras": [
                {
                    "name": "Camera Terrazzo",
                    "manufacturer": "Ezviz",
                    "model": "C3X",
                    "serialNumber": "E75104062",
                    "motion": true,
                    "motionTimeout": 15,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": false,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://admin:AIMVDO@192.168.0.147:554/H.264",
                        "subSource": "-i rtsp://admin:AIMVDO@192.168.0.147:554/H.264",
                        "stillImageSource": "-i rtsp://admin:AIMVDO@192.168.0.147:554/H.264",
                        "rtspTransport": "tcp",
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "audio": false,
                        "debug": true
                    },
                    "smtp": {
                        "email": "Camera Terrazzo"
                    },
                    "videoanalysis": {
                        "active": false
                    },
                    "mqtt": {}
                },
                {
                    "name": "Camera Ballatoio",
                    "manufacturer": "Ezviz",
                    "model": "C3X",
                    "serialNumber": "E75103968",
                    "motion": true,
                    "motionTimeout": 15,
                    "unbridge": true,
                    "hsv": true,
                    "prebuffering": false,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://admin:UPOKDT@192.168.0.146/h264_stream",
                        "subSource": "-i rtsp://admin:UPOKDT@192.168.0.146/h264_stream",
                        "stillImageSource": "-i rtsp://admin:UPOKDT@192.168.0.146/h264_stream",
                        "rtspTransport": "tcp",
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "audio": false,
                        "debug": true
                    },
                    "smtp": {
                        "email": "Camera Ballatoio"
                    },
                    "videoanalysis": {
                        "active": false
                    },
                    "mqtt": {}
                }
            ],
            "_bridge": {
                "username": "0E:B1:37:40:96:E5",
                "port": 36013
            },
            "platform": "CameraUI"
        }

**Comment by recoi1er** [comment]
I uninstalled the plugin and just use them in the Wyze app for now.

It would appear based on lack of response and no updates in the last many months that the dev might have given up on this project? Hopefully not, was looking forward to seeing how this worked in HSV

**Comment by recoi1er** [comment]
moved to a different system
