### ISSUE TITLE
Livestream working in Camera.Ui but not in HomeKit

### ISSUE THREAD

**Issue by norb-HB** [seydx/homebridge-camera-ui#668]
Hi seydx,

great plugin - thanks a lot for your work! 

I have a few cams and all working great but my Aldi/Maginon cams. I seem to have the same issue as the guy in https://github.com/seydx/homebridge-camera-ui/issues/490.
However the solution seem not to apply to my setup. I fiddled around for quite a long time and never could get the livesteam in HK working. Only in CameraUI.

I'd appreciate if you could give me a hint or maybe another user with the same cams.

                {
                    "name": "CarportUI",
                    "manufacturer": "Maginon",
                    "model": "IPC-25HDC",
                    "motion": true,
                    "doorbell": true,
                    "switches": true,
                    "motionTimeout": 3,
                    "unbridge": true,
                    "hsv": false,
                    "prebuffering": false,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i http://userid:password@ip:80/videostream.cgi",
                        "subSource": "-i http://userid:password@ip:80/videostream.cgi",
                        "stillImageSource": "-i http://userid:password@ip:80/snapshot.cgi",
                        "maxStreams": 2,
                        "maxWidth": 640,
                        "maxHeight": 480,
                        "maxFPS": 0,
                        "maxBitrate": 300,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "encoderOptions": "-preset ultrafast ",
                        "audio": false,
                        "debug": true,
                        "readRate": true
                    },
                    "smtp": {
                        "email": "CarportUI"
                    },
                    "videoanalysis": {
                        "active": false
                    },
                    "mqtt": {}
                },
                {
                    "name": "HaupteingangUI",
                    "manufacturer": "Maginon",
                    "model": "IPC-25HDC",
                    "motion": true,
                    "doorbell": true,
                    "switches": true,
                    "motionTimeout": 4,
                    "motionDoorbell": false,
                    "unbridge": true,
                    "hsv": false,
                    "prebuffering": false,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i http://userid:password@ip:80/videostream.cgi",
                        "subSource": "-i http://userid:password@ip:80/videostream.cgi",
                        "stillImageSource": "-i http://userid:password@ip:80/snapshot.cgi",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 0,
                        "forceMax": false,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "audio": false,
                        "debug": true
                    },
                    "smtp": {
                        "email": "HaupteingangUI"
                    },
                    "videoanalysis": {
                        "active": false
                    },
                    "mqtt": {}
                },

**Comment by markandersontrocme** [comment]
Live feed works perfectly in the camera.ui but not in Home. I'm using a Wyze Cam V2 and running into:

```
## I open the live stream in Home app
[23/11/2022, 14:38:37] [CameraUI] Home Cam: Starting video stream: native
[23/11/2022, 14:38:39] [CameraUI]  ERROR  Home Cam: FFmpeg exited with code: 1 and signal: null
## I close the live stream in Home app
[23/11/2022, 14:38:39] [CameraUI] Home Cam: Stopped video stream.
```

Using the following config:

```
                {
                    "name": "Home Cam",
                    "motion": true,
                    "motionTimeout": 15,
                    "unbridge": true,
                    "hsv": false,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://xxx:xxx@192.168.x.x/live",
                        "subSource": "-i rtsp://xxx:xxx@192.168.x.x/live",
                        "stillImageSource": "-i rtsp://xxx:xxx@192.168.x.x/live",
                        "rtspTransport": "tcp",
                        "maxStreams": 1,
                        "vcodec": "copy",
                        "acodec": "libfdk_aac",
                        "packetSize": 188,
                        "maxFPS": "30",
                        "audio": true,
                        "debug": true
                    },
                    "smtp": {
                        "email": "Home Cam"
                    },
                    "videoanalysis": {
                        "active": false
                    },
                    "mqtt": {}
                }
```

@seydx any idea what's going on?

**Comment by markandersontrocme** [comment]
Fixed it by disabling audio!

```
                {
                    "name": "Home Cam",
                    "motion": true,
                    "motionTimeout": 15,
                    "unbridge": true,
                    "hsv": false,
                    "prebuffering": true,
                    "prebufferLength": 4,
                    "videoConfig": {
                        "source": "-i rtsp://xxx@192.168.x.x/live",
                        "subSource": "-i rtsp://xxx@192.168.x.x/live",
                        "stillImageSource": "-i rtsp://xxx@192.168.x.x/live",
                        "maxStreams": 1,
                        "maxFPS": 30,
                        "vcodec": "copy",
                        "packetSize": 188,
                        "audio": false,
                        "debug": true
                    },
                    "smtp": {
                        "email": "Home Cam"
                    },
                    "videoanalysis": {
                        "active": false
                    },
                    "mqtt": {}
                }
```
