### ISSUE TITLE
FFmpeg prebuffer process exited with error! (null) - Unrecognized option 'rtsp_transport'. - Error splitting the argument list: Option not found -

### ISSUE THREAD

**Issue by GAMESSITE** [seydx/homebridge-camera-ui#671]
When i attempt to add my wyze cam v3 i get the error message:

[11/8/2022, 9:38:06 PM] [CameraUI]  ERROR  Side Deck: FFmpeg prebuffer process exited with error! (null) - Unrecognized option 'rtsp_transport'. - Error splitting the argument list: Option not found - 
[11/8/2022, 9:38:06 PM] [CameraUI] Side Deck: Prebuffering process closed
[11/8/2022, 9:38:06 PM] [CameraUI] Side Deck: Restart prebuffer session..
[11/8/2022, 9:38:12 PM] [CameraUI] Side Deck: Can not start videoanalysis, prebuffer process not yet started, retrying in 10s..
[11/8/2022, 9:38:16 PM] [CameraUI] Side Deck: Incoming ping request for: rtsp://admin:xxxxxxxxx@xxxxxxxxxxx/live - Timeout: 1s
[11/8/2022, 9:38:16 PM] [CameraUI] Side Deck: Pinging xxxxxxxxxxxxx
[11/8/2022, 9:38:16 PM] [CameraUI] Side Deck: Pinging xxxxxxxxxxxxx - successful
[11/8/2022, 9:38:16 PM] [CameraUI] Side Deck: Start prebuffering...
[11/8/2022, 9:38:16 PM] [CameraUI] Side Deck: Prebuffering command: ffmpeg -hide_banner -loglevel error -fflags +genpts -rtsp_transport tcp -i rtsp://admin:xxxxxxxx@xxxxxxxxxxx/live -vcodec copy -an -f tee -map 0:v? -map 0:a? [movflags=frag_keyframe+empty_moov+default_base_moof:f=mp4]tcp://xxxxxxxxxxx|[f=mpegts]tcp://xxxxxxxxxxx

I am using homebridge version 1.5.1

here is my JSON config:
{
    "name": "CameraUI",
    "port": 8081,
    "atHomeSwitch": false,
    "logLevel": "debug",
    "mqtt": {
        "active": false,
        "tls": false,
        "port": 1883
    },
    "http": {
        "active": false,
        "port": 7272,
        "localhttp": false
    },
    "smtp": {
        "active": false,
        "port": 2727,
        "space_replace": "+"
    },
    "ftp": {
        "active": false,
        "useFile": false,
        "port": 5050
    },
    "ssl": {
        "active": false
    },
    "options": {
        "videoProcessor": "ffmpeg"
    },
    "cameras": [
        {
            "name": "Side Deck",
            "manufacturer": "Wyze",
            "model": "V3",
            "serialNumber": "12324",
            "motion": true,
            "motionTimeout": 15,
            "unbridge": true,
            "hsv": true,
            "prebuffering": true,
            "prebufferLength": 4,
            "hksvConfig": {
                "source": "-rtsp_transport tcp -i rtsp://admin:xxxxxxxxx@xxxxxxxxxx:554/live",
                "audio": true
            },
            "videoConfig": {
                "source": "-rtsp_transport tcp -i rtsp://admin:xxxxxxxxx@xxxxxxxxxx:554/live",
                "subSource": "-rtsp_transport tcp -i rtsp://admin:xxxxxxxxx@xxxxxxxxxx:554/live",
                "stillImageSource": "-rtsp_transport tcp -i rtsp://admin:xxxxxxxxx@xxxxxxxxxx:554/live",
                "maxStreams": 4,
                "vcodec": "copy",
                "acodec": "libfdk_aac",
                "audio": true,
                "debug": true
            },
            "smtp": {
                "email": "Side Deck"
            },
            "videoanalysis": {
                "active": true
            },
            "mqtt": {}
        }
    ],
    "platform": "CameraUI"
}

**Comment by Bike-ops04** [comment]
I'm getting the same error with my reolink camera. Do I need to install another plugin or change a setting? My RTSP url does work in VLC.

Thank you,
Biker_ops04

**Comment by Bike-ops04** [comment]
Hi, Thank you for replying. I have it working now. It was ffmeg package was not installed.

Thank you

**Comment by zmulk** [comment]
> 

How did you install the ffmpeg package

**Comment by zmulk** [comment]
> Hi, Thank you for replying. I have it working now. It was ffmeg package was not installed. Thank you
> […](#)

How did you install the package?

**Comment by Bike-ops04** [comment]
zmulk you have to search **ffmpeg** in the package center on your synology. You need admin privileges to install it. Hope this helps.

**Comment by tpitale** [comment]
> Hi, Thank you for replying. I have it working now. It was ffmeg package was not installed. Thank you
> […](#)

@Bike-ops04 

Which version of ffmpeg did you install? Did you use the synocommunity package or something else?

**Comment by KovpakSA** [comment]
I have exactly the same problem.

I tried to install ffmpeg 4,5,6 from synocommunity, but the result is exactly the same.

Now gives an error - Gate: FFmpeg videoanalysis process exited with error! (Нул) -  Unrecognized option 'rtsp_transport'. - Ошибка разделение списка аргументов: - Вариант не найдена

Homebridge restarted after installation.

But the mistake remained.

**Comment by tpitale** [comment]
I ended up getting it to work by explicitly setting the command. I had a /bin/ffmpeg that kept taking priority and I was able to set ffmpeg6 as the command to use what was installed in /usr/local/bin/ffmpeg6.

**Comment by NambaAsuka** [comment]
I got the same issue. Here is how I solve it:

- Install ffmpeg 6 in the package center on your synology NAS.

- Open Homebridge Config Editor.

- Located "videoProcessor" in the editor

- Change the "videoProcessor": "ffmpeg" to "videoProcessor": "ffmpeg6"

Just adding a letter "6"! It's that simple!

**Comment by KovpakSA** [comment]
Hi.
 Thank you very much.
 I'll check.



Пт, 25 авг. 2023 г. в 08:12, NambaAsuka ***@***.***>:

**Comment by Miiou83** [comment]
[NambaAsuka](https://github.com/NambaAsuka)

un grand merci j'ai tellement cherché pour trouver la solution

**Comment by CanaroMen** [comment]
where to download ffmpeg6?
I tried every solution but not even one worked, and I wanted to try this solution but I can't find the download to ffmpeg6
