### ISSUE TITLE
Plugin failed to start after restore

### ISSUE THREAD

**Issue by crazyclimber999** [seydx/homebridge-camera-ui#676]
**Describe the bug**
I read this message when plugin start:

Error: spawn rtsp ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

i change the raspberry and restore the backup of home bridge, the first error message was for ffmpeg but I reinstall it with apt get install ffmpeg. After this I have the error listed before.

**Comment by crazyclimber999** [comment]
... i fix it. There was an error in the script. Everything is ok!

**Comment by Efiller91** [comment]
I am having the same exact error after similarly restoring.  Could you please elaborate on how you fixed it?
