### ISSUE TITLE
Config not saving

### ISSUE THREAD

**Issue by kapps7** [seydx/homebridge-camera-ui#682]
Strange observation using the Homebridge GUI

I am adding a camera and the a few fields such as stream config and name of the camera etc. I can see that it's added into the config json. But when I restart home bridge so that that new settings take effect, the cameras disappear and it says no cameras.

Am I missing something.
Not having any issue with any other plugin.

**Comment by Write** [comment]
Yupo same here, sometimes the config is saved, sometimes not. Not sure how to reproduce, it's very weird.

**Comment by vivekanandbv** [comment]
facing the same problem now... any fixes for this..?

**Comment by ShayL1987** [comment]
Facing the same issue. What is the resolution?

**Comment by groses92** [comment]
Same here

**Comment by BZsombor** [comment]
Same for me, it's not saving the camera config...
