### ISSUE TITLE
Error: EACCES: permission denied, mkdir '/homebridge

### ISSUE THREAD

**Issue by Alexxino** [seydx/homebridge-camera-ui#689]
**Environment and Setup**
Recently I have moved my Homebridge from a docker to a native app of Synology NAS. 

**Description of the error**
Everything is working as expected when I have installed the Camera-ui Plugin (no configuration yet), however when I configure any camera (even with dummy config) the plugin breaks because it tries to create a new folder "homebridge" which already exists, Synology NAS has created it when installing homebridge app. 
Homebridge keeps rebooting trying to load the camera-ui plugin.

**Error**
```
Error: EACCES: permission denied, mkdir '/homebridge
```

**Things I have tried**
Set the permissions of the folder homebridge and subfolders and files to user homebridge. (Homebridge app is running as root so it should have any problem)

I think the plugin should check if the folder /homebridge is created, if not -> create it otherwise then continue. 

Thank you.

**Comment by elementdc5** [comment]
I have this same issue.  Any luck getting it fixed?

**Comment by BerlinSnoop** [comment]
I have found the fix for the problem... 
Open file camera.ui/database/database.json and find section "recordings". Here you will see a "path" to a wrong path !!!!
It is a pity that nobody has found it out earlier.
