### ISSUE TITLE
Localization problem

### ISSUE THREAD

**Issue by motogon** [SeydX/homebridge-camera-ui#70]
![2020-12-12_15-00-36](https://user-images.githubusercontent.com/12997195/101983296-3d35f880-3c8b-11eb-9101-66c6165ca597.png)

Config :

{
"platform": "CameraUI",
"plugin_map": {
"plugin_name": "homebridge-camera-ui"
},
"name": "CameraUI",
"auth": "form",
"theme": "auto",
"language": "Auto",
"debug": true,
"reset": false,
"mqtt": {
"active": true,
"host": "192.168.1.74",
"port": 1883,
"username": "mqtt",
"topic": "homebridge/motion"
},
"http": {
"active": false,
"localhttp": false
},
"ssl": {
"active": false
},

Environment

    Node.js Version: 14.15.1
    Homebridge Version: HOOBS 3.3.1
    Camera UI Version: 3.1.5
    Operating System: Ubuntu 20.04.1 LTS
    Browser: Firefox 83

**Comment by SeydX** [comment]
@motogon 

u can set manually the language in the config ui x settings

![lang](https://user-images.githubusercontent.com/34152761/102110941-10721480-3e36-11eb-8540-1c56d6219d9b.JPG)
