### ISSUE TITLE
"New" camera not showing up in Homekit Add Accessory

### ISSUE THREAD

**Issue by ctgreybeard** [seydx/homebridge-camera-ui#706]
**Describe the bug**
Camera not showing in Homekit to be added

**To Reproduce**
I created a "new" camera. This one had been added before but, due to fumble fingers, was deleted. When I try to re-add it it doesn't appear in the list of Accessories that can be added.

It works OK in the Camera UI Interface but does not show up to be added in Homekit.

**Expected behavior**
I wanted to add the camera to Homekit but it doesn't show up. The "Driveway Camera" was also added this morning but that one was added easily in Homekit.

**Logs**
N/A

**Screenshots**
![IMG_0949](https://user-images.githubusercontent.com/122104/209843473-9393371c-71de-40fe-99d9-811a30e2d1d0.PNG)

**Environment**
- Node.js Version: v18.12.1
- Homebridge Version: v1.6.0
- Camera UI Version: v5.0.27
- Operating System: Raspbian Bullseye
- Browser: Safari

Config:
```
{
    "name": "CameraUI",
    "port": 8081,
    "atHomeSwitch": false,
    "logLevel": "info",
    "mqtt": {
        "active": false,
        "tls": false,
        "port": 1883
    },
    "http": {
        "active": false,
        "port": 7272,
        "localhttp": false
    },
    "smtp": {
        "active": false,
        "port": 2727,
        "space_replace": "+"
    },
    "ftp": {
        "active": false,
        "useFile": false,
        "port": 5050
    },
    "ssl": {
        "active": false
    },
    "options": {
        "videoProcessor": "/var/lib/homebridge/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"
    },
    "cameras": [
        {
            "name": "Driveway Camera",
            "manufacturer": "Wyze",
            "model": "Cam 3 Pro",
            "serialNumber": "D03F2791A57E",
            "motion": false,
            "motionTimeout": 15,
            "unbridge": true,
            "hsv": true,
            "prebuffering": true,
            "prebufferLength": 4,
            "videoConfig": {
                "source": "-i rtmp://hyrule.local:1935/roam-3",
                "subSource": "-i rtmp://hyrule.local:1935/roam-3",
                "stillImageSource": "-i rtmp://hyrule.local:1935/roam-3",
                "maxStreams": 2,
                "maxWidth": 0,
                "maxHeight": 0,
                "vcodec": "copy",
                "acodec": "libfdk_aac",
                "audio": false
            },
            "smtp": {
                "email": "Driveway Camera"
            },
            "videoanalysis": {
                "active": false
            },
            "mqtt": {}
        },
        {
            "name": "Front Camera",
            "manufacturer": "Amcrest",
            "model": "IP4M",
            "serialNumber": "AMC027927A9CDE4B57",
            "motion": false,
            "unbridge": true,
            "hsv": true,
            "prebuffering": true,
            "prebufferLength": 4,
            "videoConfig": {
                "source": "-i rtsp://weathercam:we1hav7lar@192.168.2.234:554/cam/realmonitor?channel=1&subtype=0",
                "subSource": "-i rtsp://weathercam:we1hav7lar@192.168.2.234:554/cam/realmonitor?channel=1&subtype=1",
                "maxStreams": 2,
                "maxWidth": 0,
                "maxHeight": 0,
                "vcodec": "copy",
                "acodec": "libfdk_aac",
                "audio": false,
                "stillImageSource": "-i rtsp://weathercam:we1hav7lar@192.168.2.234:554/cam/realmonitor?channel=1&subtype=0"
            },
            "videoanalysis": {
                "active": false
            },
            "motionTimeout": 15,
            "smtp": {
                "email": "Front Camera"
            },
            "mqtt": {}
        }
    ],
    "platform": "CameraUI"
}
```

**Comment by ede-kowalski** [comment]
Hi all,

unfortunately i have the same issue.
Stream is working via vlc and device shown in the ui but not added to Home app.

regards,
Ede

**Comment by ctgreybeard** [comment]
Ah! I totally forgot to post the solution, sorry!

What I had to do was go into the Homebridge setting and clear the stale cameras from the cache. I had a few in there for things that were no longer in HB. Once I cleared them the new camera was shown in Home to add.

**Comment by semaf** [comment]
> Ah! I totally forgot to post the solution, sorry!
> 
> What I had to do was go into the Homebridge setting and clear the stale cameras from the cache. I had a few in there for things that were no longer in HB. Once I cleared them the new camera was shown in Home to add.

Did not help me out :(

**Comment by starckie2023** [comment]
Had same problem - Under Homebridge Settings Unpair Bridges / Cameras / TVs / External Accessories clear out any cameras. in my case I did all of them. When the hub restarted camera.ui reloaded the current cameras and they showed up in Homekit
