### ISSUE TITLE
FFmpeg recording process exited with error! (null)

### ISSUE THREAD

**Issue by New-three** [seydx/homebridge-camera-ui#708]
I installed camera ui on my Homebridge (Synology, Docker).

There are some error messages in the log that I think have something to do with the motion detection.
Recordings are also not started via Homekit.

> [12/30/2022, 12:50:02 PM] [CameraUI]  ERROR  Weg: FFmpeg recording process exited with error! (null)
> [12/30/2022, 12:50:18 PM] [CameraUI]  ERROR  Haustur: FFmpeg videoanalysis process exited with error! (null) - [h264 @ 0x55f223b9cbc0] error while decoding MB 13 42, bytestream -5 
> [12/30/2022, 12:50:18 PM] [CameraUI]  ERROR  Haustur: FFmpeg videoanalysis process exited with error! (null) - [h264 @ 0x55f223b9cbc0] error while decoding MB 13 42, bytestream -5 
> [12/30/2022, 12:50:18 PM] [CameraUI] Haustur: Restart videoanalysis session..
> [12/30/2022, 12:50:18 PM] [CameraUI] VIDEOANALYSIS: New message: Data: {"time":"2022-12-30T11:50:18.734Z","event":"killed"} - Motion: resetted - Camera: Haustur
> [12/30/2022, 12:50:33 PM] [CameraUI] VIDEOANALYSIS: New message: Data: [{"zone":"region0","percent":65.46006774902344,"sensitivity":36,"dwell":60,"forceClose":3}] - Motion: detected - Camera: Hof
> [12/30/2022, 12:50:33 PM] [CameraUI] Hof: Motion ON

**Environment**
- Node.js Version: 18.12.1
- Homebridge Version: 1.6.0
- Camera UI Version: 5.0.26
- Operating System: Docker Synology
- Browser: Safari/Firefox

> {
>             "name": "CameraUI",
>             "port": 7575,
>             "atHomeSwitch": false,
>             "logLevel": "info",
>             "mqtt": {
>                 "active": false,
>                 "tls": false,
>                 "port": 1883
>             },
>             "http": {
>                 "active": true,
>                 "port": 7272,
>                 "localhttp": false
>             },
>             "smtp": {
>                 "active": false,
>                 "port": 2727,
>                 "space_replace": "+"
>             },
>             "ftp": {
>                 "active": false,
>                 "useFile": false,
>                 "port": 5050
>             },
>             "ssl": {
>                 "active": false
>             },
>             "options": {
>                 "videoProcessor": "/homebridge/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"
>             },
>             "cameras": [
> {
>                     "name": "Haustur",
>                     "motion": false,
>                     "doorbell": true,
>                     "switches": true,
>                     "motionTimeout": 15,
>                     "unbridge": true,
>                     "hsv": true,
>                     "prebuffering": true,
>                     "prebufferLength": 4,
>                     "videoConfig": {
>                         "source": "-i rtsp://XXX/videoMain",
>                         "subSource": "-i rtsp://XXX/videoMain",
>                         "stillImageSource": "-i rtsp://XXX/videoMain",
>                         "rtspTransport": "tcp",
>                         "vcodec": "copy",
>                         "acodec": "libfdk_aac",
>                         "audio": false
>                     },
>                     "smtp": {
>                         "email": "Haustur"
>                     },
>                     "videoanalysis": {
>                         "active": true
>                     },
>                     "mqtt": {}
>                 },

**Comment by whhumu** [comment]
Not sure if this will help. I found by removing and reinstalling the plugin - restarting the homebridge, then installing 1 camera at a time and restarting the plug in every time helped me to get rid of the issue. To solve it I had to remove the plug in totally and reinstall. I think adding multiple cameras and then saving results in coding errors. I left stream as -i XXXX, and then width, height and frame rate as 0, and bitrate empty worked for my setup

**Comment by moviebrain** [comment]
I’m also having this issue. Only 1 camera connected, nothing that I’m aware of has changed, no new cameras added.

**Comment by moviebrain** [comment]
I disabled audio and the error stopped. For me it is/was 100% an audio issue. “Wontfix”. Geez

**Comment by markywarky** [comment]
> I disabled audio and the error stopped. For me it is/was 100% an audio issue. “Wontfix”. Geez

Same for me.

**Comment by New-three** [comment]
How can i Disable Audio?

**Comment by moviebrain** [comment]
When you have your Homebridge admin page open, go to your Plugins tab, and choose the three vertical dots next to CameraUI. From there choose Plugin Config, and then choose Config from the pop up. 

From there expand the Camera menus, and under the camera causing an issue, expand the “HKSV Configuration” menus. At the very bottom of that uncheck the “Enable Audio” box. 
![IMG_6702](https://github.com/seydx/homebridge-camera-ui/assets/52259292/b354d13f-b5d8-4d7b-ab34-90cb9c9eda28)
![IMG_6700](https://github.com/seydx/homebridge-camera-ui/assets/52259292/456bb69e-9891-4879-84f3-fcf8123c78e7)
![IMG_6699](https://github.com/seydx/homebridge-camera-ui/assets/52259292/f1f3f8e6-95c5-4f1b-bafe-451f5eb401f7)
![IMG_6698](https://github.com/seydx/homebridge-camera-ui/assets/52259292/f726a3f9-0068-4e25-8c56-e6df6a0dbfe4)
