### ISSUE TITLE
ismartgate camera

### ISSUE THREAD

**Issue by koburg** [SeydX/homebridge-camera-ui#71]
I have this camera:
[https://shopeurope.ismartgate.com/ip-cameras/33-indoor-ip-camera-8437012951778.html](url)

i have issue about connecting live stream to the camera. 
the only thing I have succes about is stil image link. which is:
`http://admin:admin@192.168.1.20:88/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=admin&pwd=admin&`
 I got this from:
`https://www.ispyconnect.com/man.aspx?n=ismart+gate`

but i don't have the live feed url anybody got this working ?
I have tested many many different url / RTSP links no luck so far.

**Comment by gjs12** [comment]
You can expose the camera through the camera ffmpeg plugin, the rtsp url is rtsp://usern:pwd@IP:554/videoMain. You need to turn on onvif authentication on the camera which can be done through the foscam VMS app, at least that was what I had to do.
