### ISSUE TITLE
MaxListeners leak?

### ISSUE THREAD

**Issue by wills721** [seydx/homebridge-camera-ui#722]
**Describe the bug**
Logs show "ERROR(node:1727377) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finishLaunching listeners added to [Interface]. Use emitter.setMaxListeners() to increase limit"

**To Reproduce**
I have 11 cameras

**Expected behavior**
Not error

**Logs**
ERROR(node:1727377) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finishLaunching listeners added to [Interface]. Use emitter.setMaxListeners() to increase limit

**Screenshots**

**Environment**
- Node.js Version: v16.19.0
- Homebridge Version: v4.2.8
- Camera UI Version: v5.0.27
- Operating System: RPI
- Browser: Chrome

**Comment by wjkie** [comment]
Having the exact same problem  
"(node:131886) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 childBridgeMetadataResponse listeners added to [HomebridgeIpcService]. Use emitter.setMaxListeners() to increase limit"

**Comment by wills721** [comment]
I don't think this is a good thing (just saying)
