### ISSUE TITLE
Beyond AAC

### ISSUE THREAD

**Issue by Artoria2e5** [seydx/homebridge-camera-ui#751]
**Is your feature request related to a problem? Please describe.**
libfdk_aac is a fairly problematic choice from a licensing perspective. It would be a good idea for us to go without it.

**Describe the solution you'd like**
The bit in https://github.com/seydx/homebridge-camera-ui/blob/94dfc0bed386c53abddf65a8e2382e3de4df2e21/src/accessories/camera.js#L108-L111 should be made to change according to the config. This would allow us to use `opus` and use `copy` on a larger range of inputs (homebridge does note that ["only AAC-ELD and OPUS seem to work"](https://github.com/homebridge/HAP-NodeJS/blob/b34cc46ec4606fb0c56e0f642fc1bfc2fb255bd5/src/lib/camera/RTPStreamManagement.ts#L297)).

**Describe alternatives you've considered**
Use a less-good but legally OK AAC codec in ffmpeg. But why do that when opus is a thing?

**Additional context**
homebridge/ffmpeg-for-homebridge#52

Oh pretty sure `videoConfig.acodec` is a lie.

**Comment by Artoria2e5** [comment]
Huh, the HSV recording uses a different, non-ELD configuration still. That's interesting. But then the regex says any AAC will do.

**Comment by Neustradamus** [comment]
To follow

**Comment by Artoria2e5** [comment]
Ah heck, why not take a stab at this myself.
