### ISSUE TITLE
Room entry not saving, and not presenting saved rooms into dropdown of cameras "Select Room"

### ISSUE THREAD

**Issue by RW188** [SeydX/homebridge-camera-ui#78]
**Describe the bug**

Within the General tab, when trying to add additional rooms, the additions arent saved between viewing sessions.

I am also unable to select the rooms within the Cameras tab, Select Room to assign the camera to a room.

**To Reproduce**

Each time I start a new session, the list of rooms I have entered arent there.  When tabbing between and back to General the rooms stay, but when closing the session down don't save and arent available next time.

**Expected behavior**

Enter additional rooms, click apply and they stay as options.

Be able to use the additional rooms to assign them to a camera within the cameras tab.

**Logs**
If available, attach the log where the bug is vissible

**Screenshots**
![image](https://user-images.githubusercontent.com/42541894/105561396-85c2e600-5d0e-11eb-9aaf-4cce9f9994c2.png)
![image](https://user-images.githubusercontent.com/42541894/105561414-8f4c4e00-5d0e-11eb-9258-bc985d3c0534.png)

**Environment**
- Node.js Version: vX.X
- Homebridge Version: vX.X
- Camera UI Version: vX.X
- Operating System: XXX
- Browser: XXX

**Comment by SeydX** [comment]
@RW188 

Do you also press "Save" after you have created a room WITHOUT changing to "Cameras" ?

**Comment by SeydX** [comment]
Will be fixed with next version

**Comment by SeydX** [comment]
Fixed in [v3.3.0 Beta](https://github.com/SeydX/homebridge-camera-ui/releases/tag/3.3.0)
