### ISSUE TITLE
Protocol not found

### ISSUE THREAD

**Issue by apfelsaft87** [seydx/homebridge-camera-ui#783]
**Describe the bug**
I get the message in log:
Door: FFmpeg prebuffer process exited with error! (null) - https://172.17.5.3:554/h264_stream: Protocol not found - Did you mean file:https://172.17.5.3:554/h264_stream?

**To Reproduce**
"source": "-i https://172.17.5.3:554/h264_stream"

**Expected behavior**
In VLC Player the h264 stream with this url is just working

**Logs**
Door: FFmpeg prebuffer process exited with error! (null) - https://172.17.5.3:554/h264_stream: Protocol not found - Did you mean file:https://172.17.5.3:554/h264_stream?

**Environment**
- Node.js Version: v16.16.0
- Homebridge Version: v1.6.1
- Camera UI Version: v5.0.27
- Operating System: MacOS
- Browser: Chrome

**Comment by apfelsaft87** [comment]
Ah I found it. Error in the domain. Should start with rtsp://

**Comment by eliharrison2017-maker** [comment]
P
