### ISSUE TITLE
HomeKit Secure Video recording only 10% of motion events

### ISSUE THREAD

**Issue by reinisb** [seydx/homebridge-camera-ui#862]
**Describe the bug**
I have added Tapo C200 camera to Homebridge via homebridge-camera-ui. I've made sure to enable HSV recordings as well. Now, whenever I make any action in front of the camera, the motion event will be correctly recognized (I see the event both in Homebridge log as well as I receive a Home app notification on my iPhone). My goal is to have all of those moton events to be recoded via HSV and available on the Home app of my iPhone.

The problem is that only around 10% of motion events are recorded by Homekit Secure Video. This implies that 90% of motion event cases are missed which is a no go.

Can anyone please help? Thanks!

**Environment**
- Node.js Version: v20.9.0
- Homebridge Version: v1.7.0
- Camera UI Version: v5.0.27
- Operating System: Debian GNU/Linux Bullseye (11) on Raspberry Pi OS (pi 4)
- Browser: Chrome

**Comment by mkz212** [comment]
See #855

**Comment by reinisb** [comment]
I switched to Home Assistant + Scrypted and that HKSV works perfectly out of the box, every movement event correctly triggers HKSV recording.
