### ISSUE TITLE
Help to turn on/off At Home using webhook

### ISSUE THREAD

**Issue by BertoTavira** [SeydX/homebridge-camera-ui#94]
**Describe the bug**
Not a bug, looking for help.
Trying to use webhook to turn on/off _At Home_ mode

Idea is to add a http or webhook button in homebridge to control this after knowing what I’m missing

**Expected behavior**
I'd like this section shows you exactly the link to use (including IP or whatever’s missing if so) so dumb users like me can just copy/paste

**Screenshots**
![image](https://user-images.githubusercontent.com/74494230/108247133-8eaea800-7152-11eb-817b-61fab31d91e0.png)
![image](https://user-images.githubusercontent.com/74494230/108247155-94a48900-7152-11eb-8d93-ff08d9264be8.png)

**Environment**
- Node.js Version: v14.15.5
- Homebridge Version: v1.2.5
- Camera UI Version: v3.1.5
- Operating System: homebridge installed on Rpi using official image
- Browser: trying to send webhook from Chrome in Windows 10

**Comment by HSchmirPo** [comment]
Hi, please use atHome instead off athome.

**Comment by BertoTavira** [comment]
Thanks that did the trick! :)

**Comment by BertoTavira** [comment]
I have now my working http switch to turn it on/off :) Right now is set as _toggle_ so default state is off (and it remembers the last set state as the current one)

But, is there any way to check atHome status using http or webhook?

**Comment by SeydX** [comment]
Fixed in v3.2.2
