### ISSUE TITLE
bitrate / fps has no effect

### ISSUE THREAD

**Issue by stockima1337** [seydx/homebridge-camera-ui#962]
I will use my 4k cameras with camera-ui. I get a stream into homekit, but I need more than this 299k bit stream. The change of maxBitrate or fps has no effect. Please help.

"name": "Kamera Eingang",
            "manufacturer": "Reolink",
            "model": "RLC-810A",
            "motion": true,
            "motionTimeout": 15,
            "unbridge": true,
            "hsv": true,
            "prebuffering": false,
            "prebufferLength": 4,
            "videoConfig": {
                "source": "-i rtsp://xxxxx/h264Preview_01_main",
                "subSource": "-i rtsp://xxxxxx/h264Preview_01_sub",
                "stillImageSource": "-i http://xxxxxx/cgi-bin/api.cgi?",
                "readRate": false,
                "rtspTransport": "tcp",
                "maxStreams": 4,
                "maxWidth": 1920,
                "maxHeight": 1080,
                "maxFPS": 30,
                "maxBitrate": 1024,
                "forceMax": true,
                "vcodec": "libx264",
                "acodec": "libfdk_aac",
                "audio": true,
                "debug": true
            },
            
            
 frame=  240 fps= 32 q=38.0 size=     282KiB time=00:00:08.00 bitrate= 288.8kbits/s dup=44 drop=0 speed=1.07x

**Comment by stockima1337** [comment]
i changed the file camera.js and fixed the bug by myself. You should update it in next Version.

maxrate has no effekt to export to homekit. It use allways the standard of 299

**Comment by seydx** [comment]
next version works completely different and dont need such a option

**Comment by stockima1337** [comment]
ok, thank you for your reply.

 

And many thanks for your project - it’s awesome!!!

 

Von: seydx ***@***.***> 
Gesendet: Donnerstag, 8. August 2024 16:33
An: seydx/homebridge-camera-ui ***@***.***>
Cc: stockima1337 ***@***.***>; State change ***@***.***>
Betreff: Re: [seydx/homebridge-camera-ui] bitrate / fps has no effect (Issue #962)

 

next version works completely different and dont need such a option
