### ISSUE TITLE
Issue setting up Yi Dome 1080 Cameras

### ISSUE THREAD

**Issue by coalchamber1022** [SeydX/homebridge-camera-ui#99]
Hi All,
Trying to configure my 4 Yi Dome 1080 cameras which have all been configured with the yihack4 and rtsp enabled.

I've put in all the info like suggested in the linked example config and aligned with my IP addresses. What's odd is that in the camera UI web app I can see the cameras open the stream and all looks fine and dandy.

When I go into Homekit I see the cameras listed, the thumbnails are all able to update but when I tap into a camera I get this in the homebridge console:

[Plugin] Camera 1: ffmpeg exited with code: 1 and signal: null (Error)

Here is my current config with just one camera for demo purposes:
{
            "name": "CameraUI",
            "port": 8181,
            "auth": "form",
            "theme": "dark-gray",
            "language": "auto",
            "debug": false,
            "reset": false,
            "mqtt": {
                "active": false
            },
            "http": {
                "active": false,
                "localhttp": false
            },
            "ssl": {
                "active": false
            },
            "cameras": [
                {
                    "name": "Camera 1",
                    "manufacturer": "Yi",
                    "videoConfig": {
                        "vcodec": "h264",
                        "source": "-i rtsp://192.168.86.89/ch0_0.h264",
                        "stillImageSource": "-i rtsp://192.168.86.89/ch0_0.h264",
                        "maxStreams": 2,
                        "maxWidth": 1920,
                        "maxHeight": 1080,
                        "audio": true,
                        "socketPort": 8100
                    }
                }
            ],
            "platform": "CameraUI"
        }

Any ideas on what I'm missing? Appreciate the help.

**Comment by SeydX** [comment]
@coalchamber1022 

can u try without audio enabled pls

**Comment by SeydX** [comment]
@coalchamber1022 

can u try v3.2.2 pls

**Comment by coalchamber1022** [comment]
Works great for me now thanks!

**Comment by granborja** [comment]
> 

 hi @coalchamber1022 

I want to control my yi hack 1080 dome with Homekit through homebridge.
What plugin I need to do that? 

Thanks
